### ISSUE TITLE
[Bug] macOS x86_64 和 aarch64 产生的artifacts名称相同，会互相覆盖

### ISSUE THREAD

**Issue by ZacharyJia** [ChatGPTNextWeb/ChatGPT-Next-Web#2247]
**Describe the bug**
Action中的macOS的两个编译平台，产生的编译产物名称相同，在上传到release的时候，后运行的会先删除之前的产物，然后上传自己的。

可以参考 https://github.com/Yidadaa/ChatGPT-Next-Web/actions/runs/5447005645/jobs/9908507703 中，tauri-apps/tauri-action@v0 这个step的日志L541开始。

**Comment by Yidadaa** [comment]
tauri actions 不支持重命名产物，挺蛋疼的

**Comment by ZacharyJia** [comment]
> tauri actions 不支持重命名产物，挺蛋疼的

最新的dev版本似乎已经将arm的arch改为aarch64, 这样应该不会重名了吧。
https://github.com/tauri-apps/tauri-action/blob/dev/src/build.ts#L87-L89

不知道还有没有别的问题。

**Comment by vangie** [comment]
哪里能下载到 aarch64 版本？

**Comment by SDGLBL** [comment]
可以先自己编译凑合用
```sh
# install rust by your self
yarn add -D @tauri-apps/cli
yarn tauri build --target aarch64-apple-darwin
```

**Comment by shirok1** [comment]
@Yidadaa 我开了一个让 action 构建 universal binary 的 PR #3711
