### ISSUE TITLE
[Feature]  Code Interpreter

### ISSUE THREAD

**Issue by TrumanZYX** [ChatGPTNextWeb/ChatGPT-Next-Web#2338]
能增加Code Interpreter这个功能吗？

**Comment by TeamFan** [comment]
这个功能是openai的chatgpt自带的，api没有这个功能。。。

**Comment by huangkezhao** [comment]
开源永久免费 不注册 不登陆 不限次数  http://aiassist.plus

**Comment by daiaji** [comment]
> 开源永久免费 不注册 不登陆 不限次数 http://aiassist.plus

3.5也没啥用啊😅

**Comment by johnfelipe** [comment]
any progress for use code interpreter?

**Comment by haoranzhang929** [comment]
Maybe we could consider incorporating an open-source version of a Code Interpreter into this project. Like this one: https://github.com/shroominic/codeinterpreter-api

**Comment by haoranzhang929** [comment]
I will give it a go, if it works maybe I can open a PR for adding this?

**Comment by johnfelipe** [comment]
Nice

**Comment by rayzhl25** [comment]
这个功能非常重要，如果能支持就最好了

**Comment by rayzhl25** [comment]
这个功能有什么计划安排吗？

**Comment by SchneeHertz** [comment]
通过api的function calling参数，可以让api返回可执行的代码，再使用沙盒执行代码，可以实现代码解释器的功能
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/39257008/4757075f-8046-4abc-a8f8-b1923f8fd6d9)

**Comment by boromyr** [comment]
+1

**Comment by H0llyW00dzZ** [comment]
code interpreter it's already included, basically it's only depends on prompts from user.

e.g, you can see of my latest show off (while I was figure about models gpt-4  preview)

here we go https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/3416

**Comment by boromyr** [comment]
https://github.com/shroominic/codeinterpreter-api this looks interesting

**Comment by H0llyW00dzZ** [comment]
here is real interpreting based of user prompt in scenario we don't have to filter output from ai response
and this video are clearly natural language

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/c25cacf4-c830-4961-8733-e04c260a6d34

**Comment by H0llyW00dzZ** [comment]
and this one another show off since it 128K Context simply just paste 2 codes (e.g, `main.go` and `sessions.go`)

models:

- gpt-4-1106-preview

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/0d9ca0e1-81c6-4f00-9665-97ac0f475bbf

in that show off are about this tools

- https://pkg.go.dev/github.com/H0llyW00dzZ/ChatGPT-Next-Web-Session-Exporter

**Comment by H0llyW00dzZ** [comment]
memory prompt (automated generated known as summarize)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/8ee3be4c-c1cc-4406-a0e0-67a5691decd5)

**Comment by H0llyW00dzZ** [comment]
this a wild lol while continue a conversation

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/47699657-7b56-4d78-b00e-a88aebb05fe7)

**Comment by lloydzhou** [comment]
in v2.15.0 support plugin:

there is one demo call `CodeInterpreter` api as plugin.

https://github.com/ChatGPTNextWeb/NextChat-Awesome-Plugins/tree/main/plugins/codeinterpreterapi
