### ISSUE TITLE
[Feature] 准备引入 DALL-E 3

### ISSUE THREAD

**Issue by devyujie** [ChatGPTNextWeb/ChatGPT-Next-Web#2904]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
、

**你想要什么功能或者有什么建议？**
能否先引入 DALL-E 2 以提供专门的文生图能力，类似马上要发布官网 DALL-E 3 显示页面（虽然不知道什么时候开放 API）。

用一个专门的页面显示，而不是面具的形式，并且用户可以设置一次生成几张图片。

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48620527/a5968c23-72e3-4cbe-9e47-70a6e15d31c9)

**有没有可以参考的同类竞品？**
、

**其他信息**
、

**Comment by H0llyW00dzZ** [comment]
I had previously added this, but the problem is that I can't quickly bypass the CORS (Cross-Origin Resource Sharing) issue for the image URLs generated from OpenAI. Essentially, any image generated as a prompt using the DALL-E models cannot be exported as an image or in text/JSON format.

**Comment by H0llyW00dzZ** [comment]
[still beta]
https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/pull/52/commits/6948667589ccd53f43c2167ef5f8ed51604aa60c

**Comment by H0llyW00dzZ** [comment]
which is better than DALL-E 3 lmao
![Exploring the Milky Way galaxy (1)](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/a144b90d-66e3-44cc-8754-7b0ea6638ffc)

![Captivating Image_ Andromeda Galaxy](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/0bcee79c-588b-48fb-9d21-9d14d4c67796)
![Captivating Picture_ Milky Way](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/416f7acb-63f1-4462-b92e-0d058cb3a11d)


![Exploring Andromeda Galaxy](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/9b587528-8bf1-4cea-9020-1d19d8da0683)

**Comment by muaxb** [comment]
Have you resolved the issue with exporting the generated images?

**Comment by lloydzhou** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4300
