### ISSUE TITLE
UI crash in very long conversations [Bug] 

### ISSUE THREAD

**Issue by Pear-sudo** [ChatGPTNextWeb/ChatGPT-Next-Web#3156]
**Describe the bug**
When a conversation becomes long (over 100) only first and last few messages are visible. I cannot scroll to middle messages. The UI would bounce to top or bottom.

**To Reproduce**
Create a very very long conversation and you'll see the bug.

**Expected behavior**
I should be able to scroll to and view all the messages.

**Screenshots**
No, I cannot. Since I cannot see them.

ChatGPT.Next.Web_2.9.9_x64.dmg 
MacOS Ventura

**Comment by H0llyW00dzZ** [comment]
is there any log when crashed ? (because on windows & linux work's fine)
