### ISSUE TITLE
[Feature] 关于“面具”能力全面向“GPTs”看齐的建议

### ISSUE THREAD

**Issue by devyujie** [ChatGPTNextWeb/ChatGPT-Next-Web#3217]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
、

**你想要什么功能或者有什么建议？**
看到推上分享的 GPTs 功能，非常惊讶，这不就是“面具”吗，合理怀疑 CloseAI 抄袭本项目创意。

给每个对话设置预设词、定制模型参数、Zero One and Few Shot 等是早已实现的功能，现在就差 DALL-E 3、GPT-4 V 以及 Assistants API，今天突发奇想，又稍微想到几个建议：

先单独设置两个置顶 Tab 给 DALL E 和 Assistants，仅提供生图和上传/分析文件的能力，🔗[因为](https://platform.openai.com/docs/assistants/how-it-works/limitations) 未来几个月 Assistants API 会将 DALL E 和 GPT-4 V 融合进来，所以到时候仅通过 Assistants API 就可以在对话内完成多模态能力。
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48620527/ab792c88-d9a4-4aee-85b3-f81cc8a736e3)

等融合完毕之后，再把 Assistants 加到全局或者对话设置里，成为常驻嘉宾，通过开关按钮，来开启/关闭**是否启用文生图**、**是否允许上传图片**、**是否允许上传文件**等功能，同时可以分别设置相应的功能参数（类似 GPTs 的预设提示词啥的...），按钮打开后，相应的 UI 控件才会显示到对话中，这样也给用户极大地选择空间，到时候**面具**就会全面拥有多模态能力，哦对，还有 TTS 等语音功能。

关于上网能力，这里有一个🔗[参考](https://x.com/CocoSgt_twt/status/1722482821053477121?s=20)
关于 Assistants API 的能力扩展（接入各种知识库的开放 API），这里有一个🔗[列表](https://x.com/xiaohuggg/status/1711991024137183651?s=20)

**有没有可以参考的同类竞品？**
、

**其他信息**
、

**Comment by ClarenceDan** [comment]
很好的想法，这样面具就类似 assistant，而插件类似于官网的插件，但是这样似乎和官方的能力拉不开差距？（还是官方太猛了）

**Comment by devyujie** [comment]
> 很好的想法，这样面具就类似 assistant，而插件类似于官网的插件，但是这样似乎和官方的能力拉不开差距？（还是官方太猛了）

对，该接入的接入，毕竟人家提供 API 了，拉开差距可能要 [3.0](https://github.com/Yidadaa/ChatGPT-Next-Web/issues/138#issuecomment-1594976255) 版的插件😋

**Comment by devyujie** [comment]
> 很好的想法，这样面具就类似 assistant，而插件类似于官网的插件，但是这样似乎和官方的能力拉不开差距？（还是官方太猛了）

我觉得不需要拉开差距，把这些弄完就很丰富了，咱们用 API 的魔力在于随时想用就用，想玩就玩，每月又不用花太多钱，需求大的早都开 Plus 去了，毕竟无限用，使用门槛又低。

**Comment by H0llyW00dzZ** [comment]
also for code interpreting since we already had mask already, it only need file upload system

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/dfcf7863-02e9-4c05-a45e-512502c62a77

**Comment by H0llyW00dzZ** [comment]
another show case about code interpreting LLM Api (this a wilds) 

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/e0e382ce-d4d3-42dd-b8d6-de8ddd6e03f5)



![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/5576b2da-dc5a-4cf4-a5b2-3ffb8581c90c)




![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/63fcbe89-3808-4382-a2d8-918f40979f95)

**Comment by davideuler** [comment]
Assistant API 使用的7个例子，可以参考这里： 
https://github.com/davideuler/awesome-assistant-api

**Comment by ChrisXHL** [comment]
要不先把文件上传功能放上去，嘿嘿，API 还是快很多，比官网体验好多了

**Comment by vual** [comment]
我这边支持了gpt4-vision-preview识图功能，可以了解下。
https://github.com/vual/ChatGPT-Next-Web-Pro

**Comment by vual** [comment]
我这边增加了gpts商店支持，有需要的可以了解下：https://github.com/vual/ChatGPT-Next-Web-Pro
