### ISSUE TITLE
增加对CloudFlare AI Gateway的支持

### ISSUE THREAD

**Issue by Eventidus** [ChatGPTNextWeb/ChatGPT-Next-Web#3347]
能否增加对CloudFlare AI Gateway的支持，这样也能加速Azure OpenAI的使用
具体可点击以下链接查看https://developers.cloudflare.com/ai-gateway/providers/azureopenai/

**Comment by s544838371** [comment]
+1

**Comment by fossilet** [comment]
Related: #3079
