### ISSUE TITLE
[Feature] 添加删除记录和自定义导入导出提示词

### ISSUE THREAD

**Issue by XZ1314XZ** [ChatGPTNextWeb/ChatGPT-Next-Web#3402]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
尽管告诉我们。

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

# 建议

1. 现在有重置设置和重置聊天和设置的功能，但却没有单独重置所有聊天记录的功能类似官方或者GPT的平台的清空所有会话。希望可以增加

2. 欠缺自定义导入导出提示词功能，或考虑像chatgpt-web那种完善的Prompt Store，既有导入导出添加清空，在线添加。当然希望面具也同样这样支持。这样会更加方便生态共享，从其他人或者平台导入丰富的模板。

**Comment by H0llyW00dzZ** [comment]
I've been added this already you can see on my fork

https://github.com/H0llyW00dzZ/ChatGPT-Next-Web

if you interest I can pull req to main Yidadaa repo

**Comment by XZ1314XZ** [comment]
> I've been added this already you can see on my fork
> 
> https://github.com/H0llyW00dzZ/ChatGPT-Next-Web
> 
> web: https://chatgpt.btz.sh/
> 
> if you interest I can pull req to main Yidadaa repo

Oh, Thx, Bro. You know me so well. Besides the feature I mentioned earlier about importing via links online, you've done everything else. And you even added privacy by moving the "Clear Context" button to a more suitable position, which is great. But now I'm already using another branch version `https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain`, which adds the functionality of available plugins (although it seems like a small requirement, it compensates for the fact that the official version has not enabled plugin support). Additionally, as I mentioned before, [chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web) is also a very good project. Its prompt store aligns perfectly with my ideas. There's an unofficial [demo](https://chat9.yqcloud.top/) where you can import Prompt collections online (`https://github.com/PlexPt/awesome-chatgpt-prompts-zh`), supporting JSON format. Alternatively, you can use a more popular project (`https://github.com/f/awesome-chatgpt-prompts`
, but it uses CSV format.


Prompt Store on chatgpt-web:
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/56338784/7b891328-a41e-4162-9c0f-581bce789fe7)
)

**Comment by H0llyW00dzZ** [comment]
> > I've been added this already you can see on my fork
> > https://github.com/H0llyW00dzZ/ChatGPT-Next-Web
> > web: https://chatgpt.btz.sh/
> > if you interest I can pull req to main Yidadaa repo
> 
> I highly recommend you to PR, and I also plan to switch to your version. After all, it still satisfies my stronger needs.

must refactor about function `downloadAs` related to this issue 

[Bug] exported as a JSON file in the Windows installation version appears as unreadable content.（windows安装版的对话导出的JSON为乱码。）#3395
