### ISSUE TITLE
[Feature] 设置默认模型 Custom DEFAULT Model Support

### ISSUE THREAD

**Issue by KumaTea** [ChatGPTNextWeb/ChatGPT-Next-Web#3429]
## 支持设置默认模型

我已经搜索过了 #3384 等相关 issue，其中 `CUSTOM_MODELS` 并不是我想要的，即我并不希望通过减少可用模型的方式指定默认模型。

目前我使用的一种野蛮的方法：

```bash
cd /tmp
git clone https://github.com/Yidadaa/ChatGPT-Next-Web
cd ChatGPT-Next-Web

sed -i 's/model: "gpt-3.5-turbo" as ModelType,/model: "gpt-4-1106-preview" as ModelType,/g' ./app/store/config.ts
sed -i 's/export const SUMMARIZE_MODEL = "gpt-3.5-turbo";/export const SUMMARIZE_MODEL = "gpt-4-1106-preview";/g' ./app/constant.ts  # may not be necessary

docker build --pull -t kumatea/gpt-web --push .
docker run -d -p 3000:3000 -e OPENAI_API_KEY=sk-xxxx -e CODE=your-password kumatea/gpt-web
```

启动后可以发现默认模型已经切换。

<img width="398" alt="Screenshot 2023-12-02 231556" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/36222458/bb4a14cb-a736-4880-a755-97704f3a4a72">

希望后续得到官方支持。

---

## Support Settings of Custom DEFAULT Model

I've searched _Custom Default Model_ related issues like #3384 and confirmed those are not as I expected, that I would not like to define the default model by decreasing available choices.

Currently I found a not elegant but working way: (see code above)

After container created the desired default model has been selected.

<img width="357" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/36222458/3abe33e2-41d4-4e37-9c16-86b660322bb1">

I wish this option could be support officially later.

**Comment by H0llyW00dzZ** [comment]
this one I recommended better summarizing depends of model selected so you don't have to do this in bash

```sh
sed -i 's/export const SUMMARIZE_MODEL = "gpt-3.5-turbo";/export const SUMMARIZE_MODEL = "gpt-4-1106-preview";/g' ./app/constant.ts  # may not be necessary
```

here is example how it work you can do test in my site: https://chatgpt.btz.sh/

**Comment by H0llyW00dzZ** [comment]
another proof while summarizing using selected model

![287106222-c24e0077-037e-4969-982b-f12a25b08488](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/6f46d5b9-fc84-4265-8447-e17450d852d1)

source: https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/3416

other (this a wild)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/dccf631c-883c-4e82-8f4f-d555b519189f)

**Comment by H0llyW00dzZ** [comment]
> [!NOTE]  
> screenshot other it's context AI fixing a correct syntax for k8s

**Comment by ji-jinlong** [comment]
我也需要这个功能，希望后续能够通过环境变量切换默认模型。

**Comment by ji-jinlong** [comment]
所以后续有这个计划吗？设置一个环境变量来改变模型的优先级，该环境变量用逗号分割，从前往后，如果模型存在于CUSTOM_MODELS就作为默认模型，否者就继续判断。

**Comment by hunshcn** [comment]
any update? It is helpful.

**Comment by Dean-YZG** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4545
感谢社区小伙伴的贡献，目前最新版本已经支持了通过环境变量自定义DEFAULT_MODEL
