### ISSUE TITLE
[Bug] Unexpected backslash(\) is added when rendering codes

### ISSUE THREAD

**Issue by KevenLi8888** [ChatGPTNextWeb/ChatGPT-Next-Web#3460]
**Describe the bug**

An unexpected backslash(\\) will be added when a number follows the dollar($) sign in inline codes and code blocks. This occurs to both user input and system output, and the redundant backslash(\\) will be included when you try to copy the code.

I'm guessing this might be a conflict with the LaTex rendering.

<img width="681" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/20897139/f0887bdc-4907-488d-b1cc-75552ed1bba3">

<img width="699" alt="Screenshot 2023-12-05 at 15 29 48" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/20897139/a59a560e-908a-47da-8c1e-0ca2bdfe39d1">

**To Reproduce**

Use the following prompt:
``````
Repeat the following with no modification:

**Unexpected Behavior: when a number follows the dollar($) sign**

`$2asdf`

```
$1
```

**Normal Behavior**

$1

`$asdf`

```
$ASDF
```
``````

<img width="649" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/20897139/ddb9390e-d2c9-483b-8c5f-0c5b1f4e2596">

**Expected behavior**

See the image below:
<img width="798" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/20897139/f70e5506-dea5-492d-a1c8-99edecd1d813">

**Deployment**
- [x] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: macOS 14.1 (23B74)
 - Browser: Chrome 119.0, Safari 17.1
 - Version: v2.9.12

**Comment by Dean-YZG** [comment]
Thank you for your feedback, the problem has now been resolved~~
