### ISSUE TITLE
[Feature] 对话列表支持搜索功能

### ISSUE THREAD

**Issue by jerry-yuan** [ChatGPTNextWeb/ChatGPT-Next-Web#3496]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

我的会话搞得有点多，每个话题我都会开一个新会话，有时想回看一个GPT曾经的精彩回答却不太好找。想征求一下项目作者的看法，如果认为是合理的需求，我倒是很乐意效劳实现这个功能并提交PR(可能会需要一些时间😂)

**有没有可以参考的同类竞品？**
好像openai官网支持搜索会话来着？

**Comment by reece00** [comment]
其实已经有PR了……

**Comment by jiangying000** [comment]
对话多了以后，目前确实没法找到某个对话了

**Comment by Movelocity** [comment]
我提交了一个 PR：https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/5274

为了便于评审和测试，我提供了一个在线 [demo](http://112.74.74.13:7000/)。你可以导入一些测试用的聊天记录，然后尝试搜索功能。

如果你想快速更新，也可以使用我构建的 Docker 镜像来部署，或者从我的 fork 拉取代码并自行编译。以下是 Docker 镜像的使用方法：

```
docker pull hollway/next-chat:latest
```
希望这对你有帮助！

**Comment by Leizhenpeng** [comment]
已经支持

![CleanShot 2024-09-18 at 08 15 50@2x](https://github.com/user-attachments/assets/f0b918e3-1efb-4a24-9055-a7e5851667d1)
