### ISSUE TITLE
[Bug] Repo it's bugged since switch to organization not a personal 下游项目无法同步的 Bug

### ISSUE THREAD

**Issue by H0llyW00dzZ** [ChatGPTNextWeb/ChatGPT-Next-Web#3521]
**Describe the bug**
I can't push to my own fork

![image](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/assets/17626300/4554203e-b890-4a44-976f-1c4546f07e87)

**Comment by Algorithm5838** [comment]
+1
I am unable to edit my own fork.

**Comment by H0llyW00dzZ** [comment]
> +1 I am unable to edit my own fork. Additionally, redeploying on Vercel fails. Normally, it takes 1-3 minutes, but this time it took almost 10 minutes and then failed with the error: `Error: Cloning failed`
> 
> This is what I get from GitHub:
> 
> > Error loading page
> > An unexpected 500 error occured. Try reloading the page.

The issue is essentially due to a bug where contributors do not have the necessary permissions. It's quite amusing. I might create a new repository by copying from this original main branch, as the main repository has been transferred to an organization and contributors are not permitted to push or deploy.

**Comment by H0llyW00dzZ** [comment]
since license are MIT so yeah FREEDOM

**Comment by devyujie** [comment]
‌‌Hope to restore warehouse function update as soon as possible.

**Comment by H0llyW00dzZ** [comment]
> ‌‌Hope to restore warehouse function update as soon as possible.

I don't get it by doing claiming like this does the new devs are professional or skilled ? because this just made a mistake 

example a mistake it's breaking CI/CD Piplines

![image](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/assets/17626300/a1fc061e-e32d-4f4b-892c-f43bc140299a)

**Comment by H0llyW00dzZ** [comment]
if not professional or skilled better go back to personal instead of made this LMAO organization

**Comment by h1xy** [comment]
+1 
I can't modify my fork too. This is annoying

**Comment by H0llyW00dzZ** [comment]
> +1 I can't modify my fork too. This is annoying

Just wait; if the issue remains unresolved, I may establish a new repository with enhanced features that offer improvements.

List of additional features written in Go:
- Embedding the front-end to compile it into the binary.
- Expanding storage capacity to handle 1 chat with up to 99,999,999 messages.
- Configuring the SQL setup to support both SQL and NoSQL databases.
- Implementing improved synchronization.

**Comment by H0llyW00dzZ** [comment]
> [!NOTE]  
> additional features written in Go are possible instead of written it in other languages lmao

**Comment by Xheldon** [comment]
God, I even posted about it thinking it was my own issue😤. https://www.v2ex.com/t/1000461

**Comment by H0llyW00dzZ** [comment]
> God, I even posted about it thinking it was my own issue😤. https://www.v2ex.com/t/1000461

it's not ur issue, and it's not cause of DMCA
the main issue is claiming like this are disrespectful to be honest (for contributor), but as long latest version (most stable) already release so yeah it's seems fine

**Comment by reece00** [comment]
等待变化……
![image](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/assets/37351410/5ad4352d-fab7-4ffa-aea0-d727de8a6678)

**Comment by H0llyW00dzZ** [comment]
> 等待变化…… ![20231215070554](https://private-user-images.githubusercontent.com/37351410/290679809-c2b7d570-7fba-497b-b456-89ee857f6a08.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDUyMTAsIm5iZiI6MTcwMjYwNDkxMCwicGF0aCI6Ii8zNzM1MTQxMC8yOTA2Nzk4MDktYzJiN2Q1NzAtN2ZiYS00OTdiLWI0NTYtODllZTg1N2Y2YTA4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAxNDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZjNmMTFlYTI2ODFhNTUyZjk4MzIzMjgzMWY2ZDgxMTA0YmU2MDZhNjNiMWE5MzdmNWU0ZjZhMDZkNjQ1NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QVClOfVQQsIwEQhdSCOtJSBODhFIoh44CC3NJZp6j3I)

it doesn't work

**Comment by H0llyW00dzZ** [comment]
even on CI/CD it's forbidden also it won't fix by fork/re-fork it just removing commits 

![image](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/assets/17626300/ab5ac164-afb3-45aa-b515-9c1dea385630)

**Comment by Yidadaa** [comment]
看起来确实是个问题，我们正在想办法解决。

**Comment by Yidadaa** [comment]
大家好，经过排查，我们几乎可以确认这是 Github 的 Bug 导致，目前我们正在积极联系 Github 技术支持团队解决此问题，并且在问题解决之前，我们不会进行大的功能更新，防止下游项目无法及时获得代码更新，关于进一步动态，请大家关注此 Issue 的动态。

**Comment by Yidadaa** [comment]
大家好，Github 已经将此 Bug 修复，现在所有下游项目可以正常同步代码了，请手动 Sync Fork 一次以恢复自动更新。

![c6a6cf81ac388151887b2063fa73e8a7](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/16968934/34f329e5-df6d-41da-a707-8f7e13ccd0d5)
