### ISSUE TITLE
[Bug] 小图标很多都加载不出来

### ISSUE THREAD

**Issue by sxchou** [ChatGPTNextWeb/ChatGPT-Next-Web#3539]
![Screenshot_20231215_215136](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/125382693/da5ba2b9-3227-4204-90a2-dd0818016263)

**Comment by H0llyW00dzZ** [comment]
work's fine

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/a8bdceee-b155-465f-9025-0d0e0186444e)

**Comment by VectorZhao** [comment]
我这里也是，手机流量可以，宽带不行。之前从来没碰到过这种情况

**Comment by reece00** [comment]
自己什么破网自己能不能有点数？几万人就你加载不出来

**Comment by sxchou** [comment]
> 自己什么网自己能不能有点数？这么久了图片真要加载不出来能不知道吗？

以前就没这种情况，根本不是网络的问题，是程序的本身的问题

**Comment by VectorZhao** [comment]
> > 自己什么网自己能不能有点数？这么久了图片真要加载不出来能不知道吗？
> 
> 以前就没这种情况，根本不是网络的问题，是程序的本身的问题

实事求是就好，等其他人反馈，再看看是什么情况

**Comment by sunsky89757** [comment]
昨天作者处理了一次，好了一会，然后今天依旧还有这个问题。

**Comment by isnine** [comment]
I encounter same issue after update to latest version.

I believe this issue is not appear in old version.

**Comment by Xiaoheizi2023** [comment]
旧版本确实没有，新版本我也出现了这个情况

**Comment by Mxucc** [comment]
这个应该是程序BUG，不是很了解这个项目，只能是等修复了

**Comment by XuanRanDev** [comment]
> 这个应该是程序BUG，不是很了解这个项目，只能是等修复了

不是，就是CDN的部分图片挂了

**Comment by Yidadaa** [comment]
这个 bug 已经被修复了，升级代码即可。

**Comment by sunsky89757** [comment]
![111](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/113254524/371f5bee-3d1c-49a2-a190-78e008b4491d)
ju图标又失效了，昨天晚上发生的

**Comment by MengYingjie** [comment]
请问一下最后是怎么解决的？我也遇到了这个问题
