### ISSUE TITLE
你们的网页版被域名劫持了

### ISSUE THREAD

**Issue by tshacks01** [ChatGPTNextWeb/ChatGPT-Next-Web#3545]
地址如下：
https://tt.xuanyuanhuangdi.org/
这个网址你们看看
用的你们的网站流量，单纯是做了内容劫持。
我为什么来上报？因为我的网也被劫持了，默认给他返回444后，就跳你们的网页https://chatgpt.nextweb.fun/了。

**Comment by Agilan989** [comment]
Thank you for your email.. once again thank you very much for your support
as well

Thank you
Best regards
Agilanberan

**Comment by reece00** [comment]
你说的这个域名是谁的？都打不开。而且那个网站不叫域名劫持，你自己百度一下先。不清楚是不是中转了哪个网页，但人家中转了流量就不是盗流量好吗

**Comment by Yidadaa** [comment]
域名最近被不明原因举报禁用了，很蛋疼。

**Comment by JianleiZhang** [comment]
那我的域名可能也被举报了，现在显示 危险网站。我换了个域名，并降低了版本，希望能存活时间长点。

**Comment by ProgrammerHuang** [comment]
我们的也出现了,可是我们就自己使用的,没有开放的,怎么会被举报?

**Comment by JianleiZhang** [comment]
> 域名最近被不明原因举报禁用了，很蛋疼。

会不会引用了第三方资源造成的？之前换完域名后访问几分钟就又被标示 *危险网站*，所以现在降低了版本，目前看还正常。

**Comment by ProgrammerHuang** [comment]
> > 域名最近被不明原因举报禁用了，很蛋疼。
> 
> 会不会引用了第三方资源造成的？之前换完域名后访问几分钟就又被标示 _危险网站_，所以现在降低了版本，目前看还正常。

我也觉得有可能是第三方的资源
