### ISSUE TITLE
使用gpt-4模型，回答显示不全，一直显示“正在输入” 

### ISSUE THREAD

**Issue by Jerryzhangzhao** [ChatGPTNextWeb/ChatGPT-Next-Web#3546]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
docker 部署
使用gpt-4模型，回答显示不全，一直显示“正在输入” 。使用3.5的模型是正常的。

**如何复现**

**截图**
<img width="444" alt="捕获" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/10524773/ebf3a65b-e2fb-48f3-9d8a-2f6b34b123a5">

**一些必要的信息**
 - 系统：[ubuntu20.04]
 - 浏览器： [firefox]
 - 版本： [2.9.13]
 - 部署方式：[docker]

**Comment by zhougongjin555** [comment]
我也出现了这样问题，刚准备扒一扒issue就看到你发了

**Comment by H0llyW00dzZ** [comment]
Works fine, I ddin't got any problem in latest version
try clear all data

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/5a1d6ffc-de0b-42d7-9dde-d1f2c2790a84)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/60c11700-7339-4234-87ee-5949292ed0be)

**Comment by GOWxx** [comment]
Are you using the OpenAI API? If not, check your API.

**Comment by andyZhang37** [comment]
56+56

**Comment by andyZhang37** [comment]
56+56

**Comment by Yidadaa** [comment]
无法复现，请确保使用官方 api。
