### ISSUE TITLE
[Bug] Failed to fetch

### ISSUE THREAD

**Issue by aizzataffero** [ChatGPTNextWeb/ChatGPT-Next-Web#3548]
{
  "error": true,
  "message": "Failed to fetch"
}

I got this error, how can i fix it?

**Comment by WayneJin88888** [comment]
I had the same problem,when i am using desktop app today. Yesterday it's working well.

I've tried to downgrade to the last release or change api base url to official http://api.openai.com/v1/chat/completions

Both appimage and deb release come across the same issue.

It pop out 
{
"error": true,
"message": "Failed to load"
}

How to fix that?

**Comment by WayneJin88888** [comment]
> { "error": true, "message": "Failed to fetch" }
> 
> I got this error, how can i fix it?

I have changed base url in the settings to https://api.openai.com/
Now it's ok now. 
You can try.

**Comment by JacobDDoS** [comment]
This worked for me as well. Thank you!

**Comment by huanger-8** [comment]
worked!!thank you!! but change its base url then,you maybe need a reboot for this application.

**Comment by aizzataffero** [comment]
Thanks issued resolved!

**Comment by Zergle** [comment]
it worked, thanks!
