### ISSUE TITLE
配置了顯示餘額，點擊查看餘額一直是0,我是有錢的

### ISSUE THREAD

**Issue by zwong91** [ChatGPTNextWeb/ChatGPT-Next-Web#3552]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by zwong91** [comment]
這個功能廢棄了嗎

**Comment by zwong91** [comment]
Bug

Issues-translate-bot ***@***.***> 于 2023年12月17日周日 22:45写道：

**Comment by Yidadaa** [comment]
官方已经禁用了余额查询功能，此功能已经默认关闭。

**Comment by aes256ctr** [comment]
> 官方已经禁用了余额查询功能，此功能已经默认关闭。

难怪
