### ISSUE TITLE
[Bug] 当使用gpt-4-all绘图，消息记录里面有图片， share按钮  下载消息图片报错

### ISSUE THREAD

**Issue by tomridder** [ChatGPTNextWeb/ChatGPT-Next-Web#3553]
当使用gpt-4-all绘图，消息记录里面有图片， share按钮  下载消息图片报错

**Comment by Dean-YZG** [comment]
This problem is due to cross-domain problems with image resources. Using proxy to solve cross-domain, it is easy to cause ssrf. so, it's better to solve this problem  the resource server supports cross-domain
