### ISSUE TITLE
[Bug] can't resolve *.nextweb.fun

### ISSUE THREAD

**Issue by wowpala** [ChatGPTNextWeb/ChatGPT-Next-Web#3555]
> a.nextweb.fun
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find a.nextweb.fun: NXDOMAIN

> b.nextweb.fun
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find b.nextweb.fun: NXDOMAIN

**Comment by lwt09** [comment]
so am i ..

**Comment by Yidadaa** [comment]
#3557
