### ISSUE TITLE
搭建之后，怎么向github一样在网站栏有一个安装应用功能，像应用一样保存在桌面

### ISSUE THREAD

**Issue by jingyang7771** [ChatGPTNextWeb/ChatGPT-Next-Web#3556]
搭建之后，怎么向github一样在网站栏有一个安装应用功能，像应用一样保存在桌面
![gpt](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/102014407/ffae53c9-9cec-4232-920f-d6d4f4ea1f85)

**Comment by iccyuan** [comment]
安卓 chrome 浏览器有个添加到主屏幕，苹果没试过

**Comment by jingyang7771** [comment]
电脑桌面，类似这个
![gpt2](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/102014407/f4569448-41e2-4153-9225-b3eb9d70d23a)

**Comment by Yidadaa** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/Progressive_web_apps
