### ISSUE TITLE
域名*.nextweb.fun无法访问了

### ISSUE THREAD

**Issue by canguser** [ChatGPTNextWeb/ChatGPT-Next-Web#3557]
域名*.nextweb.fun无法访问了
<img width="778" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/24982663/d243cbe9-9d31-425e-9870-c48eba818bd6">

**Comment by siyukok** [comment]
+1

**Comment by lwt09** [comment]
#3555

**Comment by hjy2000** [comment]
+1

**Comment by yxlspider** [comment]
+1

**Comment by morninghut** [comment]
Try this website: https://gpt.nextapi.fun/

**Comment by sunkang316** [comment]
+1

**Comment by BLOSEregedit** [comment]
+1

**Comment by Aolcycle** [comment]
+1

**Comment by Enbuly** [comment]
555，代理服务器访问不了了

**Comment by yxlspider** [comment]
https://gpt.nextapi.fun/api/proxy    这个可以   
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/38686017/6d9f49f5-1f43-4ccd-8a9d-33566dc9c209)

**Comment by Enbuly** [comment]
> https://gpt.nextapi.fun/api/proxy 这个可以 ![image](https://private-user-images.githubusercontent.com/38686017/291173747-6d9f49f5-1f43-4ccd-8a9d-33566dc9c209.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODI5MjUsIm5iZiI6MTcwMjg4MjYyNSwicGF0aCI6Ii8zODY4NjAxNy8yOTExNzM3NDctNmQ5ZjQ5ZjUtMWY0My00Y2NkLThhOWQtMzM1NjZkYzljMjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA2NTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NDgxNjA3MmFhZjlhYjg1ZWNiNmZkZTM4ZWYyNDBhYzE2Y2EzNDYwNTllNzNhMDNhZDEzMWNiZDFjYTExZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ty3ItcgfEWni47P2I5cuPX-ctBam2mFfiUxTpUFgAdw)

谢谢，这个真的可以！

**Comment by Enbuly** [comment]
谢谢，真的可以！

**Comment by siegfried9516** [comment]
> https://gpt.nextapi.fun/api/proxy 这个可以 ![image](https://private-user-images.githubusercontent.com/38686017/291173747-6d9f49f5-1f43-4ccd-8a9d-33566dc9c209.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODMxMTksIm5iZiI6MTcwMjg4MjgxOSwicGF0aCI6Ii8zODY4NjAxNy8yOTExNzM3NDctNmQ5ZjQ5ZjUtMWY0My00Y2NkLThhOWQtMzM1NjZkYzljMjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA3MDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YmM0MDFiMTQ0NDc1OWU3OTUzOGQ2NzhjMmQzMWMxZmMxMWI1ZGJlNTZlNGNkNTFkNGNiY2IxYjIzYWIwMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JIQOcHb3o0yc9X1eZ9iimXXfGt468ELJn0C6Ovisp48)

Thanks a lot is now is work properly

**Comment by Yidadaa** [comment]
*.nextweb.fun 被未知原因强行停止解析了，新的域名已经迁移到 gpt.nextapi.fun

**Comment by BLOSEregedit** [comment]
如果是 docker 部署的，地址修改成以下
- BASE_URL=https://api.nextapi.fun

**Comment by lwt09** [comment]
之前的域名.nextweb.fun访问不了了，有什么办法可以拿到之前的缓存记录吗

**Comment by Yidadaa** [comment]
最新消息：看起来是被 NetCraft 识别为恶意钓鱼网站了，正在联系对方解决。

<img width="762" alt="0b3527a69fdfbd44c108a5de0f06ddb" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/16968934/510ea54b-8e64-4b3c-ba6f-d64b0c95ff55">

**Comment by shuang1729** [comment]
请问有新地址可以管理api么？以前那个api.nextweb.fun还没修复。辛苦啦。
