### ISSUE TITLE
[Feature] 建议把WebDev同步功能直接加进环境变量里

### ISSUE THREAD

**Issue by shentong0722** [ChatGPTNextWeb/ChatGPT-Next-Web#3558]
**你想要什么功能或者有什么建议？**
如题， 建议把WebDev同步功能直接加进环境变量里

**其他信息**
想要便捷的消息同步共享，又不想把WebDev账号密码分享给别人

**Comment by reece00** [comment]
不如你们新注册个共享号比再开发个同步服务器容易
