### ISSUE TITLE
[Feature] 是否可以添加默认模型进环境变量

### ISSUE THREAD

**Issue by mintdesu** [ChatGPTNextWeb/ChatGPT-Next-Web#3561]
因为每次都要选择 gpt-4-turbo 模型，是否有可以将某一模型设置为默认的功能，这样可以避免因为忘选常用模型而导致浪费大量Tokens

---

[Feature] Can a default model be added to the environment variables?

Since the gpt-4-turbo model has to be selected every time, is there a feature that allows setting a particular model as the default? This could prevent the waste of a significant number of Tokens due to forgetting to select the commonly used model.

**Comment by QAbot-zh** [comment]
有这个设置，但不是作为环境变量，我也支持作为环境变量
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/b0e5df01-2478-4332-b82b-dacb5a9c3e13)

**Comment by mintdesu** [comment]
这个设置仅限设置过的浏览器，并非严格意义上的默认模型。如果我换了一台设备或者换了一个浏览器，默认模型还是顺序排序，并非我设置的默认模型

---
This setting is only applicable to browsers that have been configured; it is not the default model in the strictest sense. If I switch to a different device or browser, the default model will still be in sequential order, not the default model I have set.

**Comment by mintdesu** [comment]
> 有这个设置，但不是环境信号，我也支持作为环境信号 ![图像](https://private-user-images.githubusercontent.com/40236765/291298670-b0e5df01-2478-4332-b82b-dacb5a9c3e13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MzUxMjQsIm5iZiI6MTcwMjkzNDgyNCwicGF0aCI6Ii80MDIzNjc2NS8yOTEyOTg2NzAtYjBlNWRmMDEtMjQ3OC00MzMyLWI4MmItZGFjYjVhOWMzZTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDIxMjcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMTk4Nzk1OGFhMDNlOGRhMTFkMGFkMmI1NDAwYTE3NmEwZmMyYzUyZjNhZGEyODUwMjJjMWIyNjdmNjFiNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.boNG6W5x2q7HZFUYyGOkGgjyCX5UzW3fvdCYjYOPsgQ)

这个设置仅限设置过的浏览器，并非严格意义上的默认模型。如果我换了一台设备或者换了一个浏览器，默认模型还是顺序排序，并非我设置的默认模型

This setting is only applicable to browsers that have been configured; it is not the default model in the strictest sense. If I switch to a different device or browser, the default model will still be in sequential order, not the default model I have set.

**Comment by Dean-YZG** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4545
目前最新版本已经支持自定义模型~~可以通过设置环境变量 DEFAULT_MODEL 来自定义
