### ISSUE TITLE
[Bug] 回答结果里面为什么不能正常显示图片？

### ISSUE THREAD

**Issue by aes256ctr** [ChatGPTNextWeb/ChatGPT-Next-Web#3571]
我的浏览器使用的是socks5代理，并没有做geoip（可能导致被屏蔽的IP不能被代理）
会不会是返回的结果里面，图片的url没有走代理？如果是，请告知图片的url是啥？我手工加入代理白名单
![为什么不能正常显示图片？](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/26144773/274a2b98-0777-4651-bdfb-f69bf11030db)

**Comment by aes256ctr** [comment]
![Snipaste_2023-12-19_09-46-00](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/26144773/32218140-d842-4551-8662-4335b396d38d)
难道`https://example.com/images/pic1.jpg`就是ChatGPT返回的图片？这也太...了

**Comment by TCOTC** [comment]
目前的客户端好像还不能显示图片的

**Comment by Yidadaa** [comment]
gpt 不保证返回图片 url 的正确性。
