### ISSUE TITLE
被Chrome识别为"危险网站"

### ISSUE THREAD

**Issue by ProgrammerHuang** [ChatGPTNextWeb/ChatGPT-Next-Web#3573]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/9100279/ba97b278-fccb-4875-a366-7582ed1daea6)

我们是使用docker部署在自己的服务器上.
上次部署的一版是6个月前部署的, 前两天出现了这个情况.
我们早上重新部署了最新的一版, 新的域名, 才部署两小时不到, 就出现了这个警告.
我们自己内部使用的, 并不对外一开放, 不大可能会是被举报.

**Comment by xiaoForest** [comment]
我昨天晚上部署到了vercel上，并且域名指向了我自己的域名，我的域名是国内备案的，有备案号。目前就我和我朋友用，还没显示过异常，哦对，我的有证书，应该不会被举报吧，不会出现你这个危险吧，😂，害怕。

**Comment by ProgrammerHuang** [comment]
同一个服务器的其它网站都正常
同一个域名的其它网站也都正常
同一类型的证书的网站也正常

我觉得不是被举报的, 也没有人盯着我们, 这才两个小时就被拉黑了.

我猜有可能是使用的第三方的库有收集信息, 或是有什么同类型的工具可能检测到我们同事在使用, 也可能是我同事使用VPN被收集了, 还不知道是什么引起的.

**Comment by Yidadaa** [comment]
最近频繁收到了类似的反馈，原因未知。

**Comment by zhangsherry** [comment]
> 我昨天晚上部署到了vercel上，并且域名指向了我自己的域名，我的域名是国内备案的，有备案号。目前就我和我朋友用，还没显示过异常，哦对，我的有证书，应该不会被举报吧，不会出现你这个危险吧，😂，害怕。

我部署在vercel上，域名是国内备案的，只有我自己使用，前两天在edge上已经显示被人举报不安全……举报完全是无稽之谈:)

**Comment by Lincest** [comment]
<img width="963" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/43769667/f6036156-afd2-4037-95f0-c5cff50f3da6">

遇到相同的问题, 不仅是网站被 chrome 识别为危险, 在更新镜像后我的整个域名被注册局封锁, 申诉后才发现是gpt next web的问题, 注册局封禁的原因也是因为钓鱼, 而我本人该域名下只部署了这个唯一的服务.

**Comment by Yidadaa** [comment]
@Lincest 这就非常扯淡了，我都不知道这玩意儿要去哪申诉。

**Comment by eiyahaoqiya** [comment]
edge 也遇到相同的问题

**Comment by H0llyW00dzZ** [comment]
yeah lmao I got this issue as well

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/df132eb9-caf7-4760-8411-6e9ba6bd9c7f)

**Comment by H0llyW00dzZ** [comment]
> [!NOTE]  
> This issue are something wrong with bad security such as netcraft or other
> because how the fuck it got red flagged

**Comment by reece00** [comment]
八成是类似网站钓鱼被列入特征库了吧，不知道哪个部分检查到符合钓鱼特征就自动封了，小网站哪来的触发这玩意。解决更玄了，谁知道管这的人在哪

**Comment by JianleiZhang** [comment]
<img width="1156" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/7637056/2e72c8ac-735c-465d-935f-b463f9d09d32">
我的也是，现在换域名并回退版本到了v2.9.11，希望赶快定位问题。

**Comment by ProgrammerHuang** [comment]
>  我的也是，现在换域名并回退版本到了v2.9.11，希望赶快定位问题。

我半年前部署的, 一直都没有升级, 也被标记了.

**Comment by ProgrammerHuang** [comment]
> @Lincest 这就非常扯淡了，我都不知道这玩意儿要去哪申诉。

Chrome和Edge的警告页面上也都有申诉入口, 不过是针对域名的, 也不知道有没有效

**Comment by ProgrammerHuang** [comment]
自己用的, 跳过警告, 也能用的.
就是有些讨厌

**Comment by zhangjian10** [comment]
一样的问题,被注册局封了，然后chrome 这还是提示这玩意，是不是 chatgpt 名称和 icon 这块和 openai 像，提示钓鱼。

**Comment by Twelveeee** [comment]
same problem

**Comment by vual** [comment]
感觉是你们二级域名带了 chatgpt 或 gpt 字眼

**Comment by zhangjian10** [comment]
> 感觉是你们二级域名带了 chatgpt 或 gpt 字眼

用的是 chat

**Comment by LittleState** [comment]
前几天在机器上用 docker 部署的，一直正常使用 3 天左右。然后昨晚想尝试下 vercel 部署，今早用电脑访问就发现被标记了…  不清楚是不是和这个有关

**Comment by QAbot-zh** [comment]
补充下个人案例：vercel 部署，完整二级域名解析，暂未出现标记情况；vercel部署，子域名解析，被标记（两个不同二级域名的子域名都被标记）；vercel 部署lobechat，子域名解析，暂未出现标记情况

**Comment by erbanku** [comment]
## Same here
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/79493862/8c4236a4-157a-434c-9ace-118e272f2397)
## Some other details
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/security/advisories/GHSA-4qmv-8xvw-v9f8

**Comment by Twelveeee** [comment]
> 感觉是你们二级域名带了 chatgpt 或 gpt 字眼

---

change `chatgpt.example.com` to `ai.example.com `

not working

**Comment by rammiah** [comment]
I met the same problem: 
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/26727562/cccd18be-8e2c-40f2-b42a-017cb425e545)

**Comment by WaterApple09** [comment]
找到一个很离谱的办法，vercel绑定@和www，@跳转到www上，因为实际最终的域名是www所以就算有警告也会是www，@没警告跳转一下就能把www的卡没，刚刚试着有效果
这警告也够玄学的，目前我三个域名一个.top直接跳红，一个link玄学爆红或者不报，爆红直接域名也没事一带目录就有事，还有一个tech一直没问题，真搞不懂了

**Comment by RyanNiu** [comment]
亲测已解决，通过https://search.google.com/search-console/ 添加认证自己的域名，并在诊断报告中上报误判

申诉原文参考
> This website does not require login, account passwords, or other information, and does not constitute an attempt to lure users into doing dangerous things, such as installing junk software or disclosing personal information, without knowing where the problem lies

申诉结果
<img width="399" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/23376595/585d2566-d46e-48c9-924a-499ee058d1d7">


> @Lincest 这就非常扯淡了，我都不知道这玩意儿要去哪申诉。

**Comment by erbanku** [comment]
> 亲测已解决，通过[search.google.com/search-console](https://search.google.com/search-console/) 添加认证自己的域名，并在诊断报告中上报误判
> 
> 申诉原文参考
> 
> > This website does not require login, account passwords, or other information, and does not constitute an attempt to lure users into doing dangerous things, such as installing junk software or disclosing personal information, without knowing where the problem lies
> 
> 申诉结果 <img alt="image" width="399" src="https://private-user-images.githubusercontent.com/23376595/292349349-585d2566-d46e-48c9-924a-499ee058d1d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMDk1NTYsIm5iZiI6MTcwMzIwOTI1NiwicGF0aCI6Ii8yMzM3NjU5NS8yOTIzNDkzNDktNTg1ZDI1NjYtZDQ2ZS00OGM5LTkyNGEtNDk5ZWUwNThkMWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAxNDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYTgxOTFkMDdiMDkyYWY5ZTE1NTZmOGY5OTA5YjgzNTIzMTBkN2RhN2JiOTM5Yzg3NDM3ZGMzOWM2NGUxZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3KHrqxgkwYzFhnAGEwNiH0wgBeSGFUFkNtgrV5ThEjc">
> 
> > @Lincest 这就非常扯淡了，我都不知道这玩意儿要去哪申诉。

我域名本来就在Google Search Console的，在Vercel部署里把项目二级域名改成别的，并在Google Search Console提交审核就解决了，新的二级域名没有问题。
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/79493862/c3769cb5-0275-4eeb-8438-d7f544ca1e7e)

**Comment by jijunhao** [comment]
> <img alt="image" width="963" src="https://private-user-images.githubusercontent.com/43769667/291560450-d95afe0d-a28b-4777-93cd-bd469fa77726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjU5MzYsIm5iZiI6MTcwMzIyNTYzNiwicGF0aCI6Ii80Mzc2OTY2Ny8yOTE1NjA0NTAtZDk1YWZlMGQtYTI4Yi00Nzc3LTkzY2QtYmQ0NjlmYTc3NzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA2MTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NmZlYzZlZWRkMWQ5ZWQ2NDUzMjhlYTdmOTgzOTVjODZkODA1M2Y4MGYzZTlkYjUzMTc1YzYxNjM1NGE3NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QdbFdQDxkN8byuG0qfUGVZ_5NsrUPUe4Lh1NO6IdywE">
> 遇到相同的问题, 不仅是网站被 chrome 识别为危险, 在更新镜像后我的整个域名被注册局封锁, 申诉后才发现是gpt next web的问题, 注册局封禁的原因也是因为钓鱼, 而我本人该域名下只部署了这个唯一的服务.

兄弟解决了吗，我的也被radix认证成了钓鱼，昨天晚上先被认证为危险，今天早上直接被封

**Comment by Lincest** [comment]
> > <img alt="image" width="963" src="https://private-user-images.githubusercontent.com/43769667/291560450-d95afe0d-a28b-4777-93cd-bd469fa77726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjU5MzYsIm5iZiI6MTcwMzIyNTYzNiwicGF0aCI6Ii80Mzc2OTY2Ny8yOTE1NjA0NTAtZDk1YWZlMGQtYTI4Yi00Nzc3LTkzY2QtYmQ0NjlmYTc3NzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA2MTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NmZlYzZlZWRkMWQ5ZWQ2NDUzMjhlYTdmOTgzOTVjODZkODA1M2Y4MGYzZTlkYjUzMTc1YzYxNjM1NGE3NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QdbFdQDxkN8byuG0qfUGVZ_5NsrUPUe4Lh1NO6IdywE">
> > 遇到相同的问题, 不仅是网站被 chrome 识别为危险, 在更新镜像后我的整个域名被注册局封锁, 申诉后才发现是gpt next web的问题, 注册局封禁的原因也是因为钓鱼, 而我本人该域名下只部署了这个唯一的服务.
> 
> 兄弟解决了吗，我的也被radix认证成了钓鱼，昨天晚上先被认证为危险，今天早上直接被封

解决了, 首先把解析记录删了, 然后到 https://radix.website/report-abuse 上报就可以了

**Comment by GriMu** [comment]
遇到同样的问题了，蹲个解决办法

**Comment by QAbot-zh** [comment]
> 亲测已解决，通过https://search.google.com/search-console/ 添加认证自己的域名，并在诊断报告中上报误判
> 
> 申诉原文参考
> 
> > This website does not require login, account passwords, or other information, and does not constitute an attempt to lure users into doing dangerous things, such as installing junk software or disclosing personal information, without knowing where the problem lies
> 
> 申诉结果 <img alt="image" width="399" src="https://private-user-images.githubusercontent.com/23376595/292349349-585d2566-d46e-48c9-924a-499ee058d1d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMDExMTcsIm5iZiI6MTcwMzMwMDgxNywicGF0aCI6Ii8yMzM3NjU5NS8yOTIzNDkzNDktNTg1ZDI1NjYtZDQ2ZS00OGM5LTkyNGEtNDk5ZWUwNThkMWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDAzMDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YjNhZWI2YWQzY2MyMzEyYjgzZmY1YTM3ZTQwMDQ3NTA1ZjAyNDFkYmRmYTYyZjU3MDE3OGZjMzZiZGE1ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YzYQ457iWbQWLcEGVHOsarSqJmy7gSSZeba6wLQLvYc">
> 
> > @Lincest 这就非常扯淡了，我都不知道这玩意儿要去哪申诉。

方法有效，感谢 👍

**Comment by ProgrammerHuang** [comment]
> 八成是类似网站（包括这玩意本身改的）钓鱼被列入特征库了吧，不知道哪个部分检查到符合钓鱼特征就自动封了，小网站哪来的触发这玩意。解决更玄了，谁知道管这的人在哪

我觉得很可能是这个原因, 有人使用这个系统做二次开发, 做些欺诈性的网站, 这些网站被列入危险网站, 网站内容的特征被用来识别类似的网站.

**Comment by fredliang44** [comment]
Hi @ProgrammerHuang @Twelveeee, we currently have a preliminary hypothesis that the project name is too close to ChatGPT. After initial discussions, we've decided to update the website name to `NextChat` to avoid this issue. You can pay attention to whether similar problems are encountered with the new domain name deployment. If such issues continue to occur, please provide feedback in this issue, and we will continue to follow up.

Additionally, because this change is not expected to directly remove the domain from Chrome's blocklist, domains that have already triggered Chrome's blocking policy will still need to appeal through the Google Search Console, as mentioned in https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3573#issuecomment-1867126500 to alleviate this.

**Comment by fredliang44** [comment]
Close for not receiving additional report.

**Comment by walterclozet** [comment]
使用最新版本搭建后, 站点名称调整为Next chat还是在数小时后被标记了. 按照评论说明提交反馈后火狐和chrome恢复正常, edge还是提示. 已提交申述等待结果.

**Comment by jokechen102** [comment]
> 最近频繁收到了类似的反馈，原因未知。

我看到这个issue关闭了，请问是由解决方案了吗？我的目前还是被识别为“危险网站”。

**Comment by longneck84** [comment]
再近常被netcraft 看上沒辦法，建議更改登入方式否則会被認為釣魚

我有一個vpn 直接被剷了

**Comment by Twelveeee** [comment]
> > 最近频繁收到了类似的反馈，原因未知。
> 
> 我看到这个issue关闭了，请问是由解决方案了吗？我的目前还是被识别为“危险网站”。

----

域名不要携带gpt 、 openai 或者chat (二级域名也不行)

然后向google (https://search.google.com/search-console/ )申诉

我的已经正常使用了

**Comment by walterclozet** [comment]
可以带chat的, 我的已经申述通过了, edge, firefox, chrome都可以了.

**Comment by walterclozet** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> You can bring chat, my application has been approved, edge, firefox, chrome are all acceptable.

chat as sub domain is ok, i use chat as sub domain.

**Comment by zhaobudaomingzi** [comment]
> 可以带chat的, 我的已经申述通过了, edge, firefox, chrome都可以了.

请问edge怎么申诉通过的，我的网站还是被识别成钓鱼网站，向微软提交反馈也没有收到任何回复
![屏幕截图 2024-01-03 110233](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/54617500/a979a2ea-719a-4d19-9ed7-833d8e8e0abe)

**Comment by walterclozet** [comment]
> > 可以带chat的, 我的已经申述通过了, edge, firefox, chrome都可以了.
> 
> 请问edge怎么申诉通过的，我的网站还是被识别成钓鱼网站，向微软提交反馈也没有收到任何回复 ![屏幕截图 2024-01-03 110233](https://private-user-images.githubusercontent.com/54617500/293825836-a979a2ea-719a-4d19-9ed7-833d8e8e0abe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTE0OTcsIm5iZiI6MTcwNDI1MTE5NywicGF0aCI6Ii81NDYxNzUwMC8yOTM4MjU4MzYtYTk3OWEyZWEtNzE5YS00ZDE5LTllZDctODMzZDhlOGUwYWJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAzMDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZjhiYTYwYTU1YTA0YTM4YTE1MjBlMmVlYmZkYWUwOWI3ODc5OTZjNzY0MThkMTRhOWI2M2U1ZWZhMTc3NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tjs5HJbYZVO7Ye5H1_-SuY0ipLpSzHD2_jYfToPdB5g)

向微软提交反馈后24小时内会恢复正常, 我反馈的时候不到6小时恢复. 如果你提交反馈了, 微软给发邮件了, 应该也是24小时内审核的.

**Comment by zhaobudaomingzi** [comment]
> > > 可以带chat的, 我的已经申述通过了, edge, firefox, chrome都可以了.
> > 
> > 
> > 请问edge怎么申诉通过的，我的网站还是被识别成钓鱼网站，向微软提交反馈也没有收到任何回复 ![屏幕截图 2024-01-03 110233](https://private-user-images.githubusercontent.com/54617500/293825836-a979a2ea-719a-4d19-9ed7-833d8e8e0abe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTE0OTcsIm5iZiI6MTcwNDI1MTE5NywicGF0aCI6Ii81NDYxNzUwMC8yOTM4MjU4MzYtYTk3OWEyZWEtNzE5YS00ZDE5LTllZDctODMzZDhlOGUwYWJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAzMDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZjhiYTYwYTU1YTA0YTM4YTE1MjBlMmVlYmZkYWUwOWI3ODc5OTZjNzY0MThkMTRhOWI2M2U1ZWZhMTc3NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tjs5HJbYZVO7Ye5H1_-SuY0ipLpSzHD2_jYfToPdB5g)
> 
> 向微软提交反馈后24小时内会恢复正常, 我反馈的时候不到6小时恢复. 如果你提交反馈了, 微软给发邮件了, 应该也是24小时内审核的.

好的谢谢，我25号就提交过反馈了，但是没有收到回复，我再重新申请一下吧

**Comment by blueblue147** [comment]
> > 机器人检测到问题正文的语言不是英语，会自动翻译。
> 
> > > <img alt="图像" width="963" src="https://private-user-images.githubusercontent.com/43769667/291560450-d95afe0d-a28b-4777-93cd-bd469fa77726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp XVCJ9 ..QdbFdQDxkN8byuG0qfUGVZ_5NsrUPUe4Lh1NO6IdywE">
> > > 我遇到了同样的问题。该网站不仅被 Chrome 识别为危险网站，而且在更新镜像后，我的整个域名都被注册表屏蔽了。申诉后发现是gpt next web的问题。注册表禁止的原因也是由于网络钓鱼。而我只在这个域名下部署了这唯一的服务。
> > 
> > 
> > 兄弟，你解决了吗？我的也被认证为基数钓鱼。昨晚首次被认证为危险，今天早上直接被封锁。
> 
> 已解决，先删除解析记录，然后举报到https://radix.website/report-abuse

我被注册局封锁后，删除解析记录，举报到https://radix.website/report-abuse说我仍然有违法行为，不给我解封，请问有什么办法吗？

**Comment by chenyu-01** [comment]
The issue still exist. And I report to edge and chrome. They didn't respond

**Comment by eric-gitta-moore** [comment]
For friends who are inconvenient to register Google Site, you can try to use `Report Incorrect Phishing Warning` to appeal for rights.

ref: https://github.com/dani-garcia/vaultwarden/discussions/4182#discussioncomment-7923508

<img width="1057" height="1049" alt="Image" src="https://github.com/user-attachments/assets/c57ece93-d792-45e0-9e13-1dae893d33a1" />
