### ISSUE TITLE
[Error] [API] Error when attepting to use OpenAI API Key.

### ISSUE THREAD

**Issue by jmartinezb3** [ChatGPTNextWeb/ChatGPT-Next-Web#3575]
**Describe the bug**
I have configured my api key in the app, but it shows me an error message that it did not show me before, I have tried in other UIs and there is no problem with my API key.

**Screenshots**
![imagen](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/94153214/2a0deeb7-6352-4dc3-bd2e-d72862243e25)

![imagen](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/94153214/d61ccfb8-b2f1-4d44-b4a6-65ad2879b006)

**Deployment**
Web vercel.
Firefox

**Comment by Yidadaa** [comment]
Please show me your env var `BASE_URL`.

**Comment by GOWxx** [comment]
Temporary setting of `OpenAI Endpoint` can be used to determine if it is an issue with the API.

**Comment by jmartinezb3** [comment]
> Please show me your env var `BASE_URL`.

Hello, I'm not using local deployment, I'm trying to use web demo, used the settings like the screen capture shows.

**Comment by jmartinezb3** [comment]
I already solved it, I changed the endpoint to https://api.openai.com Currently the default value that the app has does not work although before it did.

![imagen](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/94153214/ae3d954d-1592-4c14-99d8-662515eb887d)
