### ISSUE TITLE
[Bug] 显示1016错误码

### ISSUE THREAD

**Issue by Galun-yase** [ChatGPTNextWeb/ChatGPT-Next-Web#3577]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/49242428/7ca22f1e-7c39-4c94-ad16-e86c67f33fc1)

**Comment by ParseC-ctrl** [comment]
The proxy address has changed. Change the proxy address and redeploy your project
It may solve your problem
