### ISSUE TITLE
[Bug] Sudden {  "error": true,   "message": "Load failed" } ERROR

### ISSUE THREAD

**Issue by m0rg5** [ChatGPTNextWeb/ChatGPT-Next-Web#3580]
**Describe the bug**
Mid conversation, and before any OS or CGNW update, I got the error
`{
  "error": true,
  "message": "Load failed"
}
`
I checked credit is available (it was), and I changed the API KEY, then updated CGNW yet the issue continues, hence I can't currently use CGNW.

**To Reproduce**
Error to any chat msg, with any model.

**Screenshots**
<img width="963" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/8669538/00469284-7a64-4424-ac6b-4568005f7a61">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.2 (no update or issue before this)

**Comment by H0llyW00dzZ** [comment]
wait what, I think that problem its in server-side not client side

**Comment by m0rg5** [comment]
Yeah, very weird, also getting a sync fail on the webdav I setup, that def did work prior.
Disabling firewall (LuLu) made no difference.

Any ideas?

**Comment by DongChunlei** [comment]
> **Describe the bug** Mid conversation, and before any OS or CGNW update, I got the error `{ "error": true, "message": "Load failed" } ` I checked credit is available (it was), and I changed the API KEY, then updated CGNW yet the issue continues, hence I can't currently use CGNW.
> 
> **To Reproduce** Error to any chat msg, with any model.
> 
> **Screenshots** <img alt="image" width="963" src="https://private-user-images.githubusercontent.com/8669538/291587964-00469284-7a64-4424-ac6b-4568005f7a61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTQ2NzAsIm5iZiI6MTcwMzA1NDM3MCwicGF0aCI6Ii84NjY5NTM4LzI5MTU4Nzk2NC0wMDQ2OTI4NC03YTY0LTQ0MjQtYWM2Yi00NTY4MDA1ZjdhNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMDYzOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVkNzlhMTU0ZTJkZGNhMWI1MDJmY2YxMjY3Y2NjMWQ0NjY3ZTdiMDg1OTQzNDA0NDQ3ODNhZGFmMDAxYTgyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Trs3-OX-fQywEU2xS6PrL9UGbx5gofq6lPj1CNLgAn0">
> 
> **Desktop (please complete the following information):**
> 
> * OS: MacOS Sonoma 14.2 (no update or issue before this)

I have the same issue
<img width="258" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/34806619/45f7d77f-67dd-4cfd-bee5-b5aa99e5283f">

**Comment by devchenli** [comment]
same issue , any update?

**Comment by DongChunlei** [comment]
> same issue , any update?

app version: v2.9.12 and v2.9.13
OS: MacOS Sonoma 14.2

**Comment by H0llyW00dzZ** [comment]
On windows/linux works fine

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/498dfdda-1c00-418e-9300-f5cd550fafed)

**Comment by Yidadaa** [comment]
The old *.nextweb.fun is broken, try to replace all the `*.nextweb.fun` to `gpt.nextapi.fun` in your settings.

**Comment by m0rg5** [comment]
> The old *.nextweb.fun is broken, try to replace all the `*.nextweb.fun` to `gpt.nextapi.fun` in your settings.

I've added, HTTPS://gpt.nextapi.fun (also tried gpt.nextapi.fun) , in OpenAI Endpoint, **no change**. 

Also, excuse the possible noob Q - but why are we using a non-official endpoint?
