### ISSUE TITLE
[Bug] 消息块无内容，只有一个黑块

### ISSUE THREAD

**Issue by kwjlhh** [ChatGPTNextWeb/ChatGPT-Next-Web#3589]
在使用自定义接口时，有时候会出现消息为黑块的情况，但后台消息已经返回完成。
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/149999696/9aafcffb-dc9a-4692-ac31-8c8ce43cd5e8)

**Comment by Yidadaa** [comment]
检查接口是否符合 openai 规范。
