### ISSUE TITLE
[Feature] 让站点支持添加noindex标签以阻止搜索引擎对站点的收录来保护站点

### ISSUE THREAD

**Issue by Anjiurine** [ChatGPTNextWeb/ChatGPT-Next-Web#3597]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
是

**你想要什么功能或者有什么建议？**
当给项目套上一个被搜索引擎收录过的域名时，这个站点可能会被收录，从而被某些人利用。让站点支持添加noindex标签以阻止搜索引擎对站点的收录来保护站点。

**Comment by Yidadaa** [comment]
目前已经通过 robots.txt 来防止网站被检索。

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/public/robots.txt
