### ISSUE TITLE
[Feature] 在云同步中支持mongodb数据库

### ISSUE THREAD

**Issue by Anjiurine** [ChatGPTNextWeb/ChatGPT-Next-Web#3598]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
是

**Comment by H0llyW00dzZ** [comment]
> [!NOTE]  
> Additional Note For this Issue
> It is not recommended to chain front-end to front-end with MongoDB in the cloud. This is in contrast to a front-end to back-end configuration, which is suitable for chaining with MongoDB in the cloud.

**Comment by Anjiurine** [comment]
> Note
> 
> Additional Note For this Issue It is not recommended to chain front-end to front-end with MongoDB in the cloud. This is in contrast to a front-end to back-end configuration, which is suitable for chaining with MongoDB in the cloud.

However, compared with upstash's redis database, mongodb has a more intuitive data storage structure and easier configuration method, so this function may be considered to be added.
