### ISSUE TITLE
[Feature] 希望吧 gpt4-mobile 加上

### ISSUE THREAD

**Issue by dashixiong-11** [ChatGPTNextWeb/ChatGPT-Next-Web#3603]
希望吧 gpt4-mobile 加上

**Comment by QAbot-zh** [comment]
通过custom_model加上不就行，有什么特殊返回吗？

**Comment by dashixiong-11** [comment]
> 通过custom_model加上不就行，有什么特殊返回吗？

没用，model改成 gpt-4-mobile 接口报错

**Comment by QAbot-zh** [comment]
> > 通过custom_model加上不就行，有什么特殊返回吗？
> 
> 没用，model改成 gpt-4-mobile 接口报错

这问题该找你的上游解决啊，mobile不是官方api模型，只是人家逆向plus出来的，没有文档怎么做适配
