### ISSUE TITLE
[Bug] 当使用code登录的时候，用不了gemini-pro

### ISSUE THREAD

**Issue by DBvc** [ChatGPTNextWeb/ChatGPT-Next-Web#3616]
**Describe the bug**

使用code登录的时候，再选择gemini-pro模型，访问google的接口会带上code，而不是google api key

问题可能在这一行代码上

<img width="490" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/5419886/96b3cca6-9617-4bb8-94b5-33ed68860cd5">

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/bda3098a31284fa93bb36f639d304ee693c7add1/app/api/google/%5B...path%5D/route.ts#L43C13-L43C13

**To Reproduce**
- 用vercel部署
- 设置登录的code，设置google api key
- 访问页面，使用code登录
- 选择gemini-pro模型
- 发送消息，会报错，因为apikey用错了

**Expected behavior**
使用code登录的时候，可以正常使用gemini-pro模型

**Screenshots**

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]
 - Version [120.0.6099.129]

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by shenpvip** [comment]
> @DBvc hi, this issue should have been resolved, you can check it again

Do you need to use a VPN for accessing the Gemini-Pro model?

**Comment by bios99** [comment]
遇到同样的问题，而且我已经升级到最新

**Comment by MemoryReload** [comment]
still got this problem, anyone knows if this is fixed or not?
