### ISSUE TITLE
[Feature] Show token usage below chat title

### ISSUE THREAD

**Issue by Cow258** [ChatGPTNextWeb/ChatGPT-Next-Web#3623]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

![螢幕截圖 2023-12-25 04 33 20](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/14261588/d3030000-4f26-47f0-ad51-cdd1632c00ca)

目前我們無法知道每組對話究竟使用了多少 token
而本身`歷史訊息長度壓縮閾值`和`單次回應限制`應該是有計算 token 量的
所以如果可以在每次發送和接收時
都把 token 用數加總到對話的對像中
UI 就可以顯示每個對話使用了多少 token

Currently, we are unable to determine the exact number of tokens used in each conversation. 
The `history message length compression threshold` and the `single response limit` should involve a calculation of the token count. 
Therefore, 
if we could aggregate the number of tokens used into the conversation's context with each send and receive action, the UI could display the number of tokens utilized for each conversation.

**Comment by reece00** [comment]
test

**Comment by Yidadaa** [comment]
意义不大。
