### ISSUE TITLE
[Bug] API Key does not exist in the request in the latest version

### ISSUE THREAD

**Issue by ShinoharaHaruna** [ChatGPTNextWeb/ChatGPT-Next-Web#3628]
**Describe the bug**
目前部署在vercel上的版本到提交bd1e311，和ChatGPT API对话，得到：

```json
{
  "error": {
    "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

通过测试，API Key可用；密码直接复制过vercel环境变量，所以也不会是密码输错。

因此，这可能是软件bug。

**To Reproduce**
部署当前的最新版本（到提交bd1e311，on vercel），配置环境变量（包括API Key和密码），进行对话，失败。

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Brave
 - Version: 1.61.109

**Comment by H0llyW00dzZ** [comment]
it's because of this https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/3626

**Comment by H0llyW00dzZ** [comment]
merge a bug to main

**Comment by H0llyW00dzZ** [comment]
> [!TIP]
> Temporary Fix:
- use custom end point

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/e892601a-b05d-4f3d-966b-a4f5c8f09061)

**Comment by fredliang44** [comment]
Hi @ShinoharaHaruna @H0llyW00dzZ, the issue should be resolved in pr, you can have a try again  https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/3629
