### ISSUE TITLE
[Bug] 新版本输入登录密码一直错误

### ISSUE THREAD

**Issue by AcamelQ** [ChatGPTNextWeb/ChatGPT-Next-Web#3631]
我这边更新到新版本后，登录密码一直错误，修改后，重新登入也不行。显示要重新输入密码。

**Comment by xyz1396** [comment]
我也是这样，环境变量重设了都没用

**Comment by sagiwei** [comment]
+1

**Comment by fredliang44** [comment]
@xyz1396 @AcamelQ Hi, I cannot reproduce this issue from my end, could you please share which enviromint variables you've set in your deployment?

**Comment by fredliang44** [comment]
And please also provide which mode you are using(setting api key from the UI or through the deployment env)

**Comment by OkamiFeng** [comment]
I have same problem.
Here is my vercel env:
- OPENAI_API_KEY
- CODE

from api key or from code, can't access.

**Comment by AcamelQ** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/46049704/1a66f393-1666-40ec-a2e4-813c3d8f80c7)
the above is my deployment edition. it updated 5 hours ago 74b38c5.
the following is my environment setting:
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/46049704/37d58659-ed2c-4845-afe6-84b60c53044d)

**Comment by shenpvip** [comment]
I encountered the same issue as well; GPT-3.5 is not working, and it's showing an API key error. However, Gemini is working fine.

{
  "error": {
    "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by shenpvip** [comment]
我手动同步了一下最新代码，vercel重新构建就好了

**Comment by xiaoForest** [comment]
我是 点了立即重置，然后重新输入key好的

**Comment by fredliang44** [comment]
@AcamelQ @OkamiFeng I tried to reproduce this issue following by setting the environment variables you just provided, still cannot reproduce the issue. Could you try following https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3631#issuecomment-1868797199 to update to latest commit check whether thw issue still exists?

**Comment by fudianchn** [comment]
+1, me too, it's bug

**Comment by xyz1396** [comment]
> @xyz1396 @AcamelQ Hi, I cannot reproduce this issue from my end, could you please share what environment variables you've set in your deployment? (just share the variables name is fine)

fixed after updating. thanks so much.

**Comment by devyujie** [comment]
这个bug很久了感觉，CODE一直不稳定，感觉输入和没输入一样

**Comment by fredliang44** [comment]
@devyujie Do you have anyway to stable reproduce the issue? I could try to locate the root cause.

**Comment by devyujie** [comment]
> @devyujie Do you have anyway to stable reproduce the issue? I could try to locate the root cause.

没法稳定复现，我意思前端输入访问码的方式可不可以改一下，输入完给个确认按钮啥的，有时候感觉输入了访问码，并没用，我给朋友用的时候是这样的。

**Comment by xsfecho** [comment]
me too

**Comment by bios99** [comment]
碰到同样的问题：

**Comment by adamzhang1987** [comment]
看一下是不是密码里面有逗号，逗号用来分隔多个密码的，我就是碰到了这个情况
