### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Cherry291** [ChatGPTNextWeb/ChatGPT-Next-Web#3644]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
后端使用的one-api作为key池，前端部署在web.a.com环境变量使用BASE_URL：api.a.com作为接口请求地址，正常提问没有问题，地址是https://web.a.com/v1/chat/completions，当时遇到https://web.a.com/v1/chat/completions?retry=9这种重试链接的时候就会报错，我尝试手动改为https://api.a.com/v1/chat/completions?retry=9，的时候可以访问了
**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [chrome]
 - 版本： [2.9.13]
 - 部署方式：[vercel]

**Comment by Yidadaa** [comment]
请使用标准的 openai api url，不要带奇怪的参数。

**Comment by Cherry291** [comment]
<img width="694" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/71474660/c5f91cbe-aea2-4cd0-93bc-346f7acfbd46">
就是标准api，直接请求没问题，当遇到one-api重试的时候 这个api就报错404了

**Comment by Cherry291** [comment]
使用示例网站进行请求的时候 ，请求网址是我的api地址，重试的时候也是api地址，web页面是你的示例网站，当我使用我自己部署的站点的时候，请求的网址是web页面的域名而不是api域名，但是还是可以提问，一旦遇到自动重试的时候，就报错404了
<img width="639" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/71474660/61160313-2d58-4265-947f-f44574015698">

**Comment by acfock** [comment]
我也遇到了这种问题，重定向的uri是/v1/chat/completions?retry=4，正常请求openai的uri是/api/openai/v1/chat/completions
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/29273179/97d2f206-f91f-40cd-bd5d-d887ea12865b)
