### ISSUE TITLE
[Bug] Google api

### ISSUE THREAD

**Issue by JDxiaojuju** [ChatGPTNextWeb/ChatGPT-Next-Web#3645]
设置了 Google Get API key 也弄了环境变量还是无法使用

**Comment by StudentYee** [comment]
遇到相同问题，`GOOGLE_URL` 和 `GOOGLE_API_KEY` 环境变量均以设置但提示 `API key not valid. Please pass a valid API key.`
设置中采用客制化设置模型时可正常使用。

**Comment by JDxiaojuju** [comment]
> 遇到相同问题，`GOOGLE_URL`和`GOOGLE_API_KEY`环境指标均以设置但提示`API key not valid. Please pass a valid API key.` 设置中采用客制化设置模型时可正常使用。
有解决办法了吗

**Comment by choydone** [comment]
Delete CODE environment variable, call Google api has a bug, after configuring CODE will cause key to be set to CODE value.

**Comment by fredliang44** [comment]
duplicate issue, plz check latest commit https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3616
