### ISSUE TITLE
[Bug] 头像无法正常显示/avatar can not display normally

### ISSUE THREAD

**Issue by muxinxy** [ChatGPTNextWeb/ChatGPT-Next-Web#3646]
**Describe the bug**

头像无法正常显示/avatar can not display normally

[https://cdn.staticfile.org/emoji-datasource-apple/15.0.1/img/apple/64/1f603.png](https://cdn.staticfile.org/emoji-datasource-apple/15.0.1/img/apple/64/1f603.png)

**Screenshots**

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/32673109/f7fc2b2a-bd2a-453e-bee8-9f75a773527f)

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/32673109/15efbbc7-d523-432d-be3e-c6b97499b136)

**Deployment**
- [ ] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Windows 10**
 - Browser [e.g. chrome, safari] **Chrome**
 - Version [e.g. 22] **2.9.13**

**Comment by fudianchn** [comment]
+1, me too, it's new version bug. rollback

**Comment by JIeJaitt** [comment]
我也有这个问题

**Comment by xiaozhou26** [comment]
The cdn of the picture is broken, friends

**Comment by alexallen1** [comment]
遇到一样问题，还以为需要被强迫更新

**Comment by H0llyW00dzZ** [comment]
- #3647
