### ISSUE TITLE
Gemini使用问题

### ISSUE THREAD

**Issue by careylipu** [ChatGPTNextWeb/ChatGPT-Next-Web#3652]
部署Docker时设置了Gemini Pro key设置后，但是无法使用，或者不知道如何使用。能不能介绍一下，谢谢！

**Comment by JIeJaitt** [comment]
> 部署Docker时设置了Gemini Pro key设置后，但是无法使用，或者不知道如何使用。能不能介绍一下，谢谢！

切换成gemini模型不就能用了吗？

**Comment by careylipu** [comment]
> > 部署Docker时设置了Gemini Pro key设置后，但是无法使用，或者不知道如何使用。能不能介绍一下，谢谢！
> 
> 切换成gemini模型不就能用了吗？

模型切换菜单内没有Gemini模型

**Comment by JIeJaitt** [comment]
@careylipu 我这里是有的，在最下面

<img width="406" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/77219045/beb1bc51-50bd-4759-990e-627fa72faf52">

**Comment by careylipu** [comment]
我是Docker部署的 2.9.13版本 ，输入了 openaikey和google api key 环境变量，没有输入 google api url。

**Comment by JIeJaitt** [comment]
@careylipu 我是vercel部署的，只是在部署的时候在环境变量输入了google api key就能用了，那你可能是docker 镜像的问题

**Comment by catsimple** [comment]
> 我是Docker部署的 2.9.13版本 ，输入了 openaikey和google api key 环境变量，没有输入 google api url。

docker的是两周前构建的，gemini是两天前引入的，这是什么时空穿越

**Comment by Yidadaa** [comment]
Docker 尚未更新，请耐心等待发版。

**Comment by srcrs** [comment]
可以试试这个，它会自动同步最新版本打包镜像，目前可正常使用
https://hub.docker.com/r/unserialize/chatgpt-next-web-image

**Comment by devyujie** [comment]
我这里也不能用，vercel部署的，然后设置了GOOGLE_URL，用的这个开源[项目](https://github.com/antergone/palm-proxy)做了个代理，配合这个[套壳](https://github.com/babaohuang/GeminiProChat)用是没问题的，但是Next-Web就用不了。

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/48620527/455ff9d5-af89-4356-a0f4-8246eaf1d3df)

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/48620527/d89ce8a7-6452-4a25-8c8c-bc8a0e5a1ba7)

**Comment by JDxiaojuju** [comment]
密钥弄了 接口也是用的google
<img width="673" alt="屏幕截图 2023-12-26 201517" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/130148769/a82b339b-169a-4490-b638-8ae123f674ac">

**Comment by cyanhao** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/58835305/d2cec09a-6258-4bfb-ab8d-f9ce24e5bbc3)
能用，不过这个prompt应该可以在优化下

**Comment by newb0311** [comment]
google api url要填什么？

**Comment by fredliang44** [comment]
New release v2.10.1 have been published, you can upgrade to latest docker image and have a try: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.10.1

**Comment by catsimple** [comment]
gemini-pro model 默认会被带上用于openai chatgpt的DEFAULT_SYSTEM_TEMPLATE
这是个bug

**Comment by NEPDream** [comment]
> gemini-pro model 默认会被带上用于openai chatgpt的DEFAULT_SYSTEM_TEMPLATE 这是个bug

可以在设置中关闭那个系统注入就好了

**Comment by newb0311** [comment]
在Nextchat里调用Gemini pro,问它知识库截至什么时候， 显示是2021年9月，在Geminiprochat里面用同样的api key，问它的知识库是2022年4月，是不是GOOGLE_URL (optional) Google Gemini Pro Api Url里面的地址更换下，就可以用到更新的Gemini pro呢？

**Comment by firstuanl** [comment]
> 可以先临时试试这个，它会自动同步最新版本打包镜像，目前可正常使用，等待官方更新后再切换。 https://hub.docker.com/r/unserialize/chatgpt-next-web-image

Gemini pro api，OPENAI_API_KEY=sk-xxxx这段应该是什么

**Comment by careylipu** [comment]
> > 可以先临时试试这个，它会自动同步最新版本打包镜像，目前可正常使用，等待官方更新后再切换。 https://hub.docker.com/r/unserialize/chatgpt-next-web-image
> 
> Gemini pro api，OPENAI_API_KEY=sk-xxxx这段应该是什么

在Openai官网注册账号，获取key可以免费体验gpt3.5

**Comment by firstuanl** [comment]
> > > 可以先临时试试这个，它会自动同步最新版本打包镜像，目前可正常使用，等待官方更新后再切换。 https://hub.docker.com/r/unserialize/chatgpt-next-web-image
> > 
> > 
> > Gemini pro api，OPENAI_API_KEY=sk-xxxx这段应该是什么
> 
> 在Openai官网注册账号，获取key可以免费体验gpt3.5

想用Gemini pro api，这个 OPENAI_API_KEY 不变吗

**Comment by HQ-random** [comment]
请教各位大佬，现在在vercel上面进行部署了chatgpt与gemini pro，为什么机器人模型没有gemini的选项，谢谢
![error2](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/133569887/8437d42b-45ef-44cf-8de1-5899c46302a6)
![error1](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/133569887/5a344652-f127-4c56-8b42-a8126412ac46)
