### ISSUE TITLE
面具的emoji表情图片全部失效了。

### ISSUE THREAD

**Issue by Plainct** [ChatGPTNextWeb/ChatGPT-Next-Web#3660]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
面具的emoji表情图片全部失效了。

**如何复现**
[请告诉我们你是通过什么操作触发的该问题。](https://cdn.staticfile.org/emoji-datasource-apple/14.0.0/img/apple/64/1f606.png)
直接访问链接，图片也全是图裂

**截图**
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/120462767/c166abaf-d6a9-405a-ab4e-b93d0b07818b)

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by sunsky89757** [comment]
app/components/emoji.tsx
我查了下，同步没有检测到这个文件里的更改，手动把自己代码库里的代码替换为作者的该文件内代码，重新部署即可解决。

**Comment by gitbloodwolf** [comment]
I'm having the same issues with docker

**Comment by KenChen1998** [comment]
How to fix this problem in docker

**Comment by Derekxin** [comment]
How to fix this problem in docker？

**Comment by lem0ke** [comment]
是七牛云的锅，我也遇到了一样的问题。上周刷公众号文章还看到有人说这个事，我还搁那儿吃瓜，没想到吃着吃着这瓜落我头上了。附链接：https://mp.weixin.qq.com/s/ro29Wa6jndK5bcd997XD-A
