### ISSUE TITLE
[Feature] 求分享 DALLE GPT4V 等能力的开发进度

### ISSUE THREAD

**Issue by devyujie** [ChatGPTNextWeb/ChatGPT-Next-Web#3662]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
、

**你想要什么功能或者有什么建议？**
能分享一下 DALLE GPT4V 等能力的开发进度吗，还是有什么大招，感觉重大功能推进搁置很久了。[#3217](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3217)

**有没有可以参考的同类竞品？**
、

**其他信息**
、

**Comment by vual** [comment]
我这边有实现，可以了解下。https://github.com/vual/ChatGPT-Next-Web-Pro
