### ISSUE TITLE
[Feature] 建议部署时增加环境变量，配置是否注入系统级提示消息

### ISSUE THREAD

**Issue by Scorpio-xu** [ChatGPTNextWeb/ChatGPT-Next-Web#3665]
建议部署时增加环境变量，配置是否注入系统级提示消息
我使用的是 Gemini 模型，分享给别人后，别人老是说我这是 ChatGPT，是因为系统发了一条“you are chatgpt……”的消息，然后我就得告诉他在设置中把“注入系统级提示消息”这个设置项关掉。
能不能把这个设置项改到环境变量里啊，或者默认关闭，谢谢大佬

**Comment by H0llyW00dzZ** [comment]
works fine now for me 

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/46793654-0c54-4030-96ec-bf2a9f473f46)

been working on this
https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/commit/b9ed66141d46b77e33cc7d63bbb20292c2fdcdef

**Comment by fredliang44** [comment]
@Scorpio-xu injecting system message is useful in most cases, I guess we might need to support different system default message in the future to adjust different model provider

**Comment by H0llyW00dzZ** [comment]
> @Scorpio-xu injecting system message is useful in most cases, I guess we might need to support different system default message in the future to adjust different model provider
yeah 
not right now, gemini still unstable I've been testing on it

**Comment by walterclozet** [comment]
> @Scorpio-xu injecting system message is useful in most cases, I guess we might need to support different system default message in the future to adjust different model provider

can i set these system messages via environment variables?

**Comment by Scorpio-xu** [comment]
> works fine now for me
> 
> ![image](https://private-user-images.githubusercontent.com/17626300/293056562-46793654-0c54-4030-96ec-bf2a9f473f46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MzAzMDIsIm5iZiI6MTcwMzczMDAwMiwicGF0aCI6Ii8xNzYyNjMwMC8yOTMwNTY1NjItNDY3OTM2NTQtMGM1NC00MDMwLTk2ZWMtYmYyYTlmNDczZjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDAyMjAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNjAzYzFlNzA1ODAxMmM0MGJhYjBmMjMwYWUwNzIyNDE0Y2EyM2VkODc5N2EyZGViNjQ0MmYwMjM0NzFiYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IBMDfvXHqMB6b_5tVMwCvnYkrZh6ufoafi9OwHBkhG4)
> 
> been working on this [H0llyW00dzZ@b9ed661](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/commit/b9ed66141d46b77e33cc7d63bbb20292c2fdcdef)

The image falsely claims to be ChatGPT, but in reality, it is not.

**Comment by Scorpio-xu** [comment]
> @Scorpio-xu injecting system message is useful in most cases, I guess we might need to support different system default message in the future to adjust different model provider@Scorpio-xu 注入系统消息在大多数情况下都是有用的，我想我们将来可能需要支持不同的系统默认消息来调整不同的模型提供者



> @Scorpio-xu injecting system message is useful in most cases, I guess we might need to support different system default message in the future to adjust different model provider

是的，确实有用，但是我没说把它关掉，而是增加一个环境变量来控制它，是否开启由服务提供者自己选择。
加了这句话后，他说自己是ChatGPT，可他明明不是，产生误解了。

**Comment by Scorpio-xu** [comment]
> @Scorpio-xu injecting system message is useful in most cases, I guess we might need to support different system default message in the future to adjust different model provider

Yes, it is indeed useful, but I didn't say to turn it off. Instead, I suggested adding an environment variable to control it, allowing the service provider to decide whether to enable it. After adding this sentence, he claimed to be ChatGPT, but he clearly is not, causing a misunderstanding.

**Comment by PaperPlaneDeemo** [comment]
i have the same issue, when i use gemini pro, the system injects system-level prompt messages that says you are chatgpt. How can I turn it off when i use  gemini pro?

**Comment by H0llyW00dzZ** [comment]
> i have the same issue, when i use gemini pro, the system injects system-level prompt messages that says you are chatgpt. How can I turn it off when i use gemini pro?

in chat settings 

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/488394ef-4d3f-4262-98bf-6f4bc9a287fb)

**Comment by QAbot-zh** [comment]
同意，至少应该默认为不注入

**Comment by magicds** [comment]
I believe this design is quite poor, and it has been set as the default behavior. I am perplexed; can I disable it globally?
