### ISSUE TITLE
[Bug]  搭建好了需要开启HTTPS才能正常用

### ISSUE THREAD

**Issue by bigmn666** [ChatGPTNextWeb/ChatGPT-Next-Web#3666]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/110153229/6bc0481f-7337-493e-ba9e-221aeeaa4e2e)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by fredliang44** [comment]
@bigmn666 Hi, could you please tell me when did you deploy the service first time? you can follow this instructions to resolve this issue https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3573#issuecomment-1867126500

**Comment by walterclozet** [comment]
我昨天下午16点(东八区)部署, 修改域名为nicochat避免和chatgpt过度类似, 绑定自己的域名后也被标记了.

**Comment by fredliang44** [comment]
> 我昨天下午16点(东八区)部署, 修改域名为nicochat避免和chatgpt过度类似, 绑定自己的域名后也被标记了.

Let me double confirm is this your first time deploying on a completely new domain?

**Comment by walterclozet** [comment]
> > 我昨天下午16点(东八区)部署, 修改域名为nicochat避免和chatgpt过度类似, 绑定自己的域名后也被标记了.
> 
> Let me double confirm is this your first time deploying on a completely new domain?

yes, forked it to my github, changed some chatgpt stuff, then bind to chat.mydomain.com after about 3 hour is makrd unsafe by both microsoft smart screen and firefox.

**Comment by walterclozet** [comment]
btw, i have changed the chatgpt logo after i reported to microsoft and google.

**Comment by byte-hzzh** [comment]
> btw, i have changed the chatgpt logo after i reported to microsoft and google.

Bro, I think your domain was previously flagged by Google before you bought it, and I would suggest the site not to use chat,gpt similar names

**Comment by fred-bf** [comment]
Please feel free to comment if you still encounter similar issue. Close for not active reporting same issue
