### ISSUE TITLE
[Feature] 关于调整模型顺序和默认模型的建议

### ISSUE THREAD

**Issue by NEPDream** [ChatGPTNextWeb/ChatGPT-Next-Web#3676]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**

1. 当前CUSTOM_MODELS无法改变启动的模型的顺序
2. 没有环境变量可以指定新用户第一次登陆网页时候的默认模型

**你想要什么功能或者有什么建议？**

1. 希望CUSTOM_MODELS的模型顺序可以决定页面显示的模型顺序，或者增加一个参数去排序模型的顺序
2. 希望可以增加一个环境变量，当新用户登陆网页时候，可以自动选择变量设置的模型为默认模型

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by ji-jinlong** [comment]
截止目前好像依旧没有此功能

**Comment by Dean-YZG** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4545
感谢社区小伙伴的贡献，目前最新版本已经支持了通过环境变量自定义默认模型~~

**Comment by GrayXu** [comment]
调整模型顺序功能仍然是缺失的，应该reopen这个issue
