### ISSUE TITLE
[Bug] vercel部署的gemini pro不能用

### ISSUE THREAD

**Issue by devyujie** [ChatGPTNextWeb/ChatGPT-Next-Web#3696]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
使用vercel部署的，部署参数只填了API KEY，使用的时候是美国节点，不回复内容，只有在前台使用填入KEY的时候才可以用。

**如何复现**
、

**截图**
、

**一些必要的信息**
 - 系统：windows 10
 - 浏览器： chrome
 - 版本： 2.10.1
 - 部署方式：vercel

**Comment by acche** [comment]
用不了,错误提示: User location is not supported for the API use.User location is not supported for the API use.

**Comment by weeway** [comment]
> 用不了,错误提示: User location is not supported for the API use.User location is not supported for the API use.

@acche 我用cf的配置子域名指向vercel的ip，想国内直接访问，不挂梯子。结果遇到同样的问题。后面通过指定edge function的执行的偏好节点为美国节点，现在可以正常使用

修改地方如下：
<img width="1104" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/12637868/200305ab-81ac-42fb-97a4-11d387bf9a59">

**Comment by weeway** [comment]
根据 gemini pro 的可用地区和 vercel edge function 的可用地区取交集，得到下面的可以区域：
```
"sfo1",
"cle1",
"iad1",
"pdx1",
"bom1",
"cpt1",
"gru1",
"hnd1",
"icn1",
"kix1",
"sin1",
"syd1"
```

**Comment by fishredleung** [comment]
> 根据 [gemini pro 的可用地区](https://ai.google.dev/available_regions?hl=zh-cn#available_regions) 和 [vercel edge function 的可用地区](https://vercel.com/docs/edge-network/regions) 取交集，得到下面的可用区域：
> 
> ```
> "sfo1",
> "cle1",
> "iad1",
> "pdx1",
> "bom1",
> "cpt1",
> "gru1",
> "hnd1",
> "icn1",
> "kix1",
> "sin1",
> "syd1"
> ```

所以說如果要用gemini 必需要使用Vercel 部署? 如果部署在本地的機器上面就用不了?

**Comment by weeway** [comment]
> > 根据 [gemini pro 的可用地区](https://ai.google.dev/available_regions?hl=zh-cn#available_regions) 和 [vercel edge function 的可用地区](https://vercel.com/docs/edge-network/regions) 取交集，得到下面的可用区域：
> > ```
> > "sfo1",
> > "cle1",
> > "iad1",
> > "pdx1",
> > "bom1",
> > "cpt1",
> > "gru1",
> > "hnd1",
> > "icn1",
> > "kix1",
> > "sin1",
> > "syd1"
> > ```
> 
> 所以說如果要用gemini 必需要使用Vercel 部署? 如果部署在本地的機器上面就用不了?

@fishredleung 按我的理解，和在不在vercel部署关系不大。只需要保证访问 gemini pro 请求来源地是在它的可用地区列表里面就行，你在国内部署就得挂个美国节点的代理

**Comment by acche** [comment]
> > 用不了,错误提示: User location is not supported for the API use.User location is not supported for the API use.
> 
> @acche 我用cf的配置子域名指向vercel的ip，想国内直接访问，不挂梯子。结果遇到同样的问题。后面通过指定edge function的执行的偏好节点为美国节点，现在可以正常使用
> 
> 修改地方如下： <img alt="image" width="1104" src="https://private-user-images.githubusercontent.com/12637868/293653500-200305ab-81ac-42fb-97a4-11d387bf9a59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTc1NzMsIm5iZiI6MTcwNDcxNzI3MywicGF0aCI6Ii8xMjYzNzg2OC8yOTM2NTM1MDAtMjAwMzA1YWItODFhYy00MmZiLTk3YTQtMTFkMzg3YmY5YTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEyMzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NGYxZTk5NzUzYWE2NWYwZGI3ODg5OWRkOThkMzFmMmExZTcwMjg0ZGNiMGQxNzBmMmE5MDNjOGE0Mzg4MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rQJTMwH0eIm6hARNifGcb7YAWrR4QK5J-U0EaItZp5E">

你的意思是要覆盖掉源代码里的东西?
