### ISSUE TITLE
[Feature] Display the current model type and version in the dialog box

### ISSUE THREAD

**Issue by clickinfinite** [ChatGPTNextWeb/ChatGPT-Next-Web#3699]
**你想要什么功能或者有什么建议？**
Since the current software supports multiple service providers, it is recommended to display the name and version of the API currently being spoken to in the dialog box.

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。
![11111111111111111111](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/25527875/ae77c18c-c5b2-4727-9cae-2498c6ccccf7)

**Comment by H0llyW00dzZ** [comment]
> **你想要什么功能或者有什么建议？** Since the current software supports multiple service providers, it is recommended to display the name and version of the API currently being spoken to in the dialog box.
> 
> **有没有可以参考的同类竞品？** 可以给出参考产品的链接或者截图。 ![11111111111111111111](https://private-user-images.githubusercontent.com/25527875/293332074-ae77c18c-c5b2-4727-9cae-2498c6ccccf7.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTE1NzUsIm5iZiI6MTcwMzg1MTI3NSwicGF0aCI6Ii8yNTUyNzg3NS8yOTMzMzIwNzQtYWU3N2MxOGMtYzViMi00NzI3LTljYWUtMjQ5OGM2Y2NjY2Y3LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEyMDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNDUxMWUwNTRhZWQ5YjI3M2Y0OTVjZjAyMTEwMmQ4YmQ4OTkyOWU1MGZiMTQ4MzE0ZWYxYjIzNzc4ZTk4ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QAwJIXdVg5snTX45A9aM_V48DWzKAPNroEGBPtNM084)

it's possible but might only available here due UI/UX Layout are limited, also not sure if it's looks good in mobile as well because UI/UX Layout are limited

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/01d95302-7d83-4039-9f8a-f7d90bc7fc37)

**Comment by clickinfinite** [comment]
> it's possible but might only available here due UI/UX Layout are limited, also not sure if it's looks good in mobile as well because UI/UX Layout are limited

Thank you for your reply, it feels good to put it here. Thank you for the work you do.

**Comment by clickinfinite** [comment]
> > > it's possible but might only available here due UI/UX Layout are limited, also not sure if it's looks good in mobile as well because UI/UX Layout are limited
> > 
> > 
> > Thank you for your reply, it feels good to put it here. Thank you for the work you do.
> 
> you mean like this ?
> 
> ![image](https://private-user-images.githubusercontent.com/17626300/293374749-776b0dcc-42f8-4ac5-ae12-64ef480c58b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjA3NTAsIm5iZiI6MTcwMzg2MDQ1MCwicGF0aCI6Ii8xNzYyNjMwMC8yOTMzNzQ3NDktNzc2YjBkY2MtNDJmOC00YWM1LWFlMTItNjRlZjQ4MGM1OGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE0MzQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMTYxNTRhNmRhZDA4MjZhNmIwOTNhZTUzNjZjNjE4YWY5YTlhNDI1NzhhZDc5OTc1NDc5NmIwMTkxZDJhNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BMl0DBh53jC5f5H03o3koUpLEWa0rJlFa4tGt8xKk48)

Wow, that looks cool, you are very efficient! You can place it wherever you see fit, and of course your current screenshot will be in a good position.

**Comment by H0llyW00dzZ** [comment]
> > > > it's possible but might only available here due UI/UX Layout are limited, also not sure if it's looks good in mobile as well because UI/UX Layout are limited
> > > 
> > > 
> > > Thank you for your reply, it feels good to put it here. Thank you for the work you do.
> > 
> > 
> > you mean like this ?
> > ![image](https://private-user-images.githubusercontent.com/17626300/293374749-776b0dcc-42f8-4ac5-ae12-64ef480c58b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjA3NTAsIm5iZiI6MTcwMzg2MDQ1MCwicGF0aCI6Ii8xNzYyNjMwMC8yOTMzNzQ3NDktNzc2YjBkY2MtNDJmOC00YWM1LWFlMTItNjRlZjQ4MGM1OGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDE0MzQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMTYxNTRhNmRhZDA4MjZhNmIwOTNhZTUzNjZjNjE4YWY5YTlhNDI1NzhhZDc5OTc1NDc5NmIwMTkxZDJhNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BMl0DBh53jC5f5H03o3koUpLEWa0rJlFa4tGt8xKk48)
> 
> Wow, that looks cool, you are very efficient! You can place it wherever you see fit, and of course your current screenshot will be in a good position.

- ChatGPTNextWeb#3704

live: https://hackerchat.btz.sh/

**Comment by H0llyW00dzZ** [comment]
not bad in mobile

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/c0a698b2-f05c-4689-950c-2d368df938d2)

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/c6f2a2e5-cef2-4697-beb2-38601a83d843)

**Comment by Leizhenpeng** [comment]
![CleanShot 2024-09-12 at 21 49 48@2x](https://github.com/user-attachments/assets/c05272f1-cc0e-4ecb-8580-ab2e0ecc7063)
now support ~
