### ISSUE TITLE
[Bug] 在IOS Chrome上部分问题的Latex显示有问题，原因未知

### ISSUE THREAD

**Issue by iskycc** [ChatGPTNextWeb/ChatGPT-Next-Web#3701]
**Describe the bug**
在使用 gpt-4-1106-preview时，我问了一个问题：抽象代数中，九次对称群中的二阶元的个数是多少？
回答的结果中，Latex显示有问题

**To Reproduce**
Just select  gpt-4-1106-preview and ask 抽象代数中，九次对称群中的二阶元的个数是多少？

**Expected behavior**
显示正常

**Screenshots**
显示有问题：
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/81439128/43c4f980-e8c0-4488-b366-8a8bd56a54fd)

**Deployment**
- [Yes ] Docker

**Desktop (please complete the following information):**
ios chrome **chrome version is latest**
chatcpt-next-vesion is **2.10.1**

**Smartphone (please complete the following information):**
iPhone 14 **IOS 17.2.1**

**Additional Logs**
Nothing.

**Comment by H0llyW00dzZ** [comment]
- ChatGPTNextWeb#3239

**Comment by Yidadaa** [comment]
已知问题，请关注 #3239
