### ISSUE TITLE
Include Whisper Speech-to-Text Feature from OpenAI

### ISSUE THREAD

**Issue by skamaleo** [ChatGPTNextWeb/ChatGPT-Next-Web#3702]
**Describe the solution you'd like**
As an additional input method for the text box, I would like to have a Speech-to-Text Feature that used OpenAI's model for this: Whisper v3. See docs: https://platform.openai.com/docs/guides/speech-to-text

Just including a microphone input icon next to the "Send" button would suffice.

**Comment by vual** [comment]
My project has been implemented，https://github.com/vual/ChatGPT-Next-Web-Pro

**Comment by skamaleo** [comment]
@Yidadaa why did you close this issue? Is this feature already implemented in the project? As far as I am concerned, it is not developed in this project. I would appreciate your comments on this matter.

**Comment by uu-myheart** [comment]
I want this features too~
