### ISSUE TITLE
[Feature] An automatically growing all contributor list for your repo 

### ISSUE THREAD

**Issue by tashviks** [ChatGPTNextWeb/ChatGPT-Next-Web#3710]
**Feature that I want to add**

An auto growing list to the readme to acknowledge all the contributors in the readme file.

**Current view :**

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/105586514/a4560ab6-fae0-4acd-8aa5-ebbca8664487)

**Suggested Change :**

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/105586514/20b49d69-8d17-4f78-b91c-8845d000e5e6)

**Why add this feature ?**
Acknowledging the various contributors who have influenced the project is a humble gesture. Additionally, it enhances visibility across prominent repositories, which is advantageous. 

If you need more information or adjustments made, I'd gladly submit a pull request or modify it as per the maintainer's preferences!

**Comment by H0llyW00dzZ** [comment]
LGTM
submit a pull request

**Comment by tashviks** [comment]
PR Submitted

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/105586514/3f477f6c-1628-46c7-92d5-460002dc13bd)

**Comment by fredliang44** [comment]
merged, thanks for you conribution!
