### ISSUE TITLE
Gemini Pro didn't work [Bug] 

### ISSUE THREAD

**Issue by panxiaoguang** [ChatGPTNextWeb/ChatGPT-Next-Web#3712]
**Describe the bug**
I installed the latest version(2.10.1) of Chatgpt-next-web app locally, and input 
Google url and APikey according to your instructions. But when I use it in conversation, I encounter an error like:
```js
{
  "error": true,
  "message": "The string did not match the expected pattern."
}

```

**To Reproduce**
1. Go to setting and select model as Google
2. input google url and apikey
3. go to chat and input some words like "Hi"

**Expected behavior**
response normally

**Screenshots**
<img width="935" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/43256809/4e9941f6-b0b1-440c-ba67-0161e354acbb">
<img width="927" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/43256809/98d230d9-5aaf-46eb-bb33-8b24eb026dec">

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by howtogether** [comment]
I have the same issue.

**Comment by DoneVirtue** [comment]
Me too

**Comment by fredliang44** [comment]
the example url is not correct, just updated the instructions in https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/3719, plz remove the path in your url

**Comment by DoneVirtue** [comment]
> [示例 url 不正确，刚刚更新了#3719](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/3719)中的说明，请删除 url 中的路径
不行的，删除还是提示：


```json
{
  "error": true,
  "message": "The string did not match the expected pattern."
}
```
<img width="668" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/30615890/04cca570-bd36-45d7-aae7-7a6bb72376ad">

**Comment by panxiaoguang** [comment]
> the example url is not correct, just updated the instructions in #3719, plz remove the path in your url

No, it still raises the same error on the desktop browser even though I removed the path. Further, for some people who want to use a proxy site instead of a Google official site, it will be a big issue.

**Comment by panxiaoguang** [comment]
So please reopen the issues
