### ISSUE TITLE
[Feature]GPT4 发送图片功能 

### ISSUE THREAD

**Issue by xiaoshengaimm** [ChatGPTNextWeb/ChatGPT-Next-Web#3713]
现在好像还没有聊天中发送图片的功能吧？实在找不到按钮。

如果没有，建议加上，这个对于gpt4能力非常重要。

感谢各位！

**Comment by vual** [comment]
我的二开项目有实现，可以了解下。https://github.com/vual/ChatGPT-Next-Web-Pro

**Comment by Robertxjf** [comment]
绝了呀，不仅要几个二级域名，用自己的境外服务器配置一堆东西，还搞授权码付费这一套了... 至少先有功能试用吧

**Comment by zhengxiang5965** [comment]
顶，这个功能很难实现吗？

**Comment by snowman** [comment]
oh why this feature not supported, absolute needed

**Comment by Leizhenpeng** [comment]
一直支持点击按钮或者直接拖拽来发送图片,
