### ISSUE TITLE
[Error] Message is being blocked for reason: SAFETY

### ISSUE THREAD

**Issue by f3liiix** [ChatGPTNextWeb/ChatGPT-Next-Web#3714]
模型：Gemini Pro

报错内容：
```
{
  "error": true,
  "message": "Message is being blocked for reason: SAFETY"
}
```

是触发什么安全机制了吗？

**Comment by fredliang44** [comment]
Hi, this is the error message from Google Gemini Pro api. It should have triggered some policy from Google

**Comment by fredliang44** [comment]
@f3liiix just lower the safety settings in PR:https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/3723, you can try again to see whether the issue still exists

**Comment by f3liiix** [comment]
> @f3liiix just lower the safety settings in PR:#3723, you can try again to see whether the issue still exists

Great, your response speed is amazing! 👍
