### ISSUE TITLE
设置为gemini后无法联通[Bug] 

### ISSUE THREAD

**Issue by onlyhuman028** [ChatGPTNextWeb/ChatGPT-Next-Web#3718]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/90880928/6a4f5445-6385-40f9-affa-ba8bbec3469c)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/90880928/29308adf-68e8-4632-8d77-876105fefaba)

使用的借口地址是：https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent

**Comment by fredliang44** [comment]
the example url is not correct, just updated the instructions in https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/3719

**Comment by fredliang44** [comment]
plz remove the path in your url should works fine

**Comment by shuyaoyimei** [comment]
I also encountered this issue when using reverse proxy, resverse proxy like http://x.x.x.x:port/aabb/
