### ISSUE TITLE
[Bug] Windows 本地客户端使用 Gemini Pro 模型时报错

### ISSUE THREAD

**Issue by taurusxin** [ChatGPTNextWeb/ChatGPT-Next-Web#3735]
**Describe the bug**
使用 Gemini Pro 模型时，会出现如下报错

```json
{
  "error": true,
  "message": "Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON"
}
```

**To Reproduce**
使用 Gemini Pro 模型时

**Expected behavior**
期望出现正确的相应，在 Web 端没有问题

**Screenshots**

![PixPin_2024-01-02_10-27-09](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17809960/31f3af30-0f74-4819-827b-3b042caa7b62)

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server
- [x] Client

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version v2.10.1

**Additional Logs**
Add any logs about the problem here.

**Comment by H0llyW00dzZ** [comment]
been known this bug 
- H0llyW00dzZ#211

**Comment by H0llyW00dzZ** [comment]
it's because of this 

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/733c5129-05fc-4170-8713-c7dd3ce9cb30)

in client if using that path it's become localhost

**Comment by taurusxin** [comment]
> been known this bug
> 
> * [[Bug] cannot use gemini-pro in tauri desktop H0llyW00dzZ/ChatGPT-Next-Web#211](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/issues/211)

Thank you for your work, so this is your fork of NextChat and has not been merge into the main repo?

**Comment by H0llyW00dzZ** [comment]
> > been known this bug
> > 
> > * [[Bug] cannot use gemini-pro in tauri desktop H0llyW00dzZ/ChatGPT-Next-Web#211](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/issues/211)
> 
> Thank you for your work, so this is your fork of NextChat and has not been merge into the main repo?

later, because in a fix temporary it used a default cors host and currently can't be customize like ChatGPT LLM Api by @Yidadaa  which can be customize by using custom end point for routing it such as proxy

**Comment by onlyhuman028** [comment]
被收购后，这么个简单问题都没人搞定么？连个正常的回复都没有

**Comment by kitaev-chen** [comment]
> 我现在把 gemini pro 丢到 One API 里面，当作 openai 的 model 使用，没什么问题，非常丝滑。 NextChat 的 gemini pro 兼容目前不太稳定。

请问以下具体操作细节？不是太了解 One API

**Comment by Barry04** [comment]
这个问题还没被解决吗？

**Comment by ShinChven** [comment]
One API 兼容的问题吗？
我提交issue的时候的时候，maintainer回都不回就直接把我的issue关了。

**Comment by kitaev-chen** [comment]
可以参考这个issue https://github.com/songquanpeng/one-api/issues/887

**Comment by BLACKFTVV** [comment]
> 我现在把gemini pro丢到一个API里面，目前openai的模型使用，没什么问题，非常丝滑 。NextChat的gemini pro兼容目前不太稳定。

怎样操作啊？

**Comment by openmynet** [comment]
在未修复的本地客户端版本终端地址URL格式为：
 `https://gemini.you.proxy/v1beta/models/gemini-pro:generateContent`
`https://{domain}/v1beta/models/{model}:generateContent`

模型地址：`https://{domain}/v1beta/models` or `https://generativelanguage.googleapis.com/v1beta/models`

**Comment by lloydzhou** [comment]
麻烦测试一下最新的版本问题是否已经完全修复。
我自己在当前最新的v2.15.5版本测试是可以使用的。
