### ISSUE TITLE
最近 2 个站莫名奇妙的显示被举报了。

### ISSUE THREAD

**Issue by itcodes** [ChatGPTNextWeb/ChatGPT-Next-Web#3741]
被举报的可能性几乎没有，因为我只分享给我朋友用。而且是现实朋友。有人遇到过这个问题吗？
![CleanShot 2024-01-02 at 18 07 47@2x](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/8282645/1c816b06-a895-4d1c-a57d-5b7b02d480d8)

**Comment by onlyhuman028** [comment]
我vercel部署了一个二级域名，第二天整个域名都被ISP屏蔽了，最悲催的是还有几个其他二级域名

**Comment by dibin666** [comment]
我也是这样

**Comment by weifeng12x** [comment]
你安装的是哪个版本？因为这个项目被作者卖掉了，我现在没更新了。

**Comment by itcodes** [comment]
> 你安装的是哪个版本？因为这个项目被作者卖掉了，我现在没更新了。

我一直自动更新，目前是最新版本.

**Comment by Yidadaa** [comment]
这是误封，请使用申诉功能向 chrome 和 edge 申诉，如果域名因此被域名服务商停止解析，请发邮件给服务商申请解封。

**Comment by Rgsolo** [comment]
你们有人申诉成功吗，我这里显示的是有欺骗性内容
<img width="859" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/39179966/1e16df95-fa61-4f3e-b71d-b4757a938337">

**Comment by notdp** [comment]
我也遇到了这个问题，域名提供商直接给我域名暂停了

**Comment by Rgsolo** [comment]
> 你们有人申诉成功吗，我这里显示的是有欺骗性内容 <img alt="image" width="859" src="https://private-user-images.githubusercontent.com/39179966/294335609-1e16df95-fa61-4f3e-b71d-b4757a938337.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MTQ1NzUsIm5iZiI6MTcwNDUxNDI3NSwicGF0aCI6Ii8zOTE3OTk2Ni8yOTQzMzU2MDktMWUxNmRmOTUtZmE2MS00ZjNlLWI3MWQtYjQ3NTdhOTM4MzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA0MTExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMWY0OGM5MDBjMzBkYTQwZDdmZmE0Yjk4MDNkNzE0MDliZWE2OGE3ZDg5M2I5MGQxNmRiZmU5ZDY3OGQ0ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rKonXnl_eWPIA-rMLgHDnba-H5vJhbAQ_J4KY6x_EQo">

向goolge申诉之后成功解封
<img width="386" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/39179966/5649048a-3f03-4b9e-881c-35558a9bac55">
