### ISSUE TITLE
[Bug] 页面报错

### ISSUE THREAD

**Issue by Miykah** [ChatGPTNextWeb/ChatGPT-Next-Web#3744]
**Describe the bug**
点击设置界面，出现以下报错。
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/94845288/d280dcc9-1353-42ad-842a-0fb29ee8d4e0)

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
iOS的Safari、window端的Chrome、Edge均出现

**Comment by vanslee** [comment]
I have the same problem, but i dont how to make it. If you resolve this problem, please remind me

**Comment by vanslee** [comment]
> **Describe the bug** 点击设置界面，出现以下报错。 ![image](https://private-user-images.githubusercontent.com/94845288/293699416-d280dcc9-1353-42ad-842a-0fb29ee8d4e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjI2MDAsIm5iZiI6MTcwNDI2MjMwMCwicGF0aCI6Ii85NDg0NTI4OC8yOTM2OTk0MTYtZDI4MGRjYzktMTM1My00MmFkLTg0MmEtMGZiMjllZThkNGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA2MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZWI4NTJkYzI0ZWExMzQxMGIxMWQyYjNlMDY1MDM4NjA0Mjc3OWYzMDNiMDdkM2QzNDQxYTUzOTE2MWE2Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t4dCoYhuiz0qFu3b9SaG7TeK5SrJt5QrzkNUGs0XXuQ)
> 
> **Deployment**
> 
> * [x]  Docker
> * [ ]  Vercel
> * [ ]  Server
> 
> **Desktop (please complete the following information):** iOS的Safari、window端的Chrome、Edge均出现

这个错误百分百会出现吗?

**Comment by fredliang44** [comment]
@Miykah Could you tell me more specifically how to reproduce this problem? Tried but cannot reproduce this issue for now

**Comment by Yidadaa** [comment]
Docker 部署出现该问题时，请优先检查网络问题，请确保你的 nginx 配置放行了静态文件。
