### ISSUE TITLE
大佬这个项目支持chatgpt微调的接口和chatgpt ai assistant的接口吗

### ISSUE THREAD

**Issue by oneanime** [ChatGPTNextWeb/ChatGPT-Next-Web#3752]
大佬这个项目支持chatgpt微调的接口和chatgpt ai assistant的接口吗

**Comment by graymongooseus** [comment]
我也想知道是否支持assistant api

**Comment by fredliang44** [comment]
Could you provide more specific use cases? We do have plan to support assistant api in incoming plugin feature with backend.

**Comment by astorm-z** [comment]
+1

**Comment by Yidadaa** [comment]
支持微调，不支持 assistant api，后者会在未来提供支持。
