### ISSUE TITLE
[Gemini pro的API使用故障] 

### ISSUE THREAD

**Issue by bios99** [ChatGPTNextWeb/ChatGPT-Next-Web#3753]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
在vercel上部署的项目，本地使用Gemini pro的API，现在一直报错。

**如何复现**
使用浏览器前端访问不了Gemini

**截图**
![1](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/39224886/61518e85-8a66-4488-a4da-4f0fd364bc94)
![2](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/39224886/85f81419-3081-410a-8ace-cba94b8c2c46)

**一些必要的信息**
 - 系统：[windows 10]
 - 浏览器： [chrome]
 - 版本： [V2.10.1]
 - 部署方式：[vercel]

**Comment by H0llyW00dzZ** [comment]
it location issue,


works fine for me

**Comment by bios99** [comment]
> it location issue,
> 
> works fine for me

我可能没有说清楚，不是软件的问题，同样的文件在zeabur部署就没有这个问题，vercel的地址问题吗？

**Comment by lswlc33** [comment]
关于 API 使用过程中 “User location is not supported for the API use” 的解决方案
如果你遇到了 “User location is not supported for the API use” 的问题，请按照以下步骤进行解决：

前往 [palm-netlify-proxy](https://github.com/antergone/palm-netlify-proxy) 仓库并点击其中的 “Deploy With Netlify。
部署完成后，你将收到 Netlify 分配的域名 （例如 https://xxx.netlify.app）。
在你的 Gemini Pro Chat 项目中，设置名为 API_BASE_URL 的环境变量，其值为部署 palm-proxy 时获得的域名 (https://xxx.netlify.app)。
重新部署你的 Gemini Pro Chat 项目来完成配置。这应该可以解决问题。
感谢 [antergone](https://github.com/antergone/palm-netlify-proxy) 提供解决方案。


来自 [here](https://github.com/babaohuang/GeminiProChat/blob/main/README_cn.md)

**Comment by bios99** [comment]
> 关于 API 使用过程中 “User location is not supported for the API use” 的解决方案
> 如果你遇到了 “User location is not supported for the API use” 的问题，请按照以下步骤进行解决：
> 
> 前往 [palm-netlify-proxy](https://github.com/antergone/palm-netlify-proxy) 仓库并点击其中的 “Deploy With Netlify。
> 部署完成后，你将收到 Netlify 分配的域名 （例如 https://xxx.netlify.app）。
> 在你的 Gemini Pro Chat 项目中，设置名为 API_BASE_URL 的环境变量，其值为部署 palm-proxy 时获得的域名 (https://xxx.netlify.app)。
> 重新部署你的 Gemini Pro Chat 项目来完成配置。这应该可以解决问题。
> 感谢 [antergone](https://github.com/antergone/palm-netlify-proxy) 提供解决方案。
> 
> 
> 来自 [here](https://github.com/babaohuang/GeminiProChat/blob/main/README_cn.md)

谢谢你的回复，我现在用的也是这个方式，它会用IPV6地址去对接。
只是这个方式的**每次请求头里似乎都带上自己的的Gemini key（明文）**

补充下:
- 其实这个场景很有用，使用nextchat其中很大部分是给没有梯子的人能去分享，更便于软件IP的传播。
- 再次强调这个应该是vercel的EDGe的问题，其他容器部署正常。
