### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by qy2810580600** [ChatGPTNextWeb/ChatGPT-Next-Web#3773]
你好，可不可以编译一个armv7l版本的，希望可以支持海纳思系统本地搭建，我的系统信息如下。
![1704478188138](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/57756741/8f542bd3-f6de-477c-ab8f-65e6381c86f6)

**Comment by fredliang44** [comment]
Hi, considering the current user coverage, there is no plan in the short term. But if anyone is interested in supporting new arch, pull requests is welcomed
