### ISSUE TITLE
[Bug] Scrolls down while outputting text

### ISSUE THREAD

**Issue by chen-rn** [ChatGPTNextWeb/ChatGPT-Next-Web#3780]
The chat automatically scrolls down while inference, making it impossible to read _while_ it's outputting.

**Comment by H0llyW00dzZ** [comment]
- ChatGPTNextWeb#3324

**Comment by m0rg5** [comment]
Here for same issue, very hard (impossible?) to pause while it's doing this also.
v2.10.1

**Comment by fred-bf** [comment]
This issue should have been resolved. Ref: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4149

**Comment by m0rg5** [comment]
Unresolved in. 2.11.2 m1 mac.
