### ISSUE TITLE
[Bug] 自定义接口地址不支持http，https正常

### ISSUE THREAD

**Issue by wisinfun** [ChatGPTNextWeb/ChatGPT-Next-Web#3797]
https://app.nextchat.dev/#/
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/41355260/ea643041-32ab-41ca-bf0f-3efed3897f2e)
Mac客户端也是一样的情况

**Comment by white-z** [comment]
这不是一个BUG，浏览器会阻断HTTPS上的非安全请求（HTTP）请求。

**Comment by Yidadaa** [comment]
https 域名下无法发出 http 请求，请使用 https 域名的 api。
