### ISSUE TITLE
[Bug] WEB采用的是否是使用者本地环境的网络

### ISSUE THREAD

**Issue by liuhrme** [ChatGPTNextWeb/ChatGPT-Next-Web#3805]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [X] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [X] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

          **感谢各位开发者的辛勤付出，我发现了一些小问题，是否可以帮忙解答一下。**

**描述问题**

环境docker，ChatGPT-Next-Web版本号V2.10.1，使用终端安卓/win11，访问方式WEB，API服务自建。

在1月9日搭建应用后，容器环境网络没有问题，但是自定义openapi无法访问，后来经过反复测试，推断是WEB应用使用的是访问者的网络环境。

举例：API服务访问地址为IPV6，应用网络环境为IPV4，蜂窝网是双栈，访问应用（ipv4）后指定API（ipv6），然后应用可以正常访问；

那么问题就在这里，如果API服务部署在内网，内网自建ChatGPT-Next-Web应用后通过NGINX转发到公网环境，如果要使用，必须将内网的API服务映射到公网环境，才能正常访问。**按我个人理解，它应该是使用了客户端侧网络访问，而非服务端网络访问。**

**如何复现**
内网建立open API服务，内网建立服务端指定base_url，在服务端和api能够正常通信时，内网客户端无法使用服务。

内网建立api服务（ipv6网络），公网（ipv4网络）建立服务端，API与服务端无法正常通信，使用者可以访问两侧网络，这种情况就能够正常使用，所以我推测它是使用的用户侧的网络，而不是服务侧的网络。

**截图**

![微信图片_20240110141000](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/102905159/290557a8-3f7d-487b-a994-74b2b140c36b)
![微信图片_20240110141021](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/102905159/3203acd9-c203-430c-992a-cbecb5899b77)

![微信图片_20240110144600](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/102905159/f67eb414-ab41-4294-8f77-d7921476eb9b)
![微信图片_20240110144609](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/102905159/d617c30b-1f3d-4dc6-8dd8-caf3b6e9ae39)

这种情况，在用户侧的网络同时支持IPV6和IPV4，能够正常使用，否则不能使用。

请问这是设计就是如此，还是说我的使用方式不对。

**一些必要的信息**
 - 系统：[windows 10/ android ]
 - 浏览器： [chrome]
 - 版本： [V2.10.1]
 - 部署方式：[docker]

**Comment by H0llyW00dzZ** [comment]
> > 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。
> 
> > [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)
> 
> **反馈须知**
> 
> ⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。
> 
> 请在下方中括号内输入 x 来表示你已经知晓相关内容。
> 
> * [x]  我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
> * [x]  我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
> * [x]  我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。
>   ```
>       **感谢各位开发者的辛勤付出，我发现了一些小问题，是否可以帮忙解答一下。**
>   ```
> 
> **描述问题**
> 
> 环境docker，ChatGPT-Next-Web版本号V2.10.1，使用终端安卓/win11，访问方式WEB，API服务自建。
> 
> 在1月9日搭建应用后，容器环境网络没有问题，但是自定义openapi无法访问，后来经过反复测试，推断是WEB应用使用的是访问者的网络环境。
> 
> 举例：API服务访问地址为IPV6，应用网络环境为IPV4，蜂窝网是双栈，访问应用（ipv4）后指定API（ipv6），然后应用可以正常访问；
> 
> 那么问题就在这里，如果API服务部署在内网，内网自建ChatGPT-Next-Web应用后通过NGINX转发到公网环境，如果要使用，必须将内网的API服务映射到公网环境，才能正常访问。**按我个人理解，它应该是使用了客户端侧网络访问，而非服务端网络访问。**
> 
> **如何复现** 内网建立open API服务，内网建立服务端指定base_url，在服务端和api能够正常通信时，内网客户端无法使用服务。
> 
> 内网建立api服务（ipv6网络），公网（ipv4网络）建立服务端，API与服务端无法正常通信，使用者可以访问两侧网络，这种情况就能够正常使用，所以我推测它是使用的用户侧的网络，而不是服务侧的网络。
> 
> **截图**
> 
> ![微信图片_20240110141000](https://private-user-images.githubusercontent.com/102905159/295466441-290557a8-3f7d-487b-a994-74b2b140c36b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzE4ODMsIm5iZiI6MTcwNDg3MTU4MywicGF0aCI6Ii8xMDI5MDUxNTkvMjk1NDY2NDQxLTI5MDU1N2E4LTNmN2QtNDg3Yi1hOTk0LTc0YjJiMTQwYzM2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwNzI2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjM5M2UxNDJhNGI5NzY1NjI3ZmFiNDY1ZWYzMDc4Mjk4NjMxZjZkYTk4MmQ5NDU1Y2U1ZGJhY2E3ZjQ5ZjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AvMj3pKDOQk9I189UBWOlQkKyOf_MsGrWkszl3qdXHY) ![微信图片_20240110141021](https://private-user-images.githubusercontent.com/102905159/295466465-3203acd9-c203-430c-992a-cbecb5899b77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzE4ODMsIm5iZiI6MTcwNDg3MTU4MywicGF0aCI6Ii8xMDI5MDUxNTkvMjk1NDY2NDY1LTMyMDNhY2Q5LWMyMDMtNDMwYy05OTJhLWNiZWNiNTg5OWI3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwNzI2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGUwZjMxYTY1MGQ0MGRmODFkYWJjODY2ZGM0MTViM2UzMWU5MzFjZmNmYmVlMzkxOGZkNGVjNmEyNjcwZmQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oTJuehwzPYrsNjzNCm_mfg0QyOJXJKWOBspmiPZbcNs)
> 
> ![微信图片_20240110144600](https://private-user-images.githubusercontent.com/102905159/295474362-f67eb414-ab41-4294-8f77-d7921476eb9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzE4ODMsIm5iZiI6MTcwNDg3MTU4MywicGF0aCI6Ii8xMDI5MDUxNTkvMjk1NDc0MzYyLWY2N2ViNDE0LWFiNDEtNDI5NC04Zjc3LWQ3OTIxNDc2ZWI5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwNzI2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2JjMGMwOTMyMjFmNjVkMTJjZGIyYzQ1ZjFlMTNkOTE0ZDJjNmZiNTZjMGZjNWYwNzFiOWRmZDQ2N2RjNWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X446WzqEszIC_qq1CSjws_QTKIWHnKNdnGF3SAe7DDo) ![微信图片_20240110144609](https://private-user-images.githubusercontent.com/102905159/295474367-d617c30b-1f3d-4dc6-8dd8-caf3b6e9ae39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzE4ODMsIm5iZiI6MTcwNDg3MTU4MywicGF0aCI6Ii8xMDI5MDUxNTkvMjk1NDc0MzY3LWQ2MTdjMzBiLTFmM2QtNGRjNi04ZGQ4LWNhZjNiNmU5YWUzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwNzI2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTNkYTI5ZWFlZmQzOGMwNWYxYmQ4YWFjYWVmODg2YmI1OTEwODlkOTNmZGQ4NDc3YmQ5OWRkMzBmMTcxNWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HE0Zk1MqJ01YLYL8blnj8wNoreyAzETXfAvo00CsD-s)
> 
> 这种情况，在用户侧的网络同时支持IPV6和IPV4，能够正常使用，否则不能使用。
> 
> 请问这是设计就是如此，还是说我的使用方式不对。
> 
> **一些必要的信息**
> 
> * 系统：[windows 10/ android ]
> * 浏览器： [chrome]
> * 版本： [V2.10.1]
> * 部署方式：[docker]

I don't think so it's possible in front-end
you have to set it as `localhost` instead of `ipv6`

**Comment by H0llyW00dzZ** [comment]
alternative to fix use this ngrok for routing

https://ngrok.com/

**Comment by Yidadaa** [comment]
请在部署的时候使用 BASE_URL 指定你内网的 one-api 地址，不要在前端设置界面更改选项，请清空前端设置页面的接口地址或将其设置为 `/api/openai/`，这样就会使用你服务侧的地址发送请求。
