### ISSUE TITLE
npm install 后运行npm run dev报错

### ISSUE THREAD

**Issue by ChenZongHeng** [ChatGPTNextWeb/ChatGPT-Next-Web#3808]
./node_modules/_next@13.5.6@next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES&page=%2F_error&preferredRegion=&absolutePagePath=.%2Fnode_modules%5C_next%4013.5.6%40next%5Cdist%5Cpages%5C_error.js&absoluteAppPath=next%2Fdist%2Fpages%2F_app&absoluteDocumentPath=next%2Fdist%2Fpages%2F_document&middlewareConfigBase64=e30%3D!
Error: Invariant: Expected relative import to start with "next/", found "_next@13.5.6@next/dist/server/future/route-modules/pages/module.compiled"
    at [Symbol.replace] (<anonymous>)
    at String.replaceAll (<anonymous>)

**Comment by Yidadaa** [comment]
请尝试使用 `yarn install` 和 `yarn dev`。
