### ISSUE TITLE
[Bug] PNPM install fails with an error

### ISSUE THREAD

**Issue by thesobercoder** [ChatGPTNextWeb/ChatGPT-Next-Web#3809]
**Describe the bug**
PNPM install command fails with an error.

**To Reproduce**
1. Git clone the repo.
2. Run `pnpm install` from the root of the project.
3. See error

```sh
 ERR_PNPM_INVALID_OVERRIDES_SELECTOR  Cannot parse the "lint-staged/yaml" selector in pnpm.overrides
```

**Expected behavior**
PNPM should successfully install the dependencies.

**Comment by thesobercoder** [comment]
@Yidadaa I don't use yarn. Anyway, I was able to install the dependencies with Bun. Thanks!

**Comment by sheng-di** [comment]
Why is it closed? This issue still exists at main branch currently.

**Comment by apexglory** [comment]
In package.json, change
`  "resolutions": {
    "lint-staged/yaml": "^2.2.2"
  }`
to
`  "overrides": {
    "lint-staged/yaml": "^2.2.2"
  }`
