### ISSUE TITLE
这个链接失效了 https://cdn.staticfile.org/emoji-datasource-apple/14.0.0/img/apple/64/1f603.png

### ISSUE THREAD

**Issue by tiamohf** [ChatGPTNextWeb/ChatGPT-Next-Web#3820]
**截图**
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/33214450/ccb83e14-412a-4ca6-bc82-73d641bef39e)

**Comment by Yidadaa** [comment]
升级代码。
