### ISSUE TITLE
「面具」中设定模型名为智谱的，对话显示“参数非法”

### ISSUE THREAD

**Issue by ligj1706** [ChatGPTNextWeb/ChatGPT-Next-Web#3821]
<img width="663" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/44646119/a3f4d46d-7ad0-41d6-af2b-3ec36b654fa0">

**Comment by Yidadaa** [comment]
和你的 api 服务商有关，和这个项目没关系。
