### ISSUE TITLE
[Feature] 如果对外开放使用，怎么限制使用gpt4呀，好像没看到有类似的参数开放。

### ISSUE THREAD

**Issue by jinhuili-lab** [ChatGPTNextWeb/ChatGPT-Next-Web#3824]
既然3.5和4都可以用，大家肯定都改成4了，这样成本飙升

**Comment by jinhuili-lab** [comment]
How to set a limit for GPT4?

**Comment by SpiralTower** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/0cf66141860413f378b883660fdeaec2e909d90c/README_CN.md?plain=1#L121-L123

**Comment by jinhuili-lab** [comment]
If I used docker, how to change the config?
Thank you.

**Comment by jinhuili-lab** [comment]
I can't find DISABLE_GPT4 in docker file.

**Comment by QAbot-zh** [comment]
> If I used docker, how to change the config? Thank you.

If you use `docker run ...` command to deploy the program, then you can use the command like `docker run -e DISABLE_GPT4=1 ...` to add environment variable.

**Comment by jinhuili-lab** [comment]
OK，Get. It is my first time using docker.
Thank you so much.
