### ISSUE TITLE
[Bug] 出现额度超标，但是最近几个月都没有使用

### ISSUE THREAD

**Issue by LeanderLi1014** [ChatGPTNextWeb/ChatGPT-Next-Web#3825]
出现额度超标，但是最近几个月都没有使用
{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}
![1156](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/56808308/d16359c0-1d08-4ec5-a2b6-37c74e08c26d)

**Comment by jinhuili-lab** [comment]
你这是免费的额度过期了，需要充值
