### ISSUE TITLE
在 api.nextweb.fun充值了, 现在访问不了, 请问可以退钱吗?

### ISSUE THREAD

**Issue by yonggithub** [ChatGPTNextWeb/ChatGPT-Next-Web#3826]
在 api.nextweb.fun充值了, 现在访问不了, 请问可以退钱吗?

**Comment by Yidadaa** [comment]
原域名已失效，请使用新域名 https://home.nextapi.fun 。请及时使用该网站上方的技术支持，加入群聊获取最新动态，以免影响使用，谢谢。
