### ISSUE TITLE
[Bug] Using the Google Gemini API, but the system responds that it is ChatGPT?

### ISSUE THREAD

**Issue by andrewwutw** [ChatGPTNextWeb/ChatGPT-Next-Web#3830]
I selected gemini-pro, and asked the system "who are you?", and it answered "I am ChatGPT, a large language model trained by Google."
This is an obviously unreasonable answer.

![gemini](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/4443713/790ed7f7-0878-4c44-8271-716785726d2d)

GPT-3.5-turbo provided the correct answer.

![chatgpt](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/4443713/0e30aa52-82c1-4701-b37e-495370f1f2a7)

**Comment by andrewwutw** [comment]
It's possible that the issue is related to the 'Inject system prompts' feature. When I disable it, Gemini's responses appear to be accurate.

**Comment by Yidadaa** [comment]
Yes, you are right.

**Comment by H0llyW00dzZ** [comment]
> It's possible that the issue is related to the 'Inject system prompts' feature. When I disable it, Gemini's responses appear to be accurate.

yes
works fine here

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/88c3fca3-1425-481a-993a-9fb001ad9b25)
