### ISSUE TITLE
[Feature] 增加对Cloudflare Workers AI 的支持

### ISSUE THREAD

**Issue by ogvegzvt** [ChatGPTNextWeb/ChatGPT-Next-Web#3842]
有考虑接入Cloudflare Workers AI 的计划吗？
**Additional context**
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/49397496/c2af3eab-0ae2-4488-ad86-9fefec3a0c81)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/49397496/fe7754a0-0b93-4b90-b1b0-3521e770a8fa)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/49397496/86f1ec96-cbd3-4dbc-a673-f1cc70392ef0)

**Comment by ogvegzvt** [comment]
Workers AI 提供了一系列流行的开源模型，支持多种 AI 任务，包括：

自然语言处理：文本生成、摘要、分类、翻译、相似性分析、问答
图像生成：文本到图像生成任务
计算机视觉：图像分类、物体检测
音频处理：自动语音识别（ASR）

**Comment by haso2007** [comment]
人走茶凉，vision是遥遥无期了。

**Comment by sorker** [comment]
我构建了一个docker sorker/nextgpt 测试了一下cloudflare返回没问题，但是只支持cloudflare，不支持其他的。因为我没有额度，所以不知道有额度的情况。

**Comment by lloydzhou** [comment]
#4030

**Comment by lloydzhou** [comment]
see #4979
