### ISSUE TITLE
[Bug] Gemini Pro回答报错

### ISSUE THREAD

**Issue by 404gods** [ChatGPTNextWeb/ChatGPT-Next-Web#3855]
我在vercel上部署的该项目，使用Google Gemini Pro会回答错误如下图：
![Snipaste_2024-01-15_22-10-08](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/50573302/3dd1d737-4d51-46cc-8ecb-0392edf3242e)
已经在vercel里添加了变量GOOGLE_API_KEY，如下图
![2](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/50573302/7914c85c-8dfc-4c48-af0f-15b06a55c56e)
也尝试过添加变量GOOGLE_URL，同样也是这个错误提示，请问哪里出了问题？
Gemini Pro的密钥是好的，我在其他应用上可以使用。

**Comment by Barry04** [comment]
我在PC的应用也是出现了同样的问题。
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/61132615/d231d81a-f362-426f-ae16-4e311991cded)

**Comment by fred-bf** [comment]
please double check your local network connection

**Comment by MemoryReload** [comment]
Maybe it's similar to #3645, I still got this problem, right now!
