### ISSUE TITLE
[Bug] History list keeps jumping to top/bottom

### ISSUE THREAD

**Issue by Roiocam** [ChatGPTNextWeb/ChatGPT-Next-Web#3858]
**Describe the bug**

But I hope to find the previous Q&A records through the history list,  don't know why, but when scrolling to some item, the history list will suddenly be jumping to the top/bottom.

**To Reproduce**
1. Q&A like more than 100 records, and some Q&A contain large content.
2. Scroll Up/Down to view the history list
3. ERROR happen

**Expected behavior**

I hope the history list won't skip those record.

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Version [e.g. 22] 2.10.1

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by H0llyW00dzZ** [comment]
- ChatGPTNextWeb#3324

**Comment by Roiocam** [comment]
> * [[Bug] Should be able to disable auto scroll by scrolling up #3324[漏洞]应该能够通过向上滚动来禁用自动滚动 #3324](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3324)

Thanks, seem likes this issue is duplicate.
