### ISSUE TITLE
自己打包，如何部署到服务器？

### ISSUE THREAD

**Issue by lnsane** [ChatGPTNextWeb/ChatGPT-Next-Web#3859]
我build一下，但是好像和平常的前端项目不一样，怎么部署呢？

**Comment by lanmuz** [comment]
他这个项目写的乱七八糟,不知道是不是国人写的,几乎每个部署方法都蜻蜓点水写一点然后就不管了,等真操作各种配置问题...难绷..

**Comment by xiao2131** [comment]
付费咨询下作者不香？
