### ISSUE TITLE
gemini-pro 设置之后回答的是文言一心

### ISSUE THREAD

**Issue by adon68** [ChatGPTNextWeb/ChatGPT-Next-Web#3862]
![img_v3_0275_3ea670e9-3f3c-42ac-8074-61af10cd28eg](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/124684237/737cb44c-bd05-4041-a3fc-cbafc1798301)
![img_v3_0275_67847a8a-cf45-4e06-b5ab-b65f3146272g](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/124684237/c5b5c22c-32aa-4d37-b5dd-430d87b8a602)

**Comment by reece00** [comment]
Test
