### ISSUE TITLE
[Feature] 支持新模型 gpt-4-0125-preview 和 gpt-4-turbo-preview

### ISSUE THREAD

**Issue by devyujie** [ChatGPTNextWeb/ChatGPT-Next-Web#3927]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
、

**你想要什么功能或者有什么建议？**
官方更新了4turbo的[最新模型](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo)：gpt-4-0125-preview 和 gpt-4-turbo-preview，希望可以增加一下

**有没有可以参考的同类竞品？**
、

**其他信息**
、

**Comment by QAbot-zh** [comment]
gpt系列模型的调用方式没变啊，这个新模型支持你应该找卖你api的中转站

**Comment by Daemon-ser** [comment]
同问，新模型在ui上没有选项

**Comment by devyujie** [comment]
> gpt系列模型的调用方式没变啊，这个新模型支持你应该找卖你api的中转站

好像是需要 ui 添加进列表的...

**Comment by QAbot-zh** [comment]
> ui

如果是自己部署，不是可以通过CUSTOM_MODEL添加进环境变量吗？

**Comment by devyujie** [comment]
看到更新了，为啥没增加 [gpt-4-turbo-preview](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/3924#pullrequestreview-1844788474) 就合并了 ...

**Comment by itcodes** [comment]
> 看到更新了，为啥没增加 [gpt-4-turbo-preview](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/3924#pullrequestreview-1844788474) 就合并了 ...

老哥。这俩啥区别啊？

**Comment by H0llyW00dzZ** [comment]
already added

- ChatGPTNextWeb#3924
- ChatGPTNextWeb#3932
