### ISSUE TITLE
[Bug]使用模型Gpt-3.5-turbo-1106与gpt-4-1106-preview时公式Latex显示不正确 Incorrect display of formula Latex when using model gpt-3.5-turbo-1106 with gpt-4-1106-preview

### ISSUE THREAD

**Issue by Michalai0** [ChatGPTNextWeb/ChatGPT-Next-Web#3930]
<img width="1208" alt="截屏2024-01-26 下午4 47 41" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/67622625/8736e58a-1946-4433-9609-5390b92acb4d">

<img width="1208" alt="截屏2024-01-26 下午4 48 15" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/67622625/7c103494-6acd-4aca-b1b7-12a0e2e71736">

**将'' \[ ...\] ''改成 ''$$...$$''后可以正确显示。如下...  It can be displayed correctly after changing \[ \ ] to $$ $$. As follows...**

<img width="1208" alt="截屏2024-01-26 下午4 49 08" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/67622625/391ed24e-94a4-4a9b-b84f-85c293a3835f">

<img width="1208" alt="截屏2024-01-26 下午4 49 18" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/67622625/02ca4771-cfab-400b-9cce-7d2578c5b42a">

**Comment by reece00** [comment]
test

**Comment by H0llyW00dzZ** [comment]
been known this issue, its openai issue 

- https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/discussions/3351

**Comment by Dean-YZG** [comment]
The problem has now been resolved
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/138353356/c7ddb2aa-be7d-4996-b73c-60476817bba3)
