### ISSUE TITLE
[Feature] 部署在vercel上GOOGLE_API_KEY失效的问题，希望修改获取KEY的代码部分

### ISSUE THREAD

**Issue by KevinBrk** [ChatGPTNextWeb/ChatGPT-Next-Web#3931]
使用中发现在vercel上设置了GOOGLE_API_KEY无效

看源代码后发现，在[api/google/route.ts文件第52行](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/981a3629b6eeb9f41090c2a7cd4fd568f6981a55/app/api/google/%5B...path%5D/route.ts#L52)直接获取头部Authorization的值，有值直接使用无值才会使用服务端配置

但是当配置访问密码CODE后，头部Authorization是一直都有nk-xxxxxxx这样格式的值导致判断错误

希望能修复这个问题，感谢！

**Comment by RoversX** [comment]
> 使用中发现在vercel上设置了GOOGLE_API_KEY无效
> 
> 看源代码后发现，在[api/google/route.ts文件第52行](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/981a3629b6eeb9f41090c2a7cd4fd568f6981a55/app/api/google/%5B...path%5D/route.ts#L52)直接获取头部Authorization的值，有值直接使用无值才会使用服务端配置
> 
> 但是当配置访问密码CODE后，头部Authorization是一直都有nk-xxxxxxx这样格式的值导致判断错误
> 
> 希望能修复这个问题，感谢！

Same problem

**Comment by fred-bf** [comment]
Hi, the authorization key were injected through(a bit hacky) https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/981a3629b6eeb9f41090c2a7cd4fd568f6981a55/app/api/auth.ts#L68

I tried to reproduce the issue, but it works fine on my end. if you still encounter please provide a reproducible environment or provide env keys you've set.
