### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by limsyu666** [ChatGPTNextWeb/ChatGPT-Next-Web#3933]
HI,你好，我用的是google gemini，接口密钥和服务商没写错，聊天机器人选的也是这个模型

![截屏2024-01-26 下午9 27 56](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/147224480/86e58333-29f0-4423-bf47-17ac898e4720)，就是这样的，
![截屏2024-01-26 下午9 28 34](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/147224480/11ac6622-3107-4a2e-bfb1-281171f4f3d5)
![截屏2024-01-26 下午9 28 48](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/147224480/69a7e6bf-f16f-40ad-a087-e150c37ea974)
![截屏2024-01-26 下午9 28 58](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/14722
![截屏2024-01-26 下午9 29 08](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/147224480/f53ec8e2-5ff3-4b2e-94d8-d79e4e09ac8d)
4480/02b1cc78-f8c4-4459-b58c-26b8f6cc3f0f)
配置就是这样了

**Comment by H0llyW00dzZ** [comment]
works fine here

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/6ab067f8-a99c-4a10-a3bd-d97cf5630383)

also in terminal

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/453929ab-b0da-4791-bb3f-90f9c870bc51)

**Comment by xiongpahao** [comment]
I come across exactly the same issue, just wonder why & how to fix it

**Comment by fred-bf** [comment]
whats your configuration?

**Comment by xiongpahao** [comment]
> I come across exactly the same issue, just wonder why & how to fix it

Only in macOS native version APP exists this issue, not in the one deployed on Docker

**Comment by fred-bf** [comment]
@xiongpahao I can reproduce this issue from my end, working on it now

**Comment by xiongpahao** [comment]
> @xiongpahao I can reproduce this issue from my end, working on it now

Thanks! Hope it will be resolve soon

**Comment by fred-bf** [comment]
@xiongpahao just release a new build here, once GitHub actions finished, you can download the app and have a try

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.10.3

**Comment by xiongpahao** [comment]
> @xiongpahao just release a new build here, once GitHub actions finished, you can download the app and have a try
> 
> https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.10.3

Thanks! Everything works fine now!
