### ISSUE TITLE
[Feature] 为什么搭建好了，输入API KEY或者密码了，一直提示不对呢

### ISSUE THREAD

**Issue by xkdopod** [ChatGPTNextWeb/ChatGPT-Next-Web#3950]
为什么搭建好了，输入API KEY或者密码了，一直提示不对呢，一直让输入访问密码或者API KEY，我的KEY是SK-开头的，一直都不行

**Comment by QAbot-zh** [comment]
1. 部署的时候有没有设置CODE，如果有，访问密码填你设置的CODE
2. 部署的时候有没有设置OPENAI_API_KEY，如果没有，那就填上你的key

**Comment by null1024-ws** [comment]
> 为什么搭建好了，输入API KEY或者密码了，一直提示不对呢，一直让输入访问密码或者API KEY，我的KEY是SK-开头的，一直都不行

请问你解决了吗 我也是这个问题
