### ISSUE TITLE
[Bug] 官网可以正常使用的key一直提示我额度已经用尽

### ISSUE THREAD

**Issue by shaolinah** [ChatGPTNextWeb/ChatGPT-Next-Web#3957]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。
我用vercel部署的，填写的我自己的key，但一直提示我的额度已经用尽，You exceeded your current quota, please check your plan and billing details，我确定我的key是有额度的，因为更换了2个，这2个在官网都是可以正常使用的，我也尝试了清楚信息，清楚缓存还是不行，我尝试了搜索issues，没有找到相关的问题，这是什么原因？

**如何复现**

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/37900818/959b9db6-4663-4904-8b1d-cf1deea35af8)

**一些必要的信息**
 - 系统：windows 10，android 11，ios 17.2.1
 - 浏览器：chrome，edge
 - 版本： V2.10.1
 - 部署方式：vercel

**Comment by DoneVirtue** [comment]
官网不走API的key，官网无限使用。key过期就证明 过期或者别封禁了。

**Comment by lzwcyd** [comment]
新申请的账号也是报同样的错误

**Comment by DoneVirtue** [comment]
> 新申请的账号也是报同样的错误

你可以chatbox 或者其他验证一下，是否key的问题，或者配置问题。

**Comment by shaolinah** [comment]
> > 机器人检测到问题正文的语言不是英语，会自动翻译。
> 
> > 新申请的账号也报同样的错误。
> 
> 您可以通过聊天框或其他方法来验证是否存在关键问题或配置问题。

https://ai.qiaomu.pro/zh

> > 新申请的账号也报同样的错误
> 
> 你可以chatbox或者其他验证一下，是否密钥的问题，或者配置的问题。

https://ai.qiaomu.pro/zh，在这个上面验证过了，不是秘钥问题。。

**Comment by shaolinah** [comment]
今天电脑和手机都可以正常使用了，没做任何操作的前提下，具体原因不明无法再次复现，issues关闭~
