### ISSUE TITLE
[Bug] latex 公式渲染 问题

### ISSUE THREAD

**Issue by jiangying000** [ChatGPTNextWeb/ChatGPT-Next-Web#3964]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/23182033/b334d1fb-45f6-4aae-a152-d52f121d7d4b)

```latex
\begin{align*}
S_n &= (a_0 - a_1) + (a_1 - a_2) + (a_2 - a_3) + \dots + (a_{n-1} - a_n) + (a_n - a_{n+1}) \
&= a_0 - a_1 + a_1 - a_2 + a_2 - a_3 + \dots + a_{n-1} - a_n + a_n - a_{n+1}.
\end{align*}
```

```latex
\begin{align*}
\lim_{n\to\infty} S_n &= \lim_{n\to\infty} (a_0 - a_{n+1}) \
&= a_0 - \lim_{n\to\infty} a_{n+1} \
&= a_0 - 0 \
&= a_0.
\end{align*}
```

**Comment by H0llyW00dzZ** [comment]
OpenAi Issue

Read Here:

- ChatGPTNextWeb#3351

**Comment by Dean-YZG** [comment]
At present, the expression ability of markdown latex has been enhanced to some extent, and the problem has been solved
![Uploading image.png…]()
