### ISSUE TITLE
[Bug] mask avatars don't display properly in many areas

### ISSUE THREAD

**Issue by lainbo** [ChatGPTNextWeb/ChatGPT-Next-Web#3965]
**Describe the bug**
Mask avatars are not displayed properly. The reason is that the cdn `cdn.jsdelivr.net` that we use for avatars, has problems resolving in some regions, it can be changed to another cdn, **I can provide the PR**

**To Reproduce**
1. People in some provinces in mainland China (the exact provinces will be given at the end of the issues).
2. Open the mask page

**Expected behavior**
The mask's avatar can be displayed normally

**Screenshots**
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/46062895/74e7fe88-e921-4e74-93fb-72dab76156c2)

**Deployment**
- [x] Docker
- [x] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - It's not about the equipment

**Smartphone (please complete the following information):**
 - It's not about the equipment

**Additional Logs**
In [this PR](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/3647/commits/d614d812d554346bcd24913ebaade75a6426a2c8), the CDN of `staticfile` was changed to `jsdelivr`, and the `cdn.jsdelivr.com` is completely unavailable in some provinces of mainland China (as shown in the following picture). The `staticfile cdn` before [this PR](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/3647/commits/d614d812d554346bcd24913ebaade75a6426a2c8) can actually continue to be used, the previous can not be used because they changed the domain name (org → net). So I suggest changing the CDN back to [staticfile](https://staticfile.net/). This will ensure that users in all provinces of mainland China can see the avatar image.

Just change the code in [this line](https://github.com/H0llyW00dzZ/ChatGPT-Next-Web/blob/c250b07b0a14098bdae2fc4fa69eca76283c301c/app/components/emoji.tsx#L25) to following
```js
return `https://cdn.staticfile.net/emoji-datasource-apple/15.0.1/img/${style}/64/${unified}.png`;
```

As you can see, `cdn.jsdelivr.net` is inaccessible in many Mainland China provinces!
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/46062895/777caaee-b088-4f83-a607-d526d0570921)

**Comment by H0llyW00dzZ** [comment]
something wrong in your network

works fine here

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/ca001004-d6a3-4ffe-8e19-bf76324cf4e8)

**Comment by H0llyW00dzZ** [comment]
also about
```tsx
return `https://cdn.staticfile.net/emoji-datasource-apple/15.0.1/img/${style}/64/${unified}.png`;
```
does that CDN can handle high loads or whatever it is ?

**Comment by lainbo** [comment]
> also about
> 
> ```tsx
> return `https://cdn.staticfile.net/emoji-datasource-apple/15.0.1/img/${style}/64/${unified}.png`;
> ```
> 
> does that CDN can handle high loads or whatever it is ?

First of all, to answer your question, this CDN was used before this project, because of its domain name problems caused access failure(look at this chart below), and then was [changed to the current CDN](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/3647/commits/d614d812d554346bcd24913ebaade75a6426a2c8). 

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/46062895/fe32e0e0-5d08-42bd-98c5-683651189a8e)

Since we used to be able to use it, it shouldn't be a problem to change it back now and fix the domain name correctly.
---
If you are not sure, we can also make a minimal change to `fastly.jsdelivr.net`, this CDN and the current `cdn.jsdelivr.net` is the same service provider, although in some provinces of mainland China packet loss is higher, but the connectivity is not a problem, to provide exactly the same load capacity.

[Connectivity testing for fastly.jsdelivr.net](https://www.itdog.cn/ping/fastly.jsdelivr.net)
[Connectivity testing for staticfile.net](https://www.itdog.cn/ping/cdn.staticfile.net)

**Comment by H0llyW00dzZ** [comment]
> Summary of my speech:
> 
> * The reason for using staticfile.net is because Next Chat had previously used it, providing first-rate CDN support for all provinces in mainland China
> * The reason for using fastly.jsdelivr.net is that it is the same CDN provider currently used in our project, offering basically enough CDN support for all provinces in mainland China

yeah but it was down, and I'm not certain if it's stable again. For instance, I'm unsure if it can handle high volumes of traffic about old CDN

**Comment by lainbo** [comment]
Then you can try using `fastly.jsdelivr.net`, which is the same service provider as `cdn.jsdelivr.net` in the current project. It has the same capacity for handling traffic and can provide services to all provinces in mainland China.

**Comment by H0llyW00dzZ** [comment]
> Then you can try using `fastly.jsdelivr.net`, which is the same service provider as `cdn.jsdelivr.net` in the current project. It has the same capacity for handling traffic and can provide services to all provinces in mainland China.

alright

**Comment by H0llyW00dzZ** [comment]
- ChatGPTNextWeb#3966
