### ISSUE TITLE
[Bug] Add support for http

### ISSUE THREAD

**Issue by Anivie** [ChatGPTNextWeb/ChatGPT-Next-Web#3984]
**Describe the bug**
Tauri will disable the HTTP scheme in release mode, which means we won't be able to use the HTTP API.
Therefore, we need to disable this.

**To Reproduce**
This error occurs when any address within localhost (or 127.0.0.1) with the http scheme use in "OpenAI Endpoint".

**Expected behavior**
[See](https://github.com/tauri-apps/tauri/issues/3007).

**Screenshots**
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/88354708/2473a12b-ab12-4ebc-9a57-b793f6717c39)

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server
- [x] Client

**Desktop (please complete the following information):**
 - OS: Windows11 X64
 - Browser: Webview2
 - Version: 2.10.1

**Additional Logs**
```
Mixed Content: The page at 'https: //tauri. localhost/#/' was loaded over HTTPS, 04b39fde-8244312edb82a581.js: 193
but requested an insecure resource 'http: //10.0.0.1: 7878/v1/chat/completions'.
This request has been blocked; the content must be served over HTTPS.
```

**Comment by H0llyW00dzZ** [comment]
yeah I know that,, tbh its confusing about tauri

**Comment by Anivie** [comment]
> yeah I know that,, tbh its confusing about tauri

I was also confused about it, so I went to the Tauri Discord group for help. Luckily, I got the final answer.
