### ISSUE TITLE
[Bug] After deploying Docker, the API address was not entered into the address bar.

### ISSUE THREAD

**Issue by lobmoo** [ChatGPTNextWeb/ChatGPT-Next-Web#3990]
![Uploading image.png…]()

#!/bin/bash
docker run -d\
    --net=host \
    -e PROXY_URL=http://127.0.0.1:1314 \
    -e OPENAI_API_KEY="sk-hb3z222222222222" \
    -e CODE="xxxxx" \
    yidadaa/chatgpt-next-we
    
    The above is my startup script.

**Comment by fred-bf** [comment]
@lobmoo  Your image is broken, plz try upload again

**Comment by lobmoo** [comment]
![Uploading image.png…]()

**Comment by lobmoo** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/45560941/ed938a8d-7bce-43f2-a99b-7ff182162270)

**Comment by fred-bf** [comment]
@lobmoo I didn't understand your question too much, "the API address was not entered into the address bar." What exactly is the problem?

**Comment by reece00** [comment]
test
