### ISSUE TITLE
[Bug] Storage Quota Exceeded: 'setItem' Failure on 'chat-next-web-store'

### ISSUE THREAD

**Issue by lvguanjun** [ChatGPTNextWeb/ChatGPT-Next-Web#3994]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
    曾经存在一个性能相关的 [issue#2393](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3994) ，压测时曾发生过，现在我是真的发生了。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**

当我的本地存储的聊天记录足够多时，将会报错 `Failed to execute 'setItem' on 'Storage': Setting the value of 'chat-next-web-store' exceeded the quota.`

**如何复现**

本地存储有足够多的聊天记录

**截图**

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/58430934/25029b11-68f3-4869-854d-d9e00b609ee7)

**一些必要的信息**
 - 系统：win11
 - 浏览器： Edge
 - 版本：commit id：4511aa4d21eda4e6e0b5130d1e3222bb30734672
 - 部署方式：docker 部署

**Comment by lvguanjun** [comment]
可能不只是 `聊天记录` 导致的 local storage 不足，还存在大量的不明意义的 key

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/58430934/2cc8bc39-6b68-4f0e-a7a5-4d751e80558b)

**Comment by fred-bf** [comment]
@lvguanjun could you using the follow script in chrome console to retrieve the storage usage by key?

the key start with `unfinish-input` should have empty value, there is a high probability that the root cause is too many message records.


```
// Iterate over the local storage keys and log the key and its size
Object.entries(localStorage).forEach(([key, value]) => {
  console.log(key, value.length);
});
```

**Comment by lvguanjun** [comment]
Sure, but before this (before your reply), I have already used a script to delete keys starting with `unfinish-input` that have empty values, totaling 400 keys.

This is a screenshot of the storage space for each key.

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/58430934/a2f0cfc7-5d45-450d-8994-411bbc73a70c)

**Comment by H0llyW00dzZ** [comment]
It seems that a bug is being caused by unfinished input continually overwriting when the chat is switched.

**Comment by lvguanjun** [comment]
So far it looks like it is, but I'm not sure that even if I remove the empty key every time, as the `chat-next-web-store` records continue to grow, it will still hit the limit and report an error

**Comment by lvguanjun** [comment]
And how do you plan to solve the problem of the large number of null keys that already exist, either by adding them to the front-end code and deleting them every time, or by users manually executing scripts to delete them

**Comment by fred-bf** [comment]
@lvguanjun The `unfinish-input` itself shouldn't take up much space, currently the messages completely stored in local storage which cannot fundamentally solve this problem. In the future, we will consider supporting server-side storage to fundamentally solve this issue, but it will require more time.

**Comment by lvguanjun** [comment]
I'm not sure if these options are feasible, but from my personal use, I tend to prefer chat logs to be stored locally, thanks

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/58430934/0eff5af5-f221-4c05-9ad1-e8903c2be3c7)

**Comment by H0llyW00dzZ** [comment]
> I'm not sure if these options are feasible, but from my personal use, I tend to prefer chat logs to be stored locally, thanks
> 
> ![image](https://private-user-images.githubusercontent.com/58430934/302190561-0eff5af5-f221-4c05-9ad1-e8903c2be3c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTQ1ODEsIm5iZiI6MTcwNzExNDI4MSwicGF0aCI6Ii81ODQzMDkzNC8zMDIxOTA1NjEtMGVmZjVhZjUtZjIyMS00YzA1LTlhZDEtZTg5MDNjMmJlM2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA2MjQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNDFhNDdlNmRlYWFlMDNiOTEyOGM3N2U0MTUwZjY0YTBkY2M3YmMyOGRjYWI4MWFhODBjYTI4MzYxZDVhMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AFHMbsEySdjiJGiPNVfqEmgMtx-baXxLVYYtyrSbDeg)

It's challenging and costly (`e.g, you have to spent money more`) because it's an interpreted language that runs on a browser, unlike compiled languages. For instance, `Go` can be stored locally with ease, such as directly storing it in memory.

**Comment by H0llyW00dzZ** [comment]
Anyways As of now, there's no solution to fix it. In the future, I might consider try rewriting it in `Go + WASM` instead of solely in `Rust`. This is because `Go` offers simplicity and cost-effectiveness especially for personal/home use

**Comment by lvguanjun** [comment]
Okay, thanks for the replies, it's up to you to close the issue or not.

I might export the chat history, then clear the local storage to temporarily circumvent this issue.

**Comment by H0llyW00dzZ** [comment]
> Okay, thanks for the replies, it's up to you to close the issue or not.
> 
> I might export the chat history, then clear the local storage to temporarily circumvent this issue.

alternative this free if you want stored locally

https://github.com/seaweedfs/seaweedfs

**Comment by H0llyW00dzZ** [comment]
@lvguanjun it fix now

- #4003

should be good from stupid complexity front end



https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/600be255-1252-4e23-aabe-fc77b720307d

**Comment by lvguanjun** [comment]
Get, thanks, if I understand the video correctly, this fix also removes the `unfinish-input` key that was generated earlier.

**Comment by H0llyW00dzZ** [comment]
> Get, thanks, if I understand the video correctly, this fix also removes the `unfinish-input` key that was generated earlier.

correct

**Comment by H0llyW00dzZ** [comment]
> 可能不只是 `聊天记录` 导致的 local storage 不足，还存在大量的（400+）不明意义的值为空的 key
> 
> ![image](https://private-user-images.githubusercontent.com/58430934/302108482-2cc8bc39-6b68-4f0e-a7a5-4d751e80558b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDg1ODAsIm5iZiI6MTcwNzE0ODI4MCwicGF0aCI6Ii81ODQzMDkzNC8zMDIxMDg0ODItMmNjOGJjMzktNmI2OC00ZjBlLWE3YTUtNGQ3NTFlODA1NThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE1NTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YmY2ZDBmM2QzMTk1NzE4Njg3MmY4Y2IzOWRlZjQxMGFkYjA1NjBjNjNjYzYzNWUwMGMyMTU0NGE0OWE4OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vHbQdHTzFAGHGfBuvxQQiaX9sfqXfssCpeYCFEQkDqo)

it remove this one

**Comment by mxdlzg** [comment]
For large multi-modal models, the image cache is very large, and this error occurs frequently.

Now I can only manually delete part of the session to alleviate the problem?
