### ISSUE TITLE
[Bug] custom model name does not work any more in the latest build version

### ISSUE THREAD

**Issue by lizhe2004** [ChatGPTNextWeb/ChatGPT-Next-Web#4007]
**Describe the bug**
custom model name does not work any more in the latest build version ,with console log showing "Model xxx not found in DEFAULT_MODELS array"
**To Reproduce**
1. Go to 'setting page'
2. config API url and some custom model name list with "," mark
3. Go to chat page
4. select one custom model name 
5 send some question in the chat page
**Expected behavior**
 I think i should get the response message from the custom model  rather than no response with console eror message showing "Model xxx not found in DEFAULT_MODELS array"

I think the bug is introduced by such commit , which lost consideration the custom models  configed in user setting page, with only search the DEFAULT_MODELS  const value.
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commit/a5517a1a51de81f9527f2e734d8412f6f4f8962c#diff-87cc040dd1bc561fde5c60b722355d5151ff86b7f70c325dfe403885603ea233R98

**Screenshots**
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/6104435/dd3c1250-46b4-4cae-acca-fcc6fd247e34)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/6104435/ac7d0788-e336-4178-8d47-648704674ae8)

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [chrome,]
 - Version  121.0.6167.140]

**Comment by H0llyW00dzZ** [comment]
At present, custom models for other AI providers are not available, particularly those to which we do not have access (as contributor,devs). It's worth reconsidering how contributors, or any developers for that matter, can address bugs or make improvements to models they cannot access.

**Comment by H0llyW00dzZ** [comment]
feel free to sponsoring this project as professionalism for example giving they access such as contributor,devs then can easily fix,improve or whatever it is

**Comment by lizhe2004** [comment]
i use a service named one-api https://github.com/songquanpeng/one-api to convert some 3rd model provider api into openai compatible api, so the qwen model from aliyun dashscope can privide openai format stream response which is accepted by chatgpt next web application.
so I think the issue is not about 3rd AI provider, it is related with that the modelname validation in client side shoud take the custom model list of setting page into consideration rather than only the pre-config DEFAULT_MODELS array.  because the custom model name works in eariler version before you add the DEFAULT_MODELS  check.

**Comment by H0llyW00dzZ** [comment]
> i use a service named one-api https://github.com/songquanpeng/one-api to convert some 3rd model provider api into openai compatible api, so the qwen model from aliyun dashscope can privide openai format stream response which is accepted by chatgpt next web application. so I think the issue is not about 3rd AI provider, it is related with that the modelname validation in client side shoud take the custom model list of setting page into consideration rather than only the pre-config DEFAULT_MODELS array. because the custom model name works in eariler version before you add the DEFAULT_MODELS check.

that's not actually ai provider so still
`At present, custom models for other AI providers are not available, particularly those to which we do not have access (as contributor,devs). It's worth reconsidering how contributors, or any developers for that matter, can address bugs or make improvements to models they cannot access.`

**Comment by lizhe2004** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/6104435/db9a8fcf-bde1-4e37-b30e-b3ed5a2865e8)

sorry to bother you again.
so，how do you think the goal or purpose of such "custom models" configuration in setting page?  did i use this by wrong understanding?  i think we can use "OpenAI Endpoint " and "Custom Models" the two configuration to support some unkown new model which is compatible with openai api client, so chatgpt-next-web can only focus on openai format.

**Comment by H0llyW00dzZ** [comment]
> ![image](https://private-user-images.githubusercontent.com/6104435/302508719-db9a8fcf-bde1-4e37-b30e-b3ed5a2865e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxOTgxNzAsIm5iZiI6MTcwNzE5Nzg3MCwicGF0aCI6Ii82MTA0NDM1LzMwMjUwODcxOS1kYjlhOGZjZi1iZGUxLTRlMzctYjMwZS1iM2VkNWEyODY1ZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMDUzNzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZmZjgzYmNhMGJiYzkyMjk3MWEyMmRlMTk5MmQ2MWQ5ZWJhZTIyMDU2MTA4YjM0MWEwYTkyMmExN2FmNDUyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YCDBB1dlouZN7ITFj1J-8QZH67Bq_3hbtUAR63gbU3Q)
> 
> sorry to bother you again. so，how do you think the goal or purpose of such "custom models" configuration in setting page? did i use this by wrong understanding? i think we can use "OpenAI Endpoint " and "Custom Models" the two configuration to support some unkown new model which is compatible with openai api client, so chatgpt-next-web can only focus on openai format.

well, still I don't have access to the other ai so what can I do, anyway why should I fix it without testing or anything else when I don't have access lmao

**Comment by H0llyW00dzZ** [comment]
alternative fix it just disable this inject system prompt since its only for default models such as openai, google ai

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/baf42254-b2a1-4e43-a039-68c01f0eceaa)

**Comment by Algorithm5838** [comment]
Instead of throwing an error, it should not include a knowledge cutoff date if the date is not explicitly provided.

**Comment by H0llyW00dzZ** [comment]
> explicitly

explicitly better

**Comment by Algorithm5838** [comment]
I believe a more effective implementation would be to have an option to select a default mask for new chats. This selection could be presented in the settings as 'Start chats with a default mask [ ].' Initially, a default ChatGPT mask might be selected, but users should have the capability to change this.

**Comment by H0llyW00dzZ** [comment]
> I believe a more effective implementation would be to have an option to select a default mask for new chats. This selection could be presented in the settings as 'Start chats with a default mask [ ].' Initially, a default ChatGPT mask might be selected, but users should have the capability to change this.

so `Start chats with a default mask [ ].` for example is can be customize by users instead of default chatgpt mask ?

**Comment by lizhe2004** [comment]
i feel [Algorithm5838](https://github.com/Algorithm5838) and  [H0llyW00dzZ](https://github.com/H0llyW00dzZ)  you are talking about something about mask ,rather than my posted issue.

**Comment by Algorithm5838** [comment]
@H0llyW00dzZ Yes.

Currently, initiating a new chat requires either a default system message, a ChatGPT mask, or no system message. Although you can create masks, you must select your preferred one each time.

A proposed solution is to allow users to set a default mask for starting chats, which would be the revised setting `Start chats with a default mask [ ].`. Users could select their preferred mask from the masks settings, which could include Bard, ChatGPT, or any of their creations like DictionaryGPT. This would prevent the raised issue, as users would write the system message for the default mask themselves.

___

@lizhe2004 It might appear so, but I'm recommending a different implementation for the code that gave rise to this issue. I'm currently using one-api, but I haven't updated my NextChat fork. If I did, I would likely encounter this same problem.

**Comment by H0llyW00dzZ** [comment]
> @H0llyW00dzZ Yes.
> 
> 
> 
> Currently, initiating a new chat requires either a default system message, a ChatGPT mask, or no system message. Although you can create masks, you must select your preferred one each time.
> 
> 
> 
> A proposed solution is to allow users to set a default mask for starting chats, which would be the revised setting `Start chats with a default mask [ ].`. Users could select their preferred mask from the masks settings, which could include Bard, ChatGPT, or any of their creations like DictionaryGPT. This would prevent the raised issue, as users would write the system message for the default mask themselves.
> 
> 
> 
> ___
> 
> 
> 
> @lizhe2004 It might appear so, but I'm recommending a different implementation for the code that gave rise to this issue. I'm currently using one-api, but I haven't updated my NextChat fork. If I did, I would likely encounter this same problem.

It easy to implement it just like writing a slices byte in go

**Comment by yangbod** [comment]
v2.10.1 can use one-api ,after update to v2.10.2, it doesn't work

**Comment by fred-bf** [comment]
> v2.10.1 can use one-api ,after update to v2.10.2, it doesn't work

Please create an individual issue for your question

**Comment by fred-bf** [comment]
@lizhe2004 could you try the work around in this PR([Preview link](https://nextchat-git-fork-fred-bf-fix-custom-model-nextchat.vercel.app/))? For the time being, the default system content is set to make OpenAI by default, and the it will be considered to maintain relevant information when registering custom models at server side in the future

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4010

**Comment by lizhe2004** [comment]
> @lizhe2004 could you try the work around in this PR([Preview link](https://nextchat-git-fork-fred-bf-fix-custom-model-nextchat.vercel.app/))? For the time being, the default system content is set to make OpenAI by default, and the it will be considered to maintain relevant information when registering custom models at server side in the future
> 
> #4010

hi，[fred-bf](https://github.com/fred-bf)  ，your demo ([Preview link](https://nextchat-git-fork-fred-bf-fix-custom-model-nextchat.vercel.app/)) works for custom model name.  great.

**Comment by QAbot-zh** [comment]
> alternative fix it just disable this inject system prompt since its only for default models such as openai, google ai要解决这个问题，只需禁用此注入系统提示，因为它只适用于默认模型，如 openai 和 google ai。
> 
> ![image](https://private-user-images.githubusercontent.com/17626300/302516048-baf42254-b2a1-4e43-a039-68c01f0eceaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzE0MjgsIm5iZiI6MTcwNzI3MTEyOCwicGF0aCI6Ii8xNzYyNjMwMC8zMDI1MTYwNDgtYmFmNDIyNTQtYjJhMS00ZTQzLWEwMzktNjhjMDFmMGVjZWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDAxNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZWM3NDFkZTlkMmM3Mjk4NjA3NjY4N2VlODU4MTM5YTc3ZTI3OWU1Mjc2MjE2Y2RkYzYxNjA1YWU0YTNjMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w0Zf0oDLcc2jwAzidGAzDPVbPRleufR14dVFCrqy63k)

It doesn't work.  I disable this inject system prompt, but I still can't get the reply when I try to use non OpenAI and Google model. I use v2.10.1 version.
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/8d3cfa9a-72bf-4e3e-a8ab-a1e1046939d0)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/d9f54633-fb5d-45d7-94e4-2161b88b75e1)
