### ISSUE TITLE
[Bug] 使用webview嵌入安卓apk会报错Application Error

### ISSUE THREAD

**Issue by cxk-521** [ChatGPTNextWeb/ChatGPT-Next-Web#4014]
![3e3c6a0e1baf1e96a2da8d7522717a1](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/62629084/8c74ca0e-bb23-4fb0-a33a-86956ff700c6)

**Comment by fred-bf** [comment]
please provide more detailed information to reproduce issue

**Comment by cxk-521** [comment]
我使用fusion app打包webview填入https://app.nextchat.dev/的网址打开就是这样了

**Comment by fred-bf** [comment]
@cxk-521 you may need to provide more details to locate the issue, e.g. console log, steps to reproduce issue

you can also following the issue template here: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by MCheping8108** [comment]
> 我使用fusion app打包webview填入[https://app.nextchat.dev/的网址打开就是这样了](https://app.nextchat.dev/%E7%9A%84%E7%BD%91%E5%9D%80%E6%89%93%E5%BC%80%E5%B0%B1%E6%98%AF%E8%BF%99%E6%A0%B7%E4%BA%86)

你可以使用[tauri-app](https://beta.tauri.app)来打包此项目

**Comment by Anivie** [comment]
> > > 我使用fusion app打包webview填入[https://app.nextchat.dev/的网址打开就是这样了](https://app.nextchat.dev/%E7%9A%84%E7%BD%91%E5%9D%80%E6%89%93%E5%BC%80%E5%B0%B1%E6%98%AF%E8%BF%99%E6%A0%B7%E4%BA%86)
> > 
> > 
> > 你可以使用[tauri-app](https://beta.tauri.app)来打包此项目
> 
> tauri-app不能打包成安卓吧

Of course, [see](https://tauri.app/blog/2022/12/09/tauri-mobile-alpha/).
