### ISSUE TITLE
[Bug] Can not scroll up and down when the model is steaming response

### ISSUE THREAD

**Issue by KnaveM** [ChatGPTNextWeb/ChatGPT-Next-Web#4019]
**Describe the bug**
Can not scroll up and down when the model is generating response. If open multiple conversations with GPT, and one of the conversation have a unfinished streaming response, other conversations can not scroll up and down. The conversation view will be forced to scroll down to the botton of the conversation.

**To Reproduce**
1. Go to the main page
2. Click New Chat
3. Send a request to ask GPT a question(the response should be long enough, usually take more than 5s to stream the complete response)
4. Click a conversation in the conversation list to open another conversation, while the GPT is streaming the response
5. Scroll up and down, the view will be forced to scroll down to the bottom

**Expected behavior**
Should allow user to go through other chat history while the GPT is streaming response

**Screenshots**

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/33738071/835ac262-4dcb-4273-b8af-3001d32894f5

**Deployment**
- [x] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by H0llyW00dzZ** [comment]
- ChatGPTNextWeb#4021

**Comment by fred-bf** [comment]
The expected behavior here should be to automatically increase the height upwards when the user is already at the bottom of the chat. Once manually slid off the bottom, it is not forced at the very bottom.

**Comment by fred-bf** [comment]
@KnaveM hi, this issue should be resolved. Ref:  #4149
