### ISSUE TITLE
[Bug] gpt4-vision-preview 回答不完整

### ISSUE THREAD

**Issue by sunquan819** [ChatGPTNextWeb/ChatGPT-Next-Web#4024]
后端对接 one-api 使用 Azure OpenAI gpt-3.5 和 gpt4-vision-preview， 发现 gpt3.5正常，gpt4 回答只能显示开头的一段话，同样的使用方式，前端换成 chatgpt-web ，3.5 和 4 都正常。

**Comment by goodls-cs** [comment]
Azure-GPT4需设置 "max_tokens" 值，否则返回输出将被截断。
例如：
`{
    "messages": [ 
        {
            "role": "system", 
            "content": "You are a helpful assistant." 
        },
        {
            "role": "user", 
            "content": [
	            {
	                "type": "text",
	                "text": "Describe this picture:"
	            },
	            {
	                "type": "image_url",
	                "image_url": {
                        "url": "<image URL>"
                    }
                } 
           ] 
        }
    ],
    "max_tokens": 100, 
    "stream": false 
}`
