### ISSUE TITLE
[Bug] API Version Service Provider Google

### ISSUE THREAD

**Issue by H0llyW00dzZ** [ChatGPTNextWeb/ChatGPT-Next-Web#4031]
**Describe the bug**
this one

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/86f5a46b-c9ec-4f30-bb64-d96c1ff9cf66)

 it doesn't work when use v1beta

**Comment by H0llyW00dzZ** [comment]
Docs https://ai.google.dev/docs/api_versions

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/f01ed715-112f-48c9-ab80-2cd6e35f4db1)

**Comment by Rubuark** [comment]
However, the network request indicates that all calls are using the v1beta version, instead of the API version you provided.

For instance, in the image below, I used the v1beta and v1 versions to hold conversations, respectively. However, all web pages used the v1beta version to conduct conversations.
![bug](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/36145660/b8897b3d-2d3c-4182-9ad5-2dad382fb330)

**Comment by H0llyW00dzZ** [comment]
> However, the network request indicates that all calls are using the v1beta version, instead of the API version you provided.
> 
> For instance, in the image below, I used the v1beta and v1 versions to hold conversations, respectively. However, all web pages used the v1beta version to conduct conversations. ![bug](https://private-user-images.githubusercontent.com/36145660/309546321-b8897b3d-2d3c-4182-9ad5-2dad382fb330.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NjY2MDYsIm5iZiI6MTcwOTQ2NjMwNiwicGF0aCI6Ii8zNjE0NTY2MC8zMDk1NDYzMjEtYjg4OTdiM2QtMmQzYy00MTgyLTlhZDUtMmRhZDM4MmZiMzMwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDExNDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiOGU3ZGRlYjM4OWVkM2M4ZDFhNzdhN2ZjYjI3MWE4NTYwMDUzMTRmNGJhMjZhM2JlNWJkODBmYjkzMDY0YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0_Cpfljaz3O53Mv6yrptJ180yRa2MqyU0v5_JFUf4Kw)

it's because of [this](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/constant.ts#L88C1-L94C3)

```ts
export const Google = {
  ExampleEndpoint: "https://generativelanguage.googleapis.com/",
  ChatPath: "v1beta/models/gemini-pro:generateContent",
  VisionChatPath: "v1beta/models/gemini-pro-vision:generateContent",

  // /api/openai/v1/chat/completions
};
```
Also This repository hasn't been fixed for a long time and is essentially unmaintained, as @fred-bf is the only one managing it.

**Comment by H0llyW00dzZ** [comment]
Also,
> [!NOTE]  
> The Google Service Provider is still unstable unlike [OpenAI](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/client/platforms/openai.ts). This instability is not due to Google itself. You can see more details [here](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/client/platforms/google.ts).

**Comment by Rubuark** [comment]
> > However, the network request indicates that all calls are using the v1beta version, instead of the API version you provided.
> 
> > 
> 
> > For instance, in the image below, I used the v1beta and v1 versions to hold conversations, respectively. However, all web pages used the v1beta version to conduct conversations. ![bug](https://private-user-images.githubusercontent.com/36145660/309546321-b8897b3d-2d3c-4182-9ad5-2dad382fb330.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NjY2MDYsIm5iZiI6MTcwOTQ2NjMwNiwicGF0aCI6Ii8zNjE0NTY2MC8zMDk1NDYzMjEtYjg4OTdiM2QtMmQzYy00MTgyLTlhZDUtMmRhZDM4MmZiMzMwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDExNDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiOGU3ZGRlYjM4OWVkM2M4ZDFhNzdhN2ZjYjI3MWE4NTYwMDUzMTRmNGJhMjZhM2JlNWJkODBmYjkzMDY0YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0_Cpfljaz3O53Mv6yrptJ180yRa2MqyU0v5_JFUf4Kw)
> 
> 
> 
> it's because of [this](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/constant.ts#L88C1-L94C3)
> 
> 
> 
> ```ts
> 
> export const Google = {
> 
>   ExampleEndpoint: "https://generativelanguage.googleapis.com/",
> 
>   ChatPath: "v1beta/models/gemini-pro:generateContent",
> 
>   VisionChatPath: "v1beta/models/gemini-pro-vision:generateContent",
> 
> 
> 
>   // /api/openai/v1/chat/completions
> 
> };
> 
> ```
> 
> Also This repository hasn't been fixed for a long time and is essentially unmaintained, as @fred-bf is the only one managing it.
> 
> 
> 
> 
> 
> 
> 
> 

So in [pull request #4192]( https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4192 ), I can only simply modify the code to solve the problem I encountered (or cover up the problem). After all, refactoring this part of the code is a bit too difficult for me now😢

**Comment by H0llyW00dzZ** [comment]
> > > However, the network request indicates that all calls are using the v1beta version, instead of the API version you provided.
> > 
> > 
> > > 
> > 
> > 
> > > For instance, in the image below, I used the v1beta and v1 versions to hold conversations, respectively. However, all web pages used the v1beta version to conduct conversations. ![bug](https://private-user-images.githubusercontent.com/36145660/309546321-b8897b3d-2d3c-4182-9ad5-2dad382fb330.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NjY2MDYsIm5iZiI6MTcwOTQ2NjMwNiwicGF0aCI6Ii8zNjE0NTY2MC8zMDk1NDYzMjEtYjg4OTdiM2QtMmQzYy00MTgyLTlhZDUtMmRhZDM4MmZiMzMwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDExNDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiOGU3ZGRlYjM4OWVkM2M4ZDFhNzdhN2ZjYjI3MWE4NTYwMDUzMTRmNGJhMjZhM2JlNWJkODBmYjkzMDY0YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0_Cpfljaz3O53Mv6yrptJ180yRa2MqyU0v5_JFUf4Kw)
> > 
> > 
> > it's because of [this](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/constant.ts#L88C1-L94C3)
> > ```ts
> > export const Google = {
> > 
> >   ExampleEndpoint: "https://generativelanguage.googleapis.com/",
> > 
> >   ChatPath: "v1beta/models/gemini-pro:generateContent",
> > 
> >   VisionChatPath: "v1beta/models/gemini-pro-vision:generateContent",
> > 
> > 
> > 
> >   // /api/openai/v1/chat/completions
> > 
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also This repository hasn't been fixed for a long time and is essentially unmaintained, as @fred-bf is the only one managing it.
> 
> So in [pull request #4192](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4192), I can only simply modify the code to solve the problem I encountered (or cover up the problem). After all, refactoring this part of the code is a bit too difficult for me now😢

It's only refactoring support `v1` and `v1beta` instead of only `v1beta`

**Comment by Rubuark** [comment]
> It's only refactoring support `v1` and `v1beta` instead of only `v1beta`

I'm preparing for a test recently. After my test is over, if no one has solved it, I want to give it a try.

**Comment by H0llyW00dzZ** [comment]
> > It's only refactoring support `v1` and `v1beta` instead of only `v1beta`
> 
> I'm preparing for a test recently. After my test is over, if no one has solved it, I want to give it a try.

nice

**Comment by H0llyW00dzZ** [comment]
@Rubuark it's better to trying
