### ISSUE TITLE
[Feature] Huggingface space deploy

### ISSUE THREAD

**Issue by nnWhisperer** [ChatGPTNextWeb/ChatGPT-Next-Web#4042]
Since the system requirements of the repository is low, we can use Huggingface's free spaces to deploy the app to run 24/7, in a private VM.

In readme.md, you may add "deploy to huggingface" [like this repo](https://github.com/weaigc/bingo/blob/eaebba306d5f68b940e4486ad81897516d0db0f3/README.md?plain=1#L94).

I use google colab and have to close it after the use is over and hence I lose the history unless I deliberately save them. Instead, I'd prefer to use a machine that I could access 24/7, freely.

I think that feature would be handy for many. Thank you

**Comment by fred-bf** [comment]
@nnWhisperer Hi, you can easily using Vercel or CloudFlare deploy NextChat, may I ask is there any specific requires to deploy on HuggingFace. As for chat history, NextChat stores chat history in your browser, not relevant to the deploy platform you are using.
