### ISSUE TITLE
[Bug] 请问大家钱多多用的nextweb是哪个版本的嘞？

### ISSUE THREAD

**Issue by leezhuuu** [ChatGPTNextWeb/ChatGPT-Next-Web#4049]
[Bug] 请问大家钱多多用的nextweb是哪个版本的嘞？
感谢大佬们来回复一下

**Comment by SuiYunsy** [comment]
https://github.com/vual/ChatGPT-Next-Web-Pro

**Comment by leezhuuu** [comment]
感谢🙏🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月17日(周六) 中午12:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ChatGPTNextWeb/ChatGPT-Next-Web] [Bug] 请问大家钱多多用的nextweb是哪个版本的嘞？ (Issue #4049)




 
https://github.com/vual/ChatGPT-Next-Web-Pro
