### ISSUE TITLE
[Bug] api接口在Postman中可以调用成功，但是在nextchat里返回失败，如何配置

### ISSUE THREAD

**Issue by boboyunz** [ChatGPTNextWeb/ChatGPT-Next-Web#4050]
api接口 用Postman可以调用成功
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/45583988/f3b2467f-ec2c-475f-b97b-533e69599991)
但是配置到nextchat项目里就返回失败
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/45583988/619d0147-2c56-470d-b5b9-683f11031640)
如下是nginx代理的配置
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/45583988/df9c6645-8dbc-4b34-885e-36dd3f3f8b76)

**Comment by fred-bf** [comment]
please provide the error messages, thx
