### ISSUE TITLE
[Bug] API key 无法在ChatGPT-Next-Web中使用

### ISSUE THREAD

**Issue by zip8919** [ChatGPTNextWeb/ChatGPT-Next-Web#4052]
**Describe the bug**
API key在其他项目能使用，这个项目就不能
输入正确的访问密码提示访问密码不正确或为空
使用vercel自定义域名不能打开，显示“将您重定向的次数过多。”，使用cloudflare worker反向代理可以打开

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/110547378/47268675-8b6a-4c1e-b240-f50062c3f696)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/110547378/e5d93cf5-732e-4551-bf27-b2a4178c2675)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/110547378/25db57bb-2eb2-42ad-bd3f-cf3ab3698d70)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/110547378/58a89c8f-9af2-417e-ab13-f6968d4c5975)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/110547378/a2fcc7ec-19e0-4d7c-8357-0872a1e57edf)

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.
{
  "error": {
    "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

{
  "error": {
    "message": "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by QAbot-zh** [comment]
部署的时候接口地址配了吗

**Comment by fred-bf** [comment]
Its more like your deployment issue, you should be able to directly access via you vercel deployment url
