### ISSUE TITLE
postman测试使用代理地址正常,但是应用部署之后使用报错-3001

### ISSUE THREAD

**Issue by mlin1997** [ChatGPTNextWeb/ChatGPT-Next-Web#4063]
{
  "cause": {
    "errno": -3001,
    "code": "EAI_AGAIN",
    "syscall": "getaddrinfo",
    "hostname": "chat.m-lin.cn"
  }
}

**Comment by 66dexmg** [comment]
这是主机的hostname解析失败了，修改hostname就可以了
