### ISSUE TITLE
[Bug] error:We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.

### ISSUE THREAD

**Issue by zip8919** [ChatGPTNextWeb/ChatGPT-Next-Web#4064]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.
{
  "error": {
    "message": "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by fred-bf** [comment]
@zip8919 could you share more details about how to reproduce this issue? e.g. prompts, message, etc

**Comment by fred-bf** [comment]
@jamesKhor I mean how did you trigger this issue(e.g. prompts), and did it exists on every messages you sent or specify message?

**Comment by jamesKhor** [comment]
it was every request/prompt. I just found the root cause. i was running an old version 20230601.

**Comment by kevinxxq** [comment]
> it was every request/prompt. I just found the root cause. i was running an old version 20230601.

I have the same problem.
