### ISSUE TITLE
[Feature] 能否添加一个日志功能，希望能查询别人的使用记录，并且支持封禁等功能

### ISSUE THREAD

**Issue by ryanzhaorx** [ChatGPTNextWeb/ChatGPT-Next-Web#4074]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
能否添加一个日志功能，希望能查询别人的使用记录，并且支持封禁等功能
Can you add a log function, hope to query other people's usage records, and support blocking and other functions

**你想要什么功能或者有什么建议？**
能否添加一个日志功能，希望能查询别人的使用记录，并且支持封禁等功能
Can you add a log function, hope to query other people's usage records, and support blocking and other functions

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Caligula1022** [comment]
可以简单做一个类似于钓鱼网站的东西，把发送到外部的请求同时转发到自己的一个后端服务里保存下来，就可以查看相关信息了。我自己简单做了个。
