### ISSUE TITLE
Integrated with Ollama 

### ISSUE THREAD

**Issue by Alias4D** [ChatGPTNextWeb/ChatGPT-Next-Web#4090]
### Problem Description

I need using NextChate as Ui for Ollama on windows ?
i run Ollama om my windows pc and serve my LLMS on http://localhost:11434/

### Solution Description

by Use costume model Futers on next chat , I need to integrate NextChat with Ollama OpenApi Futers

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/27604791/acd22369-8f2a-47b2-9cdb-b390f232c9f8)

**Comment by H0llyW00dzZ** [comment]
No, not yet. Even the service provider `Google` is not as stable as the service provider `OpenAI` (`which already done`). Additionally, `Ollama` is still in pre-release and not fully stable.

**Comment by fred-bf** [comment]
You are able to use ollama in dev builds, for production builds tauri is using different hostname, you may need to configure `OLLAMA_ORIGINS` follow this instructions https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server

**Comment by fred-bf** [comment]
We will publish an individual doc with step by step guide to integrate ollama with NextChat

**Comment by Alias4D** [comment]
Thanks for reply
