### ISSUE TITLE
{   "error": {     "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",     "type": "insufficient_quota",     "param": null,     "code": "insufficient_quota"   } }[Bug] 

### ISSUE THREAD

**Issue by jessicayang24** [ChatGPTNextWeb/ChatGPT-Next-Web#4101]
### Bug Description

does this mean that need purchase token?

### Steps to Reproduce

{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}

### Expected Behavior

support

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by QAbot-zh** [comment]
翻译一下呀哥们，insufficient_quota， 你的key没额度了

**Comment by Envy271** [comment]
> 翻译一下呀哥们，insufficient_quota， 你的key没额度了

大佬，我今天也报这个了，但是我看我的5美元，才花了0.1
