### ISSUE TITLE
[Feature Request]: azure openai 部署的时候如何实现 gpt4 跟 gpt3 同时部署。

### ISSUE THREAD

**Issue by itcodes** [ChatGPTNextWeb/ChatGPT-Next-Web#4111]
### Problem Description

现在部署的时候，类似这个地址：https://{azure-resource-url}/openai/deployments/{deploy-name}
但是deploy-name只能填 1 个，意味着一个项目选一个模型。

### Solution Description

我用过cf-openai-azure-proxy，这个是可以实现，但是如何在 nextweb 中用原生的链接呢？

**Comment by fred-bf** [comment]
you can custom "BASE_URL" with provider like one-api, once user change the model they are using, the completion request will pass the selected model to server

**Comment by oicoderr** [comment]
在不更改chatgpt-next-web项目前提，可以采用代理转发https://github.com/oicoderr/azure-openai-proxy，希望可以帮助到你
