### ISSUE TITLE
[Bug] 最新版windwos客户端使用自定义API，当自定义API地址为https，且为无效的自定义证书时，会造成"Failed to fetch"

### ISSUE THREAD

**Issue by chiguabaobao** [ChatGPTNextWeb/ChatGPT-Next-Web#4112]
### Bug Description

最新版windwos客户端使用自定义API地址，当自定义API地址为https，且为无效的自定义证书时，会造成"Failed to fetch"。使用http或有效证书时，不会出现此问题。
{
  "error": true,
  "message": "Failed to fetch"
}

### Steps to Reproduce

1.部署最新windows客户端
2.分别准备一个自定义API地址，分别为http模式、https证书有效模式、自定义https证书模式
3.使用同样的token
4.分别验证，在使用自定义https证书模式触发"Failed to fetch"错误

### Expected Behavior

能否取消或修订客户端的https证书校验机制，允许自定义证书的https API地址可以使用，谢谢！

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

windows10

### Desktop Browser

Chrome

### Desktop Browser Version

122.0.6261.70

**Comment by fred-bf** [comment]
its met expectation, you will need to configure a vaild https cert
