### ISSUE TITLE
[Feature Request]: 什么时候支持开源的gemma

### ISSUE THREAD

**Issue by ynclub** [ChatGPTNextWeb/ChatGPT-Next-Web#4119]
### Problem Description

没有开源的gemma的设置

### Solution Description

什么时候支持开源的gemma?或者现在用，怎么设置？

**Comment by liheji** [comment]
#4030  Ollama 集成在计划中

**Comment by fred-bf** [comment]
@ynclub @liheji The latest release of NextChat supports Ollama. You can check out the documentation here to use Gemma through Ollama: https://docs.nextchat.dev/models/ollama

**Comment by fred-bf** [comment]
> > @ynclub @liheji The latest release of NextChat supports Ollama. You can check out the documentation here to use Gemma through Ollama: https://docs.nextchat.dev/models/ollama
> 
> 你好，我将OLLAMA_ORIGINS=tauri://localhost添加到环境变量中得到错误如下， ![image](https://private-user-images.githubusercontent.com/13515498/309688427-258788c5-d659-44e1-8fad-0b97b6dd2eef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTE0MzUsIm5iZiI6MTcwOTU1MTEzNSwicGF0aCI6Ii8xMzUxNTQ5OC8zMDk2ODg0MjctMjU4Nzg4YzUtZDY1OS00NGUxLThmYWQtMGI5N2I2ZGQyZWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDExMTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOTk1NTRkN2RhZmQwMzNjYjhmNTBhMTJlNmU4Y2MxNWNjNGNkYzBmYzlhNTlmOGIzMDU1MWY1OThlMDllN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aVPrAKNbYqcWCMiJe2Euuip5pH7LrdbH9stTbqcZFJ0)
> 
> 所以我把tauri替换成http，但是在nextweb中无法获取并得到403的错误 ![image](https://private-user-images.githubusercontent.com/13515498/309688790-fbe706df-19a1-4f96-8f23-9c2d61dbecdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTE0MzUsIm5iZiI6MTcwOTU1MTEzNSwicGF0aCI6Ii8xMzUxNTQ5OC8zMDk2ODg3OTAtZmJlNzA2ZGYtMTlhMS00Zjk2LThmMjMtOWMyZDYxZGJlY2RjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDExMTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMGIxMTA5ZTQ3MTViZGFjNGEwMzM0YTA2ODUzNDY2ZTM1ZDUwMDI4MDdlODJmMmM4Mjk5NmVhOWY3OTAxMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ADyYgiliGvtK27h4U99urbzJPrdLxuvHOdV3v8SV0IM)

You can try change env `OLLAMA_ORIGINS` value to `*://localhost`

**Comment by eryajf** [comment]
> > You can try change env `OLLAMA_ORIGINS` value to `*://localhost`
> 
> 你好, 依旧出错 "( ![image](https://private-user-images.githubusercontent.com/13515498/309756743-65743a7d-985a-402d-9308-c35aacedb01e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDY1ODEsIm5iZiI6MTcwOTY0NjI4MSwicGF0aCI6Ii8xMzUxNTQ5OC8zMDk3NTY3NDMtNjU3NDNhN2QtOTg1YS00MDJkLTkzMDgtYzM1YWFjZWRiMDFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEzNDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExM2E0ZTk1NWVkOTQ1ZmUwMzZkM2I3Y2IwNDUxZTgxMzU4ODgzYWQ4YzRiZDY3ODc2NmIyNjBhNWYwODc1YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tGEGh0rscynVnx49lv_LcOL5AEfhx7OcKKnbnyKzZsc)

估计还是因为你的环境变量没有设置成功的缘故，我一开始使用如下命令启动：

```
OLLAMA_ORIGINS=*://localhost;OLLAMA_HOST="0.0.0.0";ollama serve
```

然后请求也是看到403，改成下边的方式启动，就能正常请求了：

```
export OLLAMA_ORIGINS=*://localhost;export OLLAMA_HOST="0.0.0.0";ollama serve
```

**Comment by wanix1988** [comment]
@Leroy-X  这个问题你解决了吗？我的Linux环境也有一样的问题。
export OLLAMA_ORIGINS=*://localhost;export OLLAMA_HOST="0.0.0.0";ollama serve

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/2557883/05697f07-56df-43c0-bdfe-3d95b9bcef17)

**Comment by cnliucheng** [comment]
在mac环境下如果要使用127.0.0.1:11434或localhost:11434，应该这样设置启动才行：
export OLLAMA_ORIGINS=*://localhost;export OLLAMA_HOST="127.0.0.1";ollama serve
