### ISSUE TITLE
[Bug] 图片问答结果展示不完整

### ISSUE THREAD

**Issue by zhaojie199512** [ChatGPTNextWeb/ChatGPT-Next-Web#4143]
### Bug Description

使用gpt-4-vision模式，上传图片后，结果只展示前几个字。
docker镜像版本：v2.11.2
docker ID：sha256:e286024c3691048a2f57bdd253d2b333d3ecff563819c97616814621a5e53373

### Steps to Reproduce

选择gpt-4-vision模型，然后生成图片，回答问题。

### Expected Behavior

完整的展示图片的识别结果

### Screenshots

![下载](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/12878073/ccb64f02-b4b1-4b34-b4a3-0516dfe5a152)

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by AndyX-Net** [comment]
重复性问题，引用链接：
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4084

请在提问前确保你浏览了Issue列表中正在被报告的问题。
