### ISSUE TITLE
[Feature Request]: Implement another service provider for community/open source

### ISSUE THREAD

**Issue by H0llyW00dzZ** [ChatGPTNextWeb/ChatGPT-Next-Web#4144]
### Problem Description

By implementing another service provider for the community/open source, maintenance would be easier compared to the current use of the `OpenAI` service provider, which is already stable and doesn't require further refactoring.

### Solution Description

The solution for implementing another service provider for the community/open source can be found here:

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/d931e852-514d-48c0-9527-8efdd545f43b)

**Comment by H0llyW00dzZ** [comment]
> [!NOTE]  
> Implementing this change would also result in greater independence, unlike the current situation that relies on OpenAI service providers to utilize models not available within OpenAI itself.

**Comment by fred-bf** [comment]
duplicated to https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4030, will be add support to manage different model providers
