### ISSUE TITLE
[Feature Request]: Enhance the Service Provider for Increased Effectiveness

### ISSUE THREAD

**Issue by H0llyW00dzZ** [ChatGPTNextWeb/ChatGPT-Next-Web#4145]
### Problem Description

The current service provider is not as effective as it could be, leading to potential bugs and making maintenance challenging.

### Solution Description

Improving the current state would be beneficial. For instance, Azure, Google, and OpenAI each have their own models. Likewise, the community, including Hugging Face and Ollama, also have their own models. Enhancing the service provider in this way would not only facilitate easier maintenance but could also attract more contributors, unlike the current situation where it is primarily a solo effort.

**Comment by H0llyW00dzZ** [comment]
This enhancement related to this as well:

- #4144

**Comment by fred-bf** [comment]
duplicated to https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4030

**Comment by H0llyW00dzZ** [comment]
> duplicated to #4030

wdym duplicated you just adding yesterday after I post this issue 

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/5d3ffa3d-584b-4b74-b155-b4dbc6b12307)
