### ISSUE TITLE
[Feature Request]: 希望能单聊天窗实现多面具问答

### ISSUE THREAD

**Issue by s836064858** [ChatGPTNextWeb/ChatGPT-Next-Web#4147]
### Problem Description

无

### Solution Description

希望能单聊天窗实现多面具问答，比如一个文章，使用A面具解读其大纲，再使用B面具进行仿写。

**Comment by s836064858** [comment]
OK, looking forward to it

**Comment by lloydzhou** [comment]
1. v2.15.0支持插件功能（以GPTs action的方式封装插件）
2. 但是插件不与mask绑定，只在会话中进行选择。
3. 所以，在单个会话中可以绑定多个实现不同功能的插件(action)，会话过程中LLM会选择合适的插件去执行（依赖function tool实现）。
4. 这个效果应该比较接近
