### ISSUE TITLE
Request Header Fields Too Large [Bug] 

### ISSUE THREAD

**Issue by Pandoxie** [ChatGPTNextWeb/ChatGPT-Next-Web#4151]
### Bug Description

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/4418547/11405622-6b26-48f2-b4e3-ed2b89127fc9)
在一些模型上面会稳定出现Request Header Fields Too Large错误（GPT3.5），但是在切换GPT4之后并不会出现。观察了两者发布的header并没有发现明显问题。有没有人碰到类似问题？

浏览器： Chrome， IOS Safari等均如此，应该是某些地方的设置问题。

### Steps to Reproduce

只需要切换模型即可复现

### Expected Behavior

不同模型应该不存在一个能输出，一个header过大出错的情况。

### Deployment Method

- [X ] Docker
- [ ] Vercel
- [ ] Server

**Comment by fred-bf** [comment]
@Pandoxie should you share the original request(e.g. fetch or curl), and which model provider are you using?

**Comment by Pandoxie** [comment]
> @Pandoxie should you share the original request(e.g. fetch or curl), and which model provider are you using?

I used Aliyun proxy and I found that they have some limitations of http header:
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/4418547/9de2e2df-e578-48d9-a4bb-ce381598fc00)

Now I switched proxy provider and the above errors are gone. But may be you guys can do some digging about why the headers can be so large?

**Comment by fred-bf** [comment]
@Pandoxie could you reproduce the issue and post the request header in the chrome console here. it would be helpful to locate the issue, there is no other similar feedback up to now.

**Comment by H0llyW00dzZ** [comment]
> > @Pandoxie could you reproduce the issue and post the request header in the chrome console here. it would be helpful to locate the issue, there is no other similar feedback up to now.
> 
> sure, here is a sample Request Headers:
> 
> ![image](https://private-user-images.githubusercontent.com/4418547/308071866-7eba9fe0-3fb7-4d09-a3f2-e120b41be300.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjIwMzAsIm5iZiI6MTcwOTAyMTczMCwicGF0aCI6Ii80NDE4NTQ3LzMwODA3MTg2Ni03ZWJhOWZlMC0zZmI3LTRkMDktYTNmMi1lMTIwYjQxYmUzMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMDgxNTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Q1NzExMzU0NDY4MGEwZDEwZDdhYWMzNzc3ZWZkYzFlYmUxNjkxZjhmMTAyYjZmZTM5MGRjMDljZjBmNzRjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BUQzQw4yBZAcOrjzYatuZ9yXZAX_QV0ASFZOTKdDKXo)
> 
> I am no expert of web tech... tell me to delete the pic if some secrets may be leaked about openai account... thx

it's because of this maybe 

ff166f7b4cf52be5716fb93b7c0f3c872def2ef5 << should be not removed by @Yidadaa
