### ISSUE TITLE
[Bug] 同一个KEY会提示您超出了当前配额，但该key在其他软件可用，且我很确定没有超过配额

### ISSUE THREAD

**Issue by ji-jinlong** [ChatGPTNextWeb/ChatGPT-Next-Web#4154]
### Bug Description

前3张图证明我确实没有超过当前配额，后一张图表明这个key在另一个软件可以用。
![f104b0ee29b08dbf3c641c40138cb3a8](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/61379293/70209863-a83b-4647-bb5e-945a40ce0825)
![373465dada5f4758b14f3ef8d55de139](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/61379293/2e5ac127-1212-4b5b-949f-699b55f7f847)
![4ecf463b17ae6580c0dae81a3d9b6b64](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/61379293/6f434eb3-0e98-4341-9c8e-7f58f27c6e89)
![523df62a310f5826c46229359d14a605](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/61379293/8affcc67-8b4d-4c95-8f70-60e430f59733)

### Steps to Reproduce

我也不知道。我用的vercel部署的。设置了OPENAI_API_KEY、GOOGLE_API_KEY、CODE、ENABLE_BALANCE_QUERY。

### Expected Behavior

希望他正常使用

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

Windows11

### Desktop Browser

chrome

### Desktop Browser Version

121.0.6167.189

### Additional Logs

{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}

**Comment by fred-bf** [comment]
@ji-jinlong sorry we cannot reproducing from our side, you can try to double check you custom endpoint setting & server deployment env variables. If the above method doesn't work, you can debug to see what the OpenAI API key used in the original request

**Comment by wxin996** [comment]
same question

**Comment by H0llyW00dzZ** [comment]
have you try disable this settings ?

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/b0e5c72f-aa30-4e8f-9814-b91fdc0ae56b)

**Comment by ji-jinlong** [comment]
@H0llyW00dzZ 我确定此设置没有打开
![Clip_2024-02-27_17-08-15](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/61379293/3565694c-3358-422a-947c-c1ab7b33ef25)

**Comment by ji-jinlong** [comment]
@fred-bf @H0llyW00dzZ  我在清除浏览器本地数据后正常了。感谢各位的帮助。 @wxin996 可以按照如图删掉网页数据再进
![Clip_2024-02-27_17-19-08](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/61379293/728da579-b2e8-4e5b-84e6-3723cd8e9cf0)
![Clip_2024-02-27_17-20-18](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/61379293/94b820e9-38e3-4c0a-9f17-2040055c85cd)

**Comment by saturosfz** [comment]
我也遇到这个问题
