### ISSUE TITLE
[Feature Request]: 是否支持gpt-4-gizmo模型调用gpts

### ISSUE THREAD

**Issue by lipc20052006** [ChatGPTNextWeb/ChatGPT-Next-Web#4161]
### Problem Description

是否支持gpt-4-gizmo模型调用gpts

### Solution Description

是否支持gpt-4-gizmo模型调用gpts

**Comment by QAbot-zh** [comment]
> ### Problem Description
> 是否支持gpt-4-gizmo模型调用gpts
> 
> ### Solution Description
> 是否支持gpt-4-gizmo模型调用gpts
> 
> ### Alternatives Considered
> _No response_
> 
> ### Additional Context
> _No response_

直接自定义模型名称调用就完事了，gizmo本来也是国内中转逆向出来的模型，都是走chat端点的

**Comment by vual** [comment]
https://github.com/vual/ChatGPT-Next-Web-Pro，我这边实现了gpts功能，支持gpt-4-gizmo相关模型，及上传文件。
