### ISSUE TITLE
app.nextchat.dev 不能设置 API Key了吗？

### ISSUE THREAD

**Issue by ziming012** [ChatGPTNextWeb/ChatGPT-Next-Web#4168]
rt

**Comment by ziming012** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> **Title:** app.nextchat.dev Can’t set API Key?

没必要，这种项目除了中国人感兴趣，还有别的国家的人？

**Comment by fred-bf** [comment]
@ziming012 you can still set your own api key in chat or settings

**Comment by ziming012** [comment]
> @ziming012 you can still set your own api key in chat or settings

我没有发现该选项
