### ISSUE TITLE
[Bug] Bold text mark appears in the chat title when using `gemini-pro` model

### ISSUE THREAD

**Issue by hjkcai** [ChatGPTNextWeb/ChatGPT-Next-Web#4170]
### Bug Description

<img width="626" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/731326/925c43ed-e139-471b-8658-1a638dc36985">

### Steps to Reproduce

1. Configure `gemini-pro` with default settings
2. Enter the prompt "Give 5 pros and cons about react"
3. Wait for the chat title to change. The bold mark can be seen in the title

### Expected Behavior

No bold mark

**Comment by H0llyW00dzZ** [comment]
I've been knowing this

PR:
- #4089

> [!NOTE]  
> That PR fixes this issue

**Comment by fred-bf** [comment]
@H0llyW00dzZ merged, thanks for your contribution
