### ISSUE TITLE
[Bug] it seems that `max_token`s not be sent as a request param

### ISSUE THREAD

**Issue by slow-groovin** [ChatGPTNextWeb/ChatGPT-Next-Web#4172]
### Bug Description

# background:  
I'm using a openai  proxy gateway(api2d.com), it requires `max_tokens` param in api `v1\chat\completions` to identify if left purchase points meet require tokens, if not it will return a `402 Payment Required`  status
# problem
the request from NextChat has no param `max_tokens` whether set it or not. (test on v2.10.2  v2.11.2)
And i found that the setting `max_tokens` seems like a local setting, if set it too small, the eventstream will be end. 
(The client ends, whether the server calculate the tokens of not finished response? it seems like api2d.com does it.

### Steps to Reproduce

simply send a chat

### Expected Behavior

has a `max_tokens` request body param

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Additional Logs

the request body(has no `max_tokens`
```json
{
    "messages": [
        {
            "role": "user",
            "content": "who are u？ whatis your data endline?"
        },
        {
            "role": "assistant",
            "content": "I am a language model AI created by OpenAI. My purpose is to assist users in generating human-like text based on the input provided to me. I do not have personal data or an endline as I am a machine learning model."
        },
        {
            "role": "user",
            "content": "使用四到五个字直接返回这句话的简要主题，不要解释、不要标点、不要语气词、不要多余文本，不要加粗，如果没有主题，请直接返回“闲聊”"
        }
    ],
    "model": "gpt-3.5-turbo",
    "temperature": 0.5,
    "presence_penalty": 0,
    "frequency_penalty": 0,
    "top_p": 1
}
```

**Comment by H0llyW00dzZ** [comment]
`402 Payment Required`
it literally `api2d.com` issue lmao
