### ISSUE TITLE
[Feature Request]: Docker部署的如何开启ssl

### ISSUE THREAD

**Issue by Xiao-yux** [ChatGPTNextWeb/ChatGPT-Next-Web#4173]
### Problem Description

想开启https访问

### Solution Description

容器变量，添加证书

### Alternatives Considered

我现在使用的是nginx代理流量，但是源端口还开着，我不想占用2个端口

**Comment by fred-bf** [comment]
You can check out nginx documentation, https://nginx.org/en/docs/http/configuring_https_servers.html

The specific configuration method can be learned directly through the search engine
