### ISSUE TITLE
[Bug] Issue with NextWeb API Key Deactivation Error

### ISSUE THREAD

**Issue by JiaxiangBU** [ChatGPTNextWeb/ChatGPT-Next-Web#4176]
### Bug Description

I encountered an issue where I received the following error message while using the NextWeb API:

```json
{
  "msg": "Invalid OpenAI Response",
  "type": "application/json; charset=utf-8",
  "body": {
    "error": {
      "message": "The OpenAI account associated with this API key has been deactivated. If you are the developer for this OpenAI app, please check your email for more information. If you are seeing this error while using another app or site, please reach out to them for more help.",
      "type": "invalid_request_error",
      "param": null,
      "code": "account_deactivated"
    }
  },
  "status": 401,
  "edgeId": "next-edge-l8TUp14GKpp38atZ2wW5c"
}
```

Despite having sufficient quota in my account, I am receiving this `account_deactivated` error. I kindly request assistance in resolving this issue promptly.

### Steps to Reproduce

See content.

### Expected Behavior

See content.

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by fred-bf** [comment]
@JiaxiangBU hi, it seems to be the api key have been deactivated, its has nothing to do with whether your account has sufficient balance

**Comment by JiaxiangBU** [comment]
> @JiaxiangBU hi, it seems to be the api key have been deactivated, its has nothing to do with whether your account has sufficient balance

Hi, thank you for the clarification. Just to confirm, does this mean that there is an issue with the author's API key being deactivated, regardless of the balance in my account?

**Comment by fred-bf** [comment]
yep

**Comment by JiaxiangBU** [comment]
I contacted the developer of the project, and the API is now functioning normally.
