### ISSUE TITLE
[Bug] 访问密码不正确或为空

### ISSUE THREAD

**Issue by LOGIC-10** [ChatGPTNextWeb/ChatGPT-Next-Web#4177]
### Bug Description

11小时前的PR合并后，访问页面就一直在显示：访问密码不正确或为空，请前往[登录](https://app.nextchat.dev/#/auth)页输入正确的访问密码，或者在[设置](https://app.nextchat.dev/#/settings)页填入你自己的 OpenAI API Key。

然而我已经配置好了API key，之前正常使用的配置没有更改

### Steps to Reproduce

1. 配置所有项
2. 启动chat
3. 遇到报错

### Expected Behavior

正常chat

### Screenshots

<img width="925" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/62985169/882e6c52-c65a-4cf4-a403-a11166fb9496">

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

Mac book the latest

### Desktop Browser

safari

### Desktop Browser Version

版本17.2.1 (19617.1.17.11.12)

### Additional Logs

None

**Comment by QAbot-zh** [comment]
+1

**Comment by H0llyW00dzZ** [comment]
This is an your OpenAI issue and is not related to this repository.
