### ISSUE TITLE
The response content of gpt4-vision model is too short [Bug] 

### ISSUE THREAD

**Issue by liaokaime** [ChatGPTNextWeb/ChatGPT-Next-Web#4179]
### Bug Description

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/27792976/1cc7e006-284b-418f-b59e-3a46fd6bde89)
As you can see, the reply content is only a few short words, I tried to set max_tokens to a larger size (16000), but it didn't work.

### Steps to Reproduce

1. Set the model to gpt-4-vision-preview
2. Set max tokens to 16000
3. New chat
4. Send a picture and ask about the picture

### Expected Behavior

Reply to a full paragraph, not just a few words

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows11

### Desktop Browser Version

v2.11.2

**Comment by fred-bf** [comment]
@liaokaime plz try upgrade to latest version, fixed in https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commit/43e5dc22920c60bf87fc1b78bf95c441356bb1d8

**Comment by liaokaime** [comment]
> @liaokaime plz try upgrade to latest version, fixed in [43e5dc2](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commit/43e5dc22920c60bf87fc1b78bf95c441356bb1d8)

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/27792976/463555d0-89d3-4521-b151-2f8e34d1489f)
The latest version I saw in release was v2.11.2, as was the one I downloaded

**Comment by fred-bf** [comment]
@liaokaime The submission of this fix is not released to the latest app, please wait patiently for the new version to be released or temporarily switch to the web version first. https://app.nextchat.dev

**Comment by liaokaime** [comment]
> @liaokaime The submission of this fix is not released to the latest app, please wait patiently for the new version to be released or temporarily switch to the web version first. https://app.nextchat.dev

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/27792976/9d8724de-662c-4698-92ba-f905be606277)
Unfortunately, it seems that this online address does not fix the problem either

**Comment by fred-bf** [comment]
@liaokaime Sorry for the incorrect information, the official website was a few commits behind before the deployment. It's just been updated and you can try again
