### ISSUE TITLE
[Bug] Mac OS版本不支持中文输入

### ISSUE THREAD

**Issue by LittleFishLove** [ChatGPTNextWeb/ChatGPT-Next-Web#4182]
### Bug Description

如题，Mac OS Sonoma 14.3.1，Intel芯片下，本地部署的客户端无法输入中文，输入法会自动切换为英文输入法。软件版本是：[NextChat_2.11.2_universal.dmg](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/download/v2.11.2/NextChat_2.11.2_universal.dmg)，语言选择为中文。

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/35796964/dfcfda47-f71d-4167-958f-ffe8368ca15a)

### Steps to Reproduce

在任意相同配置Mac电脑进行测试即可

### Expected Behavior

下个版本中修复此问题

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

MacOS Sonoma 14.3.1

**Comment by fred-bf** [comment]
@LittleFishLove hi, it should be related to your system issue, NextChat cannot control which language to enter

**Comment by RRAMAYAN123** [comment]
打开系统设置：

点击屏幕左上角的苹果标志，选择“系统设置”。
导航到隐私与安全性：

在侧边栏中，向下滚动并点击“隐私与安全性”。
访问输入监控设置：

在“隐私与安全性”页面，找到并点击“输入监控”。
解锁设置以进行更改：

点击窗口左下角的锁图标，输入您的管理员密码以解锁设置。
查找并设置 ChatGPT 应用的权限：

在右侧列表中，查找 ChatGPT 应用。
如果找到，确保其旁边的开关处于开启状态。
如果未找到 ChatGPT 应用，您可能需要手动添加。
手动添加 ChatGPT 应用（如果需要）：

点击列表下方的“+”按钮。
在弹出的文件选择窗口中，导航到 ChatGPT 应用的位置，通常位于“应用程序”文件夹中。
选择 ChatGPT 应用，然后点击“打开”或“添加”。
重启 ChatGPT 应用：

关闭并重新打开 ChatGPT 应用，以确保新的权限设置生效。
