### ISSUE TITLE
[Bug] Azure gpt4的api传过来的数据为什么是2021年的

### ISSUE THREAD

**Issue by Rocky923** [ChatGPTNextWeb/ChatGPT-Next-Web#4183]
### Bug Description

配置完成Azure gpt-4-32k后问他的数据是什么时候的，返回说是2021年9月份

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/50512840/117b4a89-6a84-4bab-a4a1-262622f9d445)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/50512840/617ff16a-d631-4c55-aa3e-88c4a9a56d15)

### Steps to Reproduce

Docker部署后问他的模型和数据的时间

### Expected Behavior

根据azure中的数据时间

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by AndyX-Net** [comment]
我这测试似乎没有问题：

AzureOpenAI 操场:
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/27819097/5a72a3a7-797e-439a-9422-92580e16c6f9)

当前部署模型：
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/27819097/382446b4-5fec-4c61-b473-10080fa0bcad)

NextWeb测试(匹配gpt-4-0125-preview):
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/27819097/df2f65f5-ad6c-4991-89db-9934221be169)


建议楼主看下你是不是在NextWeb界面选错了模型。

**Comment by AndyX-Net** [comment]
Again, Check this:
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models

**Comment by reece00** [comment]
test

**Comment by CK110** [comment]
xxxx./openai/deployments/GPT4-Turbo/chat/completions?api-version=2023-07-01-preview

curl call ，能显示是23年的训练数据，用ChatGPT-Next-Web 也是提示 2021年9月

**Comment by Rocky923** [comment]
> 我这测试似乎没有问题：
> 
> AzureOpenAI 操场: ![image](https://private-user-images.githubusercontent.com/27819097/309213501-5a72a3a7-797e-439a-9422-92580e16c6f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1Mzc5MTYsIm5iZiI6MTcwOTUzNzYxNiwicGF0aCI6Ii8yNzgxOTA5Ny8zMDkyMTM1MDEtNWE3MmEzYTctNzk3ZS00MzlhLTk0MjItOTI1ODBlMTZjNmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA3MzMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZWJlNjVhMTc5MzI2N2M5MjU5NGMxOTA2N2IwMzI2ZGRmYTczMWJiNjM1OTQ0ZTk1YTk1N2ZiMjdhYTc4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oFoqsybKg_4i0PGUKBEu-j0hqlcP-K9jYhM6r2J9mkI)
> 
> 当前部署模型： ![image](https://private-user-images.githubusercontent.com/27819097/309213533-382446b4-5fec-4c61-b473-10080fa0bcad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1Mzc5MTYsIm5iZiI6MTcwOTUzNzYxNiwicGF0aCI6Ii8yNzgxOTA5Ny8zMDkyMTM1MzMtMzgyNDQ2YjQtNWZlYy00YzYxLWI0NzMtMTAwODBmYTBiY2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA3MzMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNjc5OWZiOTA2ZDY3ODZlZmQ5ODA2ZTFhMjMzZmY3NTM2Mzg1YmYyMjliYjQxMTRhNDM1ZmE2MjE5YWJkMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.__9oL7wpnu4PwsFUP9_DWIt5n7zQAMxg4o5IgLc1GZg)
> 
> NextWeb测试(匹配gpt-4-0125-preview): ![image](https://private-user-images.githubusercontent.com/27819097/309213610-df2f65f5-ad6c-4991-89db-9934221be169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1Mzc5MTYsIm5iZiI6MTcwOTUzNzYxNiwicGF0aCI6Ii8yNzgxOTA5Ny8zMDkyMTM2MTAtZGYyZjY1ZjUtYWQ2Yy00OTkxLTg5ZGItOTkzNDIyMWJlMTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA3MzMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMzdlMDQ4MzE1Y2JlNjVjNjlhYWU2ZmExMDk2N2M4MjliZTczN2IzMjQ5YjdhYjkzNmZiODVjYTBkZTIzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0D_JtSfU8Z8RbY5ylZBhF5SHn7iEWbZ0ntgMZdox1JA)
> 
> 检查微软官网文档： https://learn.microsoft.com/zh-cn/azure/ai-services/openai/concepts/models
> 
> ![image](https://private-user-images.githubusercontent.com/27819097/309214601-effe0e98-182e-42cf-8daa-b085b72c104e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1Mzc5MTYsIm5iZiI6MTcwOTUzNzYxNiwicGF0aCI6Ii8yNzgxOTA5Ny8zMDkyMTQ2MDEtZWZmZTBlOTgtMTgyZS00MmNmLThkYWEtYjA4NWI3MmMxMDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA3MzMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNTBkZWNhODRiMzMzNTNkNWE2ZjQ5ODgxOGYzMmU5NzE4ZGI3YWZiZDhmMjgzZjhhNTdlMWE0Yzk0OGM4NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NrTwv_FpKYhwLuTfGGkWxCb4RjdvwIPzkZtyCFZy7kM)
> 
> 所以，你需要以微软官方文档为主，而不是只看模型版本。。。。。。。

@AndyX-Net 大佬，我尝试更换了模型还是有同样的问题，我的资源在澳洲，所以选择了1106-preview
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/50512840/377f5ee5-d62e-4297-8fc4-5b5e161db097)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/50512840/0d7d3cac-7fcb-47ce-8ff0-656bec4fb1ae)
在Azure ai中没有问题是2023年的
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/50512840/1a29b2d6-d15e-4f47-bca3-265a0462c41e)
但是在我自己运行的Docker环境中，还是出现返回的是2021年，我已经将Azureai上其他模型全部删完了，只剩下gpt-4 (1106-preview)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/50512840/81160529-e98e-4917-bc94-1d6f507c47f5)

**Comment by goodls-cs** [comment]
AZUre-GPT4需设置 "max_tokens" 值，否则返回输出将被截断。
例如：
{
    "messages": [ 
        {
            "role": "system", 
            "content": "You are a helpful assistant." 
        },
        {
            "role": "user", 
            "content": [
	            {
	                "type": "text",
	                "text": "Describe this picture:"
	            },
	            {
	                "type": "image_url",
	                "image_url": {
                        "url": "<image URL>"
                    }
                } 
           ] 
        }
    ],
    "max_tokens": 100, 
    "stream": false 
}
