### ISSUE TITLE
[Feature Request]: 能支持gpt-4-turbo-preview模型吗

### ISSUE THREAD

**Issue by heiheiheibj** [ChatGPTNextWeb/ChatGPT-Next-Web#4184]
### Problem Description

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/6910198/aac535fb-7a7a-468a-a2c7-e42f6a8ab37b)
看OPENAI 的官网，有 gpt-4 、gpt-4-0613、gpt-4-turbo-preview 等

### Solution Description

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/6910198/4ad185a8-2e11-433f-8f15-e958e324a599)
ChatGPTNextWeb配置中，是这几个，和OPENAI的是怎么个对应关系呢
如果能支持 gpt-4-turbo-preview 最好，它的限制比较宽一些
谢谢

**Comment by ersaijun** [comment]
已支持了呀

**Comment by heiheiheibj** [comment]
搞定，谢谢

> > Bot detected the issue body's language is not English, translate it automatically.
> 
> **Title:** [Feature Request]: Can the gpt-4-turbo-preview model be supported?
> 
> ### Problem Description
> ![image](https://private-user-images.githubusercontent.com/6910198/309273575-aac535fb-7a7a-468a-a2c7-e42f6a8ab37b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzkyNzIsIm5iZiI6MTcwOTczODk3MiwicGF0aCI6Ii82OTEwMTk4LzMwOTI3MzU3NS1hYWM1MzVmYi03YTdhLTQ2OGEtYTJjNy1lNDJmNmE4YWIzN2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMTUyOTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzM3MDM4MGY3ZDE0Yzg3ZjJkNDg2ZjZmNGQ1Y2I0Mjg2YjEzNmVmNTkzY2UyODcyZGUyYzI4MDMzY2ZiNmZhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-kGb-wEcTZR_T_MCh4Sr355BinaC0VG6r25JBGbGRLc) Look at the official website of OPENAI, there are gpt-4, gpt-4-0613, gpt-4-turbo-preview, etc.
> 
> ### Solution Description
> ![image](https://private-user-images.githubusercontent.com/6910198/309273817-4ad185a8-2e11-433f-8f15-e958e324a599.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzkyNzIsIm5iZiI6MTcwOTczODk3MiwicGF0aCI6Ii82OTEwMTk4LzMwOTI3MzgxNy00YWQxODVhOC0yZTExLTQzM2YtOGYxNS1lOTU4ZTMyNGE1OTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMTUyOTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2JiZTVjNjI2MjY0OGE0MDBjNDljNWUxMDMzZTlkYzQ2MTU3MzY0NTcyOGI3YmU1ZjQwNmViNDBmYTgxNTEzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1ptaD_vujCIRBW6EoVVwLue_0FOyAdZDmSk21xhqgzM) In the ChatGPTNextWeb configuration, what is the correspondence between these and OPENAI? It would be best if it could support gpt-4-turbo-preview, which has wider restrictions. Thanks
> 
> ### Alternatives Considered
> _No response_
> 
> ### Additional Context
> _No response_
