### ISSUE TITLE
[Bug] gpt-4-vision-preview模型回答中断

### ISSUE THREAD

**Issue by apollo5578** [ChatGPTNextWeb/ChatGPT-Next-Web#4185]
### Bug Description

使用gpt-4-vision-preview模型回答最多16个token长度，切换其他模型可以正常回答完毕，其他参数无变化.

### Steps to Reproduce

使用gpt-4-vision-preview模型回答最多20个token长度，切换其他模型可以正常回答完毕，其他参数无变化

### Expected Behavior

使用gpt-4-vision-preview模型回答最多20个token长度，切换其他模型可以正常回答完毕，其他参数无变化

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Oniokey** [comment]
遇到同样的 Bug +1，我这里是回答 Token 数不会超过 20，且设置 max_tokens 无效

**Comment by Oniokey** [comment]
这似乎不是受 NextChat 影响的，我通过直接调用 API （经过代理）也会出现同样的情况

**Comment by liaokaime** [comment]
This is expected to be resolved in the next release

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4179

**Comment by fred-bf** [comment]
This issue will be tracked in #4179
