### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 244135186** [ChatGPTNextWeb/ChatGPT-Next-Web#4188]
### Bug Description

{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}

### Steps to Reproduce

发送你好 就会出现错误

### Expected Behavior

回答问题

### Screenshots

![Snipaste_2024-03-02_10-53-38](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/95526326/d0a4b0cc-e20e-4a38-8319-4ad5739ea34a)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

**Comment by H0llyW00dzZ** [comment]
> ### Bug Description
> { "error": { "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.", "type": "insufficient_quota", "param": null, "code": "insufficient_quota" } }
> 
> ### Steps to Reproduce
> 发送你好 就会出现错误
> 
> ### Expected Behavior
> 回答问题
> 
> ### Screenshots
> ![Snipaste_2024-03-02_10-53-38](https://private-user-images.githubusercontent.com/95526326/309436926-d0a4b0cc-e20e-4a38-8319-4ad5739ea34a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDk5MTcsIm5iZiI6MTcwOTM0OTYxNywicGF0aCI6Ii85NTUyNjMyNi8zMDk0MzY5MjYtZDBhNGIwY2MtZTIwZS00YTM4LTgzMTktNGFkNTczOWVhMzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDAzMjAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZTMxNThlMDUyY2M5MGQ0ZTRlM2FkYTYzZGQxYzgwYmIyNTQyNDliYThlZTFiNzc1MTVhOWU3Njc2ODk2MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ww4_Uuk0eWZQxnQxkxZHUmEog1wXV05UwlBZq-LYeI)
> 
> ### Deployment Method
> * [ ]  Docker
> * [x]  Vercel
> * [ ]  Server
> 
> ### Desktop OS
> _No response_
> 
> ### Desktop Browser
> _No response_
> 
> ### Desktop Browser Version
> _No response_
> 
> ### Smartphone Device
> _No response_
> 
> ### Smartphone OS
> _No response_
> 
> ### Smartphone Browser
> _No response_
> 
> ### Smartphone Browser Version
> _No response_
> 
> ### Additional Logs
> _No response_

This is an your OpenAI issue and is not related to this repository.

**Comment by QAbot-zh** [comment]
key没钱了，跟人家项目没关系

**Comment by 244135186** [comment]
但是我可以用3.5gpt，官网里面





发自我的iPhone


------------------ Original ------------------
From: Q.A.zh ***@***.***&gt;
Date: Sat,Mar 2,2024 4:47 PM
To: ChatGPTNextWeb/ChatGPT-Next-Web ***@***.***&gt;
Cc: yang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ChatGPTNextWeb/ChatGPT-Next-Web] [Bug]  (Issue #4188)





 
key没钱了，跟人家项目没关系

**Comment by QAbot-zh** [comment]
web和api是两码事，web 3.5免费，4.0要开plus，api是单独计费，就算你开了plus，api也要另外收费

**Comment by Oniokey** [comment]
通过 API 调用任何模型都是收费的

**Comment by 244135186** [comment]
好的麻烦了，我以为不用费用



发自我的iPhone


------------------ Original ------------------
From: 王天成 ***@***.***&gt;
Date: Sat,Mar 2,2024 4:57 PM
To: ChatGPTNextWeb/ChatGPT-Next-Web ***@***.***&gt;
Cc: yang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ChatGPTNextWeb/ChatGPT-Next-Web] [Bug]  (Issue #4188)





 
通过 API 调用任何模型都是收费的
