### ISSUE TITLE
提问后报错，是需要魔法吗？

### ISSUE THREAD

**Issue by S3257467509** [ChatGPTNextWeb/ChatGPT-Next-Web#4199]
### Bug Description

{
  "cause": {
    "name": "ConnectTimeoutError",
    "code": "UND_ERR_CONNECT_TIMEOUT",
    "message": "Connect Timeout Error"
  }
}

### Steps to Reproduce

4

### Expected Behavior

无

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

win10

### Desktop Browser

谷歌

### Desktop Browser Version

忘记

### Smartphone Device

e

### Smartphone OS

e

### Smartphone Browser

e

### Smartphone Browser Version

14

**Comment by AndyX-Net** [comment]
Docker在你本机部署的的还是服务器部署？

如果是本机部署： 使用Win10客户端的话，自行检测一下你是否能链接到Google终结点。(大概率不通，需要魔法)

如果是服务器部署：服务器在国内吗？服务器的Docker直接配置了Endpoint吗？如果在国内并且配置了Endpoint的话的话大概率同上。

通常此类连接问题跟NextWeb无关，这应该不属于Bug，你需要先自查一下先。
