### ISSUE TITLE
[Feature Request]: docker部署可否支持 -V 把数据本地持久化，以防重新部署后聊天记录消失

### ISSUE THREAD

**Issue by loveu5522** [ChatGPTNextWeb/ChatGPT-Next-Web#4201]
### Problem Description

docker部署可否支持 -V 把数据本地持久化，以防重新部署后聊天记录消失

### Solution Description

docker部署可否支持 -V 把数据本地持久化，以防重新部署后聊天记录消失

**Comment by AndyX-Net** [comment]
正如在“主要功能”中提到的：所有数据保存在用户浏览器本地

如果想持久化或者同步聊天记录，你可以参考这个：https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/docs/synchronise-chat-logs-cn.md

**Comment by fred-bf** [comment]
There are indeed plans to follow up with support for user systems & persistent data locally. But for now it's still stored locally in the browser, as @AndyX-Net said.
