### ISSUE TITLE
各位大佬们，我该怎么修改我在vercel上的部署使得我可以使用中转接口，而不是官方的接口

### ISSUE THREAD

**Issue by blackxiaobai** [ChatGPTNextWeb/ChatGPT-Next-Web#4213]
我该怎么修改使得我可以使用中转接口，而不是官方的接口

**Comment by H0llyW00dzZ** [comment]
fork

**Comment by fredliang44** [comment]
@blackxiaobai you can change the `BASE_URL` follow the instructions here https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web?tab=readme-ov-file#base_url-optional

**Comment by blackxiaobai** [comment]
> @blackxiaobai您可以按照此处的说明更改 BASE_URL https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web?tab=readme-ov-file#base_url-optional

你好，能否再给我一个更详细的方法，文档内容对这一部分的描述似乎并不清楚，感谢
