### ISSUE TITLE
[Bug] 是否已經支援 Google Tag Manager (GTM)

### ISSUE THREAD

**Issue by chiyiliao** [ChatGPTNextWeb/ChatGPT-Next-Web#4215]
### Bug Description

看到 config/server.ts 有抓取環境變數 GTM_ID
在 layout.tsx 裡也看到會取出 serverConfig.gtmId 來用，
但設定 GTM_ID 環境變數後似乎沒有作用，
請問是 bug 還是尚未正式支援 GTM?

### Steps to Reproduce

1. 在環境變數中設定 GTM_ID="id of google tag manager"
2. 啟動 server
3. 連到 chatgpt-next-web 頁面
4. 查看 GTM 中是否有紀錄

### Expected Behavior

GTM 裡面應該要有紀錄

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by fred-bf** [comment]
@chiyiliao Hi, this is supported, you can config `GTM_ID` to enable Google Tag Manager. The documentation will be updated soon
