### ISSUE TITLE
[Feature Request]: Claude3 support

### ISSUE THREAD

**Issue by jcyuan** [ChatGPTNextWeb/ChatGPT-Next-Web#4220]
### Problem Description

now the newest Claude3 model is more powerful than gpt4, especially in aspect of coding.
so, is there plan to support it?

### Solution Description

Claude3 model support

**Comment by haohaoget** [comment]
hope so, especially the Claude 3 Haiku model have better code than gpt4, but cheaper than gpt-3.5.

**Comment by H0llyW00dzZ** [comment]
> ### Problem Description
> now the newest Claude3 model is more powerful than gpt4, especially in aspect of coding. so, is there plan to support it?
> 
> ### Solution Description
> Claude3 model support
> 
> ### Alternatives Considered
> _No response_
> 
> ### Additional Context
> _No response_

In future

**Comment by Changego** [comment]
支持加入Claude3 支持。

**Comment by anlory** [comment]
hope  support Claude3

**Comment by acotor** [comment]
Please consider implementing Claude model provided by [Amazon Bedrock API](https://docs.aws.amazon.com/bedrock/latest/APIReference/welcome.html). Claude Sonnet is [available on AWS](https://aws.amazon.com/bedrock/claude/) now.

**Comment by johnsmzr** [comment]
please support claude3, it's so good now.

**Comment by zhaojie199512** [comment]
hope to support Claude3 ,can not wait to use ti

**Comment by leizhuray** [comment]
hope supporting claude 3！ That's important

**Comment by thenetguy** [comment]
+1 for supporting claude 3

**Comment by jcyuan** [comment]
https://github.com/jtsang4/claude-to-chatgpt

not sure if this lib helps, it unifys and simples the API management

**Comment by jdassd** [comment]
Really hope Claude3 can be adapted as soon as possible, because it is currently NO.1.

**Comment by H0llyW00dzZ** [comment]
- #4269

**Comment by H0llyW00dzZ** [comment]
### Info: This model provides better Markdown formatting:

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/a851623e-a2df-47ed-a1bd-55d583897fa1.png)

**Comment by QingyeSC** [comment]
> hope so, especially the Claude 3 Haiku model have better code than gpt4, but cheaper than gpt-3.5.

maybe

**Comment by H0llyW00dzZ** [comment]
> > hope so, especially the Claude 3 Haiku model have better code than gpt4, but cheaper than gpt-3.5.
> 
> maybe

It's not just Haiku; other Claude models are also cost-effective. I've tested these with my friends.

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/2d22e142-f1c1-4a69-b2b7-e8e8cc618b3e.png)

The image above shows that we spent almost $1 only. Plus, it's stable, and this repository supports SSE.

**Comment by H0llyW00dzZ** [comment]
also the formatting are better unlike openai

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/a23fb465-beaf-4e46-9993-830078d264b6)

**Comment by steven-prybylynskyi** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/3078595/477de76f-c0ee-417b-9880-366958e43d7a)

which build is that?

**Comment by steven-prybylynskyi** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/3078595/d3fcca74-69b5-4a4e-a974-b0a4c93f53da)

also, what's the point of the "Plugin" button if it's never implemented

**Comment by exgbit** [comment]
强烈建议尽快实现Claude3的支持

**Comment by Sualiu** [comment]
We need Claude3 and more.

**Comment by Lizhen0628** [comment]
We need Claude3 and more.

**Comment by asaproland** [comment]
支持Claude模型，该客户端基本无敌手了！

**Comment by zpng** [comment]
We need Claude3~  hope to support it!

**Comment by AlyssaChia2017** [comment]
claude3 please

**Comment by HeChenxiang** [comment]
同样希望加入claude3 api接入，可以用更低的价格获得更好的效果

**Comment by QingyeSC** [comment]
快一个月没更新了……等支持claude等得花都谢了

**Comment by boromyr** [comment]
+ 1 for claude 2 and 3
