### ISSUE TITLE
[Feature Request]: Image input/attachment support 

### ISSUE THREAD

**Issue by iiitmahesh** [ChatGPTNextWeb/ChatGPT-Next-Web#4223]
### Problem Description

for models gpt-4 , gemini and other models Image input/attachment support.

### Solution Description

at chat message input Image input/attachment support 
<img width="805" alt="Screenshot 2024-03-06 at 9 44 41 AM" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/13597781/6b1e02d2-b12f-4d7d-8c81-66738e4d7dd0">

**Comment by H0llyW00dzZ** [comment]
image is already support, but for other files such as docs currently not supported
