### ISSUE TITLE
现在怎么获取api-key

### ISSUE THREAD

**Issue by mobile17682318557** [ChatGPTNextWeb/ChatGPT-Next-Web#4224]
### Bug Description

我按照文档访问 https://platform.openai.com/account/api-keys，登录后直接进聊天页面了，无法获得api-key

### Steps to Reproduce

怎么获取api-key

### Expected Behavior

怎么获取api-key

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by qinggangwu** [comment]
https://blog.csdn.net/qq_52475653/article/details/135095313

**Comment by fred-bf** [comment]
https://platform.openai.com/api-keys
