### ISSUE TITLE
[Feature Request]: 使用gpt4-all模型的生成图片等功能

### ISSUE THREAD

**Issue by hcbkj** [ChatGPTNextWeb/ChatGPT-Next-Web#4227]
### Problem Description

之前有使用过gpt4-all的模型，但是今天使用模型想要生成图片的时候发现如下报错。
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/76961475/6f612032-c356-4d76-a96d-8561a808e5f9)
想问下现在是否还支持使用gpt4-all，支持的话应该怎么调整设置？

### Solution Description

无

**Comment by QAbot-zh** [comment]
啊？啊？啊？跟前端ui没关系，找你的api上游去，我使用正常，包括奇奇怪怪的自定义模型都没问题。

**Comment by hcbkj** [comment]
搞定了哈哈，感谢感谢
