### ISSUE TITLE
[Feature Request]: 添加0llama本地服务

### ISSUE THREAD

**Issue by liujvnes** [ChatGPTNextWeb/ChatGPT-Next-Web#4229]
### Problem Description

按教程设置出现如下错误
![屏幕截图 2024-03-06 174226](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/25132014/27d01bc6-bced-4305-830c-d6e9458ad644)
![屏幕截图 2024-03-06 174200](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/25132014/a8937810-5991-41d3-80a4-6270a848a9ef)

### Solution Description

1、模型供应商中添加ollama本地服务选项
2、自定义模型中添加已安装模型选择
![屏幕截图 2024-03-06 171156](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/25132014/204dfcc3-1ee7-45e2-a115-fe88690eaf57)
谢谢！

**Comment by gabbg** [comment]
请问如何"模型供应商中添加ollama本地服务选项"，我desktop版本没有这个选项

**Comment by fred-bf** [comment]
please follow the doc to set env to start ollama https://docs.nextchat.dev/models/ollama
