### ISSUE TITLE
dall-e-3

### ISSUE THREAD

**Issue by zhang19980518** [ChatGPTNextWeb/ChatGPT-Next-Web#4233]
### Problem Description

添加dall-e-3模型后不能输出图片

### Solution Description

希望可以支持dall-e-3模型

**Comment by fred-bf** [comment]
Hi plz follow support progress in  https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4030 , dalle will be support via function calling

**Comment by iiitmahesh** [comment]
@fred-bf **dalle** will be support via function calling. #4030 , can please provide more details how to achieve dall-e in current code
