### ISSUE TITLE
[Bug] 导出的本地数据无法正常使用和导入

### ISSUE THREAD

**Issue by Mr-Otaku-Lin** [ChatGPTNextWeb/ChatGPT-Next-Web#4236]
### Bug Description

windows10本地使用，正常导出的本地数据文件用常用的编码格式都无法解码，还无法导入现在版本和新版本，是我的使用方式有误吗？如何保留本地聊天记录？
![QQ截图20240307175333](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/136694888/ab1e43b1-8e50-41e6-9771-f8971827d9c8)

### Steps to Reproduce

1.点击导出
2.点击导入
3.选择文件
4.导入数百

### Expected Behavior

能够正常在新版本看到自己的聊天记录，或者将聊天记录作为文件存档

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by fred-bf** [comment]
@Mr-Otaku-Lin hi, the result is json file, you can use code editor like vscode to view in raw format

**Comment by Mr-Otaku-Lin** [comment]
> @Mr-Otaku-Lin hi, the result is json file, you can use code editor like vscode to view in raw format

Thanks for the reply, I know it's in json format, but I can't find the encoding format that I can view properly and import it back into the PC app properly again.

**Comment by TCOTC** [comment]
可能是相同的问题：#3562
