### ISSUE TITLE
[Feature Request]: RAG emmbeddings & 挂外部文档

### ISSUE THREAD

**Issue by deanwang2018** [ChatGPTNextWeb/ChatGPT-Next-Web#4237]
### Problem Description

when writing some personal document I need my own doc, if there are RAG & Emmbedding function to let me upload my personal file it will be very helpful.
当写自己私有文档时需要自己的其他文档作为参考，如果可以提供挂载外部文档的功能将非常有用。

### Solution Description

add vector db like chromadb to save local files.
增加向量数据库比如chromadb用来保存本地文件。

**Comment by Reekin** [comment]
> Implementing this feature in desktop or mobile apps is a piece of cake. However, the web version presents a challenge, especially when it comes to storing files in local storage.

Does it mean, in order to ensure consistency across multiple platforms, this project will not consider features that are difficult to implement on some platforms, no matter how useful the feature may be? 
I prefer to first integrate these key features on platforms where they are easy to implement.

**Comment by fred-bf** [comment]
> > ### Problem Description
> > when writing some personal document I need my own doc, if there are RAG & Emmbedding function to let me upload my personal file it will be very helpful. 当写自己私有文档时需要自己的其他文档作为参考，如果可以提供挂载外部文档的功能将非常有用。
> > ### Solution Description
> > add vector db like chromadb to save local files. 增加向量数据库比如chromadb用来保存本地文件。
> > ### Alternatives Considered
> > _No response_
> > ### Additional Context
> > _No response_
> 
> Implementing this feature in desktop or mobile apps is a piece of cake. However, the web version presents a challenge, especially when it comes to storing files in local storage.

It is feasible to store only the reference via localstorage. However, when the file changes, the historical references will become invalid.

The most reasonable way is to introduce back-end support and implement relevant object storage capabilities on the back-end

**Comment by fred-bf** [comment]
The workload to support embedding seems to be fine, but it needs to be tied to the user's openai account

**Comment by lloydzhou** [comment]
v2.15.0支持插件功能（可以将外部的api以gpts action一样的方式包装成plugin使用）

这里有一个示例，将fastgpt的api包装成plugin在聊天中使用

https://github.com/ChatGPTNextWeb/NextChat-Awesome-Plugins/tree/main/plugins/fastgpt
