### ISSUE TITLE
[Feature Request]:  工具栏是否可以增加语音识别，进行文字发送

### ISSUE THREAD

**Issue by rabbit-dog** [ChatGPTNextWeb/ChatGPT-Next-Web#4239]
### Problem Description

![微信图片_20240308121030](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/30332327/36d4b7c1-0758-4a57-8aa5-19ae0f8470a4)

是否可以新增语音识别进行对话发送

### Solution Description

是否可以新增语音识别进行对话发送

### Alternatives Considered

能自定义这里的组件，新增一个吗？

**Comment by vual** [comment]
我这边有实现，可以看下 https://github.com/vual/ChatGPT-Next-Web-Pro

**Comment by rabbit-dog** [comment]
你好，我没有找到类似这个的功能




我想接入聊天，识别




在 2024-03-08 14:44:01，"vual" ***@***.***> 写道：

我这边有实现，可以看下 https://github.com/vual/ChatGPT-Next-Web-Pro

**Comment by fred-bf** [comment]
duplicated to https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4163

**Comment by vual** [comment]
> 你好，我没有找到类似这个的功能 我想接入聊天，识别 在 2024-03-08 14:44:01，"vual" ***@***.***> 写道： 我这边有实现，可以看下 https://github.com/vual/ChatGPT-Next-Web-Pro — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/25891219/2ee6e35c-d97a-4278-be40-c81f81902786)
