### ISSUE TITLE
[Feature Request]: “包含 0 条预设提示词”这个弹窗，请问是否可以设计移动到角落上去？

### ISSUE THREAD

**Issue by wanvb** [ChatGPTNextWeb/ChatGPT-Next-Web#4240]
### Problem Description

包含 0 条预设提示词，这个提示框非常的遮挡交互内容，非常的影响使用体验。特别是在笔记本电脑上使用的时候，屏幕空间本来就有限，这个还一直处于遮挡中，关也关不掉，特别是编程遇到头大的问题的时候，它还一直遮挡内容，这让我头更晕了，每次我都不得不用F12删除这个提示框的HTML代码，但是新的提问它又会出现，简直烦不胜烦，希望能改进到角落进行提示。
![{2A8E1547-B1B0-4844-8B5D-5572B9D05E0F}](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/36328754/e993ef0d-efab-4385-90eb-e9cf38471404)

### Solution Description

设计能进行永久性关闭，或者改到角落进行显示

### Alternatives Considered

我个人根本不需要的功能，但是却极度的影响使用体验，感觉是一个非常糟糕的显示位置设计

**Comment by laxfer** [comment]
> ### 问题描述
> 0 条默认包含词，这个提示框非常的遮挡内容交互，非常的影响使用体验。特别是在笔记本电脑上使用的时候，屏幕空间本来就有限，这个还一直存在中遮挡，关也关不掉了，特别是Smashing遇到头大问题的时候，它还一直重叠内容，这让我头更晕了，每次我都不得不用F12删除这个提示框的HTML代码，但是新的提问它又会出现，简直烦不胜烦，希望能改进到紫色进行提示。 ![{2A8E1547-B1B0-4844-8B5D-5572B9D05E0F}](https://private-user-images.githubusercontent.com/36328754/311142258-e993ef0d-efab-4385-90eb-e9cf38471404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMzU3MzgsIm5iZiI6MTcxMDAzNTQzOCwicGF0aCI6Ii8zNjMyODc1NC8zMTExNDIyNTgtZTk5M2VmMGQtZWZhYi00Mzg1LTkwZWItZTljZjM4NDcxNDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDAxNTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMzViNmY3MzI0OTY0Y2M3YjkzYmViMTJjODk2MjUzODUxY2M3ZjM2YmU4Y2ZjMjFmYmQ0NDI3Y2JmODQ1YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.odBs0PjbK6f6pqj4Ib7wDtLYOjl4g20N-IKifs47t-4)
> 
> ### 解决方案描述
> 设计能进行永久性关闭，或者改成紫色进行显示
> 
> ### 考虑的替代方案
> 我个人根本不需要的功能，但是却极大地影响了使用体验，感觉是一个非常糟糕的显示位置设计
> 
> ### 附加背景
> _没有反应_

这个问题很好解决的在\app\components\chat.tsx里面找到 props.showToast && (改成 {props.showToast && context.length > 0 && (即可，没匹配到提示词的情况下不让显示

**Comment by Achilles0705** [comment]
请问\app\components\chat.tsx在哪里，我并没有在本地文件中找到它

**Comment by laxfer** [comment]
> 请问\app\components\chat.tsx在哪里，我并没有在本地文件中找到它

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/components/chat.tsx
这个文件，你可以下载源码自己编译

**Comment by Achilles0705** [comment]
> > 请问\app\components\chat.tsx在哪里，我并没有在本地文件中找到它
> 
> https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/components/chat.tsx 这个文件，你可以下载源码自己编译

不好意思大佬我想请教一下，我用网页直接部署的时候没有相关文件，后来我又下载了exe版本，发现只有exe这个文件，我想请问你说的源码是需要我以怎样的方式进行部署呢

**Comment by laxfer** [comment]
> > > 请问\app\components\chat.tsx在哪里，我并没有在本地文件中找到它
> > 
> > 
> > https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/components/chat.tsx 这个文件，你可以下载源码自己编译
> 
> 不好意思大佬我想请教一下，我用网页直接部署的时候没有相关文件，后来我又下载了exe版本，发现只有exe这个文件，我想请问你说的源码是需要我以怎样的方式进行部署呢

源码里面当然有这个文件了,我不是把源码的链接给你了啊，源码你改下，yarn bulid重新编译下就行了

**Comment by Achilles0705** [comment]
> > > > 请问\app\components\chat.tsx在哪里，我并没有在本地文件中找到它
> > > 
> > > 
> > > https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/components/chat.tsx 这个文件，你可以下载源码自己编译
> > 
> > 
> > 不好意思大佬我想请教一下，我用网页直接部署的时候没有相关文件，后来我又下载了exe版本，发现只有exe这个文件，我想请问你说的源码是需要我以怎样的方式进行部署呢
> 
> 源码里面当然有这个文件了,我不是把源码的链接给你了啊，源码你改下，yarn bulid重新编译下就行了

大佬，我现在把仓库克隆到本地，并且改好了，yarn build是怎么操作的，您有没有具体教程或者操作方式之类的，我刚刚涉足，还有很多东西都不知道，麻烦您了！

**Comment by wanvb** [comment]
我用Adblock屏蔽了.chat_prompt-toast___VCUf这个元素，终于不用再看到它提示了^_^

**Comment by laxfer** [comment]
> > > > > 请问\app\components\chat.tsx在哪里，我并没有在本地文件中找到它
> > > > 
> > > > 
> > > > https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/components/chat.tsx 这个文件，你可以下载源码自己编译
> > > 
> > > 
> > > 不好意思大佬我想请教一下，我用网页直接部署的时候没有相关文件，后来我又下载了exe版本，发现只有exe这个文件，我想请问你说的源码是需要我以怎样的方式进行部署呢
> > 
> > 
> > 源码里面当然有这个文件了,我不是把源码的链接给你了啊，源码你改下，yarn bulid重新编译下就行了
> 
> 大佬，我现在把仓库克隆到本地，并且改好了，yarn build是怎么操作的，您有没有具体教程或者操作方式之类的，我刚刚涉足，还有很多东西都不知道，麻烦您了！

这个一两句也说不完

**Comment by siwuxei** [comment]
确实影响体验
