### ISSUE TITLE
[Bug] 输入法选择框无法定位到输入框

### ISSUE THREAD

**Issue by Giter-t** [ChatGPTNextWeb/ChatGPT-Next-Web#4246]
### Bug Description

在win11上使用客户端时，如果客户端不是最大化，移动客户端位置后，输入法的选择框就不会在输入框处了。(使用的是微软拼音旧版输入法)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/67638483/cb5a5a1f-9306-43d7-85f3-a6e04a08aa58)

### Steps to Reproduce

1.打开客户端
2.使客户端不是最大化
3.移动客户端
4.使用旧版微软拼音输入文字

### Expected Behavior

输入法选择框始终在输入框处

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

win11

**Comment by fred-bf** [comment]
@Giter-t hi, its related to system behavior, we cannot control from the client side for now

**Comment by Achilles0705** [comment]
same，我也被这个问题困扰，只有最小化再打开一次才能使输入框定位，如果拖动了窗口就会使输入框跑到屏幕左上角
![Uploading 屏幕截图 2024-06-23 150606.png…]()
