### ISSUE TITLE
[Feature Request]: 可以增加一键清除聊天记录的按键吗，而不仅仅只是清除上下文？

### ISSUE THREAD

**Issue by liuchao0807** [ChatGPTNextWeb/ChatGPT-Next-Web#4247]
### Problem Description

当前的清除聊天按钮，仅仅只是去掉上下文关联， 聊天记录还是会保存在对话框，看起来比较乱。

### Solution Description

方案1. 增加一个清除聊天记录的按钮
方案2. 给当前清除聊天按钮增加一个配置项，用户可以选择其功能是清除上下文还是清除所有聊天记录

**Comment by fred-bf** [comment]
Hi, thanks for you feedback. There is no plan to add a button to clear the chat history data inside the chat window
