### ISSUE TITLE
[Feature Request]: 滚动优化

### ISSUE THREAD

**Issue by Reekin** [ChatGPTNextWeb/ChatGPT-Next-Web#4250]
### Problem Description

1.streaming期间锁定了滚至底部，无法向上滚动
2.经常在回答完毕后，向上滚动后想点选一些内容时，瞬间滚回底部，不知道是触发了什么

### Solution Description

1.streaming期间默认保持滚动至底部，但一旦手动向上滚动，就保持在当前视图，以便于框选内容
2.去掉不合理的滚动至底部的时机

**Comment by fred-bf** [comment]
Its already supported in latest commit https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commit/44a51273be98519a60023f3687d0dea71c02c335
