### ISSUE TITLE
[Bug] 自定义代理api返回NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by xiaozhang959** [ChatGPTNextWeb/ChatGPT-Next-Web#4251]
### Bug Description

您好，请问使用自定义的http://x.x.x.x:port形式的自定义代理api一直返回NetworkError when attempting to fetch resource.是为什么呢？我确定这个自定义代理可以正常使用并且返回的是openAI标准的格式。

### Steps to Reproduce

1.点击发送按钮后，立即返回了这个错误，并且查看服务端应该是没有经过网络请求。

### Expected Behavior

正确返回对话

### Screenshots

如图：这是每次点击发送之后的返回
![图片](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/89305607/fd1359b2-2fa4-4ecd-a99a-dfc6ca7dd069)

这是控制台的参数：
![图片](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/89305607/f0dcc1aa-aa38-437e-b49d-f4e8be8e8e88)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

windows10

### Desktop Browser

firefor

**Comment by daiaji** [comment]
docker里无法访问这个地址？

**Comment by amakerlife** [comment]
应该是跨域了，我这也有这个问题。

**Comment by wjfu99** [comment]
http的不行的，具体可以参考我之前提的issue #4095 ，对于web端有解决办法，对于app端仍然没有解决办法。

**Comment by xiaozhang959** [comment]
> http的不行的，具体可以参考我之前提的issue #4095 ，对于web端有解决办法，对于app端仍然没有解决办法。

哥，我试了下，你说得对，确实是这个问题

**Comment by xiaozhang959** [comment]
> docker里无法访问这个地址？

可以访问的，是浏览器设定https下不能访问http请求的问题
