### ISSUE TITLE
[Feature Request]: 希望添加支持上传图片和文档提问方式

### ISSUE THREAD

**Issue by NET666** [ChatGPTNextWeb/ChatGPT-Next-Web#4261]
### Problem Description

建议添加支持上传图片和文档提问方式

### Solution Description

操作如下
![1-1](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/54788321/2b3f6de5-06f2-491a-b3f5-50f42175b264)
![55](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/54788321/38ff43b8-9aed-4aea-ba52-50524c92aa08)

**Comment by 1137882300** [comment]
好的 收到

**Comment by fred-bf** [comment]
Upload image is supported in vision models(gemini vision having some capability issue)
