### ISSUE TITLE
[Bug]: 自动生成的标题一直是面具的名字。

### ISSUE THREAD

**Issue by tomcatq** [ChatGPTNextWeb/ChatGPT-Next-Web#4262]
### Problem Description

当在设置中勾选了“自动生成标题”时，如果同时选择了自定义的面具，那么使用该面具开启的所有对话，自动生成的标题都是该面具的名字，而不是具体的有意义的对话内容概括。

### Solution Description

自动生成的标题应该是有意义的对话内容概括

### Additional Context

谢谢！

**Comment by chatGPTxx** [comment]
从面具开启的对话好像的确不应该再自动生成title了，比如chatGPT里的GPT也是这样的

**Comment by tomcatq** [comment]
> 从面具开启的对话好像的确不应该再自动生成title了，比如chatGPT里的GPT也是这样的

不知道是不是prompt或者面具名参与了自动生成的过程。如果要自动生成title，应当避免prompt和面具名的影响。
我刚刚也测试了官网的chatgpt，好像并非如你所说的。

**Comment by fred-bf** [comment]
This is expected because the mask is specified

**Comment by tomcatq** [comment]
> This is expected because the mask is specified

OK. You mean that the app directly call the interface of OpenAI to generate the title for conversations, rather than do that itself? 
So this is what happened?

**Comment by fred-bf** [comment]
> > This is expected because the mask is specified
> 
> OK. You mean that the app directly call the interface of OpenAI to generate the title for conversations, rather than do that itself? So this is what happened?

Yep, when you are starting the chat without a mask, the client will automatically generate the title for you, otherwise the client will directly using the title of the mask you've selected.

This  behaviour maybe improved later, but right now its meets the expectation.

**Comment by tomcatq** [comment]
THX

**Comment by tomcatq** [comment]
> > > This is expected because the mask is specified
> > 
> > 
> > OK. You mean that the app directly call the interface of OpenAI to generate the title for conversations, rather than do that itself? So this is what happened?
> 
> Yep, when you are starting the chat without a mask, the client will automatically generate the title for you, otherwise the client will directly using the title of the mask you've selected.
> 
> This behaviour maybe improved later, but right now its meets the expectation.

THX!
