### ISSUE TITLE
[Bug] Windows桌面端的最新版本不能通过截图后直接ctrl v到聊天框，但是网页端可以

### ISSUE THREAD

**Issue by Chenm4** [ChatGPTNextWeb/ChatGPT-Next-Web#4270]
### Bug Description

如题。不知道是不是bug。
同时我希望能给这个软件设置打开快捷键，这样使用起来会更方便。

### Steps to Reproduce

如上

### Expected Behavior

如上

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Reekin** [comment]
最新的release是两周前的，而直接读剪贴板的功能是上周的代码改动
可以自己拉取最新源码build
