### ISSUE TITLE
[Feature Request]: 请问有打算支持Poe的API吗

### ISSUE THREAD

**Issue by Xc1Ym** [ChatGPTNextWeb/ChatGPT-Next-Web#4271]
### Problem Description

[Poe](poe.com)支持了API操作其内部的AI大模型，包括ChatGPT、GPT4、Claude3-Opus等大模型，同时也支持了Poe里自己构建的机器人模型，这是Poe官方提供的[API文档](https://creator.poe.com/docs/accessing-other-bots-on-poe#how-to-access-the-bot-query-api-directly)，请问ChatNextWeb能否支持Poe的API调用，因为Poe相较于OpenAI和Claude有更友好的注册方式和支付方式，所以可以增加Poe的API作为获取AI的问答的一种途径

### Solution Description

增加Poe的API调用

**Comment by fred-bf** [comment]
@Xc1Ym will be tracked in https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4030, just added Poe in the lish.

Once the underlying codes is refactored, it should be easy to add new providers
