### ISSUE TITLE
[Feature Request]: 希望可以支持谷歌的Gemini 1.5 Pro 模型

### ISSUE THREAD

**Issue by cmcccopy** [ChatGPTNextWeb/ChatGPT-Next-Web#4274]
### Problem Description

谷歌的Gemini 1.5 Pro API 可以使用了，试用了一下，比1.0好很多，希望可以支持gemini 1.5 pro API
非常感谢作者大大。

### Solution Description

希望可以支持gemini 1.5 pro API
非常感谢作者大大。

**Comment by H0llyW00dzZ** [comment]
> ### Problem Description
> 谷歌的Gemini 1.5 Pro API 可以使用了，试用了一下，比1.0好很多，希望可以支持gemini 1.5 pro API 非常感谢作者大大。
> 
> ### Solution Description
> 希望可以支持gemini 1.5 pro API 非常感谢作者大大。
> 
> ### Alternatives Considered
> _No response_
> 
> ### Additional Context
> _No response_

It's still not supported yet for APIs, only supported in https://aistudio.google.com/app/prompts/new_chat

**Comment by fred-bf** [comment]
Will be supported once google released the new model
