### ISSUE TITLE
API接口地址设置问题，访问不了

### ISSUE THREAD

**Issue by jackallam** [ChatGPTNextWeb/ChatGPT-Next-Web#4275]
接口地址填写：
https://api.openai.com

填写了API Key，开启VPN，

输入问题出现以下错误提示

{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}

意思配额不足？ 网页登陆官网是可以使用的，请问如何解决？自定义模型名是否需要填写？

**Comment by fred-bf** [comment]
It might be your openai platform running out of balance, not related to the chatgpt client
