### ISSUE TITLE
[Bug] 面具预设与历史摘要的role冲突

### ISSUE THREAD

**Issue by QAbot-zh** [ChatGPTNextWeb/ChatGPT-Next-Web#4276]
### Bug Description

当前历史摘要是以`"role": "system"`附加在消息里的，示例提供的面具预设则是以`"role": "user"`的形式。
这样就有点限制面具的能力发挥了，因为我想要使用`system`的角色来强化预设效果，但是就会导致出现两条`system`消息，遇到不支持双`system`消息的模型就会出错。
（简单的关闭历史摘要功能或者把面具角色改为user当然是可行的方法，但是或许可以找到两全的方法，比如把历史摘要附加在面具预设消息的后面？）

### Steps to Reproduce

1. 设置面具预设为system消息
2. 长对话使产生历史摘要消息
3. 调用不支持双`system`消息的模型

### Expected Behavior

将双`system`进行合并

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/f91b69f6-e475-4836-adba-4b7734081467)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

**Comment by H0llyW00dzZ** [comment]
> ### Bug Description
> 当前历史摘要是以`"role": "system"`附加在消息里的，示例提供的面具预设则是以`"role": "user"`的形式。 这样就有点限制面具的能力发挥了，因为我想要使用`system`的角色来强化预设效果，但是就会导致出现两条`system`消息，遇到不支持双`system`消息的模型就会出错。 （简单的关闭历史摘要功能或者把面具角色改为user当然是可行的方法，但是或许可以找到两全的方法，比如把历史摘要附加在面具预设消息的后面？）
> 
> ### Steps to Reproduce
> 1. 设置面具预设为system消息
> 2. 长对话使产生历史摘要消息
> 3. 调用不支持双`system`消息的模型
> 
> ### Expected Behavior
> 将双`system`进行合并
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/40236765/312116743-f91b69f6-e475-4836-adba-4b7734081467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTYwMzQsIm5iZiI6MTcxMDI1NTczNCwicGF0aCI6Ii80MDIzNjc2NS8zMTIxMTY3NDMtZjkxYjY5ZjYtZTQ3NS00ODM2LWFkYmEtNGI3NzM0MDgxNDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE1MDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYTAyNDdkYjBkNmE5ZGE0NGM4ZTcyMDZlZDY5NzkwNGIxNTQwYWZlOGU3NDA1YmIwNzU1MWIzYzhmZDQzNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7fyEdRO0RK1K5qjJCUDF9mTx-YUjQ7K8XJUYAg734D0)
> 
> ### Deployment Method
> * [ ]  Docker
> * [x]  Vercel
> * [ ]  Server
> 
> ### Desktop OS
> _No response_
> 
> ### Desktop Browser
> _No response_
> 
> ### Desktop Browser Version
> _No response_
> 
> ### Smartphone Device
> _No response_
> 
> ### Smartphone OS
> _No response_
> 
> ### Smartphone Browser
> _No response_
> 
> ### Smartphone Browser Version
> _No response_
> 
> ### Additional Logs
> _No response_

That feature is related to this repository and is currently only compatible with and supported by OpenAI:

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/f5a51a00-9c4d-4547-9b1e-de89dfcaa533)

**Comment by QAbot-zh** [comment]
@H0llyW00dzZ 
So, can I assume that this project does not consider the dual `system` message a bug, but rather a result of OpenAI's reasonable design?

**Comment by H0llyW00dzZ** [comment]
> @H0llyW00dzZ So, can I assume that this project does not consider the dual `system` message a bug, but rather a result of OpenAI's reasonable design?

Yes, for OpenAI, it's not a bug but a design choice. The system supports multiple `system` roles, which are concatenated when sending the memory prompt. However, Anthropic (Claude), which is still a work in progress, only supports one `system` role, and it must be at the top.

**Comment by QAbot-zh** [comment]
All right, so regret to here that. 
So how are you guys planning to deal with the dual system issue in Anthropic model ?

**Comment by H0llyW00dzZ** [comment]
> All right, so regret to here that. So how are you guys planning to deal with the dual system issue in Anthropic model ?

That's what I'm still trying to figure out, to find a better way to handle it.

**Comment by QAbot-zh** [comment]
Okay, I comprehend.

**Comment by H0llyW00dzZ** [comment]
@QAbot-zh I have already found a better way to handle it.

Example:

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/87ea5b2c-2f11-4fec-abe7-df903514ef91)

It's functioning perfectly fine.

**Comment by QAbot-zh** [comment]
> @QAbot-zh I have already found a better way to handle it.
> 
> Example:
> 
> ![image](https://private-user-images.githubusercontent.com/17626300/312302913-87ea5b2c-2f11-4fec-abe7-df903514ef91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDYyNTcsIm5iZiI6MTcxMDMwNTk1NywicGF0aCI6Ii8xNzYyNjMwMC8zMTIzMDI5MTMtODdlYTViMmMtMmYxMS00ZmVjLWFiZTctZGY5MDM1MTRlZjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA0NTkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyM2FlNWIwOGRiM2YwOGVhZjBhZTVlMWM4MmYzMjQ0NDUzMzJmOGRjMTg1YTRjOGJhZTQ5YjU5MDZlZWJlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xp5TiupjntqHJAFqla_xuhy3sc-DWKs4XPJx-hAhzEo)
> 
> It's functioning perfectly fine.

I can't get it from your screenshot. Could you please provide more details ?

**Comment by H0llyW00dzZ** [comment]
> > @QAbot-zh I have already found a better way to handle it.
> > Example:
> > ![image](https://private-user-images.githubusercontent.com/17626300/312302913-87ea5b2c-2f11-4fec-abe7-df903514ef91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDYyNTcsIm5iZiI6MTcxMDMwNTk1NywicGF0aCI6Ii8xNzYyNjMwMC8zMTIzMDI5MTMtODdlYTViMmMtMmYxMS00ZmVjLWFiZTctZGY5MDM1MTRlZjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA0NTkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyM2FlNWIwOGRiM2YwOGVhZjBhZTVlMWM4MmYzMjQ0NDUzMzJmOGRjMTg1YTRjOGJhZTQ5YjU5MDZlZWJlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xp5TiupjntqHJAFqla_xuhy3sc-DWKs4XPJx-hAhzEo)
> > It's functioning perfectly fine.
> 
> I can't get it from your screenshot. Could you please provide more details ?

it's related about this

- https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4276#issuecomment-1991951308
- https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4276#issuecomment-1992014317
