### ISSUE TITLE
[Feature Request]: 希望能增加用户注册登录功能，管理员后台管理密钥，或者token管理

### ISSUE THREAD

**Issue by CyrilTang** [ChatGPTNextWeb/ChatGPT-Next-Web#4280]
### Problem Description

希望能增加用户注册登录功能，管理员后台管理密钥，或者token管理

### Solution Description

希望能增加用户注册登录功能，管理员后台管理密钥，或者token管理

**Comment by fred-bf** [comment]
duplicated issue, will be supported in V3.0
