### ISSUE TITLE
[Feature Request]: Add more environment variable options（添加更多的环境变量选项）

### ISSUE THREAD

**Issue by iTvX** [ChatGPTNextWeb/ChatGPT-Next-Web#4291]
### Problem Description

目前的环境变量选项太少了，使用docker部署之后，我甚至不知道如何更改这些环境变量。比如我想把默认的界面设置成中文，默认设置gpt 4-0125模型等，无法自定义。一旦浏览器清除cookie后，这些设置将不复存在。

### Solution Description

希望可以在环境变量中添加所有的配置选项，比如设置语言/设置温度/设置默认gpt模型等等

**Comment by H0llyW00dzZ** [comment]
> ### Problem Description
> 目前的环境变量选项太少了，使用docker部署之后，我甚至不知道如何更改这些环境变量。比如我想把默认的界面设置成中文，默认设置gpt 4-0125模型等，无法自定义。一旦浏览器清除cookie后，这些设置将不复存在。
> 
> ### Solution Description
> 希望可以在环境变量中添加所有的配置选项，比如设置语言/设置温度/设置默认gpt模型等等
> 
> ### Alternatives Considered
> _No response_
> 
> ### Additional Context
> _No response_

no, too complex

**Comment by fred-bf** [comment]
It is not expected to be configured in the environment variables, the specific parameter configuration will be unified in the future in the service side of the development maintenance
