### ISSUE TITLE
One-API转发VLLM的API回答完问题后还在输出直到超出token

### ISSUE THREAD

**Issue by SongXiaoMao** [ChatGPTNextWeb/ChatGPT-Next-Web#4293]
### Problem Description

Ubuntu系统部署VLLM跑本地模型，使用one-api转发后发现回答问题后一直再乱输出，有没有什么地方可以设置stop的？

### Solution Description

可以设置stop参数

### Alternatives Considered

无

### Additional Context

无

**Comment by heycc** [comment]
我遇到类似问题，现象是在输出中还有新的 ### ASSISTANT 内容。搜索一些资料后，怀疑是 chat 模板处理的不对

后来发现是 vllm 的版本太低了。因为我用的是 vllm 的 docker: vllm/vllm-openai:latest，其实我们的镜像版本是5个月前的，不是最新版本。更新镜像版本到最新后（0.4.0），就解决问题了
