### ISSUE TITLE
[Bug] MacOS 下 Safari 中使用中文输入法时回车

### ISSUE THREAD

**Issue by freejool** [ChatGPTNextWeb/ChatGPT-Next-Web#4297]
### Bug Description

MacOS 下 Safari 中使用中文输入法输入一些字符，此时输入的字符以英文输入输入框后立即被发送，而不是仅输入输入框
同设备下Chrome无此问题

### Steps to Reproduce

1. 将发送键设置为Enter
2. 切换到中文输入法
3. 输入一些字符
4. 按一次回车
5. 输入的字符以英文输入输入框后立即被发送

### Expected Behavior

字符仅输入输入框，不被发送

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

MacOS 14.4

### Desktop Browser

Safari

### Desktop Browser Version

17.4

**Comment by hanxiao790** [comment]
Mac 版桌面 App 也是这个问题，不得不切换成了 Ctrl + Enter 来发送

**Comment by iTvX** [comment]
mac下safari测试也有这个问题，但是chromium类型的浏览器就没有这个问题

**Comment by fred-bf** [comment]
I've tested it and can't reproduce it. Can you provide the specific input content to reproduce the issue?

**Comment by chongiscool** [comment]
我设置成 shift + enter 发送，暂时能满足

**Comment by freejool** [comment]
> I've tested it and can't reproduce it. Can you provide the specific input content to reproduce the issue?

actually anything

**Comment by imraax** [comment]
> I've tested it and can't reproduce it. Can you provide the specific input content to reproduce the issue?

On MacOS, Tauri uses the Safari kernel by default, and Safari's event.isComposing is always false, and only keyCode is used to determine whether it is an input method state.

**Comment by imraax** [comment]
可以参考我的commit，加一行keyCode判断。这是非直接输入法在Safari中的`React.CompositionEvent<HTMLTextAreaElement>` 事件判断回车和空格等功能键为flase产生的Bug，

**Comment by fred-bf** [comment]
Merged, @freejool would you mind check whether the issue still exists again

**Comment by freejool** [comment]
@fred-bf I don't know if I'm doing right.

> Your build has completed!
> 
> [Preview deployment](https://4322-vercelpreviewdeployment.pr.nextchat.dev)

I checked the build in #4322, and it's not fixed.

My service deployed in docker and I believe the fix is not released as docker img.

**Comment by imraax** [comment]
> @fred-bf I don't know if I'm doing right.
> 
> > Your build has completed!
> > [Preview deployment](https://4322-vercelpreviewdeployment.pr.nextchat.dev)
> 
> I checked the build in #4322, and it's not fixed.
> 
> My service is deployed in docker and I believe the fix is not released as docker img.

I think so,you can try the project website :[app.nextchat.dev/](https://app.nextchat.dev/),becasue it was merged.

**Comment by imraax** [comment]
> @fred-bf I don't know if I'm doing right.
> 
> > Your build has completed!
> > [Preview deployment](https://4322-vercelpreviewdeployment.pr.nextchat.dev)
> 
> I checked the build in #4322, and it's not fixed.
> 
> My service is deployed in docker and I believe the fix is not released as docker img.

@freejool I think so, I  found that build still have the bug, you can check my new build https://chat-gpt-next-web-git-main-raaxs-projects.vercel.app

**Comment by freejool** [comment]
> @freejool I found the preview of deployments,[Preview](https://nextchat-1q8i76jz3-nextchat.vercel.app/)

Yeah, this build is working fine, Cheers!🍻🍻
