### ISSUE TITLE
[Feature Request]: 是否可以代理gpts

### ISSUE THREAD

**Issue by evirts** [ChatGPTNextWeb/ChatGPT-Next-Web#4298]
### Problem Description

是否可以代理gpts

### Solution Description

是否可以代理gpts

### Alternatives Considered

是否可以代理gpts

### Additional Context

是否可以代理gpts

**Comment by vual** [comment]
我这边有gpts，可以看下：https://github.com/vual/ChatGPT-Next-Web-Pro

**Comment by evirts** [comment]
> 我这边有gpts，可以看下：https://github.com/vual/ChatGPT-Next-Web-Pro

你的这个还要收费，不是开源的

**Comment by evirts** [comment]
> > ### Problem Description
> > 是否可以代理gpts
> > ### Solution Description
> > 是否可以代理gpts
> > ### Alternatives Considered
> > 是否可以代理gpts
> > ### Additional Context
> > 是否可以代理gpts
> 
> it already had proxy [`example`](https://app.nextchat.dev/api/proxy/openai)

收到谢谢，我是想部署私人ChatGPT网页应用，部署完成后gpts是默认开启还是需要加什么参数嘛

**Comment by evirts** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> > > ### Problem Description
> > > Is it possible to proxy gpts
> > > ### Solution Description
> > > Is it possible to proxy gpts
> > > ### Alternatives Considered
> > > Is it possible to proxy gpts
> > > ### Additional Context
> > > Is it possible to proxy gpts
> > 
> > 
> > it already had proxy [`example`](https://app.nextchat.dev/api/proxy/openai)
> 
> Thank you. I want to deploy a private ChatGPT web application. After the deployment is completed, will gpts be enabled by default or do I need to add any parameters?

参照了docker部署的文档，启动命令是docker pull yidadaa/chatgpt-next-web

docker run -d -p 3000:3000 \
   -e OPENAI_API_KEY=sk-xxxx \
   -e CODE=页面访问密码 \
   yidadaa/chatgpt-next-web
