### ISSUE TITLE
[Feature Request]: 请问为什么不支持dalle，因为我发现其实很容易就可以实现这个功能

### ISSUE THREAD

**Issue by zby909** [ChatGPTNextWeb/ChatGPT-Next-Web#4300]
### Problem Description

为什么这个项目到现在还没有支持dalle模型，是因为有什么难以实现的点还是没人去做这个事情？因为我拉了代码尝试了一下发现很容易就可以实现dalle的图片输出。
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/55353369/10080690-2c8f-4bfb-8a92-1075a16ae00e)

### Solution Description

我想知道目前对于dalle的支持是已经在计划内且已经有人正在做了，还是因为别的什么原因无法实现等等

**Comment by zby909** [comment]
如果没有人正在做这个事情的话，我想我是否可以完善这个功能后发起pr请求？

**Comment by zby909** [comment]
#4349

**Comment by lloydzhou** [comment]
1. `dall-e-3`作为openai下的一个模型，可以支持直接会话调用。
2. `Dalle3`支持作为插件（v2.15.0支持）功能，可以在支持function call的模型会话的时候，以调用tool的方式调用 https://github.com/ChatGPTNextWeb/NextChat-Awesome-Plugins/tree/main/plugins/dalle

**Comment by Genuifx** [comment]
能否支持azure的 dall-e 模型？
