### ISSUE TITLE
[Feature Request]: 预设提示词能在后台换成别的吗？

### ISSUE THREAD

**Issue by xiaobai9978** [ChatGPTNextWeb/ChatGPT-Next-Web#4302]
### Problem Description

![图片](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/11792557/f1a49309-b2b4-45ed-a37c-4d456402f72b)

### Solution Description

预设提示词能在后台换成别的吗？

**Comment by codeayzy** [comment]
在 .\ChatGPT-Next-Web\app\locales\cn.ts 文件里可以改，打开这个ts文件，直接按 Ctrl+F 搜 "有什么可以帮你的吗" 替换即可。

**Comment by xiaobai9978** [comment]
> 在 .\ChatGPT-Next-Web\app\locales\cn.ts 文件里可以改，打开这个ts文件，直接按 Ctrl+F 搜 "有什么可以帮你的吗" 替换即可。

请问 用docker 安装的路径在什么位置？

**Comment by fred-bf** [comment]
@xiaobai9978 work dir is `/app`, you can check the details in the dockerfile https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/Dockerfile
