### ISSUE TITLE
[Bug] i cant update by vercel havent difference with your repo

### ISSUE THREAD

**Issue by johnfelipe** [ChatGPTNextWeb/ChatGPT-Next-Web#4304]
### Bug Description

i cant update by vercel havent difference with your repo

### Steps to Reproduce

I want to update vercel with my fork, but havent new commits

### Expected Behavior

update to latest version in my vercel instance

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by fred-bf** [comment]
Could you explain more?

**Comment by johnfelipe** [comment]
I can't update normally in vercel with mi fork in my account, then is
nothing to merge, then vercel not update a build newer versions

**Comment by fred-bf** [comment]
please fetch upstream code and update your merge in your forked repo
