### ISSUE TITLE
网页版的回答总是中断，不完整。

### ISSUE THREAD

**Issue by dige210** [ChatGPTNextWeb/ChatGPT-Next-Web#4305]
### Bug Description

网页版的回答速度很慢，总是中断，不完整。

### Steps to Reproduce

网页版的回答速度很慢，总是中断，不完整。

### Expected Behavior

不知道是什么原因

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

win10

### Desktop Browser

Chrome

### Desktop Browser Version

122.0.6261.95（正式版本） （64 位）

**Comment by fred-bf** [comment]
@dige210 its related to your deployment method and model provider. Switching to non-serverless platforms may help.
