### ISSUE TITLE
[Bug] 无法修改Gemini的安全等级

### ISSUE THREAD

**Issue by do02fw** [ChatGPTNextWeb/ChatGPT-Next-Web#4311]
### Bug Description

我通过抓包发现模型的安全等级很高，这会导致很多内容无法输出，并且没办法自定义安全等级

### Steps to Reproduce

打开浏览器控制台，点网络，发送消息，会发现安全等级被设置成了最高

### Expected Behavior

可以通过环境变量修改安全等级

### Screenshots

![企业微信截图_20240315152024](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/138294823/96afdf96-cfb4-41a0-9d00-121075b6bc16)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

Windows11

### Desktop Browser

edge

### Additional Logs

[
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_ONLY_HIGH"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_ONLY_HIGH"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_ONLY_HIGH"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_ONLY_HIGH"
  }
]

**Comment by do02fw** [comment]
https://ai.google.dev/docs/safety_setting_gemini?hl=zh-cn
这里有详细的安全等级介绍，希望增加环境变量修改安全等级或者默认安全等级改为BLOCK_NONE

**Comment by fredliang44** [comment]
The default security level is set very low, and we will consider supporting similar custom parameters after completing multi-model adaptation.

**Comment by fred-bf** [comment]
The default security level is set very low, and we will consider supporting similar custom parameters after completing multi-model adaptation in https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4030
