### ISSUE TITLE
[Feature Request]: 希望增加中转/代理的Gemini支持

### ISSUE THREAD

**Issue by zbzzh** [ChatGPTNextWeb/ChatGPT-Next-Web#4315]
### Problem Description

gemini pro模型只支持官方api地址调用，使用第三方中转服务的地址目前无法使用gemini，希望增加可以选择中转的api支持

### Solution Description

增加中转的gemini支持

**Comment by haso2007** [comment]
以前是支持的，现在版本完全不能支持Gemini的API，是阉割掉了吗？

**Comment by ManJieqi** [comment]
原来是这样，nextchat支持gemini的api直接访问，第三方的是使用openai的请求方式。这还是直接使用openai的请求吧，不然谁单独给gemini设代理啊，代理了它，其他的模型又用不了了。

**Comment by fred-bf** [comment]
You can customize gemini api host via environment variables. If your api provider only supports OpenAI format api, you will need to configure the OpenAI api via environment variables or settings.

**Comment by zbzzh** [comment]
我使用的中转API是oneapi，可是我的api提供商里gemini的模型名就是gemini-pro，没办法更改也就是重定向，这样导致我在nextweb中填写gemini-pro的时候它走谷歌的api地址，没办法走我的中转api地址
