### ISSUE TITLE
[Feature Request]: Update the Gemini 1.5 pro version to support image video together

### ISSUE THREAD

**Issue by haso2007** [ChatGPTNextWeb/ChatGPT-Next-Web#4318]
### Problem Description

the Gemini 1.5 is avaialbe now, one model support all media now. 

### Solution Description

the Gemini 1.5 is avaialbe now, one model support all media now. Can we do the update accordingly, then we don't need the Gemini pro vision anymore！thanks your help

**Comment by H0llyW00dzZ** [comment]
> ### Problem Description
> the Gemini 1.5 is avaialbe now, one model support all media now.
> 
> ### Solution Description
> the Gemini 1.5 is avaialbe now, one model support all media now. Can we do the update accordingly, then we don't need the Gemini pro vision anymore！thanks your help
> 
> ### Alternatives Considered
> _No response_
> 
> ### Additional Context
> _No response_

not possible for video, because there is no storage for handling it

**Comment by haso2007** [comment]
These issues already raised in anothertopic
