### ISSUE TITLE
能否每个对话可以单独设置api以及接口地址？

### ISSUE THREAD

**Issue by YoloBird** [ChatGPTNextWeb/ChatGPT-Next-Web#4323]
或者环境变量可以设置多套api与接口地址，对话可以任选

**Comment by Eyion** [comment]
当填入自己的api时，接口地址是否需要更改？
另外，免费申请的api key应该选哪个模型？
谢谢。

**Comment by GrayXu** [comment]
或者一个相对简单的实现也会好很多，如每个对话可以使用不同key，而不是简单的轮询策略。

**Comment by fred-bf** [comment]
There are no relevant plans to support custom models per chat
