### ISSUE TITLE
[Feature Request]: 二个建议

### ISSUE THREAD

**Issue by bian2022** [ChatGPTNextWeb/ChatGPT-Next-Web#4324]
### Problem Description

Gemini不支持多个key
无法单独为某个模型设置密码

### Solution Description

希望Gemini可以支持多个key轮询 
因为GPT4价格有些高，所以希望可以只为GPT4模型设置密码

**Comment by fred-bf** [comment]
Due to the complexity of the implementation and the conflict with the current interaction mode, it will not be placed in the roadmap for the time being
