### ISSUE TITLE
[Bug] NextChat tries to query the wrong endpoint

### ISSUE THREAD

**Issue by LiamPerson** [ChatGPTNextWeb/ChatGPT-Next-Web#4325]
### Bug Description

The NextClient download for Windows pings the wrong endpoint when setup according to the documentation found here: https://docs.nextchat.dev/models/ollama

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/34695601/bebe47f9-ceda-42dc-ae2c-464b6b8f3143)

### Steps to Reproduce

1. Download the windows client: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/download/v2.11.3/NextChat_2.11.3_x64-setup.exe
2. Install the windows client
3. Serve ollama https://docs.nextchat.dev/models/ollama `OLLAMA_ORIGINS=* ollama serve`
4. Modify your settings in NextChat in accordance with Step 3 here https://docs.nextchat.dev/models/ollama
5. Try and query the model

### Expected Behavior

There will be a valid response.

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/34695601/847a2d98-7843-47cf-a977-40663a6cf0bc)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/34695601/81c731ce-bd9a-427f-b880-19be7a023b1c)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/34695601/09eb3e95-fe39-48ff-a48e-533e45b93575)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/34695601/bd373735-da00-4c32-b993-3887bd5fdf25)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

Windows 10

### Additional Logs

```
[GIN] 2024/03/17 - 15:25:48 | 200 |    3.7461199s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2024/03/17 - 15:25:51 | 204 |        16.1µs |       127.0.0.1 | OPTIONS  "/v1/chat/completions"
[GIN] 2024/03/17 - 15:25:51 | 404 |       215.5µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/03/17 - 15:25:51 | 404 |       143.3µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/03/17 - 15:26:12 | 404 |       192.5µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/03/17 - 15:26:35 | 204 |        19.5µs |       127.0.0.1 | OPTIONS  "/v1/chat/completions"
[GIN] 2024/03/17 - 15:26:35 | 404 |         206µs |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/03/17 - 15:27:08 | 404 |       258.8µs |       127.0.0.1 | POST     "/v1/chat/completions"
```

**Comment by fred-bf** [comment]
https://ollama.com/blog/openai-compatibility

ollama supports openai format api, please upgrade to require ollama version.
