### ISSUE TITLE
[Feature Request]: 消息归档 | Message Archive

### ISSUE THREAD

**Issue by Reekin** [ChatGPTNextWeb/ChatGPT-Next-Web#4328]
### Problem Description

在一场对话中经常会产生大量分支话题（比如一些执行过程中的细节问题），这些对话内容不需要作为历史消息发出去（浪费token & 影响记忆），但仍会有查看的需求。

### Solution Description

提供一个能够批量将若干条消息标记为归档的操作，这些消息仍出现在聊天记录中，但不会作为历史消息被发出；
提供一个视图选项：隐藏归档消息，以便于更清晰地查看对话主干；

### Additional Context

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4301
本issue与这一条是两个不同的需求

**Comment by fred-bf** [comment]
Due to the complexity of the implementation and the conflict with the current interaction mode, it will not be placed in the roadmap for the time being
