### ISSUE TITLE
[Feature Request]: 增加禁用登录页输入密钥部分的选项，以防止被误判为钓鱼网站

### ISSUE THREAD

**Issue by wy580477** [ChatGPTNextWeb/ChatGPT-Next-Web#4329]
### Problem Description

我用的 .top 域名，部署一段时间后被微软edge浏览器警告钓鱼网站了。

我其它的二级域名都工作正常。

### Solution Description

猜测应该是登录页输入API密钥部分触发的，增加一个删除这部分的选项应该可以避免这种情况。

**Comment by QAbot-zh** [comment]
我猜你在找这个

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/f544fa90-e4e8-445e-bb00-865fec360ccb)

**Comment by wy580477** [comment]
> 我猜你在找这个
> 
> ![image](https://private-user-images.githubusercontent.com/40236765/313473944-f544fa90-e4e8-445e-bb00-865fec360ccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODEzNjYsIm5iZiI6MTcxMDY4MTA2NiwicGF0aCI6Ii80MDIzNjc2NS8zMTM0NzM5NDQtZjU0NGZhOTAtZTRlOC00NDVlLWJiMDAtODY1ZmVjMzYwY2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEzMTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOTg4OTU0ODNmYzA2ODY5YjRlYTkyOGJhOGIwNGU5NmQwZjFhOWI3MGJjMThjYzg3M2I4YmQ2NjU3NTUzZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T3-NCNxqL2pckSk4dsdwdZHS3E1Q5WQvuY713lsd6x0)

谢！
