### ISSUE TITLE
[Feature Request]: 能否支持下中国阿里，百度的模型，如果支持，有好心人说下怎么用嘛

### ISSUE THREAD

**Issue by lobmoo** [ChatGPTNextWeb/ChatGPT-Next-Web#4334]
### Problem Description

[Feature Request]: 能否支持下中国阿里，百度的模型，如果支持，有好心人说下怎么用嘛

### Solution Description

[Feature Request]: 能否支持下中国阿里，百度的模型，如果支持，有好心人说下怎么用嘛

**Comment by QAbot-zh** [comment]
最简单的做法就是用`one-api`或者`new-api`中转一下，大模型太多了，靠前端一一适配是有点吃力的。

**Comment by fred-bf** [comment]
QAbot-zh's answer is the most convenient way right now. If you are refer to support them in NextChat, you can refer to progress at https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4030
