### ISSUE TITLE
[Bug] CUSTOM_MODELS Does not work when I upgraded to v2.11.3

### ISSUE THREAD

**Issue by weifeng12x** [ChatGPTNextWeb/ChatGPT-Next-Web#4338]
### Bug Description

When I upgraded to v2.11.3 from v2.9.x
I found that CUSTOM_MODELS does not work, it worked on v2.9.x. 
My configuration is 
- CUSTOM_MODELS=-all,+gpt-3.5-turbo-0125,+gpt-4-0125-preview

### Steps to Reproduce

1. Set the environment in docker-compose.yml
2. Chech the model list on client.

### Expected Behavior

Its supposed to show 2 models which I listed in configuration file. However, it listed all models on client.

### Screenshots

Configuration:
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/76556787/a10148d3-e05d-4cde-8eb7-91d920ac2380)

Client model list:
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/76556787/ebfd5e9e-4f04-48bc-af7b-fcf2715b4e4b)

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by weifeng12x** [comment]
> try to open in InPrivate mode. Check whether it works.

I tried different broswer, it still doesn't work. Addtional, not only i can see the model list, but also can use it if the api key have permission.

**Comment by steven-prybylynskyi** [comment]
Is it possible to use Claude 3 as a custom model?

**Comment by crbon** [comment]
Likely related issue, even after adding the `ANTHROPIC_API_KEY` the Calude-3 models don't show up in model the list.
Using: `docker`

**Comment by crbon** [comment]
> > Likely related issue, even after adding the `ANTHROPIC_API_KEY` the Calude-3 models don't show up in model the list.
> 
> how did you start the container,`docker run` or `docker compose`? Have you recreate the container after changing config?
> 
> Add `ANTHROPIC_API_KEY` and `CUSTOM_MODELS`(if you using), recreate(not restart) container, then refresh in browser.

Sorry, after adding the `CUSTOM_MODELS` environment variable, yes those custom models come through.
Although, I'm still not clear on how to add Anthropic's Claude-3 Haiku for instance to NextChat. I have the model open come in the GUI, however, I must be doing something wrong.

Could you provide a sample `docker-compose.yml` or `docker run` command that would add a Claude-3 model?

P.S. I was running NextChat with `docker compose`

**Comment by crbon** [comment]
I got it resolved.

Make sure to add of the following 3 environment variables to be able to use use Claude-3 (any model).

- `CUSTOM_MODELS` 
- `ANTHROPIC_API_KEY`
- `ANTHROPIC_API_VERSION`
- `ANTHROPIC_URL`


---

Sample for anyone having issues, until the update arrived with better built in support for Claude-3

- `CUSTOM_MODELS="+claude-3-haiku-20240307"`
- `ANTHROPIC_API_KEY="{your-api-key}"`
- `ANTHROPIC_API_VERSION="2023-06-01"` (currently the latest version)
- `ANTHROPIC_URL="https://api.anthropic.com/v1/messages"`

**Comment by crbon** [comment]
Weird. It didn't work for me till I added the `ANTHROPIC_API_VERSION`.

I already had the `ANTHROPIC_API_KEY`, `ANTHROPIC_URL` and `CUSTOM_MODELS`, but without `ANTHROPIC_API_VERSION` it would fallback to GPT-3

**Comment by weifeng12x** [comment]
This bug has beed fixed in v2.12.2
