### ISSUE TITLE
[Bug] 更新后wbedav同步失效了

### ISSUE THREAD

**Issue by CatCars** [ChatGPTNextWeb/ChatGPT-Next-Web#4357]
### Bug Description

之前的版本我是可以通过wbedav正常同步的，但在我更新v2.11.3后。点击同步提示成功但实际无效。
之前我使用的是“Cloudreve”的wbedav功能一切正常，在我更新后变得无法读取同步文件，也无法创建同步文件。我尝试更换其他wbedav项目（比如坚果云）都无效。目录内没有生成新的文件。

### Steps to Reproduce

![捕获2](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/44657929/e161b3c3-b62d-47da-8859-48fefd600df0)

### Expected Behavior

我是更新了程序，其余设置未更改。

### Screenshots

![捕获](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/44657929/ef7dec08-1045-4a2e-a2b5-301c5de79d72)

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

win 10

### Desktop Browser

chrome

**Comment by fred-bf** [comment]
@CatCars duplicated to https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4335, you could try the bugfix at https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4353
