### ISSUE TITLE
[Feature Request]: 【建议】用户请求携带的IP地址，在请求GPT 的时候带过去，

### ISSUE THREAD

**Issue by qianyin123** [ChatGPTNextWeb/ChatGPT-Next-Web#4358]
### Problem Description

统计请求的ip地址

### Solution Description

用户请求携带的IP，在请求GPT 的时候带过去

**Comment by exgbit** [comment]
这是什么需求？统计的话，也是Openai来统计
你如果要看ip统计结果有很多其他方案
你自己建立一个中转服务器，所有请求发向这个服务器，再用这台服务器往Openai跳
所有统计结果可以在这台中转服务器实现和查看

这种功能实现跟ChatGPT-Next-Web没有必然关系

**Comment by fred-bf** [comment]
For data privacy reasons, the client ip is not currently carried when calling the api
