### ISSUE TITLE
[求助] 设置自定义域名后访问自定义域名大量308 redirect

### ISSUE THREAD

**Issue by sergeylzc** [ChatGPTNextWeb/ChatGPT-Next-Web#4360]
我fork了一份代码，采用的安装方式是 vercel 傻瓜式部署，部署完成后，访问vercel提供的域名访问正常，后设置了自定义域名访问就会出现308 redirect：
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/90981137/b46fc56f-a8c9-4453-8950-f8a41cc060cb)

控制台 Network 不断308 redirect：
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/90981137/dc124217-f540-497f-ab92-8327c7098ce6)

我的域名的 nameserver 是在 cloudflare 的。

有人遇到这样的问题不？不知道怎么解决呀...

**Comment by Todyzhou** [comment]
@Issues-translate-bot

**Comment by sergeylzc** [comment]
换了nameserver后解决了。

**Comment by FelixMotorcycle** [comment]
没有啊

Sergey ***@***.***>于2024年3月21日 周四03:15写道：
