### ISSUE TITLE
[Bug] Use a new api key to .env.local but still load old key?

### ISSUE THREAD

**Issue by Liozhang** [ChatGPTNextWeb/ChatGPT-Next-Web#4367]
### Bug Description

I upgrade into the newest version, got some issue
I change the `OPENAI_API_KEY` into new one (the key work in another client well),
but after I `yarn install && yarn start`, It seems to be using an old KEY with no balance.

How can I refresh the key?

### Steps to Reproduce

1.Change API-key

### Expected Behavior

Use new key successfully

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Additional Logs

```
{
  "error": {
    "message": "Your account balance is less than 0.8, which is not enough to use the gpt-4 model. Please visit https://peiqishop.me/buy/18 to recharge.",
    "type": "chatanywhere_error",
    "param": null,
    "code": "403 FORBIDDEN"
  }
}
```

**Comment by fred-bf** [comment]
This seems to have nothing to do with the project code. Please try starting the service again or check whether your api key is available.
