### ISSUE TITLE
[Bug]  任何回复都是 "message": "empty response"

### ISSUE THREAD

**Issue by frankpei1984** [ChatGPTNextWeb/ChatGPT-Next-Web#4368]
### Bug Description   任何回复都是  "message": "empty response"

任何回复都是这个错误提示

 {
  "error": true,
  "message": "empty response"
}

使用了今日github新版本代码，重新部署在Verce上，错误提示依旧。  Chrome, Firefox 浏览器都清理过缓存与清空历史记录。
使用VPN ，不使用VPN都切换测试过。 

![返回空响应](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/136059425/76e6095b-fc59-45f4-a9d5-abcec846a779)

### Steps to Reproduce

直接窗口内回复问答。

### Expected Behavior

能正常得到ChatGPT的回复内容 

### Deployment Method

- [ ] Docker
- [x] Vercel
- [ ] Server

### Desktop OS

win7

### Desktop Browser

Chrome, Firefox

**Comment by QAbot-zh** [comment]
浏览器F12打开网络，看看完整的请求信息

**Comment by frankpei1984** [comment]
Request URL: https://chatgpt.gentos.com.cn/api/openai/v1/chat/completions
Request Method: POST
Status Code: 405 
Remote Address: 76.76.21.9:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-headers: *
access-control-allow-methods: *
access-control-allow-origin: *
access-control-max-age: 86400
cache-control: public, max-age=0, must-revalidate
content-disposition: inline; filename="500"
content-type: text/html; charset=utf-8
date: Fri, 22 Mar 2024 07:58:54 GMT
server: Vercel
strict-transport-security: max-age=63072000
x-matched-path: /500
x-vercel-cache: BYPASS
x-vercel-id: fra1::k5c76-1711094333946-aab720055147
:authority: chatgpt.gentos.com.cn
:method: POST
:path: /api/openai/v1/chat/completions
:scheme: https
accept: application/json, text/event-stream
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9
authorization: Bearer nk-26745999
content-length: 518
content-type: application/json
cookie: cna=y+liHnw+OUkCAXFu5AbGoOu8
origin: https://chatgpt.gentos.com.cn
referer: https://chatgpt.gentos.com.cn/
sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

**Comment by QAbot-zh** [comment]
你漏密码了，赶紧改了吧，Status Code: 405 是服务被拒绝了，不通过 vercel 前端，你能直接调用你的 api 吗

**Comment by frankpei1984** [comment]
> 你漏密码了，赶紧改了吧，Status Code: 405 是服务被拒绝了，不通过 vercel 前端，你能直接调用你的 api 吗

![API Key 是可以正常调用的。](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/136059425/e297b6f7-45e5-4b7f-a322-de830ec41a13)
通过一个翻译工具。是可以测试调用这个API Key的。   其他的Chat前端，我还建设测试。

**Comment by frankpei1984** [comment]
![AIP key在客户端上可以正常使用](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/136059425/b686b94e-78fb-41ab-8840-78d5394ccae0)

API Key  在客户端上，可以正常使用。  那应该是 vercel 前端的问题。

**Comment by fred-bf** [comment]
close for no reply in a long time, feel free reply with additional information to reproduce the issue
