### ISSUE TITLE
[Bug] 调用gpt-4-vision-preview 识别jpg图片直接报错

### ISSUE THREAD

**Issue by ZhangYouJie-Major** [ChatGPTNextWeb/ChatGPT-Next-Web#4369]
### Bug Description

```json
{
  "error": {
    "message": "Invalid content type. image_url is only supported by certain models. (request id: 2024032211284178654458462542246) (request id: )",
    "type": "invalid_request_error",
    "param": "messages.[1].content.[1].type",
    "code": null
  }
}
```

### Steps to Reproduce

1、选择gpt-4-vision-preview模型
2、询问 ```里面的内容，具体描述了什么```
3、报错无法支持

### Expected Behavior

期望可以识别结果

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by QAbot-zh** [comment]
你的api支持真的 gpt-4-vision-preview 模型吗? 我测试是可用的。

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/d406c28c-942f-4f89-8ec7-b15b13302275)

**Comment by chuangzhidan** [comment]
> 你的api支持真的 gpt-4-vision-preview 模型吗? 我测试是可用的。
> 
> ![image](https://private-user-images.githubusercontent.com/40236765/315907626-d406c28c-942f-4f89-8ec7-b15b13302275.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjk2OTQsIm5iZiI6MTcxMjEyOTM5NCwicGF0aCI6Ii80MDIzNjc2NS8zMTU5MDc2MjYtZDQwNmMyOGMtOTQyZi00Zjg5LThlYzctYjE1YjEzMzAyMjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA3Mjk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYmI5MDNjYmEyMzM3ZTcyYWM4NTNmOWU5MzhiYmI3YjliYWI3ZTIwNzAxMTU2ODk2YTFjYmRkZTY0N2FlMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ubToP9pn-lzViIrym_yg9ckrVsm8VCWQCKcHNLFZHhY)

怎么支持图片？

**Comment by fred-bf** [comment]
@ZhangYouJie-Major please use vision models(e.g. gpt-4-vision)
