### ISSUE TITLE
[Bug] After updating the version, messages cannot be sent without a proxy address.

### ISSUE THREAD

**Issue by SupGiant** [ChatGPTNextWeb/ChatGPT-Next-Web#4370]
### Bug Description

在更新最新的版本之后，发现不配置接口代理为https://api.nextchat.dev/api/proxy/openai的话，会直接报错

```
{
  "error": true,
  "message": "Failed to fetch"
}
````
并且回滚到旧版本之后也出现了

### Steps to Reproduce

1. 使用clash for window客户端
2. VPN访问openai的官网屎正常的
3. 安装新的客户端之后无法正常使用
4. 安装旧版的也无法使用了

### Expected Behavior

我想直接使用官方的api接口，也就是api.openai.com

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by KSnow616** [comment]
Typing https://api.openai.com/ into it instead of leaving it blank solves the problem for me. 
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/55991421/51a8bffe-a464-400c-af27-3b1e5adc89bb)
