### ISSUE TITLE
[Feature Request]: Please add the anthropic api interface

### ISSUE THREAD

**Issue by 395273034** [ChatGPTNextWeb/ChatGPT-Next-Web#4371]
### Problem Description

Please add the anthropic api interface，It is so popular，thanks！

### Solution Description

1.Add the anthropic api like the openai API；
2.Or add the Add custom interfaces。

**Comment by Dean-YZG** [comment]
Thanks for the feedback, the latest version has been supported, if you have any questions, please feel free to contact us
