### ISSUE TITLE
对于gpt4或者claude23这样的模型增加文件上传功能

### ISSUE THREAD

**Issue by Liukairong2023** [ChatGPTNextWeb/ChatGPT-Next-Web#4372]
### Problem Description

对于gpt4或者claude23这样的模型增加文件上传功能

### Solution Description

对于gpt4或者claude23这样的模型增加文件上传功能

### Alternatives Considered

对于gpt4或者claude23这样的模型增加文件上传功能

### Additional Context

对于gpt4或者claude23这样的模型增加文件上传功能

**Comment by vual** [comment]
可以看看我这二开项目，https://github.com/vual/ChatGPT-Next-Web-Pro

**Comment by Dean-YZG** [comment]
Thank you for your feedback, we will adopt the suggestion and support this function soon

**Comment by Dean-YZG** [comment]
At present, the gpt file upload ability is strongly bound to the account, and the interface design of gpt determines that the file must be hosted in the cloud. Between the above two reasons, we do not implement this ability for the time being
