### ISSUE TITLE
[Feature Request]: 增加Gemini 1.5Pro和剩余token

### ISSUE THREAD

**Issue by do02fw** [ChatGPTNextWeb/ChatGPT-Next-Web#4374]
### Problem Description

官方现在已经开放了1.5的API，https://ai.google.dev/models?hl=zh-cn    ，希望可以加上，剩余token像这个项目一样https://github.com/lobehub/lobe-chat

### Solution Description

增加Gemini1.5Pro和剩余token显示

**Comment by mountainguan** [comment]
gemini1.5只是放出了模型，还没开放api

**Comment by fred-bf** [comment]
@mountainguan This PR still has issues that need to be fixed, and actually uses the 1.0 model

**Comment by Icestab** [comment]
我收到1.5 api的通过的申请邮件了，我想知道怎么才能配置1.5

**Comment by mountainguan** [comment]
> 我收到1.5 api的通过的申请邮件了，我想知道怎么才能配置1.5

修改该项目 ./app/constant.ts 把ChatPath修改为 "v1beta/models/gemini-1.5-pro-latest:generateContent",就ok了

**Comment by Rubuark** [comment]
可以看看#4412

**Comment by meteorjim** [comment]
> 可以看看#4412

感谢大佬

**Comment by Rubuark** [comment]
> This PR still has issues that need to be fixed, and actually uses the 1.0 model

Please review my PR #4412

**Comment by fengzai6** [comment]
剩余token显示想要加一

**Comment by ShinChven** [comment]
gemini-1.5-pro 的正确 model name 是 `gemini-1.5-pro-latest`

https://github.com/google-gemini/cookbook/issues/52#issuecomment-2053605198

**Comment by Dean-YZG** [comment]
> > This PR still has issues that need to be fixed, and actually uses the 1.0 model
> 
> Please review my PR #4412 ,Thank you.

Thanks for your work!

**Comment by Dean-YZG** [comment]
now, Gemini-1.5 supported
