### ISSUE TITLE
[Bug] 2.11.3客户端不能设置密码，只能设置api访问

### ISSUE THREAD

**Issue by Allen123Hao** [ChatGPTNextWeb/ChatGPT-Next-Web#4387]
### Bug Description

2.11.3客户端不能设置密码，只能设置api访问，而网页版的可以设置密码访问。

### Steps to Reproduce

2.11.3版本客户端不能设置密码，只能设置api访问，而网页版的可以设置密码访问。

### Expected Behavior

希望客户端的设置界面和网页端的设置界面一样，运行通过设置密码访问。

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Allen123Hao** [comment]
Please tell me which version can set password

**Comment by fred-bf** [comment]
It is as expected, there are no password restrictions on the client itself(not involved server api)
