### ISSUE TITLE
[Bug] GPT-3.5 Expenses Without Reason GPT-3.5 无故消耗

### ISSUE THREAD

**Issue by chesha1** [ChatGPTNextWeb/ChatGPT-Next-Web#4388]
### Bug Description

模型类型选择的是GPT-4，但是GPT-3.5也跟着产生了微小的消耗

如下图所示，GPT-3.5的费用大致跟随GPT-4的费用，但是量很少

The model type selected is GPT-4, but GPT-3.5 also produces a small consumption.

As shown in the figure below, the cost of GPT-3.5 roughly follows the cost of GPT-4, but the amount is very small.

<img width="745" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/49867392/e0ef3b32-f040-4c9d-ae5b-abbb363f255d">

### Steps to Reproduce

No errors.

### Expected Behavior

选择GPT-4的时候，GPT-3.5不产生消耗

When GPT-4 is selected, GPT-3.5 does not generate costs.

### Deployment Method

- [ ] Docker
- [x] Vercel
- [ ] Server

### Desktop OS

Windows 11 and macOS

### Desktop Browser

Chrome

### Desktop Browser Version

123.0.6312.58

**Comment by QAbot-zh** [comment]
Just turn off these two options.
关掉这两个选项即可。

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/c5c40144-ed8b-4eed-a499-65979699ceff)

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/a35a57ad-2fbb-4bcf-aed6-6ac6f083ffa7)

**Comment by fred-bf** [comment]
@chesha1 NextChat using GPT3.5 to generate chat titles, as @QAbot-zh mentioned, you can disable them in settings.

**Comment by zyl-hub** [comment]
由于现在gpt-4o-mini更加便宜，可以在constant.ts中设置export const SUMMARIZE_MODEL = "gpt-4o-mini";

Since GPT-4o-mini is now cheaper, you can set export const SUMMARIZE_MODEL = "gpt-4o-mini"; in constant.ts.
