### ISSUE TITLE
[功能请求]：能否增加functioncall能力

### ISSUE THREAD

**Issue by shutter-cp** [ChatGPTNextWeb/ChatGPT-Next-Web#4392]
### Problem Description

能否增加functioncall能力 参考如下：
https://platform.openai.com/docs/guides/function-calling
可以增强外部接口，工具的调用能力

### Solution Description

能否增加functioncall能力 参考如下：
https://platform.openai.com/docs/guides/function-calling

**Comment by fred-bf** [comment]
Hi, thanks for your suggestions. The progress will be tracked at https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4030
