### ISSUE TITLE
[Bug] 在vercel部署填入环境变量OPENAI_API_KEY和BASE_URL无效，但是在设置填入自定义接口正常

### ISSUE THREAD

**Issue by chengtx809** [ChatGPTNextWeb/ChatGPT-Next-Web#4397]
### Bug Description

在vercel部署填入环境变量OPENAI_API_KEY和BASE_URL无效，但是在设置填入自定义接口正常

### Steps to Reproduce

在vercel部署，填入环境变量OPENAI_API_KEY和BASE_URL后Redeploy进行聊天会出现下图的提示，但是在设置自定义接口项填入相同的请求地址和apikey则正常聊天

### Expected Behavior

正常聊天

### Screenshots

在vercel部署填入环境变量OPENAI_API_KEY和BASE_URL无效:
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/103792951/306e1bf1-f9ad-482b-a65d-a8028edc28f5)
在设置填入自定义接口正常:
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/103792951/639fc826-0fe2-473d-a018-e7e969c458d0)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

Windows10

### Desktop Browser

Edge

**Comment by chengtx809** [comment]
问题已解决

**Comment by SleepynSleep** [comment]
您好，请问是怎么解决的？我也遇到了这个问题
