### ISSUE TITLE
[Feature Request]: 调用GPT4  支持上传文件功能  

### ISSUE THREAD

**Issue by evan1936** [ChatGPTNextWeb/ChatGPT-Next-Web#4399]
### Problem Description

是否有计划 添加上传文件的功能  调用GPT4的时候需要上传文件

### Solution Description

在聊天框的旁边有文件入口

**Comment by Dean-YZG** [comment]
Thanks for the feedback, a lot of plans is being promoted, and it will be improved and optimized according to everyone's demands
