### ISSUE TITLE
[Bug] The code is not being parsed into a Markdown code block

### ISSUE THREAD

**Issue by quickquickcode** [ChatGPTNextWeb/ChatGPT-Next-Web#4403]
### Bug Description

When chatgpt replies with some python code, next chat comments are parsed into titles and code into body text. Not parsed into code blocks.
for example 
<img width="846" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/151628510/032bb3ba-5d80-426c-9c0a-379e858f8abe">

### Steps to Reproduce

Check recognition logic

### Expected Behavior

All py codes can be parsed correctly
<img width="830" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/151628510/07fa8d93-e553-4feb-ad3b-03a0e0250fe2">

### Screenshots

<img width="838" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/151628510/cccfd3cf-6379-44dd-870d-d3214a714d06">

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Dean-YZG** [comment]
This may be due to the fact that the format of the content returned by chatgpt does not strictly follow the markdown syntax
