### ISSUE TITLE
[Feature Request]: 好像目前的接口代理地址不支持cloudflare的AI gateway生成的代理地址

### ISSUE THREAD

**Issue by Keetop** [ChatGPTNextWeb/ChatGPT-Next-Web#4405]
### Problem Description

我按照这种格式填写的地址无效https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai。实际软件代理后多了一个v1。调用openai接口报这个Unknown request URL: POST /v1/v1/chat/completions

### Solution Description

希望大佬有时间开发支持一下

**Comment by Dean-YZG** [comment]
Please descript the reproduction procedure. Thanks

**Comment by Dean-YZG** [comment]
there is a way to solute your problem by setting env var 'BASE_URL' to 'https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai', instead of setting 'custom endpoint' on web Page,
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/138353356/38dee14d-538d-44bf-96b4-55d21ee6e70d)
the webchat proxy server would help you  Initiate a network request  with 「https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai/v1/chat/completions?path=v1&path=chat&path=completions」

**Comment by JankinHou** [comment]
> 有一种方法可以通过将环境变量“BASE_URL”设置为“https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai”来解决您的问题，而不是在网页上设置“自定义端点”，![image](https://private-user-images.githubusercontent.com/138353356/317959007-38dee14d-538d-44bf-96b4-55d21ee6e70d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzQ1NDYsIm5iZiI6MTcxMzk3NDI0NiwicGF0aCI6Ii8xMzgzNTMzNTYvMzE3OTU5MDA3LTM4ZGVlMTRkLTUzOGQtNDRiZi05NmI0LTU1ZDIxZWU2ZTcwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxNTU3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGVkMjIwM2M1M2MxMzY1MjFhMGYxOTNkZTc1OThhZjdkNTc3ZGRmZjkzY2M0Y2VjOTA4ZmJiNDI0MmFlNjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S9a7QmCz-uKEFP1vvDZhpx6dTIMgPsq-tEpeK8wcShk)网络聊天代理服务器将帮助您使用“[https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai/v1/chat/completions?path=v1&path=chat&path=completions”](https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai/v1/chat/completions?path=v1&path=chat&path=completions%E3%80%8D)发起网络请求

这种方式是不行的，https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai 会被映射到https://api.openai.com/v1 
<img width="1461" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/38063730/867d24fb-bf52-474a-8472-d3a6e640e09d">
cloudflare文档地址：https://developers.cloudflare.com/ai-gateway/get-started/connecting-applications/#openai

因此https://gateway.ai.cloudflare.com/v1/ACCOUNT_TAG/GATEWAY/openai/v1/chat/completions 会被转换成https://api.openai.com/v1/v1/chat/completions  链接里面多了一层 v1 就会报错

**Comment by Silentely** [comment]
问题并没有解决 加了/openai 发送过去的依旧会多套一层/v1
