### ISSUE TITLE
[Feature Request]: 增加一个环境变量来指定默认模型

### ISSUE THREAD

**Issue by chengtx809** [ChatGPTNextWeb/ChatGPT-Next-Web#4413]
### Problem Description

无法设置用户聊天默认使用的模型

### Solution Description

通过环境变量来指定用户默认使用的模型

**Comment by Dean-YZG** [comment]
Thanks for the feedback, we will improve the relevant functions as soon as possible, a big wave of plans are already on the way, please look forward to it

**Comment by Dean-YZG** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4545
感谢社区小伙伴的贡献，目前，最新版本已经支持了设置默认模型
