### ISSUE TITLE
右键自动复制粘贴

### ISSUE THREAD

**Issue by AlawnCN** [ChatGPTNextWeb/ChatGPT-Next-Web#4414]
### Bug Description

能否关闭右键自动复制粘贴的设计？或者给个开关来关闭这功能，大多数情况下右键只是为了打开Chrome的右键菜单而已，这个功能真的很让人崩溃

### Steps to Reproduce

右键任意聊天的内容

### Expected Behavior

不自动复制并粘贴

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

macOS

### Desktop Browser

Chrome

### Desktop Browser Version

14.1.1

**Comment by Dean-YZG** [comment]
Thanks to the feedback, we have made prompt replication more friendly depending on PC and mobile scenarios

**Comment by fengzai6** [comment]
我也觉得，不小心了一下就写入了

**Comment by Dean-YZG** [comment]
Thank you for your feedback, we will adopt the suggestion through more friendly forms of interaction
