### ISSUE TITLE
怎么配置能获取到所有的请求参数，比如用户通过chatgpt发送给openai的问题？

### ISSUE THREAD

**Issue by Qiuy97** [ChatGPTNextWeb/ChatGPT-Next-Web#4415]
### Problem Description

怎么配置能获取到所有的请求参数，比如用户通过chatgpt发送给openai的问题？

### Solution Description

可以获取到请求到具体数据

**Comment by QAbot-zh** [comment]
自己加log

**Comment by Qiuy97** [comment]
> 自己加log

加在哪里呢，代码小白，可以简单指导一下吗。大佬
