### ISSUE TITLE
[Feature Request]: Add code completion shortcut key settings.

### ISSUE THREAD

**Issue by QAbot-zh** [ChatGPTNextWeb/ChatGPT-Next-Web#4416]
### Problem Description

代码块放在两个\`\`\`符号中可以保留格式，使聊天记录看起来更加规整。但是手动输入两次符号不够方便。

Code blocks enclosed in two \`\`\` symbols can preserve formatting, making the chat log look more organized. However, manually typing the symbols twice is not very convenient. 

### Solution Description

是否可以考虑在文本输入区增加快捷键，快速输入两个\`\`\`符号并使光标处于两个符号之间？
Could you consider adding a shortcut in the text input area to quickly input two \`\`\`symbols and place the cursor between them?

**Comment by Dean-YZG** [comment]
Thank you for your feedback, we will adopt the suggestion

**Comment by Dean-YZG** [comment]
Thank you for your feedback, we will consider the proposal
