### ISSUE TITLE
需要自定义模型名，应该怎么指定供应商[Bug] 

### ISSUE THREAD

**Issue by XZ1314XZ** [ChatGPTNextWeb/ChatGPT-Next-Web#4419]
### Bug Description

如果是自定义的模型名，模型供应商应该如何指定，试过使用括号，但并不能正常

### Steps to Reproduce

1. 设置
2. 填写了自定义模型名

### Expected Behavior

正确正常使用openai格式去使用这个模型

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/56338784/8bdbccf8-af6c-426f-9ca4-6ab47511d17c)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

Windows 11

### Desktop Browser

Chrome

### Desktop Browser Version

112

**Comment by Dean-YZG** [comment]
You can ignore the vendor in parentheses, the app will work fine, thanks to the feedback, we will improve the relevant content presentation logic
