### ISSUE TITLE
[Feature Request]: Website integration

### ISSUE THREAD

**Issue by iliakan** [ChatGPTNextWeb/ChatGPT-Next-Web#4420]
### Problem Description

Can I use this project to integrate ChatGPT with my website, as an "AI helper"? Or it must be a standalone (web) app?

### Solution Description

Add an "AI helper" to my website.

**Comment by H0llyW00dzZ** [comment]
> ### Problem Description
> Can I use this project to integrate ChatGPT with my website, as an "AI helper"? Or it must be a standalone (web) app?
> 
> ### Solution Description
> Add an "AI helper" to my website.
> 
> ### Alternatives Considered
> _No response_
> 
> ### Additional Context
> _No response_

Currently, it must be a standalone web app. For example, you can quickly deploy it on Vercel.
