### ISSUE TITLE
我是小白

### ISSUE THREAD

**Issue by yhuuih** [ChatGPTNextWeb/ChatGPT-Next-Web#4431]
### Problem Description

这个项目更新了，我找不到app.ts,虽然这个问题对于你们来说很简单，但是对于我来说很难，使用我问一下，怎么配置让用户一登陆上去就有openaikey，而不需要输入自己输入，在此请问，谢谢有大佬回答

### Solution Description

我不是很清楚

**Comment by i2qaq** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/README_CN.md#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

密钥应该通过环境变量设置，不是修改app.ts吧
