### ISSUE TITLE
[Bug] 当前对话设置用户输出预处理，在重试时会重复进行预处理

### ISSUE THREAD

**Issue by sukidesuka** [ChatGPTNextWeb/ChatGPT-Next-Web#4434]
### Bug Description

我有一条这样的预处理信息：
Translate this text to English, don’t reply more message: {{input}}

使用时工作良好，消息被正常预处理：
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/63297045/4221d9f4-80d8-46b8-8477-1106159ecdf4)

但是如果我觉得输出不佳，点击重试，那么信息会被再次预处理：
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/63297045/c6368581-fb40-46aa-8549-82ab2f508d9f)

### Steps to Reproduce

1. 在左下角点击对话设置
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/63297045/853f7c8d-dd48-4f3f-913f-fffb0cbf267f)

2. 修改用户输入预处理
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/63297045/a4039807-130d-4424-83ac-22fb2fe49a01)

3. 正常发送消息
4. 点击重试，此时消息会被二次预处理

### Expected Behavior

希望发送消息时正常预处理，重试时不进行预处理

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

MacOS 14.1.1

### Desktop Browser

Chrome

### Desktop Browser Version

122.0.6261.69

**Comment by Dean-YZG** [comment]
已解决重复添加预处理字符串问题，但请不要使用{{input}}等特殊字符串  https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4461/files
