### ISSUE TITLE
[Bug] 部署的时候环境变量设置了APIKEY和code，进入网站提示未设置，在settings页面设置了CODE，打开网页没有出现密码验证

### ISSUE THREAD

**Issue by mengluo04** [ChatGPTNextWeb/ChatGPT-Next-Web#4437]
### Bug Description

在vercel上部署，部署的时候环境变量设置了APIKEY和code，进入网站提示未设置，在settings页面设置了CODE，打开网页没有出现密码验证

### Steps to Reproduce

1、fork项目
2、在vercel新建
3、选择fork的项目
4、设置环境变量
5、部署
6、进入页面
7、页面提示没有设置apikey和code
8、设置之后刷新或者新开页面没有弹出密码框

### Expected Behavior

正常进行页面密码验证

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by fengzai6** [comment]
vercel中redeploy试试

**Comment by amoonlighti** [comment]
出现了一样的问题 我这边是CODE的设置生效了 KEY和代理不生效。

**Comment by fred-bf** [comment]
@mengluo04 cannot reproduce this issue. if you send message in chat did the app response letting user to set code?

**Comment by mengluo04** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> Try redeploy in vercel

I do it now,but also not work right

**Comment by mengluo04** [comment]
> @mengluo04 cannot reproduce this issue. if you send message in chat did the app response letting user to set code?

I delete the project ,and create project,before deloy,i set the env 
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/32565940/305c8504-b218-451e-8ee4-4657a9684052)
when deply success,I open the domain:https://chat-gpt-next-web-ten-lake-58.vercel.app/
the page show me not set key and code
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/32565940/ae9dc8d8-7d0c-402b-aa4b-e4ce32bde5e5)

**Comment by mengluo04** [comment]
> …… CODE的作用是保护网站不被没有授权的随意使用，服务端部署CODE，浏览器打开网站的时候需要输入CODE才能正常使用。 CODE会缓存在本地，不需要每次打开都输入，如果希望每次打开都输入，可以使用浏览器的隐私模式，不会保留任何缓存。

无痕模式一样的，没有出现code验证页面，换浏览器也一样

**Comment by small05** [comment]
> > …… CODE的作用是保护网站不被授权的随意使用，服务端配置CODE，浏览器打开网站的时候需要输入CODE才能正常使用。 CODE会缓存在本地，不需要每次打开都输入，如果需要另外打开都输入，可以使用浏览器的隐私模式，不会保留任何缓存。
> 
> 无痕模式一样的，没有出现代码验证页面，换浏览器也一样

你要点登录，然后再登录页面输入你的code，本身是不会跳出来密码验证

**Comment by mengluo04** [comment]
> > > …… CODE的作用是保护网站不被授权的随意使用，服务端配置CODE，浏览器打开网站的时候需要输入CODE才能正常使用。 CODE会缓存在本地，不需要每次打开都输入，如果需要另外打开都输入，可以使用浏览器的隐私模式，不会保留任何缓存。
> > 
> > 
> > 无痕模式一样的，没有出现代码验证页面，换浏览器也一样
> 
> 你要点登录，然后再登录页面输入你的code，本身是不会跳出来密码验证

在登录页设置了密码，然后新开一个无痕浏览器，打开页面也是一样的，没有出现密码验证。环境变量里设置的两个APIKEY都生效了，登录页的key设置不是必须的
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/32565940/48293d18-e934-4efa-9dd6-90e8b25f7091)
在无痕模式打开，进入登录页，设置的密码没了。
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/32565940/728a6beb-0288-444d-8911-47bc6b229986)
在设置了密码的页面，在控制台的localstorage中，access-control变量里存在accessCode，但是刷新页面无效。
页面密码存在本地没有任何作用，因为环境变量里的key是生效了的，可以直接调用

**Comment by Dean-YZG** [comment]
如果设置了CODE 环境变量，则会强制提示验证信息，除非曾经在『设置』中输入过 任意服务提供商的apikey

**Comment by HeiHeiHeMianMa** [comment]
一样的 这功能就是个摆设
