### ISSUE TITLE
[Bug] 历史记录被删除，软件被初始化 the software automatically clears all conversation records and requires re-entering the API key

### ISSUE THREAD

**Issue by chuangzhidan** [ChatGPTNextWeb/ChatGPT-Next-Web#4438]
### Bug Description

每隔一段时间，软件的对话历史被清空，需要重新输入地址和秘钥 ，想知道怎么回事，真的很烦。
谢谢

### Steps to Reproduce

无法复制，这个通常一个月才出现一次

### Expected Behavior

希望能解决问题
希望能方便导出对话记录

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by QAbot-zh** [comment]
导出对话记录不是本来就支持的吗？

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/6fea264c-327e-4be3-a461-1bf7cc03339a)

**Comment by Dean-YZG** [comment]
the app don't clean storage actively, you can check other apps could clean the storage

**Comment by wangyashuu** [comment]
I don't know if you're using Safari or not, but I'm suffering the same problem with Safari. I found that starting with Safari 13, the local storage will be cleared after 7 days of no user interaction with the website (see more at https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/). I have not found any way to disable this feature. If anyone finds it, please let me know and thanks in advance.
