### ISSUE TITLE
[Feature Request]: 添加独立登录页面

### ISSUE THREAD

**Issue by 0xffffharry** [ChatGPTNextWeb/ChatGPT-Next-Web#4439]
### Problem Description

希望可以添加独立的登录界面，而不是在设置中输入鉴权字符串

### Solution Description

如上

**Comment by Dean-YZG** [comment]
we have a independent auth page, is this page to satisfy your purpose

**Comment by 0xffffharry** [comment]
我在文档中并未找到，只找到类似的访问密码

**Comment by Dean-YZG** [comment]
Are you your own privately deployed application?

**Comment by 0xffffharry** [comment]
是的，我使用docker部署

**Comment by Dean-YZG** [comment]
if you have deployed a privately application, you can set the Code var to call the auth page 
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/138353356/564cb2c9-372c-441b-921d-603cdd14ebb1)

**Comment by 0xffffharry** [comment]
我按照文档提示操作，但是依然没有独立的登录界面，需要在设置中填入code才能正常访问，这并非独立页面

**Comment by Dean-YZG** [comment]
独立页面是用来填写apikey？

**Comment by 0xffffharry** [comment]
不是，是将apikey与访问密码分开

**Comment by Dean-YZG** [comment]
使用 code 环境变量之后，应用就会强制开启登录，会在对话框内首先提示登录，点击登录链接，就可以跳转至登录页啦~~，目前，没有区分的主要原因是：用户提供了apiKey 或 正确的accessCode，都可以正常使用应用（若用户提供了apiKey，则使用用户提供的apiKey；若用户提供了accessCode，则使用应用服务端配置的 apikey）
