### ISSUE TITLE
[Bug] Error 1002

### ISSUE THREAD

**Issue by A-l-an** [ChatGPTNextWeb/ChatGPT-Next-Web#4441]
### Bug Description

I set my own BASE_URL from my school's Openai API, but it fails when I tried to use it.
BASE_URL = https://【myschool】/v1/chat/completions

### Steps to Reproduce

.

### Expected Behavior

.

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

MacOS

### Desktop Browser

Chrom

**Comment by QAbot-zh** [comment]
BASE_URL does not need to include /v1/chat/completions part

**Comment by A-l-an** [comment]
> BASE_URL does not need to include /v1/chat/completions part

It doesn't work. still shows error code: 1002.
The reference code my school provide is as below:
`url = "https://gpt-api.【school】.edu.cn/v1/chat/completions"
headers = { 
"Content-Type": "application/json", 
"Authorization": "Bearer xxx"
}
data = { 
"model": "gpt-4", # "gpt-3.5-turbo" version in gpt-3.5-turbo-1106, "gpt-4" version in gpt-4-1106-version (gpt-4-vision-preview is NOT available in azure openai), "gpt-3.5-turbo-16k", "gpt-4-32k"
"messages": [{"role": "user", "content": "Q"}], 
"temperature": 0.7 
}
response = requests.post(url, headers=headers, data=json.dumps(data))
print(response.json())`

I supposed that error is because of the different usage of the api? or sth else?

**Comment by Dean-YZG** [comment]
Please provide a callable, complete, domain-desensitized url
Our concatenation rule of url calling gpt is    'BASE_URL' + 'v1/chat/completions'
