### ISSUE TITLE
[Feature Request]:  Add text and image input capabilities to the Gemini model

### ISSUE THREAD

**Issue by cnhkbbs** [ChatGPTNextWeb/ChatGPT-Next-Web#4446]
### Problem Description

Add text and image input capabilities to the Gemini model

### Solution Description

Add text and image input capabilities to the Gemini model

**Comment by QAbot-zh** [comment]
use gemini-pro-vision model, then you can upload image

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/544eac97-7097-4bc3-a65a-ad1c0870975b)

**Comment by cnhkbbs** [comment]
> 使用Gemini-Pro-Vision模型，然后就可以上传图片了
> 
> ![图像](https://private-user-images.githubusercontent.com/40236765/319880647-544eac97-7097-4bc3-a65a-ad1c0870975b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTk4NTYsIm5iZiI6MTcxMjM5OTU1NiwicGF0aCI6Ii80MDIzNjc2NS8zMTk4ODA2NDctNTQ0ZWFjOTctNzA5Ny00YmMzLWE2NWEtYWQxYzA4NzA5NzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDEwMzIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNDM3MWZjZjVhZGNjY2VkZGQ1M2VmNTc4MDJkYTY1YjBhYmVhYWY4NTM2NDRjYWE4NWE1NzQxMWI0N2NkMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xXRZI9dSZl7zslK7FjfxTo9ipkPcyWTLw1TFvXhe8fI)

Thanks a ton.😀
