### ISSUE TITLE
[点击内容自动发送]

### ISSUE THREAD

**Issue by ssrsss** [ChatGPTNextWeb/ChatGPT-Next-Web#4451]
### Problem Description

能否支持点击蓝色高亮（markdown）的内容自动发送

如图所示，点击图片中的蓝色高亮文字会自动发送

![IMG_0144](https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/assets/129376251/e117e356-8ba1-4fe6-98eb-e797f3498512)

### Solution Description

无

### Alternatives Considered

无

### Additional Context

前作者在QQ频道的面具板块，有发过类似的，现在好像被作者删除了。

所以说程序本身应该就支持这个功能，但是不容易被发现，希望可以指点一下

**Comment by yet8main** [comment]
蓝色不是超链接吗，比如
[网站超链接为何是蓝色的](https://www.163.com/dy/article/IPNC69GJ0550W16F.html)

**Comment by Dean-YZG** [comment]
Thank you for your feedback, but the blue string usually represents a hyperlink
