### ISSUE TITLE
For static files generated by yarn export, can you support customizing the base url address、api key and models

### ISSUE THREAD

**Issue by ikexue** [ChatGPTNextWeb/ChatGPT-Next-Web#4458]
### Problem Description

For static files generated by yarn export, can you support customizing the base url address (usually used for the openai proxy api address), the api key, and the model?

### Solution Description

customizing the base url address、api key and models

**Comment by Dean-YZG** [comment]
you can use .env file to solve this problem

**Comment by Dean-YZG** [comment]
Thank you for your feedbacks, we will adopt the suggestion
