### ISSUE TITLE
[Bug] High browser CPU usage when streaming outpu 

### ISSUE THREAD

**Issue by chatGPTxx** [ChatGPTNextWeb/ChatGPT-Next-Web#4459]
### Bug Description

I notice when the chatbot streaming output, there's CPU usage surge in my Chrome, and then goes down when streaming ouput finihsed, is it my browser issue or bug?

### Steps to Reproduce

Ask question to AI model. wait for the response starts streaming

### Expected Behavior

CPU usage should not be too high 

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows 10

### Desktop Browser

Chrome

**Comment by Dean-YZG** [comment]
Thank you for feedback, We'll deal with that

**Comment by shansing** [comment]
也许你可以修改流式输出的动画。`app/client/platforms/openai.ts` （其他平台类似）下有一个 `animateResponseText()` 函数，做了两件事：

1. 将同一个增量消息（delta）再拆分批次，最坏情形下可能拆成一个字一个字输出；
2. 通过 requestAnimationFrame 递归调用自身（`requestAnimationFrame(animateResponseText)`）。

我个人不喜欢 1，所以自己的 fork 直接改成遵循接口拆分的 delta。并且我发现 2 会偶尔导致输出停止，此时控制台报错 `"Maximum update depth exceeded"`，似乎是框架的一种防御机制。兜兜转转，我现在完全删除了 `animateResponseText()` 函数，只在收到一条新消息时（onmessage）请求一次动画帧。ref: https://github.com/shansing/ChatGPT-Next-Web/commit/d81fdbf1df5485192141ca1ff6efc3f02f037a9b#diff-6de03d672a0a7c506b48a06a6bec2b3763d7e29f9b9c4fbd490fa2e177fbb01fR264

我认为这样应该能提升性能。因为只在必要时请求动画帧（而不是一直嵌套调用），并且不做多余拆分动作。供参考。
