### ISSUE TITLE
[Bug] Windows application has stopped working

### ISSUE THREAD

**Issue by Valdri** [ChatGPTNextWeb/ChatGPT-Next-Web#4465]
### Bug Description

Displays an error
```{
  "error": true,
  "message": "Failed to fetch"
}
```

### Steps to Reproduce

1. Open applications
2. type something in the new chat

### Expected Behavior

Returning response

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/13934649/98109f36-dd8f-47e8-b3e6-6171b674c2ee)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows 11 NextChat v2.11.3

**Comment by andenixa** [comment]
Same issue under Windows 11, worked before

**Comment by Dean-YZG** [comment]
Thank you for your feedback，we're dealing with it as a matter of urgency, and will be back soon

**Comment by Dean-YZG** [comment]
We had some issues with our deployment, which has now been restored
