### ISSUE TITLE
[Bug] 最新版本自定义模型时，不支持输入图片了

### ISSUE THREAD

**Issue by live106** [ChatGPTNextWeb/ChatGPT-Next-Web#4467]
### Bug Description

最新版本自定义模型时，不支持输入图片了

### Steps to Reproduce

1. 设置自定义模型
2. 输入时没有输入图片的功能按钮

### Expected Behavior

设置自定义模型时输入时支持输入图片的功能

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Dean-YZG** [comment]
Thanks for the feedback, we will fix it quickly

**Comment by Dean-YZG** [comment]
可以具体说一下自定义的model名称么？目前，只有模型名中，只有包含 vision 、claude-3 这两个字符串的才可支持上传图片

**Comment by QAbot-zh** [comment]
个人直接改下代码把show改成true，默认所有模型支持图片算了，毕竟每个人的自定义模型名字都不一样

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/c0aec6f6-9295-4ec1-9885-a27c151cbc58)

**Comment by Dean-YZG** [comment]
好的，目前，我们仅对市面上支持图片上传的模型开放上传按钮功能~~如果私有大模型需要开放该功能可在下图代码块中增加欲支持的模型名称
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/138353356/9195fa9e-70c0-4d7c-b456-239d1934ddd9)
