### ISSUE TITLE
[Bug] gemini-pro:streamGenerateContent

### ISSUE THREAD

**Issue by ztdy** [ChatGPTNextWeb/ChatGPT-Next-Web#4468]
### Bug Description

软件里gemini-pro:streamGenerateContent这个参数与官方示例不太一样，我测试了下官方的参数能成功响应，本软件里会报错。

官方示例如下：
API_KEY="YOUR_API_KEY"
curl -H 'Content-Type: application/json' \
     -d '{"contents":[
            {"role": "user",
              "parts":[{"text": "Give me five subcategories of jazz?"}]}]}' \
     "https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent?key=${API_KEY}"

### Steps to Reproduce

设置为gemini-pro，然后询问问题会报错。

### Expected Behavior

{
  "error": true,
  "message": "An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting"
}

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Win11

### Desktop Browser

chrome

**Comment by Dean-YZG** [comment]
Thanks for the feedback, we will fix it quickly

**Comment by Dean-YZG** [comment]
It has not been reproduced

**Comment by Dean-YZG** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/138353356/577d1a44-119f-4c66-8085-e019073b7085)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/138353356/5e1fdd02-24bb-4e81-a3d0-3788bf951129)
