### ISSUE TITLE
如果问答的时候异常，界面通过message做出相应的提醒

### ISSUE THREAD

**Issue by 143heyan** [ChatGPTNextWeb/ChatGPT-Next-Web#4471]
### Bug Description

我不小心设置了top_p=0,问答的时候界面一直转圈圈，最后f12定位才发现了问题[Request] parse error {"error": "[address=0.0.0.0:35083, pid=14871] top_p must be in (0, 1], got 0.0."}，这种情况建议直接在界面提示异常。

**Comment by Dean-YZG** [comment]
Hello, at present, we have not reproduced issue through  gpt-3.5/claude1/gemini-pro, please describe the model you used in detail
