### ISSUE TITLE
[Feature Request]: Auto-cleaning dialog history

### ISSUE THREAD

**Issue by horw** [ChatGPTNextWeb/ChatGPT-Next-Web#4472]
### Problem Description

Hello,
I usually create a new dialogue for a new question when chatting with GPT because this way the context is fresh. Sometimes I revisit my dialogue history to review previous chat answers, but not very frequently. If there are already numerous dialogues, it significantly slows down the Next.

### Solution Description

It might be useful to have the option to set a maximum limit for the number of dialogues. Once this limit is reached, the system could employ a FIFO approach.

### Additional Context

If you think this will be helpful, you can assign it to me, and I will try to implement it.

**Comment by Dean-YZG** [comment]
Thank you for your feedback, we will consider the proposal about how much messages should be retained
