### ISSUE TITLE
[Bug] BASE_URL Error1002

### ISSUE THREAD

**Issue by A-l-an** [ChatGPTNextWeb/ChatGPT-Next-Web#4474]
### Bug Description

> BASE_URL does not need to include /v1/chat/completions part

Originally posted by @QAbot-zh in https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4441#issuecomment-2036563721

It doesn't work. still shows error code: 1002.

The reference code my school provide is as below:
url = "[https://gpt-api.【school】.edu.cn/v1/chat/completions](https://gpt-api.xn--school-hu3eoa.edu.cn/v1/chat/completions)"
headers = { "Content-Type": "application/json", "Authorization": "Bearer xxx" }
data = { "model": "gpt-4", # "gpt-3.5-turbo" version in gpt-3.5-turbo-1106, "gpt-4" version in gpt-4-1106-version (gpt-4-vision-preview is NOT available in azure openai), "gpt-3.5-turbo-16k", "gpt-4-32k" "messages": [{"role": "user", "content": "Q"}], "temperature": 0.7 }
response = requests.post(url, headers=headers, data=json.dumps(data))
print(response.json())

I supposed that error is because of the different usage of the api? or sth else?

### Steps to Reproduce

/

### Expected Behavior

/

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

MacOS

### Desktop Browser

Chrom

**Comment by Dean-YZG** [comment]
Please provide a callable, complete, domain-desensitized url
Our concatenation rule of url calling gpt is 'BASE_URL' + 'v1/chat/completions'

**Comment by Dean-YZG** [comment]
Please verify that your available urls match our url concatenation rules

**Comment by A-l-an** [comment]
> Please provide a callable, complete, domain-desensitized url Our concatenation rule of url calling gpt is 'BASE_URL' + 'v1/chat/completions'

yes it's `https://gpt-api.hkust-gz.edu.cn/v1/chat/completions` , but when I changed the BASE_URL to `https://gpt-api.hkust-gz.edu.cn/ `

**Comment by fred-bf** [comment]
@A-l-an would you mind share the original error response?

**Comment by A-l-an** [comment]
> @A-l-an would you mind share the original error response?

Sure, the error shows as below:
<img width="881" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/63406861/c914f27c-2b04-42a4-8a4c-2510a2920502">

**Comment by A-l-an** [comment]
> I mean the raw response from the chrome devtools 

The response is still the same as below:
<img width="1097" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/63406861/33df0a22-2cbf-4750-bbc2-5ad53248b8bd">

But I did notice that the request URL is still the original one instead of my school's.
<img width="961" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/63406861/23aa09f9-fe2a-4512-9f4d-c4f351481533">

And I did change the BASE_URL and redeploy the web as the pic showed below:
<img width="952" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/63406861/e75c449d-a286-4098-9694-8d17cdaf7342">

**Comment by QAbot-zh** [comment]
So, can you successfully get a response using the reference code provided by your school? 
Run the school's reference code first to test your network environment.

**Comment by A-l-an** [comment]
> So, can you successfully get a response using the reference code provided by your school? Run the school's reference code first to test your network environment.

Yes, it worked successfully on the  reference code .

**Comment by QAbot-zh** [comment]
So it might be necessary to inquire with your school whether they have imposed restrictions on visiting IPs, because the program deployed by Vercel makes requests using the IPs provided by Vercel. You can try downloading the released software of NextChat and use it on your computer to see if the problem still exists.

**Comment by A-l-an** [comment]
> #4480, In this PR, the user-defined model will use the openai interface protocol instead of the anthropic interface protocol

sorry, but how should I fix this?

**Comment by QAbot-zh** [comment]
You can download the release to use the api if you can run the reference code.  [release is here](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases)

**Comment by A-l-an** [comment]
> You can download the release to use the api if you can run the reference code. [release is here](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases)

in this case, should I change the OpenAI Endpoint to my school's?  
`https://gpt-api.hkust-gz.edu.cn/`

cause when I did, another error showed up:
`{
  "error": true,
  "message": "Load failed"
}
`

**Comment by QAbot-zh** [comment]
It's confusing.

**Comment by Dean-YZG** [comment]
sorry,it's my fault,I closed this issue by mistake,ignore it

**Comment by H0llyW00dzZ** [comment]
I think there might be something wrong with the header handler. Also, I'm surprised that your school allows the use of AI ?

**Comment by A-l-an** [comment]
> I think there might be something wrong with the header handler. Also, I'm surprised that your school allows the use of AI ?

sorry what do you mean by header handler? and yes we are encouraged to use AI tools.

**Comment by A-l-an** [comment]
> It's confusing.

yeah, all I did just replace the Endpoint and type in my API key...

**Comment by H0llyW00dzZ** [comment]
> > I think there might be something wrong with the header handler. Also, I'm surprised that your school allows the use of AI ?
> 
> sorry what do you mean by header handler? and yes we are encouraged to use AI tools.

Here's an example:

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/2e7c1ef6-3f16-41aa-9de5-ab3a2d4bd437)


Also, can you take a screenshot of it and censor/hide any contained API keys?

**Comment by H0llyW00dzZ** [comment]
and censor/hide any other value contained sensitive as well

**Comment by A-l-an** [comment]
> > > I think there might be something wrong with the header handler. Also, I'm surprised that your school allows the use of AI ?
> > 
> > 
> > sorry what do you mean by header handler? and yes we are encouraged to use AI tools.
> 
> Here's an example:
> 
> Also, can you take a screenshot of it and censor/hide any contained API keys?

here it is, I do not know what went wrong

![CleanShot 2024-04-09 at 21 57 49@2x](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/63406861/72eab7fe-3b25-4d23-a04d-a3cc078ece06)

**Comment by H0llyW00dzZ** [comment]
> > > > I think there might be something wrong with the header handler. Also, I'm surprised that your school allows the use of AI ?
> > > 
> > > 
> > > sorry what do you mean by header handler? and yes we are encouraged to use AI tools.
> > 
> > 
> > Here's an example:
> > Also, can you take a screenshot of it and censor/hide any contained API keys?
> 
> here it is, I do not know what went wrong
> 
> ![CleanShot 2024-04-09 at 21 57 49@2x](https://private-user-images.githubusercontent.com/63406861/320875117-72eab7fe-3b25-4d23-a04d-a3cc078ece06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzE1MTYsIm5iZiI6MTcxMjY3MTIxNiwicGF0aCI6Ii82MzQwNjg2MS8zMjA4NzUxMTctNzJlYWI3ZmUtM2IyNS00ZDIzLWEwNGQtYTNjYzA3OGVjZTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE0MDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzOGJkZDgyZjhjOTg1YzM3NjA2ZTAxOWEwN2UzZTIzYWYxYWMwMTE2YjhlMDliNjA1YmJmOTQ5YjEyNTFkYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xLHytwgSPVrdGO3W5Y_P62gAlFAxTay1zsE6c8hHhSM)

It could be an issue with your school's [https://gpt-api.【school】.edu.cn/v1/chat/completions](https://gpt-api.xn--school-hu3eoa.edu.cn/v1/chat/completions) REST APIs (e.g., permissions related to CORS). The request header is correct.

**Comment by H0llyW00dzZ** [comment]
> > > > > > I think there might be something wrong with the header handler. Also, I'm surprised that your school allows the use of AI ?
> > > > > 
> > > > > 
> > > > > sorry what do you mean by header handler? and yes we are encouraged to use AI tools.
> > > > 
> > > > 
> > > > Here's an example:
> > > > Also, can you take a screenshot of it and censor/hide any contained API keys?
> > > 
> > > 
> > > here it is, I do not know what went wrong
> > > ![CleanShot 2024-04-09 at 21 57 49@2x](https://private-user-images.githubusercontent.com/63406861/320875117-72eab7fe-3b25-4d23-a04d-a3cc078ece06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzE1MTYsIm5iZiI6MTcxMjY3MTIxNiwicGF0aCI6Ii82MzQwNjg2MS8zMjA4NzUxMTctNzJlYWI3ZmUtM2IyNS00ZDIzLWEwNGQtYTNjYzA3OGVjZTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE0MDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzOGJkZDgyZjhjOTg1YzM3NjA2ZTAxOWEwN2UzZTIzYWYxYWMwMTE2YjhlMDliNjA1YmJmOTQ5YjEyNTFkYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xLHytwgSPVrdGO3W5Y_P62gAlFAxTay1zsE6c8hHhSM)
> > 
> > 
> > It could be an issue with your school's [https://gpt-api.【school】.edu.cn/v1/chat/completions](https://gpt-api.xn--school-hu3eoa.edu.cn/v1/chat/completions) REST APIs (e.g., permissions related to CORS,region blocked because it used vercel to request into your school REST APIs). The request header is correct.
> 
> but I also tried to download the release version and use the api locally before. and another error showed up: `{ "error": true, "message": "Load failed" } `

try this method:

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17626300/8c582724-eebb-48a2-bcdb-32cf6afc8564)

**Comment by A-l-an** [comment]
> url = "[https://gpt-api.【school】.edu.cn/v1/chat/completions](https://gpt-api.xn--school-hu3eoa.edu.cn/v1/chat/completions)"

the original reference  url  is https://gpt-api.【school】.edu.cn**/v1/chat/completions.**
all right, thanks for your considerate answer!! I guess I better check with the school's technician about this part.

**Comment by H0llyW00dzZ** [comment]
> > url = "[https://gpt-api.【school】.edu.cn/v1/chat/completions](https://gpt-api.xn--school-hu3eoa.edu.cn/v1/chat/completions)"
> 
> the original reference url is [https://gpt-api.【school】.edu.cn**/v1/chat/completions](https://gpt-api.%E3%80%90school%E3%80%91.edu.cn**/v1/chat/completions).** all right, thanks for your considerate answer!! I guess I better check with the school's technician about this part.

Yes, it seems to be an issue related to permissions, which is why you got a forbidden access error.

**Comment by A-l-an** [comment]
> > > url = "[https://gpt-api.【school】.edu.cn/v1/chat/completions](https://gpt-api.xn--school-hu3eoa.edu.cn/v1/chat/completions)"
> > 
> > 
> > the original reference url is [https://gpt-api.【school】.edu.cn**/v1/chat/completions](https://gpt-api.%E3%80%90school%E3%80%91.edu.cn**/v1/chat/completions).** all right, thanks for your considerate answer!! I guess I better check with the school's technician about this part.
> 
> Yes, it seems to be an issue related to permissions(e.g, `CORS`), which is why you got a forbidden access error.

They said the system must access to GPT-API by Campus Network (specified SSID required ).
I was wondering if this means there's no way out for this situation?

**Comment by QAbot-zh** [comment]
I think if you can run the reference code in your PC, then you can run it on the release program keeping the same network setting. They should not have any essential differences, both are sending requests to a third-party endpoint.  What information will this return using `https://gpt-api.hkust-gz.edu.cn` on your release nextchat setting.

**Comment by A-l-an** [comment]
> I think if you can run the reference code in your PC, then you can run it on the release program keeping the same network setting. They should not have any essential differences, both are sending requests to a third-party endpoint. What information will this return using `https://gpt-api.hkust-gz.edu.cn` on your release nextchat setting.

it returns:

```json
{
  "error": true,
  "message": "Load failed"
}
```

**Comment by QAbot-zh** [comment]
Perhaps the API offered by your school does not allow for streaming responses? You could conduct a test using the subsequent illustration:

```
import requests
import json
import os

url = "xxxx/v1/chat/completions"
headers = { "Content-Type": "application/json", "Authorization": "Bearer xxx" }
data = { "model": "gpt-4",  "messages": [{"role": "user", "content": "Q"}], "stream": True }

response = requests.post(url, headers=headers, data=json.dumps(data), stream=True)
if response.status_code == 200:
   for chunk in response:
        print(chunk)
else:
    print(f"Error: {response.status_code}")
```

**Comment by A-l-an** [comment]
> Perhaps the API offered by your school does not support for streaming responses? You could conduct a test using the subsequent illustration:
> 
> ```
> import requests
> import json
> import os
> 
> url = "xxxx/v1/chat/completions"
> headers = { "Content-Type": "application/json", "Authorization": "Bearer xxx" }
> data = { "model": "gpt-4",  "messages": [{"role": "user", "content": "Q"}], "stream": True }
> 
> response = requests.post(url, headers=headers, data=json.dumps(data), stream=True)
> if response.status_code == 200:
>    for chunk in response:
>         print(chunk)
> else:
>     print(f"Error: {response.status_code}")
> ```

Ok. I got it. The Campus GPT API has been re – encapsulated so I could only access it by the reference code .... Thanks for your help.
