### ISSUE TITLE
[Bug] You exceeded your current quota

### ISSUE THREAD

**Issue by microSoftware** [ChatGPTNextWeb/ChatGPT-Next-Web#4482]
### Bug Description

{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}

### Steps to Reproduce

I set the open api url to "https://api.openai.com/"
In the token field, i used the token from my open api dashboard "sk-Pt .... "
I tried several url but they all failed.
Also i have 0$ / 5$ used in  my openai dashboard because it's a new account.

### Expected Behavior

It would be good to have a details log in the ChatGPTNextWeb dashboard. At the very least have log to see if the url field is correct and if the token is correct. Because right now i'm trying to debug it but i have no log error beside the error "You exceeded your current quota"

### Screenshots

![Screen Shot 2024-04-09 at 19 21 00](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/3915272/f2a19f4a-a235-4137-9c94-1b2fd40b4c8c)

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Ubuntu

**Comment by Dean-YZG** [comment]
This new account is not available and requires the apikey of the paid account

**Comment by microSoftware** [comment]
Oh okay.
