### ISSUE TITLE
[Feature Request]: 通过 Vertex API 添加 gemini-1.5-pro 的接口

### ISSUE THREAD

**Issue by ShinChven** [ChatGPTNextWeb/ChatGPT-Next-Web#4483]
### Problem Description

现在 AI Studio 不给 gemini-1.5-pro API 的权限，但是 vertex API 是可以用的。
vertex API 和 AI Studio 的 API 调用方式不一样，需要用 Google Cloud SDK 登录以后获取 access token 来访问。

我通过下面的脚本获取到了配置信息，已经在 Next Chat 上用上了 gemini-1.5-pro。 

```bash
API_ENDPOINT="us-central1-aiplatform.googleapis.com"
PROJECT_ID=<PROJECT_ID>
LOCATION_ID="us-central1"
MODEL_ID="gemini-1.5-pro-preview-0409"
ACCESS_TOKEN="$(gcloud auth print-access-token)"
URL="https://${API_ENDPOINT}/v1/projects/${PROJECT_ID}/locations/${LOCATION_ID}/publishers/google/models/${MODEL_ID}:streamGenerateContent"

echo "URL:"
echo ${URL}
echo "ACCESS TOKEN:"
echo ${ACCESS_TOKEN}
echo "MODEL_ID:"
echo ${MODEL_ID}
```

Next Chat 具体配置方法是：

1. Model Provider 选 Google 
2. Endpoint Address 填 URL
3. API Key 填 ACCESS_TOKEN
4. API Version 删掉默认
5. Custom Model 填 gemini-1.5-pro-preview-0409

### Solution Description

希望 Next Chat 能更好的支持 Vertex API。

**Comment by Dean-YZG** [comment]
我们已经有计划，改造应用中的 provider实体和model实体的关系，来允许用户自定义provider，以及provider提供的models，这样最大限度适配市面上各个服务提供商的模型接口

**Comment by ShinChven** [comment]
https://github.com/ShinChven/vertex-ai-proxy

Vertex AI 只能用 Jason api key，我写了个中继接口，可以临时解决一下 vertex AI token 刷新问题。

可以配置到 Next Chat 里面用。
