### ISSUE TITLE
[Feature Request]: 增加 gpt-4-turbo 识图功能

### ISSUE THREAD

**Issue by DreamsCat** [ChatGPTNextWeb/ChatGPT-Next-Web#4484]
### Problem Description

OpenAI 发布了GPT-4-Turbo 正式版

带有视觉能力，上下文 128k。

现在调整到 gpt-4-turbo ，没有识图功能，希望能增加支持

### Solution Description

现在调整到 gpt-4-turbo ，没有识图功能，希望能增加支持

**Comment by robotJie** [comment]
上传图片功能按钮是否可以跟具体的模型解耦？比如设置里可以手动开启，或者always on?

**Comment by Rubuark** [comment]
#4487

**Comment by Dean-YZG** [comment]
> 上传图片功能按钮是否可以跟具体的模型解耦？比如设置里可以手动开启，或者always on?
> 
> 目前只有vision的model，该按钮才会appear

目前，各个模型api对图片的传输有特定的接口协议，因此，不通的模型还是需要对图片传输做针对性的开发，因此，无法对任意模型开放图片上传能力

**Comment by Dean-YZG** [comment]
接下来会支持该能力，敬请期待~~

**Comment by Dean-YZG** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4487 ，已支持~~
