### ISSUE TITLE
[Feature Request]: support gpt-4-turbo-2024-04-09

### ISSUE THREAD

**Issue by jiangying000** [ChatGPTNextWeb/ChatGPT-Next-Web#4486]
### Problem Description

https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4
new model gpt-4-turbo-2024-04-09

### Solution Description

add model

**Comment by Rubuark** [comment]
#4487

**Comment by Dean-YZG** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4487 Thanks for contribution
