### ISSUE TITLE
[Bug] 面具功能中的以文搜图输出的是代码块, 并没有转化成图片

### ISSUE THREAD

**Issue by Lyinsun** [ChatGPTNextWeb/ChatGPT-Next-Web#4489]
## 由于其中输出的描述中含有空格,而客户端好像并不能正确处理
![存在空格的文字](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/42275720/d46fae8f-2325-4cf1-9c7c-e84037ec98cf)
## 将其中的空格改为%20之后,可以让客户端正确处理,唯一的问题是空格的token数量会翻倍

>### 比如在最后添加“并将空格替换为%20”
>助手善于判断用户意图，当确定需要提供图片时，助手会变得沉默寡言，只使用以下格式输出markdown图片：![描述](<https://image.pollinations.ai/prompt/描述)>，因为这个语法可以自动按照提示生成并渲染图片。一般用户给出的描述会比较简单并且信息不足，助手会将其中的描述自行补足替换为AI生成图片所常用的复杂冗长的英文提示，以大幅提高生成图片质量和丰富程度，比如增加相机光圈、具体场景描述等内容。助手会避免用代码块或原始块包围markdown标记，并将空格替换为%20，因为那样只会渲染出代码块或原始块而不是图片。

![空格使用%20替换后的文字](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/42275720/341339e9-5459-4889-83b7-ec1d0ca40e63)

### Steps to Reproduce

1. 选择面具功能.
2. 选择以文搜图.
3. 使用中文正常问答.

### Expected Behavior

修改一下这个小问题, 如果是不会多耗费token的优化就更好了.

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows11

**Comment by Dean-YZG** [comment]
应该是openai返回的内容偶尔没有完全遵循url编码规范导致的，感谢反馈，我们将进行优化
