### ISSUE TITLE
[Feature Request]: 希望增加一个开关可以关闭对用户输入内容的转义

### ISSUE THREAD

**Issue by black-zero358** [ChatGPTNextWeb/ChatGPT-Next-Web#4494]
### Problem Description

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/53086059/bf62bcc7-9499-4224-bef1-c1aed2e05784)
默认情况下会以md的格式显示用户输入内容，所以每行前的空格也没有显示出来

虽然使用消息框的复制按钮确实会可以获取到输入的原始文本，但是也希望有一个开关可以控制显示模式

### Solution Description

希望添加一个开关，控制用户输入内容的显示模式（转义/不转义）

**Comment by Dean-YZG** [comment]
Thank you for your feedback, we will carefully analyze your feedback, currently you can make markdown strive to display your code snippet by adding "```programming language name" to the first line of the code and "```" to the next line of the end line
