### ISSUE TITLE
[Bug] code bypass vulnerability

### ISSUE THREAD

**Issue by secf0ra11** [ChatGPTNextWeb/ChatGPT-Next-Web#4499]
### Bug Description

chat-next-web 可以通过设置http header 绕过登录code，在2.9.x版本

### Steps to Reproduce

1.随意输入登录密码
2.设置http header，Authorization: Bearer ak-*****，***为任意值
3.获取chatgpt

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/108478753/ab64b0db-e443-4313-ab8a-1ef2a20e2317

### Expected Behavior

绕过登录

### Deployment Method

- [X] Docker
- [X] Vercel
- [X] Server

### Desktop OS

windows 10

### Desktop Browser

firefox

### Desktop Browser Version

89

**Comment by Dean-YZG** [comment]
是私有化部署么？最新版本已经解决了这个问题，可以升级到最新版本
