### ISSUE TITLE
[Feature Request]: 代理地址功能

### ISSUE THREAD

**Issue by DSLZL** [ChatGPTNextWeb/ChatGPT-Next-Web#4501]
### Problem Description

能使用多个代理地址，并可选择让代理地址特定代理某些模型，不代理其他未配置的

### Solution Description

有上面的功能

**Comment by Dean-YZG** [comment]
感谢反馈，我们会认真考虑这个建议，在之后的版本中会逐步实现提供商和模型的解耦，为用户提供更加灵活的配置方式
