### ISSUE TITLE
[Bug] 同步始终有问题，谢谢

### ISSUE THREAD

**Issue by 404gods** [ChatGPTNextWeb/ChatGPT-Next-Web#4503]
### Bug Description

1、webdav无法同步，显示同步成功，但是webdav网盘里始终是空。
2、upstash可以同步成功，能否添加自动同步功能？谢谢

### Steps to Reproduce

1、webdav无法同步，显示同步成功，但是webdav网盘里始终是空。
2、upstash可以同步成功，能否添加自动同步功能？谢谢

### Expected Behavior

1、webdav无法同步，显示同步成功，但是webdav网盘里始终是空。
2、upstash可以同步成功，能否添加自动同步功能？谢谢

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

**Comment by Dean-YZG** [comment]
感谢提出的建议，关于提到的问题，我们会尽快修复

**Comment by Dean-YZG** [comment]
Should be no synchronization success, but the error is hidden by the underlying code, so the upper code shows synchronization success, there is a console error screenshot?

**Comment by Dean-YZG** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4507
我们修复了客户端请求webdav的url拼接逻辑，同时向上抛出了同步报错

**Comment by daiaji** [comment]
现在这个同步逻辑是咋样的，我在本地搭建了NextWeb，webdav同步可用，但逻辑很奇怪，似乎总是从云端覆盖到本地。

**Comment by Dean-YZG** [comment]
> 现在这个同步逻辑是咋样的，我在本地搭建了NextWeb，webdav同步可用，但逻辑很奇怪，似乎总是从云端覆盖到本地。

目前的逻辑是将云端的内容拉取下来与本地的进行merge，之后将merge的结果同步到云端

**Comment by Dean-YZG** [comment]
> > #4507 我们修复了客户端请求webdav的url拼接逻辑，同时向上抛出了同步报错
> 
> 谢谢答复，我更新了代码，现在提示了同步失败。
> 
> ![1](https://private-user-images.githubusercontent.com/50573302/321978854-8d400560-2386-4e4b-adbc-6193fbbf610c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTExNzgsIm5iZiI6MTcxMzI1MDg3OCwicGF0aCI6Ii81MDU3MzMwMi8zMjE5Nzg4NTQtOGQ0MDA1NjAtMjM4Ni00ZTRiLWFkYmMtNjE5M2ZiYmY2MTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA3MDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMzZhYWMxM2U5MjE1ZDcwMjhhZjM2MzZkN2Y4ODBmMDljM2M4ZjYyYzRlZTUwMjQzNThlNjVjYjU0NmU1NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O5xP6qvyjhSrcpVpNl8Lyo6yu39eQfIL1fI-dFJyLiA) ![2](https://private-user-images.githubusercontent.com/50573302/321978859-e1fadcaa-7f3b-4ea3-a4cf-ef39dbb78019.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTExNzgsIm5iZiI6MTcxMzI1MDg3OCwicGF0aCI6Ii81MDU3MzMwMi8zMjE5Nzg4NTktZTFmYWRjYWEtN2YzYi00ZWEzLWE0Y2YtZWYzOWRiYjc4MDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA3MDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZDFlMzZmMjJiNTJiMzEyZjJmNTBiMDc5MjM3YmRjNGI2MGViMThlNzE3ZTRmMTNhODAyMGE1YjJiMDE1YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49yFzD5LcbupfiTvvo86L5vF6ouTOuQOkxBaXGH4oaQ) ![3](https://private-user-images.githubusercontent.com/50573302/321978862-919f497b-4c42-40c1-b162-9c273ff8fb2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTExNzgsIm5iZiI6MTcxMzI1MDg3OCwicGF0aCI6Ii81MDU3MzMwMi8zMjE5Nzg4NjItOTE5ZjQ5N2ItNGM0Mi00MGMxLWIxNjItOWMyNzNmZjhmYjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA3MDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNDZkMzZjNDI3NzM2NmQ4OWU0NjJmNzViMDU5ZTlkOGE4MTRiNWQwNTkxZWRkZTRmOTI0MGE5ZDY3N2RjNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cPE2CBrQkq8bbsFxpOK96YCUHEFTZzJ46g6R4FBYkNc)

调用了api/upstash 是一个bug ，已经在这个pr中解决 https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4525
