### ISSUE TITLE
When you scroll up to a certain position and then click the mouse, it will automatically jump to the bottom.[Bug] 

### ISSUE THREAD

**Issue by Mgrsc** [ChatGPTNextWeb/ChatGPT-Next-Web#4504]
### Bug Description

When I scroll up to view the history records, if I click on a blank space, it jumps directly to the bottom. Also, when I try to copy historical content and drag to select, it jumps to the bottom with just one click. However, this only happens when scrolling up for the first time and clicking again; on the second attempt, it works normally.

### Steps to Reproduce

1. Ask ChatGPT to reply with some content so that the old content scrolls up on the screen, then pause for a moment without moving.
2. Scroll up to view past content.
3. Click anywhere randomly.

### Expected Behavior

Will not jump to the bottom.

### Deployment Method

- [X] Docker
- [x] Vercel
- [ ] Server

**Comment by Dean-YZG** [comment]
we will revise the ui and ue soon, and at that time, we will focus on solving the experience problems that you feedback

**Comment by Mgrsc** [comment]
Alright,  hope this project will continue to improve.
