### ISSUE TITLE
[Bug] Using 'yarn build' or 'npm build' causes the server to crash.

### ISSUE THREAD

**Issue by doolachen** [ChatGPTNextWeb/ChatGPT-Next-Web#4511]
### Bug Description

Using yarn or npm to build the program will cause the CPU and memory load to reach 100%, leading to server crashes. 
The server is configured with 2 cores and 2GB of RAM. 
Are there any measures to control resource usage, or limit resource consumption during development?

使用yarn或者npm构建程序会导致cpu和内存负载达到100%，并且导致服务器宕机。
服务器配置为2核2G
是否有任何控制资源占用的措施，或者限制开发时的资源占用情况？

### Steps to Reproduce

1. install nodejs and yarn first
2. config local env vars in `.env.local`
3. run
```
yarn install
yarn build or yarn dev
```

### Expected Behavior

Hope to control memory usage during the build process
build过程可以控制内存占用

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

Ubuntu 20.04

**Comment by doolachen** [comment]
Finally, I had to try compiling and releasing the Docker image on a more powerful local machine to ensure that my server has the latest version available for use.
最后，我不得不尝试用性能更强大的本地机器编译docker镜像并发布，以保证我的服务器有最新的版本可以使用

**Comment by QAbot-zh** [comment]
2+2 确实编译不动，实在不行就蹭一下github actions来构建docker镜像
