### ISSUE TITLE
[Bug] 使用gpt-4-turbo模型时 max_tokens设置大于4096就会报错

### ISSUE THREAD

**Issue by hjdyzy** [ChatGPTNextWeb/ChatGPT-Next-Web#4517]
### Bug Description

使用gpt-4-turbo模型时 max_tokens设置大于4096就会报错，这是问题吗？

### Steps to Reproduce

1、model选择 gpt-4-turbo 或 gpt-4-turbo-2024-04-09
2、设置 max_tokens 值大于 4096

### Expected Behavior

max_tokens 值设置大于4096 时，gpt-4-turbo 或 gpt-4-turbo-2024-04-09 模型能正常使用

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/71299416/31b1a49c-a363-47d1-9438-b7af4a2f3512)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

Windows 10

### Desktop Browser

Chrome

### Desktop Browser Version

123.0.6312.107

**Comment by QAbot-zh** [comment]
不是问题，官网没标gpt-4-turbo的最大输出，但是对标1106和0125的话，估计输出限制仍然是4096，真正的问题是 nextchat 用 max_tokens 来限制对话队列，混淆了其真实含义
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4443

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/e11033ad-7656-429e-a226-3b3349347988)

**Comment by hjdyzy** [comment]
感谢回复，不是问题的话那我关闭了😂
