### ISSUE TITLE
[Bug] 自定义接口勾选取消后，接口调用仍然在使用自定义接口未使用服务中配置的baseurl

### ISSUE THREAD

**Issue by varg1714** [ChatGPTNextWeb/ChatGPT-Next-Web#4518]
### Bug Description

当我把自定义接口打开后，配置了自定义接口b，此时访问的是b接口，但是当我关闭该选项后，仍然使用b接口未使用后台中配置的baseurl的a

### Steps to Reproduce

1. 服务启动时配置baseurl为a
2. 页面直接访问，请求中发出的地址为a
3. 开启自定义接口，指定自定义接口地址为b
4. 页面访问，此时请求中发出的地址为b
5. 关闭自定义接口，此时请求访问的地址仍然为b

### Expected Behavior

在第5部关闭自定义接口后期待调用原配置的baseurl a

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

macos

### Desktop Browser

arc浏览器(chrome内核)

### Desktop Browser Version

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by i2qaq** [comment]
Indeed, this issue has been present ever since the button came out. 
So...
> It's not a bug. It's a feature.

**Comment by Dean-YZG** [comment]
Thanks to the feedback, this feature logic is really confusing to users, we will optimize the logic and eliminate counter-intuitive logic

**Comment by varg1714** [comment]
> Thanks to the feedback, this feature logic is really confusing to users, we will optimize the logic and eliminate counter-intuitive logic感谢反馈，这个功能逻辑确实让用户感到困惑，我们将优化逻辑并消除反直觉的逻辑

Thank you for your contributions!

**Comment by Dean-YZG** [comment]
fix it in this pr https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4525
