### ISSUE TITLE
[Bug] issue

### ISSUE THREAD

**Issue by adminlove520** [ChatGPTNextWeb/ChatGPT-Next-Web#4519]
### Bug Description

请问如何 docker  配置代理  只允许Gemini  然后其他请求走正常网络呢

### Steps to Reproduce

null

### Expected Behavior

docker部署

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by Dean-YZG** [comment]
you can follow this command to deploy app through docker
```shell
docker pull yidadaa/chatgpt-next-web

docker run -d -p 3000:3000 \
   -e OPENAI_API_KEY=sk-xxxx \
   -e CODE=页面访问密码 \
   yidadaa/chatgpt-next-web
```
and then add `-e 环境变量=环境变量值` to set env vars
finally, the `CUSTOM_MODELS` var could help you to custom model you want
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/138353356/61786ed2-f08f-4267-a3d0-2a7b9e0d2913)

**Comment by Dean-YZG** [comment]
> ### Bug Description
> 请问如何 docker 配置代理 只允许Gemini 然后其他请求走正常网络呢
> 
> ### Steps to Reproduce
> null
> 
> ### Expected Behavior
> docker部署
> 
> ### Screenshots
> _No response_
> 
> ### Deployment Method
> * [x]  Docker
> * [ ]  Vercel
> * [ ]  Server
> 
> ### Desktop OS
> _No response_
> 
> ### Desktop Browser
> _No response_
> 
> ### Desktop Browser Version
> _No response_
> 
> ### Smartphone Device
> _No response_
> 
> ### Smartphone OS
> _No response_
> 
> ### Smartphone Browser
> _No response_
> 
> ### Smartphone Browser Version
> _No response_
> 
> ### Additional Logs
> _No response_

另外，走正常网络指的是Gemini模型走代理的接口，其他模型走其他服务提供的接口是么？可以在客户端中自定义配置不同provider对应的服务接口
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/138353356/9e349b8c-0264-43f5-a299-ebc0c4beec30)
