### ISSUE TITLE
[Feature Request]: gpt-4-turbo-2024-04-09 

### ISSUE THREAD

**Issue by importtime** [ChatGPTNextWeb/ChatGPT-Next-Web#4526]
### Problem Description

openai 发布了最新的 api版本gpt-4-turbo-2024-04-09。希望添加gpt-4-turbo-2024-04-09 选项。

### Solution Description

openai 发布了最新的 api版本gpt-4-turbo-2024-04-09。希望添加gpt-4-turbo-2024-04-09 选项。

### Additional Context

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/112325019/f252aeb4-7103-45a6-85db-bd8d9b023211)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/112325019/27b0fc1b-6009-43a8-8794-7aa2973bc4ed)

**Comment by Dean-YZG** [comment]
thanks to your suggestion, but `gpt-4-turbo-2024-04-09 ` is a model version of `gpt-4-turbo`, so we dont provide to the user as a default option, However,you can use the env var named `CUSTOM_MODEL` to support  `gpt-4-turbo-2024-04-09 ` model

**Comment by X1AOX1A** [comment]
After setting the `CUSTOM_MODEL` environment variable to support `gpt-4-turbo`, it cannot enable the vision feature for image uploads.
