### ISSUE TITLE
[Bug] 默认prompt，knowledge cutoff 不准确

### ISSUE THREAD

**Issue by jiangying000** [ChatGPTNextWeb/ChatGPT-Next-Web#4529]
### Bug Description

"gpt-4-turbo-2024-04-09"

```
You are ChatGPT, a large language model trained by OpenAI.
Knowledge cutoff: 2021-09
Current model: gpt-4-turbo-2024-04-09
Current time: 4/17/2024, 7:01:09 AM
Latex inline: \\(x^2\\) 
Latex block: $$e=mc^2$$\n\n"
```

默认 prompt 里是 2021-09
应该是 2023-12

https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/23182033/1a4a6b90-7e85-47d4-904a-7b01a85d4568)

### Steps to Reproduce

选模型，对话

### Expected Behavior

应该是 2023-12

### Deployment Method

- [ ] Docker
- [x] Vercel
- [ ] Server

**Comment by QAbot-zh** [comment]
我记得新版本改过了呀？
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/dda1d9c2-f605-465c-8b9e-0f64e456a894)

**Comment by jiangying000** [comment]
同步代码后，发现已经修复了
