### ISSUE TITLE
[Feature Request]: 系统之后是否支持接入国内的开源大模型

### ISSUE THREAD

**Issue by xiezhongren** [ChatGPTNextWeb/ChatGPT-Next-Web#4531]
### Problem Description

目前我发现gpt-4-turbo-preview等大模型在针对企业信息这块 查中国境内的企业很多会查不到。

### Solution Description

建议平台支持国内的大模型的选择

**Comment by Dean-YZG** [comment]
[Feature] Plans to add model provider support · Issue #4030 · ChatGPTNextWeb/ChatGPT-Next-Web   在这个规划中，我们会逐步对主流的大模型进行支持
