### ISSUE TITLE
[Feature Request]: 为每个对话独立设置模型

### ISSUE THREAD

**Issue by koolca** [ChatGPTNextWeb/ChatGPT-Next-Web#4536]
### Problem Description

目前调用不同模型的步骤稍显麻烦

### Solution Description

不同的聊天对话使用不同模型

**Comment by QAbot-zh** [comment]
没太懂，“不同的聊天对话使用不同模型”，现在不就是吗？你期待的交互是什么样的，能比现在的切换模型更方便？

**Comment by koolca** [comment]
> 没太懂，“不同的聊天对话使用不同模型”，现在不就可以吗？你期待的交互是什么样的，能比现在的切换模型更方便？

现在切换模型会影响到所有对话，我希望能为对话设置不同模型

**Comment by QAbot-zh** [comment]
你不是在这里设置当前对话的模型的吗？设置页的模型是全局设置，这里是对话设置

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/a1bb0bb8-3a7e-4cab-9ea8-d8e794202736)
