### ISSUE TITLE
API-KEY

### ISSUE THREAD

**Issue by qqqqxun** [ChatGPTNextWeb/ChatGPT-Next-Web#4546]
### Bug Description

部署之后按照vercle的文档添加了api-key,但无法给出回答，是否因为仅支持GPT4的key

### Steps to Reproduce

1fork  2vercle部署 3 配置code和密码，添加OPENAI_API_KEY和密钥 4部署  5登录浏览器输入密码 6无法出现回复

### Expected Behavior

希望给出模型接口的详细的说明

### Screenshots

![屏幕截图 2024-04-19 164701](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/125483283/bdca9b16-61c2-44d8-91b1-98871de54b01)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

window10

### Desktop Browser

chrome

### Desktop Browser Version

89.0

### Additional Logs

如何对接预训练模型

**Comment by QAbot-zh** [comment]
翻译一下报错呀哥，提示你key没额度了

**Comment by Skyminers** [comment]
我也遇到了这个问题，我已经持续使用接近一年了。额度和限制都是充足的，但是在今天突然出现了这个报错
<img width="318" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/23115950/8edeb6e9-643c-4914-b7d2-66f8437cbc52">

**Comment by QAbot-zh** [comment]
> 我也遇到了这个问题，我已经持续使用接近一年了。额度和限制都是充足的，但是在今天突然出现了这个报错 <img alt="image" width="318" src="https://private-user-images.githubusercontent.com/23115950/324166094-8edeb6e9-643c-4914-b7d2-66f8437cbc52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDM2ODcsIm5iZiI6MTcxMzYwMzM4NywicGF0aCI6Ii8yMzExNTk1MC8zMjQxNjYwOTQtOGVkZWI2ZTktNjQzYy00OTE0LWI3ZDItNjZmODQzN2NiYzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA4NTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyOGE3NzIwNTk4NzA2NDBhMTI4ZmY5NWVmMGViMTk2N2U4MDdjZmVlNDc4NzQ4Y2ZmNDU4MDI2YWM2OTFlNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tk3WaC7S6gqwvFwy8C0uwuSwIUbpCRtidoDjqkVaP_0"> <img alt="image" width="681" src="https://private-user-images.githubusercontent.com/23115950/324166133-28087b14-7c4c-4ee6-bfd8-4fbcb5d0c8b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDM2ODcsIm5iZiI6MTcxMzYwMzM4NywicGF0aCI6Ii8yMzExNTk1MC8zMjQxNjYxMzMtMjgwODdiMTQtN2M0Yy00ZWU2LWJmZDgtNGZiY2I1ZDBjOGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA4NTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZjQ5NjQ1Nzk3YTllNmY0YTVkZTJmNDVkZDEyZGIyMzg2ZGUwYTc3Y2MzODA1MjVjODliNTRjMmU3ZWU3ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fd1TMXiZ5atZYelP6ysOTaXK4fUdfZWZNFzyOSrW6B4"> 我尝试通过搜索的方式来解决，但是没有人给出 “检查使用的额度是否超过限制” 之外的办法。


https://platform.openai.com/docs/api-reference/making-requests
用curl或者别的方式直接请求看看：
```
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'
```

**Comment by Skyminers** [comment]
<img width="859" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/23115950/049329cc-3176-4bcc-8cf5-eb7bc10036b1">
仍然会得到相同的错误，看来是 OpenAI 的问题

**Comment by Dean-YZG** [comment]
看来是的，

> ### Bug Description
> 部署之后按照vercle的文档添加了api-key,但无法给出回答，是否因为仅支持GPT4的key
> 
> ### Steps to Reproduce
> 1fork 2vercle部署 3 配置code和密码，添加OPENAI_API_KEY和密钥 4部署 5登录浏览器输入密码 6无法出现回复
> 
> ### Expected Behavior
> 希望给出模型接口的详细的说明
> 
> ### Screenshots
> ![屏幕截图 2024-04-19 164701](https://private-user-images.githubusercontent.com/125483283/323893662-bdca9b16-61c2-44d8-91b1-98871de54b01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTAxODksIm5iZiI6MTcxMzc0OTg4OSwicGF0aCI6Ii8xMjU0ODMyODMvMzIzODkzNjYyLWJkY2E5YjE2LTYxYzItNDRkOC05MWIxLTk4ODcxZGU1NGIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwMTM4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWE3N2I2NzBlYzM2NWYyMmNkNmY0OTVhZWI2YjU3MzZhOWQ1ZmJlODdmYWJkYWIxZDI1MWMyNTYyMjJhMjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jTHg-O-K6-J1EsUdJEMTGO_pVAm99CjTyysTItS6YFY)
> 
> ### Deployment Method
> * [ ]  Docker
> * [x]  Vercel
> * [ ]  Server
> 
> ### Desktop OS
> window10
> 
> ### Desktop Browser
> chrome
> 
> ### Desktop Browser Version
> 89.0
> 
> ### Smartphone Device
> _No response_
> 
> ### Smartphone OS
> _No response_
> 
> ### Smartphone Browser
> _No response_
> 
> ### Smartphone Browser Version
> _No response_
> 
> ### Additional Logs
> 如何对接预训练模型

应该是额度的问题，充值后应该会接的哈~~
