### ISSUE TITLE
[Feature Request]: 是否有计划支持一键清空对话

### ISSUE THREAD

**Issue by chengfengfengwang** [ChatGPTNextWeb/ChatGPT-Next-Web#4549]
### Problem Description

每次使用我都会新开一个对话，隔一段时间就需要手动挨个删除对话。总在一个对话里的话，上下文其实是无用的，而且会浪费token。所以是否有清空对话的功能计划？

### Solution Description

每次使用我都会新开一个对话，隔一段时间就需要手动挨个删除对话。总在一个对话里的话，上下文其实是无用的，而且会浪费token。所以是否有清空对话的功能计划？

**Comment by Dean-YZG** [comment]
感谢提出的建议，可以使用清除上下文功能，使用这个功能后，会打一个点，再发起新的提问，则不会携带打点之前的历史对话
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/138353356/622f31b7-1074-4bbd-8a57-ee86bf6537c0)

**Comment by QAbot-zh** [comment]
你还可以通过对话缩略图标来清除该对话

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/3d0fb5f1-fc32-4162-9743-fcb0b0dd33ea)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/18e41076-9fa7-440a-9cea-ad97b8069787)

**Comment by quloos** [comment]
清除上下文，是否会清除存储在面具里的提示词呢？
