### ISSUE TITLE
[Feature Request]: 如何添加除openai以外的api接口

### ISSUE THREAD

**Issue by Gao-yu-1214** [ChatGPTNextWeb/ChatGPT-Next-Web#4553]
### Problem Description

默认使用的是api.openai.com，我应该如何改变这一现状

### Solution Description

在docker部署的时候环境变量可以添加

**Comment by 2936401755** [comment]
BASE_URL

**Comment by Dean-YZG** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/138353356/cc1a5fe1-5767-474b-8e87-c9c240e0a606)
you can use this env var to  suit your needs
