### ISSUE TITLE
[Feature Request] api setting 快捷设置

### ISSUE THREAD

**Issue by lqyiwwx** [ChatGPTNextWeb/ChatGPT-Next-Web#4555]
### Bug Description

请问，我在oneapi中发现了，可以快捷访问chatgpt-next-web的官方链接，并且通过api可以做到快速设置url和key，请问说明文档没有写出可以带什么参数，可以完成快速设置的功能麻烦提供一些可以配置那些参数，以及参数具体的含义？

### Steps to Reproduce

无

### Expected Behavior

无

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

**Comment by Dean-YZG** [comment]
nextchat 页面会读取地址url上携带的参数，目前支持的参数包括 `settings`，值是一个json，包括两个字段`key`(设置openaiApiKey，您的openai ApiKey)`url`（openaiUrl，api方式调用大模型的接口），其他的参数还包括 `fill`（快速输入，一个字符串，直接显示在nextchat对话框中），`submit`（快速发起提问，一个字符串，页面上直接触发提问），`code`（访问密码，非必需）

**Comment by lqyiwwx** [comment]
> 这个是fast_link，不是什么api控制，只支持三个参数设置code、key和url，没了

请教一下大佬，key 和 url 我测试能正常配置，code做不到？还是就能配置key和url？

**Comment by lqyiwwx** [comment]
> nextchat 页面会读取地址url上携带的参数，目前支持的参数包括 `settings`，值是一个json，包括两个字段`key`(设置openaiApiKey，您的openai ApiKey)`url`（openaiUrl，api方式调用大模型的接口），其他的参数还包括 `fill`（快速输入，一个字符串，直接显示在nextchat对话框中），`submit`（快速发起提问，一个字符串，页面上直接触发提问），`code`（访问密码，非必需）

感谢回复

**Comment by lqyiwwx** [comment]
希望可以增加更多参数，这样可以通过第三方接口免配置进入页面直接聊天！！！
