### ISSUE TITLE
[Feature Request]: 如何设置默认的模型

### ISSUE THREAD

**Issue by WanFengQC** [ChatGPTNextWeb/ChatGPT-Next-Web#4558]
### Problem Description

我将模型列表设置为了CUSTOM_MODELS=-all,+gpt-3.5-turbo-0125,+gpt-4-0613,+gpt-4-turbo-preview，也就是只有+gpt-3.5-turbo-0125,+gpt-4-0613,+gpt-4-turbo-preview，我想要打开网页时默认使用的模型为gpt-3.5-turbo-0125，但现在默认使用的模型为gpt-4-0613，似乎是参照列表的顺序决定的，并且在查看了环境变量后没有发现相关的参数可以修改默认模型

### Solution Description

添加一个环境变量，可以便捷的修改默认模型

**Comment by Dean-YZG** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4545
社区的小伙伴最近帮助完善了设置默认模型功能，可以使用DEFAULT_MODEL  env var 来设置默认模型
