### ISSUE TITLE
希望可以增加改变google api version的环境变量

### ISSUE THREAD

**Issue by htdohk** [ChatGPTNextWeb/ChatGPT-Next-Web#4559]
### Problem Description

如题，gemini 1.5 pro preview刚出来的时候可以直接调用，但是现在提示不可通过v1beta访问。但是好像并没有提供可以改变这个环境变量的方式。因为我是多设备访问的场景下使用，不想通过在浏览器端设置，而是通过环境变量预置

### Solution Description

no

**Comment by Dean-YZG** [comment]
感谢反馈，建议非常有价值，目前正在计划重构多模型适配相关的模块，完成重构之后会提供给用户更多的自由配置的空间
