### ISSUE TITLE
[Feature Request]: support different providers/endpoints for individual conversations.

### ISSUE THREAD

**Issue by atmomomo** [ChatGPTNextWeb/ChatGPT-Next-Web#4561]
### Problem Description

All conversations must use the same provider and endpoint.

### Solution Description

Allow different provider/endpoint for different conversations.

**Comment by Dean-YZG** [comment]
Thank you for your feedback, we will take your suggestion seriously

**Comment by Dean-YZG** [comment]
but, nextchat has supported switch models in a session ,so you can config  providers eg:Azure Google ro Anthropic through env vars to meet your needs

**Comment by Dean-YZG** [comment]
And you can config these providers in App
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/138353356/c7d8ae75-05f3-43da-ad60-c3a98adc07ab)

**Comment by atmomomo** [comment]
Many thanks!
