### ISSUE TITLE
[Feature Request]: 关于二次开发如何接入新的API

### ISSUE THREAD

**Issue by MagicH0le** [ChatGPTNextWeb/ChatGPT-Next-Web#4562]
### Problem Description

想问一下如何接入新的API，服务器上部署了一个LLM，主要想给我的LLM接口套下UI界面，有具体的操作或者文档吗？

### Solution Description

无

**Comment by QAbot-zh** [comment]
遵循 openai 的参数、响应结构和路由（v1/chat/completions），就可以套用了

**Comment by Dean-YZG** [comment]
你的LLM Api可以直接效仿 openai 的接口协议实现，然后，在部署nextchat应用的时候，在环境变量中设置BASE_URL指向你的LLM服务，在openai API协议的入参中，有一个model字段，标识的是你调用的模型名，这个model字段在你的LLM Api的接口实现中可以忽略掉
