### ISSUE TITLE
[Bug] webDav.UpStash云端同步失败

### ISSUE THREAD

**Issue by cacosub7** [ChatGPTNextWeb/ChatGPT-Next-Web#4563]
### Bug Description

在使用正确的坚果云WebDav / UpStash配置后，检查可用性看上去没问题，但是点击同步后均失败
## WebDav
看上去跨域直接报错了，如果要配置这个代理的话 具体教程/参考有么
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/46550268/d59b0580-917a-4f3e-b93f-a683be5fa072)
## UpStash
chatnextweb的前端代码没有响应这个重定向吗？
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/46550268/68be9aee-4747-4da7-9941-8717ef3c9a0f)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/46550268/082a7a3e-cf83-44ab-9a5b-e9c65cee45a7)

### Steps to Reproduce

如题

### Expected Behavior

保存正确的WevDav/UpStash 配置后能够正常访问

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop Browser

Chrome

**Comment by cacosub7** [comment]
# Durrent version  
2.11.3

**Comment by Dean-YZG** [comment]
使用的是最新版本么？nextchat应用是部署在vercel了是么？webdev的配置是什么有截图么？

**Comment by cacosub7** [comment]
> 使用的是最新版本么？nextchat应用是部署在vercel了是么？webdev的配置是什么有截图么？

1.使用目前最新的[2.11.3](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.11.3)
2.部署在vercel
3.webdav用的坚果云账户，代理没有配
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/46550268/e4cbc3b2-5be5-40d6-b9e0-a5083fc26f24)

**Comment by davidw0374** [comment]
Cloud Data Sync does not work.
1.version: 2.11.3
2.windows 10 client
3.upstash protocol, and no proxy config.
  a.watching from client:
     check connection is OK
     sync is OK
  b.watching from upstash admin platform,:
     10 reads , 0 writes, 0 byte storage

**Comment by haso2007** [comment]
已知上一版本是没有这个问题的，我同步后部署到vercel upstash部署就就不行了。

**Comment by xcpky** [comment]
我用UpStash，也是同步失败，chat-next的版本是v2.12.2，部署在vercel上

**Comment by rooben-me** [comment]
@xcpky 我也遇到了同样的问题，可以尝试这个分支 #4610

**Comment by starsead** [comment]
> @xcpky 我也遇到了同样的问题，可以尝试这个分支 #4610

你说的这个分支在 vercel 怎么部署？

**Comment by rooben-me** [comment]
@starsead https://github.com/rooben-me/ChatGPT-Next-Web/tree/fix-sync

Can you use my fork

**Comment by 80imike** [comment]
> 我用UpStash，也是同步失败，chat-next的版本是v2.12.2，部署在vercel上


我也遇到这个问题 docker 部署 用的 2.12.2
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4658

**Comment by Jiayou-Chao** [comment]
在2.12.4版本遇到同样的问题，使用webdav连通性良好，使用其它软件也可以连接，但是点击同步就显示同步失败。

**Comment by sandyplus** [comment]
我用的2.12.3的web版本，也遇到同样的问题。设置好webdav之后，连通性良好，但是点击同步就显示同步失败。更换了webdav的设置，也是同步失败，因此肯定不是webdav的设置问题。

**Comment by sandyplus** [comment]
我用的2.12.3的web版本，也遇到同样的问题。设置好webdav之后，连通性良好，但是点击同步就显示同步失败。更换了webdav的设置，也是同步失败，因此肯定不是webdav的设置问题。

**Comment by eric-easyhealth** [comment]
I also encounted the same issue, with version 2.15.2 on vercel, i'm pretty sure the webdav works.
