### ISSUE TITLE
Environment Variables in vercel for all models for latest version?

### ISSUE THREAD

**Issue by johnfelipe** [ChatGPTNextWeb/ChatGPT-Next-Web#4565]
![SNAG-0170](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/428820/d8221990-6d19-49a4-b061-1fe45487a5cd)

but now we have Claude model in differents version

wich one is variable?

**Comment by Dean-YZG** [comment]
We are refactoring multi Models, before long, nextchat will allow user to config any model from any provider

**Comment by Dean-YZG** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4030
