### ISSUE TITLE
[Feature Request]:  Add File Upload Capability and Support for Latest GPT Version

### ISSUE THREAD

**Issue by f1h0** [ChatGPTNextWeb/ChatGPT-Next-Web#4572]
### Problem Description

I often find myself limited by the inability to directly share files within NexChat. Whether it's a text document, an image, or an audio file, I have to utilize other services to share these files and then reference them in the chat. This extra step is inconvenient and disrupts the flow of conversation.

### Solution Description

I would like NexChat to introduce a feature that allows users to upload files directly into the chat interface. This could be implemented with a simple drag-and-drop functionality or through traditional file selection dialogs. Once uploaded, it would be highly beneficial if the AI, such as GPT-4 or future versions, could analyze the contents of these files and provide responses or actions based on the data received.

### Alternatives Considered

An alternative solution would be to integrate NexChat with other file-sharing services, but this would still not provide the seamless experience that native file upload functionality would offer.

### Additional Context

File sharing is a fundamental part of modern communication platforms. By integrating this feature, NexChat could significantly enhance user experience and expand use-case scenarios, especially in professional settings where sharing documents is commonplace.

**Comment by fred-bf** [comment]
It in the roadmap, duplicated to https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4030
