### ISSUE TITLE
[Feature Request]: Integration of the Latest GPT Model Released on 04.09 version

### ISSUE THREAD

**Issue by f1h0** [ChatGPTNextWeb/ChatGPT-Next-Web#4573]
### Problem Description

Staying up-to-date with the latest advancements in AI is crucial for providing users with the best possible experience. NexChat currently does not support the latest GPT model released by OpenAI on 04.09

### Solution Description

I propose that NexChat integrates the latest GPT model as soon as possible to leverage improved language understanding and generation capabilities. This update will ensure that users benefit from the most recent enhancements in AI technology for their conversations and inquiries.

### Alternatives Considered

While waiting for integration, an interim solution could be to provide users with information on when they might expect the new model to be available on NexChat.

### Additional Context

The prompt release of updates following new model releases by OpenAI is crucial for maintaining user trust and satisfaction with NexChat's service quality.

**Comment by QAbot-zh** [comment]
The latest GPT model released by OpenAI on April 29 ? Today is April 26.  You mean gpt-4-turbo-20240409 ?

**Comment by f1h0** [comment]
> The latest GPT model released by OpenAI on April 29 ? Today is April 26. You mean gpt-4-turbo-20240409 ?

04.09 fixed it. I've been working hard for days.

**Comment by fred-bf** [comment]
@f1h0 gpt-4-turbo point to gpt-4-turbo-2024-04-09(refer: https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4)
