### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JimmyPowell** [ChatGPTNextWeb/ChatGPT-Next-Web#4574]
### Bug Description

报错：QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'chat-next-web-store' exceeded the quota.

### Steps to Reproduce

我一直在使用nextweb进行图片识别，但是今天打开软件的时候报错如上

### Expected Behavior

我询问了gpt，得到的回答是数据量超出了默认值，我希望能够给出一个人性化的自定义数据量大小的方法

### Screenshots

![屏幕截图 2024-04-26 113808](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/139760437/f53516f9-3ce6-4631-8207-58d20a095dac)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

win 11

**Comment by JimmyPowell** [comment]
这个问题出现在windows桌面端2.11.3版本

**Comment by fred-bf** [comment]
Hi, its the storage is limited by the browser you've been using. You can try clear the website's local storage, which will also remove your chat history

**Comment by RinggaV** [comment]
我也遇到了这个问题, 发生这个问题的时候我向其发送了一个简单的提问, 但此时左侧回复出现了两个正在思考的聊天气泡;
我是通过开发者工具->应用程序->本地存储->NextChat->右键选中并删除了unfinished prompts? 可能是, 我记大不大清楚了, 而后刷新页面就恢复了, 且数据都在.
