### ISSUE TITLE
[Feature Request]: 允许存储/切换多个模型服务商

### ISSUE THREAD

**Issue by Zxilly** [ChatGPTNextWeb/ChatGPT-Next-Web#4575]
### Problem Description

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/31370133/26481bc1-f2a8-4ffd-b8c6-5e28c30d029c)
当前只能设置唯一的模型服务商

### Solution Description

允许设置存储多个不同的模型服务商，并允许在设置中快速切换

**Comment by guokun1998** [comment]
非常赞同，支持存储/切换模型来源很有用，希望能加上！

Very much agree, support to store / switch model sources is very useful, I hope to add!

**Comment by fred-bf** [comment]
duplicated to https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4030
