### ISSUE TITLE
[Bug] The environment variable GOOGLE-API_KEY has been set, but an error message will appear indicating Request failed

### ISSUE THREAD

**Issue by chenjiangbo** [ChatGPTNextWeb/ChatGPT-Next-Web#4578]
### Bug Description

The environment variable GOOGLE-API_KEY has been set, but an error message will appear indicating Request failed
ANTHROPIC-API_KEY is also the same

### Steps to Reproduce

1.visit vercel.com ,add environment variable GOOGLE-API_KEY
2.use nextchat get error

### Expected Behavior

want to use gemini

### Deployment Method

- [ ] Docker
- [x] Vercel
- [ ] Server

**Comment by fred-bf** [comment]
plz check you internet connection
