### ISSUE TITLE
想要使用chatgpt-next-web对本地llm接口进行调用，  在使用本地llm封装的接口时，想要更改chatgpt-next-web发送数据的封装格式，应该在哪里进行修改？[Bug] 

### ISSUE THREAD

**Issue by surviveMiao** [ChatGPTNextWeb/ChatGPT-Next-Web#4579]
### Bug Description

想要使用chatgpt-next-web对本地llm接口进行调用，  在使用本地llm封装的接口时，想要更改chatgpt-next-web发送数据的封装格式，应该在哪里进行修改？

### Steps to Reproduce

想要使用chatgpt-next-web对本地llm接口进行调用，  在使用本地llm封装的接口时，想要更改chatgpt-next-web发送数据的封装格式，应该在哪里进行修改？

### Expected Behavior

想要使用chatgpt-next-web对本地llm接口进行调用，  在使用本地llm封装的接口时，想要更改chatgpt-next-web发送数据的封装格式，应该在哪里进行修改？

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by fred-bf** [comment]
please config custom endpoint in settings page
