### ISSUE TITLE
Cloud Data Sync (upstash) does not work, Windows 10 client ,version: 2.11.3

### ISSUE THREAD

**Issue by davidw0374** [ChatGPTNextWeb/ChatGPT-Next-Web#4583]
### Bug Description

1.version: 2.11.3
2.Windows 10 client
3.upstash protocol, and no proxy config.
4.watching from client: 1.check connection is OK; 2.sync is OK
5.watching from upstash admin platform:10 reads , 0 writes, 0 byte storage

### Steps to Reproduce

N/A

### Expected Behavior

Cloud Data Sync is real OK 

### Screenshots

N/A

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows 10 Client

### Desktop Browser

NA

### Desktop Browser Version

NA

### Smartphone Device

N/A

### Smartphone OS

N/A

### Smartphone Browser

N/A

### Smartphone Browser Version

N/A

**Comment by haso2007** [comment]
same problem, but previous project work fine. Is a cros proxy reqruied?
