### ISSUE TITLE
[Feature Request]: 请问对话实际储存在哪里呢？

### ISSUE THREAD

**Issue by leshui1991** [ChatGPTNextWeb/ChatGPT-Next-Web#4586]
### Problem Description

我看很多人反应用WebDAV同步失败，能不能直接公布对话储存的位置，然后用其他网盘（onedrive或者百度）直接同步文件呢？

### Solution Description

有了实际的位置之后用mklink，连接到网盘在本地的映射？

**Comment by fred-bf** [comment]
The chat history is stored in the webpage localstorage

**Comment by Yniije** [comment]
> The chat history is stored in the webpage localstorage聊天记录存储在网页本地存储中

tks u，what can I do to find it？

**Comment by Zeyun-Deng** [comment]
> > > The chat history is stored in the webpage localstorage
> > 
> > 
> > tks u，what can I do to find it？
> 
> 不出意外的话本地的聊天记录应该存储在该文件下，里面有一个单文件存储着对话记录
> 
> C:\Users\NAME\AppData\Local\com.yida.chatgpt.next.web\EBWebView\Default\IndexedDB\http_tauri.localhost_0.indexeddb.blob

我找到了里边的文件，然而这个文件打开来似乎是乱码，应该使用什么打开方式读取？
