### ISSUE TITLE
[Bug] 使用非gpt.3.5的模型聊天导致无法自动总结内容

### ISSUE THREAD

**Issue by chengtx809** [ChatGPTNextWeb/ChatGPT-Next-Web#4587]
### Bug Description

我使用了[https://github.com/Harry-zklcdc/go-proxy-bingai](url)项目部署了newbing的代理api，
使用的模型列表如下：
-all,+gpt-4-turbo-preview,+gpt-4-vision-preview,+Precise-g4t,+Balanced-g4t,+Creative-g4t,+Precise-g4t-offline,+Balanced-g4t-offline,+Creative-g4t-offline,+Precise-g4t-18k,+Balanced-g4t-18k,+Creative-g4t-18k
但是无法总结聊天内容并自动写标题

### Steps to Reproduce

直接聊天，使用gpt-4-turbo-preview模型

### Expected Behavior

无法总结聊天内容并总结标题

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

**Comment by chengtx809** [comment]
初步看了看好像是app/constant.ts把总结模型写死了的问题

```
export const SUMMARIZE_MODEL = "gpt-3.5-turbo";
export const GEMINI_SUMMARIZE_MODEL = "gemini-pro";
```

**Comment by chengtx809** [comment]
我提交了pr来修复这个bug： #4588

**Comment by chengtx809** [comment]
> 这个issue我记得当初考虑的是gpt4系列模型价格非常贵，回退到3.5，在加入gemini的时候讨论过，具体的issue一时没找到

但是如果写死，我又不使用gpt-3.5的模型进行聊天，会导致无法总结：（
可能个人观点问题吧，我认为与其看着一堆“新的聊天”还不如花多点token，哭笑不得了属于是

**Comment by Dean-YZG** [comment]
目前看问题出在，通过环境变量禁用了  gpt-3.5-turbo，因此在nextchat proxy端，拒绝了所有调用gpt-3.5-turbo的请求 ，但是，gpt-3.5-turbo是 gpt 开头的所有模型的总结模型，因此，当使用gpt-* 模型的时候，无法进行总结，目前可以在 proxy侧，单独对 gpt-3.5-turbo 放开，使 对 gpt-3.5-turbo 的调用可以正常响应

**Comment by Dean-YZG** [comment]
目前，无法生成总结题目的情况会出现在使用 gpt-* 这类模型上，  gpt-3.5-turbo 是 gpt-* 这类模型的总结模型，但是，通过环境变量禁用 gpt-3.5-turbo 之后，nextchat proxy会拒绝一切调用 gpt-3.5-turbo 的请求，因此导致无法总结。
gpt-3.5-turbo禁用的情况下，希望仍然使用 gpt-3.5-turbo 生成总结，还是使用 『当前模型』进行总结？
> ### Bug Description
> 我使用了[https://github.com/Harry-zklcdc/go-proxy-bingai](url)项目部署了newbing的代理api， 使用的模型列表如下： -all,+gpt-4-turbo-preview,+gpt-4-vision-preview,+Precise-g4t,+Balanced-g4t,+Creative-g4t,+Precise-g4t-offline,+Balanced-g4t-offline,+Creative-g4t-offline,+Precise-g4t-18k,+Balanced-g4t-18k,+Creative-g4t-18k 但是无法总结聊天内容并自动写标题
> 
> ### Steps to Reproduce
> 直接聊天，使用gpt-4-turbo-preview模型
> 
> ### Expected Behavior
> 无法总结聊天内容并总结标题
> 
> ### Screenshots
> _No response_
> 
> ### Deployment Method
> * [ ]  Docker
> * [x]  Vercel
> * [ ]  Server
> 
> ### Desktop OS
> _No response_
> 
> ### Desktop Browser
> _No response_
> 
> ### Desktop Browser Version
> _No response_
> 
> ### Smartphone Device
> _No response_
> 
> ### Smartphone OS
> _No response_
> 
> ### Smartphone Browser
> _No response_
> 
> ### Smartphone Browser Version
> _No response_
> 
> ### Additional Logs
> _No response_

**Comment by chengtx809** [comment]
> 目前，无法生成总结题目的情况会出现在使用 gpt-* 这类模型上， gpt-3.5-turbo 是 gpt-* 这类模型的总结模型，但是，通过环境变量禁用 gpt-3.5-turbo 之后，nextchat proxy会拒绝一切调用 gpt-3.5-turbo 的请求，因此导致无法总结。 gpt-3.5-turbo禁用的情况下，希望仍然使用 gpt-3.5-turbo 生成总结，还是使用 『当前模型』进行总结？
> 
> > ### Bug Description
> > 我使用了[https://github.com/Harry-zklcdc/go-proxy-bingai](url)项目部署了newbing的代理api， 使用的模型列表如下： -all,+gpt-4-turbo-preview,+gpt-4-vision-preview,+Precise-g4t,+Balanced-g4t,+Creative-g4t,+Precise-g4t-offline,+Balanced-g4t-offline,+Creative-g4t-offline,+Precise-g4t-18k,+Balanced-g4t-18k,+Creative-g4t-18k 但是无法总结聊天内容并自动写标题
> > ### Steps to Reproduce
> > 直接聊天，使用gpt-4-turbo-preview模型
> > ### Expected Behavior
> > 无法总结聊天内容并总结标题
> > ### Screenshots
> > _No response_
> > ### Deployment Method
> > 
> > * [ ]   Docker
> > * [x]   Vercel
> > * [ ]   Server
> > 
> > ### Desktop OS
> > _No response_
> > ### Desktop Browser
> > _No response_
> > ### Desktop Browser Version
> > _No response_
> > ### Smartphone Device
> > _No response_
> > ### Smartphone OS
> > _No response_
> > ### Smartphone Browser
> > _No response_
> > ### Smartphone Browser Version
> > _No response_
> > ### Additional Logs
> > _No response_

我个人希望使用当前模型进行总结

**Comment by hiroi-sora** [comment]
我也有这个问题。
版本： `2.11.2`、`2.12.3` 都试过。
部署：Docker，未屏蔽`gpt-3.5-turbo`。
网页设置中，“自动生成标题”已勾选。
试过不同key、不同主机部署，均有该问题。
现象：无论使用什么模型，都无法生成标题。所有对话的标题都是“新的聊天”。
试过不同key、不同主机部署，均有该问题。（我用这项目很久了，似乎几个月前开始出现这种现象）

部署指令：
```
docker run -d -p 3003:3000  --restart always \
    -e BASE_URL=XXXX \
    -e OPENAI_API_KEY=XXXX \
    -e CODE=XXXX \
    -e ENABLE_BALANCE_QUERY=1 \
    -e DEFAULT_MODEL=gpt-4o \
    yidadaa/chatgpt-next-web
```

特例：如果故意使用不支持的模型（比如某个key不支持`gpt-4o`依然选该模型），使得返回报错，则可以触发标题总结。

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/56373419/cc59b666-5667-42df-99c7-fc8465834c1d)

**Comment by gitsang** [comment]
Related to [!3916](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3916)

**Comment by gitsang** [comment]
I believe that supporting configurable summary models is important, as enforcing a specific model will only lead to more issues (for instance, using `gpt-4o (Azure)` now still sends summary requests through the OpenAI API).

Additionally, using string prefix matching in this way is also very fragile, which could affect all future functionalities related to model naming. I think that, at the very least, the logic `if (currentModel.startsWith("gpt"))` should be removed.

---

我认为应该支持总结模型可配，强制模型只会带来更多的问题（比如使用 `gpt-4o (Azure)` 时仍然在用 openai 的 API 发送总结请求）

使用字符串匹配前缀的这种方式也非常的脆弱，这会导致后续所有与模型命名相关的功能都可能被这个匹配方式所影响。我认为无论如何，都至少应该删除 `if (currentModel.startsWith("gpt"))` 这段逻辑。
