### ISSUE TITLE
[Feature Request]: Gemini API safety settings not avalable

### ISSUE THREAD

**Issue by arunyagoojar** [ChatGPTNextWeb/ChatGPT-Next-Web#4592]
### Problem Description

Gemini API supports safety settings, but the app lacks safety settings controls. Integration would be valuable.

### Solution Description

https://ai.google.dev/gemini-api/docs/safety-settings

**Comment by Dean-YZG** [comment]
currentlly, we have followed the Gemini Safety settings, What else do we need to do, please tell us in detail, thanks

**Comment by i486** [comment]
@Dean-YZG 

> What else do we need to do, please tell us in detail, thanks

They are likely asking you to add these settings to NextChat, allowing users to adjust Safety settings directly within the application.

<img width="429" alt="safety_settings_ui" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/625325/66e51a23-a78c-44e9-9b5b-84c884b9e664">

Additionally, the gemini-1.5-pro model allows for a temperature setting range between 0 and 2, while NextChat only supports settings up to 1.

https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini
