### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by fleqing** [ChatGPTNextWeb/ChatGPT-Next-Web#4594]
### Bug Description

The newly released version number in release has not been modified and is still 2.11.3

### Steps to Reproduce

1.Modify version number

### Expected Behavior

Modify version number

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by davyzhu** [comment]
下载的版本号错了

**Comment by fred-bf** [comment]
@fleqing thanks for flagging, just updated the version in new release: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4595

Release:https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.12.2

**Comment by fleqing** [comment]
> @fleqing thanks for flagging, just updated the version in new release: #4595
> 
> Release:https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.12.2

Can you give me a contributor? If you can, thank you very much.
