### ISSUE TITLE
不支持groq兼容的openai endpoint[Bug] 

### ISSUE THREAD

**Issue by GitSarp** [ChatGPTNextWeb/ChatGPT-Next-Web#4599]
### Bug Description

想使用groq的llama3模型，docker-compose配置了
```  
- "BASE_URL=https://api.groq.com/openai/v1"
- "OPENAI_API_KEY=xxxxx"
```
使用模型后，返回错误：
{
  "error": {
    "message": "Unknown request URL: POST /openai/v1/v1/chat/completions. Please check the URL for typos, or see the docs at https://console.groq.com/docs/",
    "type": "invalid_request_error",
    "code": "unknown_url"
  }
}
next-web上Gemini模型正常使用；groq api在open-webui上使用正常

### Steps to Reproduce

1. docker-compose配置了
```  
- "BASE_URL=https://api.groq.com/openai/v1"
- "OPENAI_API_KEY=xxxxx"
```
2. 启动容器，访问异常
{
  "error": {
    "message": "Unknown request URL: POST /openai/v1/v1/chat/completions. Please check the URL for typos, or see the docs at https://console.groq.com/docs/",
    "type": "invalid_request_error",
    "code": "unknown_url"
  }
}

### Expected Behavior

希望可以使用groq的llama3模型

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by GitSarp** [comment]
> 把v1去掉试试，链接拼错了

去掉应该是可以了，谢谢！（模型是在变量中配置增加的）

**Comment by 523550914** [comment]
我有一样的问题，但是删掉v1还是不行
