### ISSUE TITLE
[Feature Request]: 完善gemini的支持

### ISSUE THREAD

**Issue by rtxneko** [ChatGPTNextWeb/ChatGPT-Next-Web#4600]
### Problem Description

目前使用脚本部署的话是强制要求填写openai key的
使用docker部署的话，填了google aistudio key后默认依然会请求openai的api

### Solution Description

额 docker部署时加个能选择的参数？

**Comment by pp6451303** [comment]
window版本和web版本都能用gemini，只有docker版本的用不了，提示{
  "error": true,
  "message": "Request failed"
}

怎么解决
