### ISSUE TITLE
[Bug] Customized endpoint settings are not working.

### ISSUE THREAD

**Issue by haso2007** [ChatGPTNextWeb/ChatGPT-Next-Web#4602]
### Bug Description

Customized endpoint settings are not working.all the local global endpoint proxy and apikey not work.

### Steps to Reproduce

every new sitting

### Expected Behavior

fix it like 2.11.3

### Deployment Method

- [X] Docker
- [X] Vercel
- [X] Server

**Comment by haso2007** [comment]
使用docker版本安装到本地，最新版本的用户端点运行是没有问题的

**Comment by Dean-YZG** [comment]
可以提供一下使用的app版本和错误截图么？
