### ISSUE TITLE
[Bug] v2.12.2 使用 url settings 参数配置地址和密钥之后没有自动启动自定义接口选项

### ISSUE THREAD

**Issue by ShinChven** [ChatGPTNextWeb/ChatGPT-Next-Web#4609]
### Bug Description

使用 url settings 参数配置地址和密钥之后没有自动启动自定义接口选项，因此在配置以后无法非上使用。

### Steps to Reproduce

1. 在全新用户的浏览器标签地址栏输入地址和配置参数
2. 点击确认地址和密钥
3. 输入消息
4. 返回密码不正确或者为空的错误

### Expected Behavior

自动启用自定义接口选项

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by ShinChven** [comment]
回滚到 v2.11.3 或者以前的版本可以临时解决这个问题。

**Comment by Dean-YZG** [comment]
感谢反馈，会尽快解决

**Comment by ShinChven** [comment]
测试了 v2.12.3 已经修复此问题。
