### ISSUE TITLE
[Bug] GEMINI_SUMMARIZE_MODEL

### ISSUE THREAD

**Issue by QAbot-zh** [ChatGPTNextWeb/ChatGPT-Next-Web#4611]
### Bug Description

gemini 系列模型并不都是以gemini-pro为前缀，应该修改GEMINI_SUMMARIZE_MODEL的适用条件，如：currentModel.startsWith("gemini")

```
function getSummarizeModel(currentModel: string) {
  // if it is using gpt-* models, force to use 3.5 to summarize
  if (currentModel.startsWith("gpt")) {
    return SUMMARIZE_MODEL;
  }
  if (currentModel.startsWith("gemini-pro")) {
    return GEMINI_SUMMARIZE_MODEL;
  }
  return currentModel;
}
```

### Steps to Reproduce

调用 gemini-1.5-pro 模型将不会使用 GEMINI_SUMMARIZE_MODEL 进行总结

### Expected Behavior

调用 gemini 系列模型都使用 GEMINI_SUMMARIZE_MODEL 进行总结

### Deployment Method

- [X] Docker
- [X] Vercel
- [ ] Server

**Comment by Dean-YZG** [comment]
可以说一下原因么？

**Comment by QAbot-zh** [comment]
> 可以说一下原因么？

因为 gemini 的模型名称并不是都以 “gemini-pro” 开头，早期只有gemini-pro和gemini-pro-vision，但现在新模型已经不符合这个规律了
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/de0f2fc7-17a2-43a4-b1d2-f6e5b368a66b)

设置 GEMINI_SUMMARIZE_MODEL 本意应该是使用它来对所有的 gemini 模型的会话进行总结对吧，所以应该根据新的模型命名调整判断条件了。实际上 Nextchat 在其他判定是否gemini类型的地方其实已经修改过了，只是总结模型这里留了一个历史遗留问题。

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/6bce8825-b7b1-425e-a9ec-887df8cc2ca8)

**Comment by Dean-YZG** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4625
