### ISSUE TITLE
[Bug] home.nextapi.fun上没有gpt-4-vision-preview和claude等模型可以选

### ISSUE THREAD

**Issue by AUSERGEE** [ChatGPTNextWeb/ChatGPT-Next-Web#4619]
### Bug Description

https://home.nextapi.fun/ 上创建key，没有gpt-4-vision-preview和claude等模型可以选

### Steps to Reproduce

1.创建key
2.选择模型

### Expected Behavior

有gpt-4-vision-preview和claude等模型可以选

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

Window10

### Desktop Browser

Chrome

### Additional Logs

无

**Comment by Dean-YZG** [comment]
Can you describe it in detail? It is best to include information such as screenshots

**Comment by fred-bf** [comment]
please use app.nextchat.dev or selfhosted NextChat

**Comment by AUSERGEE** [comment]
> Can you describe it in detail? It is best to include information such as screenshots

Like this screenshots, when creating a key on the https://home.nextapi.fun/ interface, there are no models like gpt-4-vision-preview and claude available to choose.
![企业微信截图_1715044941278](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/22318843/9b9d2e84-f05f-4b04-a93b-3411b323fb21)
