### ISSUE TITLE
[Bug] fix message error

### ISSUE THREAD

**Issue by QAbot-zh** [ChatGPTNextWeb/ChatGPT-Next-Web#4621]
### Bug Description

仍然是之前的问题，可能之前没有表述清楚，实际上该issue涉及的问题还没有完全解决就被关掉了。再次表述问题，希望该问题得到关注。
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4443#issue-2224967161

由于claude模型对于消息队列中第一条消息的role有严格的限制（ https://docs.anthropic.com/claude/reference/messages_post ），而nextchat在根据“附带历史消息数”和“单次最大恢复限制”来处理历史消息时，没有针对性处理，导致很容易发生第一条消息的role是“assistant”（因为提问的“user”消息从消息队列里被弹出了）
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/97d5dff0-4709-447c-a629-d37be858683a)

nextchat 对历史消息进行处理，产生的不被claude接受的“错误”消息：
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/97eb28f7-bfdc-48cc-8766-204ce63c4a36)

无法得到正确的响应：
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/126a93cb-6a7a-4a8b-a2f2-92019138b3a5)

### Steps to Reproduce

调低单次最大回复、增加附带历史消息数、进行容易引发长回复的提问，就很容易触发该现象

### Expected Behavior

消息队列保持第一条消息的角色为system或user，禁止出现首条消息的角色为 assistant

### Deployment Method

- [X] Docker
- [X] Vercel
- [ ] Server

**Comment by Dean-YZG** [comment]
非常感谢反馈，会尽快处理

**Comment by Dean-YZG** [comment]
已修复 https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4625

**Comment by QAbot-zh** [comment]
Thanks !
