### ISSUE TITLE
[Feature Request]: 你好，请问windows 客户端的ChatGPT-Next-Web 是用什么工具打包的，体积还挺小的

### ISSUE THREAD

**Issue by egomoor2023** [ChatGPTNextWeb/ChatGPT-Next-Web#4629]
### Problem Description

你好，请问windows 客户端的ChatGPT-Next-Web 是用什么工具打包的，体积还挺小的
可以告诉我吗？

### Solution Description

求助

**Comment by lwd-temp** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/.github/workflows/app.yml

**Comment by frostime** [comment]
tauri ，一个基于 Rust 的 Electron 替代品。

**Comment by egomoor2023** [comment]
> tauri ，一个基于 Rust 的 Electron 替代品。

thanks
