### ISSUE TITLE
[Feature Request]: Copy, edit, delete, and pin button on the bottom of the chat response

### ISSUE THREAD

**Issue by nolepguy** [ChatGPTNextWeb/ChatGPT-Next-Web#4638]
### Problem Description

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/157486295/f376d8a5-88bc-41eb-a33a-a686da6c5e13)
Im always frustrated when I have long chat response, and when I want to edit/delete the response, I have to scroll up and choose the edit/delete for the response

### Solution Description

The Copy, Edit, Delete button should be on top  and also on the bottom of the chat response.

**Comment by Dean-YZG** [comment]
in the v3 of nextchat, the message action buttons is placed on the bottom of the chat message

**Comment by Dean-YZG** [comment]
welcome to use the v3, and put forward valuable suggestions
