### ISSUE TITLE
[Feature Request]: 请教怎样在NextChat中使用Deepseek V2的API

### ISSUE THREAD

**Issue by haso2007** [ChatGPTNextWeb/ChatGPT-Next-Web#4643]
### Problem Description

Deepseek V2情能突出，响应很快，关键是价格很低

### Solution Description

实现模型调用

### Additional Context

暂无

**Comment by QAbot-zh** [comment]
deepseek 和 openai 格式兼容，直接填就好，接口地址填 https://api.deepseek.com

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/9141bd8f-d579-430b-8ecc-66879c6c9270)

**Comment by sadkga** [comment]
但是我还是返回 模型不存在
![17157796066351715779605649.png](https://gitee.com/sadkga/cartographic-bed/raw/master/17157796066351715779605649.png)

**Comment by QAbot-zh** [comment]
不能啊，我直接能用嘞

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/bdbad4ef-8eda-4ef2-9b8c-3aa5436b22a2)

![Clip_2024-05-15_21-36-17](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/f01195df-4418-4124-b82b-622ccab78a37)

**Comment by Rustieo** [comment]
模型名字填deepseek-chat, deepseek-coder,不要瞎写

**Comment by haso2007** [comment]
我也能用了，如果是关于编程的使用coder的更好用。不过免费的gpt4o 都有了，还要什么自行车？

**Comment by Rustieo** [comment]
> 我也能用了，如果是关于编程的使用coder的更好用。不过免费的gpt4o 都有了，还要什么自行车？

但是我用的是wrap连不上gpt,哭力

**Comment by MichaelYeung2004** [comment]
> 但是我还是返回模型不存在 ![17157796066351715779605649.png](https://camo.githubusercontent.com/faa53380fccb77fcbfe2770f63a480bbaa4bcfb05e5323b9fcbfad1b935b5564/68747470733a2f2f67697465652e636f6d2f7361646b67612f636172746f677261706869632d6265642f7261772f6d61737465722f31373135373739363036363335313731353737393630353634392e706e67) ![17157798896421715779888832.png](https://camo.githubusercontent.com/97293daccf5e31863b46762d69c4def926418f37726e1b01b7482fcfaeb28de7/68747470733a2f2f67697465652e636f6d2f7361646b67612f636172746f677261706869632d6265642f7261772f6d61737465722f31373135373739383839363432313731353737393838383833322e706e67)

请问怎么解决的
