### ISSUE TITLE
[Feature Request]: 支持配置 Google Fonts 镜像地址

### ISSUE THREAD

**Issue by CH3CHO** [ChatGPTNextWeb/ChatGPT-Next-Web#4655]
### Problem Description

NextChat 在访问时会从 Google Fonts 加载字体信息。由于众所周知的原因，中国大陆访问 Google Fonts 的官方地址 https://fonts.googleapis.com 会有一些困难，导致访问页面时报“Internal Server Error”。

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/2909796/89be745a-0a97-4ee5-b7ef-5876cae1f291)

### Solution Description

支持通过环境变量自定义镜像地址，例如：
- 谷歌官方镜像：https://fonts.font.im
- 上海交通大学镜像：https://google-fonts.mirrors.sjtug.sjtu.edu.cn

**Comment by sanbei011** [comment]
That's true, but mine doesn't have that problem

**Comment by Dean-YZG** [comment]
Thank you for your feedback, we will adopt the suggestion
