### ISSUE TITLE
[Feature Request]: 在arm64的linux环境中的客户端应该如何打包呢，release中没有支持arm64的

### ISSUE THREAD

**Issue by jiangsasa** [ChatGPTNextWeb/ChatGPT-Next-Web#4656]
### Problem Description

由于设备原因，无法使用docker，如何打包一个arm64的Linux可执行文件呢

### Solution Description

打包一个arm架构的客户端

**Comment by zhiwen95** [comment]
use tauri, see document
https://tauri.app/v1/api/js/os/
https://tauri.app/v1/guides/building/linux

**Comment by lloydzhou** [comment]
计划增加linux arm的打包，我自己作为开发者，使用的环境就是`archlinux arm`

**Comment by lloydzhou** [comment]
# [v2.15.1](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.15.1) 新增arm.deb



![image](https://github.com/user-attachments/assets/89eefc21-3490-40e0-839a-bb94d4ce1c0e)
