### ISSUE TITLE
[Bug] UpStash 同步失败

### ISSUE THREAD

**Issue by 80imike** [ChatGPTNextWeb/ChatGPT-Next-Web#4658]
### Bug Description

 docker 部署 用的 2.12.2

按文档配置后
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/docs/synchronise-chat-logs-cn.md

检查可用性是正常的

<img width="876" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/1665201/bf20af68-f6ed-49f7-b74c-7c22d9246f8c">

同步报错

<img width="1479" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/1665201/140dae05-091f-4ed3-bb4c-8d138a4bd7f9">

请问有大佬遇到个这个问题吗？

### Steps to Reproduce

UpStash 同步失败

### Expected Behavior

UpStash 同步正常

### Deployment Method

-  Docker

**Comment by rooben-me** [comment]
@80imike Can you try this pr #4610

**Comment by 80imike** [comment]
> @80imike Can you try this pr #4610

不错，这个 pr 解决了  UpStash 同步问题

<img width="759" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/1665201/5900a297-ebed-45a1-9484-6b5f2f7138b3">


但 webdav 方式还是失败

<img width="576" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/1665201/9d7a12ad-22a5-4686-b73a-9a6ee98a0db5">

**Comment by rooben-me** [comment]
If you want webdav, I can fix it. 

Personally I don't use webdav that's why never tried it.

**Comment by Why-SVIP** [comment]
> > @80imike Can you try this pr #4610
> 
> 不错，这个 pr 解决了 UpStash 同步问题
> 
> <img alt="image" width="759" src="https://private-user-images.githubusercontent.com/1665201/329756721-5900a297-ebed-45a1-9484-6b5f2f7138b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDI1NTQsIm5iZiI6MTcxNTQ0MjI1NCwicGF0aCI6Ii8xNjY1MjAxLzMyOTc1NjcyMS01OTAwYTI5Ny1lYmVkLTQ1YTEtOTQ4NC02YjVmMmY3MTM4YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMTU0NDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBhYWJiMTlmODFjMTBmMTZlYjM1YzM1ZmFmY2NhN2NlN2JiNGRhMjViZjU4ZGI4ZDY4NWNiM2MyZjBiYTc0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Lxh7PQbcmoSu6UCr_IzH34mm1rkBcVnoblNwlmDayis">
> 但 webdav 方式还是失败
> 
> <img alt="image" width="576" src="https://private-user-images.githubusercontent.com/1665201/329756952-9d7a12ad-22a5-4686-b73a-9a6ee98a0db5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDI1NTQsIm5iZiI6MTcxNTQ0MjI1NCwicGF0aCI6Ii8xNjY1MjAxLzMyOTc1Njk1Mi05ZDdhMTJhZC0yMmE1LTQ2ODYtYjczYS05YTZlZTk4YTBkYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMTU0NDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk4MDE2MDMxOWViMTBlM2FmMWRjOWMwNDNlNGMxY2VlMzRjNmFmMjFlODAxNzIxOGFlZjc5YWE3YzA1ZmUzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m6BQev-vNHHq1ZW5qBjDeYpo8fD6dO42bnk9jyWSDCQ">

兄弟，为什么我的还不行，版本也是2.12.2，我照着教程设置，把REST API需要的数据复制进去，启用代理是默认打开的，代理地址填写什么，我空着的，检查同步也正确，点同步按钮就一直同步失败

**Comment by rooben-me** [comment]
@80imike it is a problem with the code that's not a problem on your side

**Comment by Why-SVIP** [comment]
> @80imike it is a problem with the code that's not a problem on your side

这句话的意思是等作者修复吗？我英语不好

**Comment by Why-SVIP** [comment]
> @80imike it is a problem with the code that's not a problem on your side

还有一个问题 /api/cors/ 是怎么设置的，我使用的是VPS

**Comment by Scribing** [comment]
> > @80imike it is a problem with the code that's not a problem on your side
> 
> 还有一个问题 /api/cors/ 是怎么设置的，我使用的是VPS

API代码有问题，等发新版或者自己编译，调设置没用的

**Comment by Why-SVIP** [comment]
> > > @80imike it is a problem with the code that's not a problem on your side
> > 
> > 
> > 还有一个问题 /api/cors/ 是怎么设置的，我使用的是VPS
> 
> API代码有问题，等发新版或者自己编译，调设置没用的

好的 谢谢

**Comment by 80imike** [comment]
> @80imike If you want webdav, I can fix it.
> 
> Personally I don't use webdav that's why never tried it.

Thank you, it would be great if you could fix it. Could you provide me with a PR address once the fix is complete? @rooben-me
