### ISSUE TITLE
[Help] 我把这个项目fork下来之后，更换了我自己接口，使用axios，接口是没有问题的，正常流式返回，但是我本地打印出来是一次性出来的，但是我部署到服务器上又是好的，甚至我只是更改了项目原本的fetch的接口路径和传参，本地也是不行，是为什么呢，可以解答一下吗

### ISSUE THREAD

**Issue by wisdomlsh** [ChatGPTNextWeb/ChatGPT-Next-Web#4661]
### Bug Description

希望能够流式返回

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/116431228/857ccb13-1ae7-49ae-a817-804da640d225

### Steps to Reproduce

正常问答

### Expected Behavior

希望流式返回

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

mac M

### Desktop Browser

chrome

### Desktop Browser Version

124.0.6367.119

**Comment by Dean-YZG** [comment]
您的接口支持event-source么？有接口响应信息的截图么？

**Comment by wisdomlsh** [comment]
是这样的
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/116431228/b9ca7c32-f2e7-4e68-a249-831ed1b29bab)

**Comment by wisdomlsh** [comment]
因为这个接口我在其他的AI项目中也有用到，都是正常流式返回，感觉有点像返回被什么缓存了，但是仅限于这个next的本地项目，其他的都正常，很奇怪
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/116431228/cf03ec3d-840e-4a3d-8526-7160d3fefab0)

**Comment by wisdomlsh** [comment]
<img width="316" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/116431228/11734e8d-6d0a-4944-b734-c156754d2fa3">
解决了，因为next本地开发默认开启gzip压缩，导致流式接口变成了普通接口，next.config.mjs文件添加compress: false,关闭gzip压缩就好了
