### ISSUE TITLE
[Bug] 总结历史会话时，会有一条空的system 消息，导致 LM Studio 报错

### ISSUE THREAD

**Issue by digitXen** [ChatGPTNextWeb/ChatGPT-Next-Web#4667]
### Bug Description

当历史消息压缩启用时，向 API 接口发送的的 POST 请求中，messages的第一条 syetem 消息 content 为空。
```
 Received POST request to /v1/chat/completions with body: {
  "messages": [
    {
      "role": "system",
      "content": ""
    },
    {
      "role": "user",
      "content": "你是谁？"
    },
... 中间省略
,
    {
      "role": "system",
      "content": "简要总结一下对话内容，用作后续的上下文提示 prompt，控制在 200 字以内"
    }
  ],
```

而用 LM Studio进行推理时，不能接受空消息，报错如下内容：
```
 [Server Error] {"title":"'messages' array must only contain objects with a 'content' field that is not empty"}
```

### Steps to Reproduce

启用历史消息压缩，即可能有此问题。

另外，当对话历史中存在空消息（如在大模型推理输出前就进行中断，产生了一条空的消息记录）时，LM Studio 即会报错。

### Expected Behavior

希望在发送推理请求时，自动去掉 content 为空的消息。

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

MacOS

### Desktop Browser

Firefox

**Comment by Dean-YZG** [comment]
产生空系统消息的原因一般是：历史消息长度大于设定的压缩消息长度阈值 ，会发起一次对话，用于总结历史消息，同时携带上一次的『总结』，这样的方式来生成新的『总结』，作为新的『压缩消息』，但是，有时『上一次的总结』不存在，例如被清空，或是第一次发起『消息压缩』，这是逻辑默认增加一个空字符串作为『上一次总结』。这个pr兼容不支持空字符串的模型，将空字符串修改为";" 
  https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4671

**Comment by Dean-YZG** [comment]
目前，最新的解决方式为判断是否有『历史总结』，若无，则不会在消息中携带『历史总结』，修复代码已合并入主干
