### ISSUE TITLE
[Feature Request]: 希望在环境变量中可以加入特定的prompt

### ISSUE THREAD

**Issue by GeekHank** [ChatGPTNextWeb/ChatGPT-Next-Web#4668]
### Problem Description

一些关于角色扮演的prompt很常用，希望可以加入到环境变量中，可以实现在设置中加入特定prompt同样的功能

### Solution Description

一些关于角色扮演的prompt很常用，希望可以加入到环境变量中，可以实现在设置中加入特定prompt同样的功能

**Comment by QAbot-zh** [comment]
使用面具功能就好啦

**Comment by QAbot-zh** [comment]
面具可以把角色设置为system的

**Comment by GeekHank** [comment]
但是这样好像并不能解决跨设备打开自动启用提示词吧?我希望能够输入code后就可以使用，这样可以实现么



---Original---
From: ***@***.***&gt;
Sent at: 2024年5月12日(Sun) Evening10:34
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ChatGPTNextWeb/ChatGPT-Next-Web] [Feature Request]: 希望在环境变量中可以加入特定的prompt (Issue #4668)




 
面具可以把角色设置为system的

**Comment by QAbot-zh** [comment]
不能

**Comment by GeekHank** [comment]
好吧 再想想办法



---Original---
From: ***@***.***&gt;
Sent at: 2024年5月12日(Sun) Evening10:48
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ChatGPTNextWeb/ChatGPT-Next-Web] [Feature Request]: 希望在环境变量中可以加入特定的prompt (Issue #4668)




 
不能

**Comment by Dean-YZG** [comment]
[在环境变量中增加了提示词设置，是否满足需要？](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4671/files)

**Comment by GeekHank** [comment]
满足，谢谢



---Original---
From: ***@***.***&gt;
Sent at: 2024年5月13日(Mon) Evening6:01
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ChatGPTNextWeb/ChatGPT-Next-Web] [Feature Request]: 希望在环境变量中可以加入特定的prompt (Issue #4668)




 
在环境变量中增加了提示词设置，是否满足需要？
