### ISSUE TITLE
support gpt4o

### ISSUE THREAD

**Issue by jiangying000** [ChatGPTNextWeb/ChatGPT-Next-Web#4673]
### Problem Description

as in title

### Solution Description

add option for new model

**Comment by younes-io** [comment]
@jiangying000  : could you please translate into English? Thank you

**Comment by jiangying000** [comment]
> @jiangying000 : could you please translate into English? Thank you



> @jiangying000 : could you please translate into English? Thank you



> @jiangying000 : could you please translate into English? Thank you

done thanks

**Comment by leo4life2** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4674

**Comment by fred-bf** [comment]
Merged
