### ISSUE TITLE
[Bug] vercel部署总是失败

### ISSUE THREAD

**Issue by chengfengfengwang** [ChatGPTNextWeb/ChatGPT-Next-Web#4677]
### Bug Description

error An unexpected error occurred: "https://registry.npmmirror.com/@types/hoist-non-react-statics/-/hoist-non-react-statics-3.3.1.tgz: Request failed \"504 Gateway Timeout\"".

### Steps to Reproduce

1. fork 项目
2. 在vercel里导入fork的项目并且部署
3. 部署失败：error An unexpected error occurred: "https://registry.npmmirror.com/@types/hoist-non-react-statics/-/hoist-non-react-statics-3.3.1.tgz: Request failed \"504 Gateway Timeout\"".

### Expected Behavior

部署成功

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

**Comment by Xramas** [comment]
修复了，早晨那会npmmirrors挂了

**Comment by chengfengfengwang** [comment]
thanks
