### ISSUE TITLE
[bug]求助，网页端调用同一个群晖创建的docker api 无法使用 提示has been blocked by CORS policy

### ISSUE THREAD

**Issue by chris7395328** [ChatGPTNextWeb/ChatGPT-Next-Web#4678]
### Bug Description

是docker创建的 missuo/FreeDuckDuckGo 项目，测试通过，在沉浸翻译等插件下调用也正常。但是用next的网页调用始终无法使用，控制台提示http://192.168.123.232:3456/v1/chat/completions' from origin 'http://192.168.123.232:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

 

### Steps to Reproduce

docker 安装missuo/FreeDuckDuckGo 和next-web镜像。

### Expected Behavior

请教准确的设置方法

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by fred-bf** [comment]
Please ensure your llm provider added your NextChat deployment domain in the whitelist
