### ISSUE TITLE
[Feature Request]: How can I "define" many LLM providers (with their creds) and then use them accordingly?

### ISSUE THREAD

**Issue by younes-io** [ChatGPTNextWeb/ChatGPT-Next-Web#4680]
### Problem Description

For now, it's hard to switch between LLM providers. Every time I have to switch from one LLM provider to another, I need to get the API key and copy/paste manually, then put the URL of the other LLM provider, etc.

This is not very efficient, I think. It would be great to have a way to set up many LLM providers and their models, then switch between them using a drop down list. This also will make it easier for masks. Today, a mask with an LLM that belongs to an LLM provider that's not my "current" LLM, will fail; I have to switch manually to make it work.

### Solution Description

So, I believe the definition of LLM/LLM provider should be done in the setup, and then each conversation/mask should use the credentials defined with the LLM provider details required to call the LLM.

### Alternatives Considered

I'm already using https://big-agi.com/ because Next-Chat doesn't support this feature unfortunately 

### Additional Context

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/discussions/4669

**Comment by Green-li** [comment]
> ### Problem Description
> For now, it's hard to switch between LLM providers. Every time I have to switch from one LLM provider to another, I need to get the API key and copy/paste manually, then put the URL of the other LLM provider, etc.
> 
> This is not very efficient, I think. It would be great to have a way to set up many LLM providers and their models, then switch between them using a drop down list. This also will make it easier for masks. Today, a mask with an LLM that belongs to an LLM provider that's not my "current" LLM, will fail; I have to switch manually to make it work.
> 
> ### Solution Description
> So, I believe the definition of LLM/LLM provider should be done in the setup, and then each conversation/mask should use the credentials defined with the LLM provider details required to call the LLM.
> 
> ### Alternatives Considered
> I'm already using https://big-agi.com/ because Next-Chat doesn't support this feature unfortunately
> 
> ### Additional Context
> #4669

Maybe you can deploy the one-api(https://github.com/songquanpeng/one-api), and add different provides to the one api.

**Comment by fred-bf** [comment]
We are developing v3 of NextChat, will publish more details sooon

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4622

**Comment by younes-io** [comment]
alright, thank you
