### ISSUE TITLE
[Bug] Docker 构建镜像后访问3000端口页面无法打开(本地和服务器均是)ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by doolachen** [ChatGPTNextWeb/ChatGPT-Next-Web#4682]
### Bug Description

如题

### Steps to Reproduce

1. 拉取最新镜像 `git clone https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web`
2. `cd ChatGPT-Next-Web`
3. 构建docker镜像 `docker build --platform=linux/amd64 -t myname .`
4. `docker tag myname account/myname:latest`
5. `docker push account/myname:latest`
6. 服务器拉取构建的镜像 `docker pull account/myname:latest`
7. 运行容器 `docker run -d -p 3000:3000 \
   -e OPENAI_API_KEY=sk-xxxx \
   -e CODE=your-password \
   account/myname`
8. 访问ip:3000端口出现502 bad gateway 

### Expected Behavior

之前版本是可以正常构建并且push部署
同时我尝试了本地构建本地运行，出现ERR_CONNECTION_RESET

### Screenshots

查看docker日志：
`docker logs e2f4518c958c`
```
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
localnet 127.0.0.0/255.0.0.0
localnet ::1/128
[ProxyList]
http 127.0.0.1 7890
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16
   ▲ Next.js 14.1.1
   - Local:        http://127.0.0.1:3000
   - Network:      http://127.0.0.1:3000

 ✓ Ready in 41ms
```

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

MacOS 13 /Ubuntu 20.04

**Comment by doolachen** [comment]
尝试在容器内部手动执行`node server.js`后执行成功，dockerfile是否存在一些问题？

**Comment by ReeseWang** [comment]
在容器内运行`netstat -l`发现node监听的地址是`localhost:3000`，与两周前上一个版本的`:::3000`不同。Dockerfile上次修改是5个月前，不应该是Dockerfile的问题

**Comment by doolachen** [comment]
> 二分法查了一下，可能是把Next.js从13.4.9升级到14.1.1导致的

尝试仅回滚next.js升级的部分，问题依旧存在

**Comment by chizhiao** [comment]
same question

**Comment by coderc** [comment]
same question

**Comment by hrz6976** [comment]
Looks like they are working on a fix: #4689, guess that's something caused by the update of next.js -> 14.

As a temporary walkaround, add the following one-liner to the docker run command:
```shell
docker run -d --network host yidadaa/chatgpt-next-web:v2.12.3 sh -c 'if [ -n "$PROXY_URL" ]; then export HOSTNAME="0.0.0.0"; protocol=$(echo $PROXY_URL | cut -d: -f1); host=$(echo $PROXY_U
RL | cut -d/ -f3 | cut -d: -f1); port=$(echo $PROXY_URL | cut -d: -f3); conf=/etc/proxychains.conf; echo "strict_chain" > $conf; echo "proxy_dn
s" >> $conf; echo "remote_dns_subnet 224" >> $conf; echo "tcp_read_time_out 15000" >> $conf; echo "tcp_connect_time_out 8000" >> $conf; echo "l
ocalnet 127.0.0.0/255.0.0.0" >> $conf; echo "localnet ::1/128" >> $conf; echo "[ProxyList]" >> $conf; echo "$protocol $host $port" >> $conf; ca
t /etc/proxychains.conf; proxychains -f $conf node server.js; else node server.js; fi'
```

Now the container binds 0.0.0.0:
```
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16
   ▲ Next.js 14.1.1
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000
```

**Comment by LoopOptimum** [comment]
我也遇到了相同问题，我想是代理的原因。
本人在境外，只要不定义 PROXY_URL 就正常
但是远程内地的主机定义本地代理后就出现这个问题，代理本身是没问题的，就算有问题应该也是API请求超时而不是无法访问

**Comment by ReeseWang** [comment]
@LoopOptimum 不是代理的问题。之前为了解决 #1556 ，这里加了个逻辑：如果有`PROXY_URL`，就设置`HOSTNAME=127.0.0.1`。
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/cf635a5e6fe21b5ae4cfc4f17ec7f7f2f8aa053e/Dockerfile#L45-L46 

但是`HOSTNAME`会被用来设置监听地址（可能是Next.js 14的新行为），而监听`127.0.0.1`会拒绝一切外部访问。

**Comment by LoopOptimum** [comment]
> @LoopOptimum 不是代理的问题。之前为了解决 #1556 ，这里加了个逻辑：如果有`PROXY_URL`，就设置`HOSTNAME=127.0.0.1`。
> 
> https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/cf635a5e6fe21b5ae4cfc4f17ec7f7f2f8aa053e/Dockerfile#L45-L46
> 
> 但是`HOSTNAME`会被用来设置监听地址（可能是Next.js 14的新行为），而监听`127.0.0.1`会拒绝一切外部访问。

我回滚到v2.12.2 没有出现这个问题, v2.12.3 尝试用ipv6 可以访问，但是API请求超时

**Comment by doolachen** [comment]
> @LoopOptimum 不是代理的问题。之前为了解决 #1556 ，这里加了个逻辑：如果有`PROXY_URL`，就设置`HOSTNAME=127.0.0.1`。
> 
> https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/cf635a5e6fe21b5ae4cfc4f17ec7f7f2f8aa053e/Dockerfile#L45-L46
> 
> 但是`HOSTNAME`会被用来设置监听地址（可能是Next.js 14的新行为），而监听`127.0.0.1`会拒绝一切外部访问。

请问你删除后有尝试过自己再次构建docker镜像吗？我按你的方案删除了` export HOSTNAME="127.0.0.1"; \ `，
`docker history`显示docker执行确实没有HOSTNAME了：

`sha256:a34fa6ea6c94f19112c65cddb01415816a47b02e3e9c3d68d968fa8005a32f09   20 minutes ago   CMD ["/bin/sh" "-c" "if [ -n \"$PROXY_URL\" ]; then     protocol=$(echo $PROXY_URL | cut -d: -f1);     host=$(echo $PROXY_URL | cut -d/ -f3 | cut -d: -f1);     port=$(echo $PROXY_URL | cut -d: -f3);     conf=/etc/proxychains.conf;     echo \"strict_chain\" > $conf;     echo \"proxy_dns\" >> $conf;     echo \"remote_dns_subnet 224\" >> $conf;     echo \"tcp_read_time_out 15000\" >> $conf;     echo \"tcp_connect_time_out 8000\" >> $conf;     echo \"localnet 127.0.0.0/255.0.0.0\" >> $conf;     echo \"localnet ::1/128\" >> $conf;     echo \"[ProxyList]\" >> $conf;     echo \"$protocol $host $port\" >> $conf;     cat /etc/proxychains.conf;     proxychains -f $conf node server.js;     else     node server.js;     fi"] `
docker logs结果next.js依然监听127.0.0.1
```
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
localnet 127.0.0.0/255.0.0.0
localnet ::1/128
[ProxyList]
http 172.25.131.140 7899 doola dorachen
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16
   ▲ Next.js 14.1.1
   - Local:        http://25eff16d89df:3000
   - Network:      http://127.0.0.1:3000

 ✓ Ready in 101ms
```
同时也尝试修改HOSTNAME="0.0.0.0" 问题依旧没有得到解决

**Comment by ReeseWang** [comment]
> 同时也尝试修改HOSTNAME="0.0.0.0" 问题依旧没有得到解决

这样设置以后的log是什么？

**Comment by doolachen** [comment]
> > 同时也尝试修改HOSTNAME="0.0.0.0" 问题依旧没有得到解决
> 
> 这样设置以后的log是什么？删掉这行的确不能解决问题，见 [#4689 (comment)](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4689#issuecomment-2111524641) 。我最终的解决方案是`HOSTNAME=0.0.0.0`

我参考https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4682#issuecomment-2110699051的方法重新执行docker run命令，绑定本机3000端口运行正常了。
我想之前是因为我的3000端口有一个进程在运行，因此我使用3001作为替代 并且删除了--network host字段，通过3001端口仍然无法访问，命令为：
`docker run -d -p 3001:3000 -e PROXY_URL="" image/image-name:latest sh -c 'if [ -n "$PROXY_URL" ]; then export HOSTNAME="0.0.0.0"; protocol=$(echo $PROXY_URL | cut -d: -f1); host=$(echo $PROXY_URL | cut -d/ -f3 | cut -d: -f1); port=$(echo $PROXY_URL | cut -d: -f3); conf=/etc/proxychains.conf; echo "strict_chain" > $conf; echo "proxy_dns" >> $conf; echo "remote_dns_subnet 224" >> $conf; echo "tcp_read_time_out 15000" >> $conf; echo "tcp_connect_time_out 8000" >> $conf; echo "localnet 127.0.0.0/255.0.0.0" >> $conf; echo "localnet ::1/128" >> $conf; echo "[ProxyList]" >> $conf; echo "$protocol $host $port" >> $conf; cat /etc/proxychains.conf; proxychains -f $conf node server.js; else node server.js; fi'`
```
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
localnet 127.0.0.0/255.0.0.0
localnet ::1/128
[ProxyList]
http 172.25.131.140 7899 doola dorachen
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16
   ▲ Next.js 14.1.1
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Ready in 87ms
```
修改了容器外监听端口为3001后就出现了问题，现在我已经重新使用3000端口，可以正常运行

**Comment by ahzmr** [comment]
看到现在还没有提供解决办法，我先临时用不重新编译的方式解决，方法如下：
1. 通过配置文件配置代理: `proxychains.conf`；
2. 改docker启动命令和挂载解决: `docker-compose.yml`。

这种方式影响小，希望对大伙有用。

附件：
1. proxychains.conf
```
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
localnet 127.0.0.0/255.0.0.0
localnet ::1/128
[ProxyList]
http 192.168.31.1 1087
```
2. docker-compose.yml
```
version: '3.3'

services:
    chatgpt-next-web:
        image: yidadaa/chatgpt-next-web
        restart: always
        container_name: chatgpt-next-web
        ...
        environment:
          ...
          HOSTNAME: '0.0.0.0'
        command: ["proxychains", "-f", "/etc/proxychains.conf", "node", "server.js"]
        volumes:
          - ./proxychains.conf:/etc/proxychains.conf
```

**Comment by ItTonySuperMan** [comment]
> 尝试在容器内部手动执行`node server.js`后执行成功，dockerfile是否存在一些问题？

根据这个提示之后，我暂时用以下命令临时解决
`docker exec 容器名 node server.js &
`

**Comment by LoopOptimum** [comment]
> 看到现在还没有提供解决办法，我先临时用不重新编译的方式解决，方法如下：
> 
> 1. 通过配置文件配置代理: `proxychains.conf`；
> 2. 改docker启动命令和挂载解决: `docker-compose.yml`。
> 
> 这种方式影响小，希望对大伙有用。
> 
> 附件：
> 
> 1. proxychains.conf
> 
> ```
> strict_chain
> proxy_dns
> remote_dns_subnet 224
> tcp_read_time_out 15000
> tcp_connect_time_out 8000
> localnet 127.0.0.0/255.0.0.0
> localnet ::1/128
> [ProxyList]
> http 192.168.31.1 1087
> ```
> 
> 2. docker-compose.yml
> 
> ```
> version: '3.3'
> 
> services:
>     chatgpt-next-web:
>         image: yidadaa/chatgpt-next-web
>         restart: always
>         container_name: chatgpt-next-web
>         ...
>         environment:
>           ...
>           HOSTNAME: '0.0.0.0'
>         command: ["proxychains", "-f", "/etc/proxychains.conf", "node", "server.js"]
>         volumes:
>           - ./proxychains.conf:/etc/proxychains.conf
> ```

已经解决，不过代理不能用127.0.0.1:端口，只能用主机自己的局域网IP

**Comment by Aincvy** [comment]
现在好像仍然无法使用。 

docker 里面目前是使用 --host 的方式添加参数的， 但是 docker 界面里面仍然是 127.0.0.1:3000.   
文件可见：  https://hub.docker.com/layers/yidadaa/chatgpt-next-web/latest/images/sha256-643a791a909b4e863ad3b12b91bf037c00b7d06d2b5db477dd6e362ec0751477?context=explore

PR 的最后的一部分的修改 应该是没合并到镜像里面：  https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4689/commits/d411159124925420cff793fa05afdbd6783845d6

**Comment by daiaji** [comment]
我的评价是纯纯的弱智。
```
env
BASE_URL=http://localhost:3000
NODE_VERSION=18.20.4
YARN_VERSION=1.22.19
HOSTNAME=0.0.0.0
SHLVL=1
PORT=2999

ss -plant
State                  Recv-Q               Send-Q                             Local Address:Port                                Peer Address:Port              Process                                           
LISTEN                 0                    511                                      0.0.0.0:8000                                     0.0.0.0:*                                                                   
LISTEN                 0                    200                                      0.0.0.0:5432                                     0.0.0.0:*                                                                   
LISTEN                 0                    511                                  10.10.10.10:3210                                     0.0.0.0:*                                                                   
LISTEN                 0                    511                                  10.10.10.10:2999                                     0.0.0.0:*                  users:(("next-server",pid=1,fd=18))              
LISTEN                 0                    4096                                   127.0.0.1:9000                                     0.0.0.0:*                                                                   
LISTEN                 0                    4096                                   127.0.0.1:2019                                     0.0.0.0:*                                               
```
绑定你妈的10.10.10.10呢……
