### ISSUE TITLE
[Feature Request]: 默认不显示gpt-4o的模型选择，需要自行添加

### ISSUE THREAD

**Issue by whiteless9** [ChatGPTNextWeb/ChatGPT-Next-Web#4688]
### Problem Description

默认不显示gpt-4o的模型选择，需要自行添加

### Solution Description

默认不显示gpt-4o的模型选择，需要自行添加

**Comment by fred-bf** [comment]
plz upgrade to latest version

**Comment by zs-dima** [comment]
@fred-bf latest version does not starting https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4692
