### ISSUE TITLE
[Feature Request]: support for GPT4-o

### ISSUE THREAD

**Issue by Qi2013** [ChatGPTNextWeb/ChatGPT-Next-Web#4694]
### Problem Description

OpenAI released the access for GPT4-o model with cheaper price and better resutls. We should add the support for this model.

### Solution Description

When users open the list for chose a model to use, he can choose  gpt4-o.

**Comment by 04041b** [comment]
upgrade to newest version

**Comment by xeastsun** [comment]
> upgrade to newest version

I updated to the V2.12.3, and chose the gpt-4o.
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/127654649/30c23f53-2a68-4fed-812a-d84314cb6322)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/127654649/c14a5f14-84af-4c94-b9be-b66d9bb7a6b3)
Am I using the correct version（gpt-4o）?

**Comment by zs-dima** [comment]
> @04041b upgrade to newest version
It is container start issue
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4692
