### ISSUE TITLE
[Bug] The gpt-4o option does not work

### ISSUE THREAD

**Issue by xeastsun** [ChatGPTNextWeb/ChatGPT-Next-Web#4696]
### Bug Description

I have upgraded to the latest version, in the model can also choose gpt-4o, and gpt-40-2004-05-13. But these two options don't seem to switch to gpt-4o properly, as follows:
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/127654649/c62fe7c3-1266-418a-a3b3-fd1d2bd1ae47)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/127654649/031d1f32-e822-4173-974c-a38cc70b03cb)
Am I doing something wrong?
Thanks！

### Steps to Reproduce

I have upgraded to the latest version, in the model can also choose gpt-4o, and gpt-40-2004-05-13. But these two options don't seem to switch to gpt-4o properly, as follows:
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/127654649/c62fe7c3-1266-418a-a3b3-fd1d2bd1ae47)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/127654649/031d1f32-e822-4173-974c-a38cc70b03cb)
Am I doing something wrong?
Thanks！

### Expected Behavior

gpt-4o, and gpt-40-2004-05-13 don't seem to switch to gpt-4o properly

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

**Comment by SpiralTower** [comment]
I heard that gpt4o supports image input and Internet search. Why not try these functions?

**Comment by xeastsun** [comment]
> I heard that gpt4o supports image input and Internet search. Why not try these functions?

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/127654649/a942a681-1baa-456b-8bd6-c6962bb3b928)

**Comment by xeastsun** [comment]
Maybe this is OPenAI's problem，I vist https://platform.openai.com/usage and get the info:
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/127654649/a61c79d4-3c35-48c9-8cb4-18f666464ad8)
So, I am in gpt-4o.
