### ISSUE TITLE
[Bug] 无法使用v1beta接口

### ISSUE THREAD

**Issue by do02fw** [ChatGPTNextWeb/ChatGPT-Next-Web#4699]
### Bug Description

发送消息返回
json
{
  "error": true,
  "message": "models/gemini-1.5-pro is not found for API version v1beta, or is not supported for StreamGenerateContent. Call ListModels to see the list of available models and their supported methods."
}

### Steps to Reproduce

调用加入beta版的Gemini账号的API，会报错

### Expected Behavior

调用v1beta的API

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

windows11

### Desktop Browser

edge

### Desktop Browser Version

125

### Additional Logs

```json
{
  "error": true,
  "message": "models/gemini-1.5-pro is not found for API version v1beta, or is not supported for StreamGenerateContent. Call ListModels to see the list of available models and their supported methods."
}
```

**Comment by QAbot-zh** [comment]
v1beta 对应的模型名称是 gemini-1.5-pro-latest

**Comment by QAbot-zh** [comment]
> gemini-1.5-pro-latest

use the model name "gemini-1.5-pro-latest"
