### ISSUE TITLE
[Feature Request]: support for gemini-1.5-flash-latest 

### ISSUE THREAD

**Issue by gochendong** [ChatGPTNextWeb/ChatGPT-Next-Web#4701]
### Problem Description

new Google model

### Solution Description

support image input

**Comment by daiaji** [comment]
gemini-1.5-flash currently does not support streaming response, so it is necessary to turn off the streaming response button.

**Comment by fred-bf** [comment]
merged in https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commit/0bf758afd4c5db6996d1de5f41ee75f899181d68

**Comment by fred-bf** [comment]
@daiaji streaming mode works fine in my end, would you mind share more specify issue when you tried gemini flash?

**Comment by gochendong** [comment]
> @daiaji streaming mode works fine in my end, would you mind share more specify issue when you tried gemini flash?

flash model should be added into "isVisionModel" list

**Comment by gochendong** [comment]
> merged in [0bf758a](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/commit/0bf758afd4c5db6996d1de5f41ee75f899181d68)

flash model should be added into "isVisionModel" list

**Comment by daiaji** [comment]
> @daiaji streaming mode works fine on my end, would you mind share more specific issue when you tried gemini flash?

The v1 API does not support streaming response, while the v1beta API supports streaming response. However, I believe this is because it provides an interface switch to handle APIs that do not support streaming response.
