### ISSUE TITLE
[Feature Request]: openai官网已支持免登录使用，这个项目能否不用key也能使用

### ISSUE THREAD

**Issue by imjmo** [ChatGPTNextWeb/ChatGPT-Next-Web#4704]
### Problem Description

请教一下，目前官网已支持免登录使用，我按照项目介绍部署了最新的代码，还是需要填入openai key才可以正常使用，能否不用输入key也能使用本项目搭建好的网站？
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/55728384/9b0f7922-f2fe-49e9-bf40-a344e207b710)

### Solution Description

如上。

**Comment by myvica** [comment]
这种需要逆向转API或者找镜像站的项目吧

**Comment by DMirolli** [comment]
I'd love to be a part of this in some way, although I don't know how to read Chinese and I can't code well enough yet to ask to be a part of such a cool project. I will continue to check them out and watch folks who do know what they're doing.

**Comment by jinjianming** [comment]
https://chat.chatapi.asia/
