### ISSUE TITLE
[Bug] 使用gpt-4o模型无法调用图片上传

### ISSUE THREAD

**Issue by yehao1991** [ChatGPTNextWeb/ChatGPT-Next-Web#4707]
### Bug Description

使用gpt-4o模型无法调用图片上传
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/158235386/534488df-0048-4fc5-800f-8aee8bb76d72)

### Steps to Reproduce

选择gpt-4o，但是无法调用图片上传按钮

### Expected Behavior

修复BUG

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/158235386/edc69d0f-1512-4eae-978d-4cb9f70a3f9d)

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

ubuntu 22.04

**Comment by fred-bf** [comment]
hi, please upgrade to latest version. the bugfix have been addressed in this commit https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4703

**Comment by yehao1991** [comment]
已经更新到2.12.3版本才发现这个问题的；
