### ISSUE TITLE
[Bug] gpt4o模型没有上传图片按钮

### ISSUE THREAD

**Issue by BaiJiang007** [ChatGPTNextWeb/ChatGPT-Next-Web#4717]
### Bug Description

目前只有gpt-4-vision-preview有这个按钮，gpt-4o也应该支持

### Steps to Reproduce

选择gpt-4o模型，不展示上传图片按钮

### Expected Behavior

展示上传按钮

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by spe1995** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/19503431/3ab51b54-09be-46a7-96bc-0442150f4ed9)
I can change it like this

**Comment by BaiJiang007** [comment]
It's fixed
