### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by anyeshi** [ChatGPTNextWeb/ChatGPT-Next-Web#4718]
### Bug Description

绑定域名成功，但是打开网页显示"重定向次数过多"

### Steps to Reproduce

1.点击绑定的域名
2.“显示”重定向次数过多"

### Expected Behavior

正常访问

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

WINDOWS10LTSC

### Desktop Browser

EDGE

### Desktop Browser Version

124.0.2478.80 (正式版本) (64 位)

**Comment by SpiralTower** [comment]
If the dns of your domain is provided by cloudflare, please set the Proxy status to DNS only

**Comment by zc360** [comment]
把SSL/TLS 加密模式改为完全（严格）就不会出现问题了
