### ISSUE TITLE
[Bug] Setting `max_tokens` didn't work when using OpenAI models.

### ISSUE THREAD

**Issue by SirlyDreamer** [ChatGPTNextWeb/ChatGPT-Next-Web#4721]
### Bug Description

The payload of request didn't contains 'max_tokens'. 

### Steps to Reproduce

1. Go to 'settings', and set max_tokens to any value.
2. Open Chrome Developer Tools and switch to 'Network' tab.
3. Apply a chat request.

### Expected Behavior

The request should have key 'max_tokens'.

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/45280500/bdee73b8-06f1-4799-9576-c4deeb8dfce2)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

Windows 11

### Desktop Browser

Chrome

### Desktop Browser Version

124.0.6367.208

**Comment by SpiralTower** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/f55f04ab4f23fc5a5ac84aba0d2d926c557816c3/app/client/platforms/openai.ts#L119-L129
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/discussions/3208
