### ISSUE TITLE
[Bug] Icon is too large in macbook

### ISSUE THREAD

**Issue by liaokaime** [ChatGPTNextWeb/ChatGPT-Next-Web#4724]
### Bug Description

Obviously the icon is bigger than all the icons, and I think that's a problem

<img width="1337" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/27792976/ad1db957-6813-4cf0-b293-50d3f0a0e076">

### Steps to Reproduce

1. install
2. open it

### Expected Behavior

The icon is as big as any other icon

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

macos 14.4.1

**Comment by Dean-YZG** [comment]
Thank you for your feedback, we will adopt the suggestion
