### ISSUE TITLE
[Feature Request]: 关于 max_tokens 用法的建议

### ISSUE THREAD

**Issue by code-october** [ChatGPTNextWeb/ChatGPT-Next-Web#4729]
### Problem Description

不同模型的 max_tokens 参数使用方式不一而足，有些模型如果 max_tokens 传的值不合适会导致请求拒绝或者吐字被中断，给视觉模型加上 max_tokens 的额外设置就是由于这个问题，关于 max_tokens 传不传参的 issue 讨论也不少。

### Solution Description

对此我想给出一个建议，可以在前端设置一个切换按钮，用来控制当前对话是否给模型传入 max_tokens 参数。这样在适配新模型的时候可以适当减少在程序中硬编码的工作，因为除了 isVisionModel 的判别外，用户可以直接通过前端控制传 max_tokens。我想这样的设计能有效减少 max_tokens 参数带来的对话困扰。

**Comment by Dean-YZG** [comment]
非常同意你对max_tokens的看法，目前看，max_tokens和具体模型是强关联的，因此，在新版本中，我们将会把max_tokens作为具体模型的参数，支持用户对于模型的max_tokens进行自定义
