### ISSUE TITLE
[Bug] 使用过程中（发送新消息时）报错，储存空间不够 (web 和 win exe都有)

### ISSUE THREAD

**Issue by jiangying000** [ChatGPTNextWeb/ChatGPT-Next-Web#4733]
### Bug Description

![1716091521207](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/23182033/147e986f-96e6-4260-9549-87b142127dfa)

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/23182033/e532f06f-60be-4fe1-acd3-97634f923410)

### Steps to Reproduce

有很多对话时，继续聊天就会触发

### Expected Behavior

不报错

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by jiangying000** [comment]
除了 localstorage ，还有更好的储存会话的方式吗？
5MB或者 10MB太小了

**Comment by Dean-YZG** [comment]
localStorage 的存储能力，对于对话存储的应用场景来说，确实太有限了，目前，正在探索多技术联合的方案，解决存储空间受限的问题

**Comment by lloydzhou** [comment]
v2.15.0版本支持更大存储空间
