### ISSUE TITLE
[Bug]  gpt-4-0314 模型选项不见了

### ISSUE THREAD

**Issue by jiangying000** [ChatGPTNextWeb/ChatGPT-Next-Web#4735]
### Bug Description

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/23182033/d026485a-4ebe-4a4e-b187-42734bd8c24c)

### Steps to Reproduce

升级到main，打开下拉框

### Expected Behavior

应该有 

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by jiangying000** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/23182033/bd586ea8-3eed-45ae-9a7d-a53281aff6e3)


我需要它，所以我现在加了custom model作为临时方案

**Comment by Dean-YZG** [comment]
> ![image](https://private-user-images.githubusercontent.com/23182033/331913815-bd586ea8-3eed-45ae-9a7d-a53281aff6e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzY0NjcsIm5iZiI6MTcxNjE3NjE2NywicGF0aCI6Ii8yMzE4MjAzMy8zMzE5MTM4MTUtYmQ1ODZlYTgtM2VlZC00NWFlLTlhN2QtYTUzMjgxYWZmNmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAzMzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMDNjMmRlNmM4NjI2MGIwNTcwMjUwYjIxODU4YjQ0MTk2YjQwZDA4MjNkNjVkMDdhMzM2ZjBkNmU4Yjg3ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W7Gw57Yrs0HVsgywPlSppkyZdMLTU7fu-T3iEfBGPVU)
> 
> 我需要它，所以我现在加了custom model作为临时方案

带有日期标记的临时版本，由于其不稳定性，未来将不会再增加新的这类临时版本的model作为内置model选项，目前可通过 custom model 变量进行配置，未来将提供给更强大的能力支持自定义模型
