### ISSUE TITLE
[Feature Request]: include attachments support (PDFs, images, etc)

### ISSUE THREAD

**Issue by younes-io** [ChatGPTNextWeb/ChatGPT-Next-Web#4737]
### Problem Description

I cannot use NextChat to "chat with my documents" or just take a screenshot of some code snippet or some mathematical formula and then use that in my chat with the LLM

### Solution Description

I want to be able to:
* upload documents to my conversation (PDF, Word, raw text files like CSV, PowerPoint, Images) and chat with them _(this is the priority for me)_
* define a Mask/Assistant (just like in the OpenAI playground) that is connected to a knowledge base (one or a bunch of docs) and then chat with it whenever I want to => it will be a specialized Mask, that answers based on my own knowledge base, not just relying on the training data of the LLM with a system prompt

### Alternatives Considered

ChatGPT (for the first item)
[OpenAI's Assistants](https://platform.openai.com/assistants) (for both items)
[ChatKit](https://chatkit.app/#)

**Comment by Dean-YZG** [comment]
Thank you for your feedback, we have planed to build data storage capacity for the future to upload files, but you know, building data storage capacity is not only technically complex, but more importantly, a data security issue. Therefore, we will build this capacity after developing a reliable technical solution

**Comment by younes-io** [comment]
@Dean-YZG even for local data storage?

**Comment by BMurdochUK** [comment]
But the Gemini-pro-vision model allows images to be uploaded via the NextWeb app. So guessing it persists temporarily to local data storage? So why cant same feature be rolled out to ChatGPT model?

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4446

**Comment by younes-io** [comment]
> @Dean-YZG even for local data storage?

@Dean-YZG could you please comment my question or someone from the team? =) Thank you

**Comment by nealhan** [comment]
bump for this feature, it's so important!

**Comment by zhsh006** [comment]
We need the feature.

**Comment by suchorski** [comment]
Want that too
