### ISSUE TITLE
[Feature Request]: Max Request Per IP etc

### ISSUE THREAD

**Issue by Niansuh** [ChatGPTNextWeb/ChatGPT-Next-Web#4738]
### Problem Description

showing error on high requests from my api

### Solution Description

showing error on high requests from my api i want to add a feature max request per ip in mintue etc

**Comment by Dean-YZG** [comment]
do you want to look up api-errors in server-logs?

**Comment by Dean-YZG** [comment]
this feature is diffcult and complex when use edge computing  from the perspective of application services. You can explore this at the infrastructure level
