### ISSUE TITLE
[Bug] 更新docker 镜像 v2.12.3 之后。新的模型不能使用，显示 400 Bad Request

### ISSUE THREAD

**Issue by Fei2015** [ChatGPTNextWeb/ChatGPT-Next-Web#4739]
### Bug Description

从docker 镜像 v2.11.2 升级到 v2.12.3 之后新的模型 gpt-4-turbo, gpt-4o, ... 不能使用
{
  "code": 400,
  "error": "Encountering an error when receiving the github copilot response: 400 Bad Request"
}

### Steps to Reproduce

...

### Expected Behavior

...

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Dean-YZG** [comment]
请问有应用报错截图，接口报错截图么？我想这可能和Copilot Chat有关

**Comment by Fei2015** [comment]
我就是更新后，在对话页面 http://localhost:3000/#/
不管输入什么，都显示：
{
  "code": 400,
  "error": "Encountering an error when receiving the github copilot response: 400 Bad Request"
}
你说的应用报错或者接口报错 在哪里看？

**Comment by QAbot-zh** [comment]
为什么会是报github copilot response的错误，用了 copilot 转 api ？

**Comment by Fei2015** [comment]
> 为什么会是报github copilot response的错误，用了 copilot 转 api ？

对的，用了copilot-gpt4-service

**Comment by QAbot-zh** [comment]
那可能是copilot-gpt4-service的问题，copilot应该没有第一时间提供gpt-4o模型吧，我记得这种转api服务很多模型都是重定向了，毕竟copilot本身就没有提供多少模型

**Comment by Fei2015** [comment]
> 那可能是copilot-gpt4-service的问题，copilot应该没有第一时间提供gpt-4o模型吧，我记得这种转api服务很多模型都是重定向了，毕竟copilot本身就没有提供多少模型

原来是这样，好的谢谢
