### ISSUE TITLE
支持阿里的通义千问吗。qwen。。。大降价。。1块钱可以买200万令牌

### ISSUE THREAD

**Issue by Whichbfj28** [ChatGPTNextWeb/ChatGPT-Next-Web#4746]
### Problem Description

支持阿里的通义千问吗。qwen。。。大降价。。1块钱可以买200万令牌

### Solution Description

支持阿里的通义千问吗。qwen。。。大降价。。1块钱可以买200万令牌

**Comment by z2n** [comment]
https://help.aliyun.com/zh/dashscope/developer-reference/compatibility-of-openai-with-dashscope/

**Comment by lhylhy38** [comment]
好像不行啊 改base url 和key
一直报错

**Comment by shansing** [comment]
楼上的 URL 非常有用。我魔改了项目，跟原有 OpenAI 模型共存，如有需要可以参考我的改动点（但是不推荐直接用我的定制项目，没考虑通用性）：

https://github.com/shansing/ChatGPT-Next-Web/commit/61a1bd626d40f31601e897860cceeaa70b55fca1

**Comment by huayune** [comment]
> 楼上的 URL 可供使用。我的魔改了项目，跟原有 OpenAI 模型共存，如有需要可以参考我的共识点（但是不推荐直接用我的定制项目，没考虑通用性）：
> 
> [山星@ 61a1bd6](https://github.com/shansing/ChatGPT-Next-Web/commit/61a1bd626d40f31601e897860cceeaa70b55fca1)

@shansing  方便帮忙看一下吗，我用你的项目，改了alibaba的key，访问接口提示403，
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/73863578/58ea1f4d-0787-4289-89b1-21a5f1fbcf2c)

**Comment by lloydzhou** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4942

support qwen model now.
