### ISSUE TITLE
[Feature Request]: Does it support the Qwen model?

### ISSUE THREAD

**Issue by wkst1000** [ChatGPTNextWeb/ChatGPT-Next-Web#4750]
### Problem Description

I don't know how to use the Qianwen model's API endpoint. Does this software not support the Qwen model?

### Alternatives Considered

no

**Comment by z2n** [comment]
https://help.aliyun.com/zh/dashscope/developer-reference/compatibility-of-openai-with-dashscope/
.env 配置 key 和 `BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/` （目前走客户端的话会有 cors 问题）

**Comment by lloydzhou** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4942

support qwen model now.
