### ISSUE TITLE
[Bug] 无法导入本地的json数据

### ISSUE THREAD

**Issue by hugo0819** [ChatGPTNextWeb/ChatGPT-Next-Web#4751]
### Bug Description

我原来使用的是2.9.13版本，下载最新的2.12.3版本后，原来导出的本地数据无法导入，导入时直接显示导入失败，请问应该怎么解决？

### Steps to Reproduce

在2.9.13版本的设置中选择导出本地数据
在2.12.3版本的设置中选择导入本地数据

### Expected Behavior

正常导入所有的聊天数据

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows 10

**Comment by Dean-YZG** [comment]
do you have any screenshot about error log in browser devtool, I need know the detail about the error

**Comment by hugo0819** [comment]
It only shows import failure and there is no extra display

**Comment by Ajianxian** [comment]
这是因为[v2.11.2及以前的版本源码](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/bc1794fb4af5229c4811008ad247b57bbf091334/app/utils.ts#L59)在导出时是使用的二进制格式导出，所以导入时解析失败了。
我的解决方法是本地拉取对应历史版本的代码，然后把utils.ts#L59这块的代码换成最新版本的代码，然后再使用visual studio重新打包出来一个应用程序文件，运行后用新的代码导出文件，就可以正常进行导入了
