### ISSUE TITLE
[Feature Request]: 增加多个自定义提供商功能

### ISSUE THREAD

**Issue by muamua33** [ChatGPTNextWeb/ChatGPT-Next-Web#4759]
### Problem Description

有多个支持openai endpoint的提供商，但nextchat却只能填写一个，造成无法切换多个自定义支持openai endpoint的提供商

### Solution Description

增加自定义提供商功能可以添加保存删除的列表，提供切换多个自定义提供商的功能

**Comment by Dean-YZG** [comment]
Happy to tell everyone, we will support this feature in the V3 nextchat!

**Comment by lloydzhou** [comment]
新的版本从2.13.0支持多服务商逻辑
