### ISSUE TITLE
真心提问：大家的api key都是从哪里买的？

### ISSUE THREAD

**Issue by Chris-Arith** [ChatGPTNextWeb/ChatGPT-Next-Web#4760]
### Problem Description

想买一个3.5-turbo的key，大家有没有靠谱又划算的渠道推荐下，谢谢。

**Comment by proxyxai** [comment]
> ### Problem Description
> 想买一个3.5-turbo的key，大家有没有靠谱又划算的渠道推荐下，谢谢。
> 
> ### Solution Description
> 想买一个3.5-turbo的key，大家有没有靠谱又划算的渠道推荐下，谢谢。
> 
> ### Alternatives Considered
> _No response_
> 
> ### Additional Context
> _No response_

请查收 qq 邮箱

**Comment by huelsgp27** [comment]
openrouter

**Comment by ZpitQ** [comment]
虚拟信用卡，充钱进去就完事了。买别人得，别人要赚你钱

**Comment by Chris-Arith** [comment]
> 虚拟信用卡，充钱进去就完事了。买别人得，别人要赚你钱

只要账户里有余额，就可以使用api key是吗，有没有过期时间

**Comment by Chris-Arith** [comment]
> openrouter

好的，我搜一下看看

**Comment by Chris-Arith** [comment]
> > ### Problem Description
> > 想买一个3.5-turbo的key，大家有没有靠谱又划算的渠道推荐下，谢谢。
> > ### Solution Description
> > 想买一个3.5-turbo的key，大家有没有靠谱又划算的渠道推荐下，谢谢。
> > ### Alternatives Considered
> > _No response_
> > ### Additional Context
> > _No response_
> 
> 请查收 qq 邮箱

收到

**Comment by Chris-Arith** [comment]
> 3.5 纯对话的话，自己逆一下就 free 了

你好，可以详细说一下吗，或者有没有类似的文章分享下，多谢！

**Comment by lloydzhou** [comment]
如果购买AI资源，最好还是直接到官方购买！
