### ISSUE TITLE
[Bug] 配置BASE_URL后直接返回html代码

### ISSUE THREAD

**Issue by RogerProSelf** [ChatGPTNextWeb/ChatGPT-Next-Web#4761]
### Bug Description

在配置自部署的One-API的自定义BASE_URL后（形式如<https://xxx.xxx.xxx:1234>，非自签名SSL证书，端口外网访问正常），聊天界面直接返回HTML代码。

疑似是服务端侧访问导致的问题，因为在web ui中使用完全一样的自定义接口地址而不用默认的“api/openai”后就可以正常使用了。我看了之前别人的issue，似乎有提到在使用“api/openai”时是服务端侧访问，而自定义web ui中的接口地址时是客户端侧访问。

### Screenshots

![截屏2024-05-22 02 45 11](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/55005611/32b3a7ed-3742-401d-8170-2c29628c6dc5)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

**Comment by Dean-YZG** [comment]
do you have screenshot about the error request in browser dev tool?

**Comment by Dean-YZG** [comment]
the cause of reponsing html page is the path is not exsit on finally target server deployed, please check your env vars, the splicing rule of a forward url is 'BASE_URL/v1/chat/completions'

**Comment by lloydzhou** [comment]
不知道这个配置问题处理好了没有？

如果已经配置好了，就先关闭issue了
