### ISSUE TITLE
目前项目本身支持Azure OpenAI 吗？还是只能通过搭建第三方代理的方式来访问？

### ISSUE THREAD

**Issue by Lufffya** [ChatGPTNextWeb/ChatGPT-Next-Web#4765]

**Comment by QAbot-zh** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/c335bb9f-8d41-4a52-87eb-e605c8b4a76b)

**Comment by oicoderr** [comment]
在不更改chatgpt-next-web项目前提，可以采用代理转发https://github.com/oicoderr/azure-openai-proxy

**Comment by oicoderr** [comment]
在不更改chatgpt-next-web项目前提，可以采用代理转发，希望可以帮助到你https://github.com/oicoderr/azure-openai-proxy

**Comment by lloydzhou** [comment]
#4930

**Comment by lloydzhou** [comment]
当前已经支持通过CUSTOM_MODELS配置azure的deployment name
