### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yexia553** [ChatGPTNextWeb/ChatGPT-Next-Web#4767]
### Bug Description

使用自定义接口（Azure OPENAI）时，我基于gpt-4o部署了一个模型，但是当**自定义模型名**为gpt-4o时，在模型(model)那里就选不到我自定义这个，把自定义模型名修改为其他值就可以，但是，此时UI上输入框这里就没有上传文件的功能
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/25142514/c9bc81fa-406a-48b6-bab1-eac846fd2c4e)

感谢开发者提供这个好用的工具~~

### Steps to Reproduce

参考下面这个截图进行配置即可复现，我在多个浏览器上都试过，每次都必现
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/25142514/65155980-8f7f-464b-b381-16d8024559ff)

### Expected Behavior

能修复这个问题就好啦

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

windows11

### Desktop Browser

chrome

**Comment by sparkssssssssss** [comment]
用的最新版,内置了4o的吧

**Comment by Dean-YZG** [comment]
you can use 'gpt-4o-customized' as your model'name，if include 'gpt-4o' in the model name, you can use the image upload function

**Comment by lloydzhou** [comment]
请升级新版本，使用新的支持多服务商逻辑的版本
