### ISSUE TITLE
[Bug] 接入自定义模型 阿里的Qwen

### ISSUE THREAD

**Issue by xiaolan66** [ChatGPTNextWeb/ChatGPT-Next-Web#4772]
### Bug Description

这是错误代码
```
{
  "error": {
    "code": "invalid_parameter_error",
    "param": null,
    "message": "Range of top_p should be (0.0, 1.0)",
    "type": "invalid_request_error"
  }
}
```
问题就是这top_p参数的问题，程序默认的事整数1，而不是浮点数1.0

### Steps to Reproduce

{
  "error": {
    "code": "invalid_parameter_error",
    "param": null,
    "message": "Range of top_p should be (0.0, 1.0)",
    "type": "invalid_request_error"
  }
}

### Expected Behavior

{
  "error": {
    "code": "invalid_parameter_error",
    "param": null,
    "message": "Range of top_p should be (0.0, 1.0)",
    "type": "invalid_request_error"
  }
}

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by Dean-YZG** [comment]
Is there a screenshot of the interface request error in the browser console? As you know,  integer type and float type is both number in javascript , the param type of 'top_p' is number in nextchat, so i guess the error was caused by something else, for example, (0.0, 1.0) is a open interval

**Comment by shansing** [comment]
我也遇到了。跟浮点不浮点没关系，你改成字符串（用引号包裹）会报不是浮点数。改成`1.0`也没用。似乎真是开区间。建议手动处理，大于等于1时变成0.999之类。

**Comment by sanbei011** [comment]
我也遇到了这个问题!

**Comment by bequt** [comment]
我现在手动改成0.9是可以了，[是否未来考虑通过参数达到部署时进行配置。
目前阿里云免费开放这个模型，智商水平还是在线的。

**Comment by chenggb123** [comment]
确实，将top_p改为0.9可以正常使用，默认的1无法正常使用qwen模型，现在不知道如何修改默认的top_p
