### ISSUE TITLE
[Feature Request]: 增加复制对话的功能

### ISSUE THREAD

**Issue by muamua33** [ChatGPTNextWeb/ChatGPT-Next-Web#4774]
### Problem Description

增加复制对话的功能，方便对话进行分叉

### Solution Description

给对话增加复制功能，复制一个一模一样的对话

**Comment by Dean-YZG** [comment]
Thank you for your feedback, we will adopt the suggestion. Currently, we have a plan to support forking of conversations in V3 nextchat

**Comment by Leizhenpeng** [comment]
![CleanShot 2024-09-12 at 22 30 42@2x](https://github.com/user-attachments/assets/407f27be-4afe-4a19-8529-49fb90faad69)

暂且这样处理

**Comment by Leizhenpeng** [comment]
注意模型和历史记录都带着~
