### ISSUE TITLE
[Bug] 随机触发全屏报错

### ISSUE THREAD

**Issue by Zhou-Shilin** [ChatGPTNextWeb/ChatGPT-Next-Web#4775]
### Bug Description

随机触发全屏报错，触发位置不定（主页/面具/设置界面均可能触发），见Screenshot栏。

### Steps to Reproduce

1. Fork本项目
2. 使用Vercel部署，设置apikey和baseurl有关环境变量
3. 如果能打开主页，就可以正常聊天
4. 在使用过程中随机引发全屏报错，触发概率20%+

### Expected Behavior

不会有报错，功能正常运行。

### Screenshots

![28CDE880-E5FA-450A-9D7A-07910B338C69](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/86581525/f6013c92-43d7-49d8-9beb-ad5385d18c65)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Smartphone Device

iPad Air 5

### Smartphone OS

iPadOS 16.2 Beta 2

### Smartphone Browser

Safari

### Smartphone Browser Version

16.2 (Safari浏览器随系统版本更新，版本号与系统版本号相同)

### Additional Logs

Vercel服务器端没有输出日志。

**Comment by SpiralTower** [comment]
vercel服务器在国外，大陆访问网络时好时坏导致的

**Comment by Zhou-Shilin** [comment]
> vercel服务器在国外，大陆访问网络时好时坏导致的

我这边是开了全局的，也有这种情况

> The problem still exists with a proxy.

**Comment by Dean-YZG** [comment]
> > vercel服务器在国外，大陆访问网络时好时坏导致的
> 
> 我这边是开了全局的，也有这种情况
> 
> > The problem still exists with a proxy.

从目前的截图上看，因为有css资源未加载成功，导致报错，可以检查一下proxy的链接稳定性，可以打开safari的开发者工具，查看css资源下载情况。目前这种资源加载失败的情况是只局限在 截图中的css资源么，还是其他的资源也会出现这种加载失败的情况？

**Comment by Zhou-Shilin** [comment]
现在不怎么触发了，就是那天一直有问题 下次再碰到reopen吧 当时疏忽了除了截图都没记录 T^T
