### ISSUE TITLE
How to config Azure OpenAI?

### ISSUE THREAD

**Issue by hecongy** [ChatGPTNextWeb/ChatGPT-Next-Web#4787]
I tried this:
```
docker run -d -p 3000:3000 -e CODE={} -e AZURE_URL=https://{azure-resource-url}/openai/deployments/{deploy-name} -e AZURE_API_KEY={} -e AZURE_API_VERSION={} yidadaa/chatgpt-next-web
```

When open in browser, I got below error:

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/17422767/a2c8ec96-1632-4f58-9941-068d9c3677de)

Did I miss something in the docker command?

**Comment by hecongy** [comment]
> Please follow the [issue template](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) to update title and description of your issue.

The page is not found.

**Comment by romellfudi** [comment]
@hecongy did you fix it?

**Comment by romellfudi** [comment]
@hecongy I fixed it, just I set the full endpoint in the endpoint.

**Comment by hecongy** [comment]
Yes, I fix it, the issue is that I used a wrong AZURE_API_VERSION.
