### ISSUE TITLE
[Bug] 消息列表控制逻辑混乱

### ISSUE THREAD

**Issue by SuiYunsy** [ChatGPTNextWeb/ChatGPT-Next-Web#4788]
### Bug Description

对话后，点击顶上的标题，可以看到目前的消息列表：
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/104718844/4df97e9b-dee6-4241-a191-41581e7251f4)

点击”包含0条提示词“或者对话框顶上的”设置“按钮，看不到消息列表：
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/104718844/6df46586-d586-4437-8644-d7c9e061f15a)

### Steps to Reproduce

反之，点击对话框顶上的”设置“按钮，填入消息：
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/104718844/0a7521f0-f1fc-4783-b30c-6f8e8bb78bda)

现在点击”新的聊天“标题，反而看不到一点消息：
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/104718844/625fa5a8-ee9e-4bb9-85ec-b09dfbab6528)

### Expected Behavior

二者这样的设置逻辑是有什么特殊意义吗？
如果我想要控制历史的消息列表，应该点击”标题“还是”设置“进行修改控制？

个人认为是可以把二者统一，这样子便于操作。

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by lloydzhou** [comment]
1. 消息记录(chat history)
2. 会话设置(session mask config) 
是两个不同的东西。
