### ISSUE TITLE
接口如果返回的是201而不是200会导致意外情况

### ISSUE THREAD

**Issue by leadscloud** [ChatGPTNextWeb/ChatGPT-Next-Web#4797]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/da2e2372aa8490deee3fb50bd01dbdd9ca3f1dba/app/client/platforms/openai.ts#L216

```
if (
    !res.ok ||
    !res.headers
      .get("content-type")
      ?.startsWith(EventStreamContentType) ||
    res.status !== 200
  ) {
```

诸如nestjs中，post接口返回的默认是201，但以上判断是200，导致正常的stream内容直接以源内容格式显示，导致错误。

建议这个逻辑修改下。201也是res.ok

**Comment by Dean-YZG** [comment]
Thank you for your feedback, we will adopt the suggestion

**Comment by lloydzhou** [comment]
我想，当前项目是为了方便大家接入市面上的大多数大语言模型API，但是目前为止，这些服务商提供的API正常情况都是返回的200，所以这里是否还有更改的必要？
