### ISSUE TITLE
[Bug] nexthchat is stuck, how can I export my application data.

### ISSUE THREAD

**Issue by LinhanXu3928** [ChatGPTNextWeb/ChatGPT-Next-Web#4803]
### Bug Description

I'm using [NextChat_2.12.3_x64-setup.exe]. I entered too much content in the dialog box at once, which caused nextcat to get stuck, and every time I reopened it, it would get stuck. reinstalling without deleting the application data is also of no use.

### Steps to Reproduce

Click the pencil button on the already sent conversation to re edit the content, input a lot of content at once (I entered 5000 lines), then click confirm, the software will freeze

### Expected Behavior

Firstly, I would like to know the location of my application data so that I can transfer and save it. Secondly, I hope to fix this bug.

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/86815251/e1871af7-f8c7-476e-956c-71fa67787c67)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

windows 10

### Desktop Browser

chrome but not using

**Comment by lloydzhou** [comment]
你可以试试v2.15.0，这个版本有处理一个可能有关的优化。看看问题是否还在。
