### ISSUE TITLE
[Bug] 在新拉取项目到本地电脑上，不能通过 bun run dev 在本地运行

### ISSUE THREAD

**Issue by mazwei** [ChatGPTNextWeb/ChatGPT-Next-Web#4805]
### Bug Description

执行命令 bun run dev 后，提示如下：
webpack.JavascriptModulesPlugin has moved to webpack.javascript.JavascriptModulesPlugin
webpack.LibraryTemplatePlugin is deprecated and has been replaced by compilation.outputOptions.library or compilation.addEntry + passing a library option
SingleEntryPlugin was renamed to EntryPlugin
webpack.WebpackOptionsDefaulter is deprecated and has been replaced by webpack.config.getNormalizedWebpackOptions and webpack.config.applyWebpackOptionsDefaults

### Steps to Reproduce

1. 拉取项目：`git clone https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web.git`
2. 安装相关包：`bun install`
3. 运行项目：`bun bun run dev`

### Expected Behavior

请问怎么样才能在本地运行这个项目？

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by joe-ieta** [comment]
first using `npm run build` to build the project and then using "npm start" to start running it.
使用 npm run build 编译，然后运行 npm start
