### ISSUE TITLE
[Feature Request]: 能不能加入PDF文档分析功能

### ISSUE THREAD

**Issue by Why-SVIP** [ChatGPTNextWeb/ChatGPT-Next-Web#4806]
### Problem Description

我看插件那栏一直没有开发，想问能不能加入PDF分析功能

### Solution Description

求一个PDF分析

**Comment by vual** [comment]
可以通过中转接口实现调用pdf插件。https://github.com/vual/ChatGPT-Next-Web-Pro

**Comment by lloydzhou** [comment]
v2.15.0 支持插件

然后支持接入 docx 的api分析pdf作为插件使用
或者接入fastgpt的知识库作为插件
