### ISSUE TITLE
[Feature Request]: 可以添加url参数来自动填写key吗？

### ISSUE THREAD

**Issue by iOSFDTeam** [ChatGPTNextWeb/ChatGPT-Next-Web#4807]
### Problem Description

比如访问登陆页面：
https://app.nextchat.dev/#/auth
加了key的参数
https://app.nextchat.dev/#/auth?key=sk-xxxxxxxxxxxxxx
或者
https://app.nextchat.dev/#/auth?code=xxxxxxxxxxxxxx
这样用户进来后就自动填写，无需自己写

### Solution Description

支持URL参数

**Comment by iOSFDTeam** [comment]
> 参考设置fast_link
> 
> [#4555 (comment)](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4555#issuecomment-2076254760)

谢谢，我试过用setting可以设置，但是每次打开页面都会有个设置的提示，可以去掉吗？想要让用户无感知设置

**Comment by Jiayou-Chao** [comment]
现阶段只有url和key可以传入？我希望至少能再加上“model”可以改变默认的模型

**Comment by gyc-12** [comment]
> 现阶段只有url和key可以传入？我希望至少能再加上“model”可以改变默认的模型

现在支持这个吗

**Comment by lloydzhou** [comment]
不推荐
