### ISSUE TITLE
[Feature Request]: 什么时候能够添加GPT4o的支持？

### ISSUE THREAD

**Issue by day9011** [ChatGPTNextWeb/ChatGPT-Next-Web#4808]
### Problem Description

目前openai已经开放了GPT4o的接口，但是目前NextWeb没法支持图片上传

### Solution Description

学习GPT4o的UI，添加上传图片的UI

**Comment by Dream-Rainy** [comment]
目前版本2.12.3已经支持了啊
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/88184993/783d7118-6ad3-43b1-8bd0-1993913813f2)

**Comment by day9011** [comment]
部署了，需要2G的内存，感谢
