### ISSUE TITLE
[Bug] Not support key from https://github.com/chatanywhere/GPT_API_free

### ISSUE THREAD

**Issue by liudonghua123** [ChatGPTNextWeb/ChatGPT-Next-Web#4828]
### Bug Description

I got a free key and tested with `openai` python package with custom `base_url="https://api.chatanywhere.tech/v1"` successfully. But when I configured the same key in OpenAI API Key and "https://api.chatanywhere.tech/", "https://api.chatanywhere.tech" or "https://api.chatanywhere.tech/v1" in OpenAI Endpoint. None of them works.

The UI only shown this error.

```json
{
  "error": true,
  "message": "empty response from server"
}
```

### Steps to Reproduce

1. open the windows desktop app
2. fill `key` in `OpenAI API Key`, `https://api.chatanywhere.tech` in `OpenAI Endpoint`
3. back to conversation and try to input something

### Expected Behavior

work as expected.

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/2276718/651d3d2b-c983-4f5d-9465-a49649d1ec97)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Microsoft Windows [Version 10.0.22631.3672]

### Desktop Browser

Edge

### Desktop Browser Version

125

### Additional Logs

The tested code.

```python
from openai import OpenAI

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="<the-key-from-GPT_API_free>",
    base_url="https://api.chatanywhere.tech/v1"
    # base_url="https://api.chatanywhere.cn/v1"
)

completion = client.chat.completions.create(
    model="gpt-4",
    messages=[
        {
            "role": "user",
            "content": "How do I output all files in a directory using Python?",
        },
    ],
)
print(completion.choices[0].message.content)
```

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/2276718/0a8557c7-fdc5-4acc-87da-79f2202b8bf0)

**Comment by liudonghua123** [comment]
I tested the same key and `https://api.chatanywhere.tech` as `API Host` in [Chatbox](https://github.com/Bin-Huang/chatbox), it's working as expected.

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/2276718/1687141e-48ca-484e-bc7c-eeb2341bb020)

**Comment by fred-bf** [comment]
plz double check with you model provider

**Comment by liudonghua123** [comment]
> plz double check with you model provider

I use openai model provider and gpt4o model (also tried gpt3.5 model, but it's the same).

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/2276718/2de35d8f-0026-4c71-94f5-97be7da6d00c)

**Comment by liudonghua123** [comment]
It's my mistake, I forgot to copy the complete key which contains `sk-` prefix.
