### ISSUE TITLE
[Bug] 无法使用Deploy部署 Unable to deploy with Deploy

### ISSUE THREAD

**Issue by chatGPT-AI-API** [ChatGPTNextWeb/ChatGPT-Next-Web#4829]
### Bug Description

无法使用Deploy部署
Unable to deploy with Deploy

### Steps to Reproduce

1.转到开始使用
1. Go to Getting Started
2. 点击Deploy
2. Click Deploy
3.提示404，该页面不存在
3. prompt 404, the page doesn't exist.

### Expected Behavior

可以使用Deploy部署
Deployments can be made using Deploy

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/130991061/99a472fd-a7d7-4cda-822f-7d63aa15a0d4)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows 11

### Desktop Browser

Microsoft Edge

### Desktop Browser Version

126.0.2592.24

**Comment by 122cygf** [comment]
fork之后用vercel连接你fork出来的那个仓库
