### ISSUE TITLE
[Bug] ERR_SSL_SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by 18516329677** [ChatGPTNextWeb/ChatGPT-Next-Web#4833]
### Bug Description

{
  "cause": {
    "library": "SSL routines",
    "reason": "sslv3 alert handshake failure",
    "code": "ERR_SSL_SSLV3_ALERT_HANDSHAKE_FAILURE"
  }
}

### Steps to Reproduce

1. unraid 安装旁路由，旁路由安装clash出国
2. 群晖新建macvlan，macvlan 网关设置为旁路由
3. 群晖安装next-web, 网络选择macvlan
4. 本地ip加端口访问next-web，开始聊天
5. 报错

### Expected Behavior

正常使用next-web

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by fred-bf** [comment]
please check with your reverse proxy settings
