### ISSUE TITLE
无法显示自定义模型

### ISSUE THREAD

**Issue by curry-he** [ChatGPTNextWeb/ChatGPT-Next-Web#4836]
### Bug Description

部署时OPENAI_MODEL_LIST变量设置开头设置-all后，部署后网页设置自定义模型不显示

### Steps to Reproduce

1.首先vercel部署项目

2.添加环境变量OPENAI_MODEL_LIST变量，变量设置如下
-all,+gpt-3.5-turbo,+gpt-3.5-turbo-0301,+gpt-3.5-turbo-0613,+gpt-3.5-turbo-1106,+gpt-3.5-turbo-0125,+gpt-3.5-turbo-16k,+gpt-3.5-turbo-16k-0613,+gpt-3.5-turbo-instruct,+gpt-4,+gpt-4-0314,+gpt-4-0613,+gpt-4-1106-preview,+gpt-4-0125-preview,+gpt-4-32k,+gpt-4-32k-0314,+gpt-4-32k-0613,+gpt-4-turbo-preview,+gpt-4-turbo,+gpt-4-turbo-2024-04-09,+gpt-4o,+gpt-4o-2024-05-13,gpt-4-vision-preview,+dall-e-3,+gemini-1.0-pro,+gemini-1.5-pro-latest,+gemini-1.5-flash-latest,+gemini-pro-vision,+claude-3-haiku-20240307,+claude-3-sonnet-20240229,+claude-3-opus-20240229,+deepseek-chat,+deepseek-coder,+7376874536723251211=Jarvis-qwen-max,+7376906480815505419=Jarvis-moonshot-v1-128k,+7376907850977067008=Jarvis-MiniMax6.5s,+deepseek-ai/deepseek-v2-chat,+alibaba/Qwen2-72B-Instruct,+alibaba/Qwen1.5-110B-Chat,+01-ai/Yi-1.5-34B-Chat,+zhipuai/glm4-9B-chat,+mixtralai/Mistral-7B-Instruct-v0.2,+glm-4,+kimi,+Doubao-pro-128k,+Doubao-lite-128k

3.打开部署后的网页，添加自定义模型名称claude-3-haiku

4.点击聊天页面机器人图标切换模型，未显示自定义模型，点击聊天页面设置图标打开设置中模型选项也未显示自定义模型

### Expected Behavior

预期结果：
添加环境变量OPENAI_MODEL_LIST后首先移除所有模型，然后显示添加的模型，网页添加自定义模型可以正常显示和使用

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

Windows 11

### Desktop Browser

Chrome

### Desktop Browser Version

125.0.6422.142

### Smartphone Device

HONOR V30 Pro

### Smartphone OS

Harmony OS 4.0

### Smartphone Browser

Chrome

### Smartphone Browser Version

125.0.6422.165

**Comment by code-october** [comment]
这样就和预期不符了，部署的时候通过 -all 的行为就是允许网站管理者只开放部分模型使用，如果用户在前端自行添加模型名称就能调用所有模型，那管理者屏蔽了半天结果不起作用。
不过我认为用户在前端填入自定义接口和key的时候，自定义模型应该以前端配置为优先，而不是仍然按照环境变量的设置。

**Comment by curry-he** [comment]
@code-october 好的，明白了，就是目前模型列表是环境变量优先，所以前端自定义不起作用，如果前端显示的话，用户就可以通过自定义模型使用不在环境变量里的模型了，这样就不能限制用户了，对吧
