### ISSUE TITLE
内地访问速度缓慢[Bug] 

### ISSUE THREAD

**Issue by day9011** [ChatGPTNextWeb/ChatGPT-Next-Web#4838]
### Bug Description

部署好服务后，在内地访问，经常超时，然后报错。之前的版本不会出现这个问题，是不是某个组件被Ban掉了

### Steps to Reproduce

1. 本地化部署好服务
2. 在内地用IP访问
3. 超时报错
4. 后台出现错误
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/6396215/7ec97b56-e8cc-4c31-b01c-3d6b4e97ef8a)

### Expected Behavior

希望能优化内地访问速度的问题

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/6396215/713e9368-fc63-49be-825e-7c209cc44976)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/6396215/698ffa96-9bc2-42a4-9ff5-c0304722e79a)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [x] Server

**Comment by ersaijun** [comment]
http://ai.omegaxyz.cn/ 推荐平台，速度还可以

**Comment by day9011** [comment]
我添加了个代理，看来是访问速度慢导致的
