### ISSUE TITLE
[Bug] Message stuck in a loop

### ISSUE THREAD

**Issue by kungfudante** [ChatGPTNextWeb/ChatGPT-Next-Web#4840]
### Bug Description

Please see screenshot

### Steps to Reproduce

Please see screenshot

### Expected Behavior

Chat bot can respond normally

### Screenshots

![成功喜悦](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/106713170/cf8979e6-3381-46d4-8b8c-4f214333a6a4)

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows 11

### Desktop Browser

Edge

### Desktop Browser Version

125.0.2535.92

**Comment by fred-bf** [comment]
Its related to the mode you've been using
