### ISSUE TITLE
[Bug] AZURE related environment variables not work.

### ISSUE THREAD

**Issue by BaysianBrick** [ChatGPTNextWeb/ChatGPT-Next-Web#4843]
### Bug Description

I set all the 3 AZURE environment variables and redeploy the code, but it still can't reflect in the setting page, am I missing some configs? 

### Steps to Reproduce

set all the ENV
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/36719749/fca4ccfa-c040-41ec-a402-e426644f4126)

check the setting in the page.
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/36719749/a1ba55c3-6c3b-42e4-899d-b14e3ba9e875)

### Expected Behavior

Expected automatically switch to AZURE mode with all url/key set, from all users.

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

Win 10/11

### Desktop Browser

Edge

**Comment by potaly** [comment]
Same question as you
