### ISSUE TITLE
[Bug] 用v2.12.3镜像创建docker，可设置界面显示还是v2.11.2版本

### ISSUE THREAD

**Issue by bluezsd** [ChatGPTNextWeb/ChatGPT-Next-Web#4844]
### Bug Description

拉取v2.12.3镜像，创建ChatGPT-Next-Web的docker，但是设置界面显示ChatGPT-Next-Web的版本还是v2.11.2
![1](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/57561033/d57a640c-1d25-470b-be66-cedc683da290)
![2](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/57561033/0d20d29c-7457-41bc-b8a9-86279bd2f100)

### Steps to Reproduce

1、拉取v2.12.3镜像
2、创建ChatGPT-Next-Web的docker
但是设置界面显示ChatGPT-Next-Web的版本还是v2.11.2

### Expected Behavior

拉取v2.12.3镜像，创建ChatGPT-Next-Web的docker，但是设置界面显示ChatGPT-Next-Web的版本还是v2.11.2

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by ersaijun** [comment]
这个小问题建议看下代码，有部分是设置版本号的
