### ISSUE TITLE
一些语言无法与浏览器语言设置同步显示 [Bug] 

### ISSUE THREAD

**Issue by DDDDD12138** [ChatGPTNextWeb/ChatGPT-Next-Web#4853]
### Bug Description

我的浏览器设置为中文，但是默认显示的却是英文内容。
例如：将浏览器语言设置为中文或日文，却默认显示为英文内容，
若设置为英文或者法文，可以正确显示对应的内容

### Steps to Reproduce

1. 将浏览器语言设置为中文
2. 进入并刷新页面显示的为英文内容
3. 将浏览器设置为法语
4. 进入并刷新页面显示的为正确的法语内容

### Expected Behavior

浏览器语言为中文是，默认显示为中文

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/43703884/da0a7fdc-b8cc-488b-af37-b64ee306e8a5)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

Windows 10

### Desktop Browser

Edge, Chrome

### Desktop Browser Version

126

**Comment by lloydzhou** [comment]
Can you provide the browser version and detailed user agent information?

**Comment by DDDDD12138** [comment]
> Can you provide the browser version and detailed user agent information?


User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
Edge & Chrome 126.0 version

**Comment by DDDDD12138** [comment]
> Can you provide the browser version and detailed user agent information?

这和浏览器版本可能没什么关系，只是在代码中 navigator.language 和 国际化 language code 并没有完全对应上，例如我上面的截图， navigator.language 为 ’zh‘ 时，并不能和代码中 ’cn‘ 匹配上，新用户显示的语言会回退到默认语言 DEFAULT_LANG = "en"，还有一些语言也存在类似的情况

**Comment by lloydzhou** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/1826685/2bf36cd6-4161-4fc0-bbd4-a9b0d82b2a6b)

@DDDDD12138 
这个值在不同浏览器上的取值的情况可能有一些差异，所以，这里可能还需要考虑更完善一些

**Comment by lloydzhou** [comment]
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/1826685/cab6cf8a-b867-4e84-8062-6725e44cf90c)

同时，我也注意到项目中在语言这里实际是将  language和country code混用的。
可能也需要整体的规范一下。

**Comment by DDDDD12138** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language ![image](https://private-user-images.githubusercontent.com/1826685/345269993-2bf36cd6-4161-4fc0-bbd4-a9b0d82b2a6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5Nzc3ODAsIm5iZiI6MTcxOTk3NzQ4MCwicGF0aCI6Ii8xODI2Njg1LzM0NTI2OTk5My0yYmYzNmNkNi00MTYxLTRmYzAtYmJkNC1hOWIwZDgyYjJhNmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMDMzMTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTExMzQ5NDFkNzlmNTI5M2Q4NTVjMjcyMjUwMWU2MDdkOTk2ZDBiZjU3NTRkZmI2Yjg5YWUzZDExYzc4MmVmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BMs_RgZ-idI4R5msfBQEIp2ZAbnj0nWkhqWs4Nsl5S8)
> 
> @DDDDD12138 这个值在不同浏览器上的取值的情况可能有一些差异，所以，这里可能还需要考虑更完善一些

我观察到了这个区别，但同时项目中 getLanguage 方法默认 toLowerCase 返回了小写的字符，所以 #4855 这个 pr 中 lang 始终是小写的，就目前的情况，是可以解决与浏览器语言不同步的问题

**Comment by DDDDD12138** [comment]
> ![image](https://private-user-images.githubusercontent.com/1826685/345270789-cab6cf8a-b867-4e84-8062-6725e44cf90c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5Nzc3ODAsIm5iZiI6MTcxOTk3NzQ4MCwicGF0aCI6Ii8xODI2Njg1LzM0NTI3MDc4OS1jYWI2Y2Y4YS1iODY3LTRlODQtODA2Mi02NzI1ZTQ0Y2Y5MGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMDMzMTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY2YjUyZWI3YTViYmYwNjQ5MzM4MjFiMDkzODY2NGQ4MGU3YmM1NTQzMWMyMDI1Njk5NjNjNTExNGYxY2UwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lTUL7uA6DD1pUzSa8Ri5w4H-wPQBkUoiVk9uslasEbQ)
> 
> 同时，我也注意到项目中在语言这里实际是将 language和country code混用的。
> 
> > 例如en是语言，cn实际是国家代码，语言应该是zh/zh-CN，台湾地区的繁体中文应该是 zh-TW
> > 可能也需要整体的规范一下。

我注意到很多项目都存在这个问题，似乎没有比较完善方案去映射或者最佳实践，又例如香港地区和台湾地区都是以繁体为主，意味这可能不同的语言会对应同一份翻译文件

**Comment by lloydzhou** [comment]
我经手的有一些项目，使用混合的策略：
1. 如果一个语言不区分国家/地区，就使用语言本身（两个字符例如  ja）
2. 如果一个语言区分国家和地区，就使用完整的（zh-CN/zh-TW，有的时候为了考虑文件命名之类的方便，会使用linux中locale的命名方式zh_CN/zh_TW）

**Comment by DDDDD12138** [comment]
> 我经手的有一些项目，使用混合的策略：
> 
> 1. 如果一个语言不区分国家/地区，就使用语言本身（两个字符例如  ja）
> 2. 如果一个语言区分国家和地区，就使用完整的（zh-CN/zh-TW，有的时候为了考虑文件命名之类的方便，会使用linux中locale的命名方式zh_CN/zh_TW）

感谢老哥的建议！我本想基于你的建议做一些修改。
但可能存在其他问题：lang 被存入了 localStorage，若修改 language 值：
1.对于已经修改过语言的老用户，需要额外的兼容代码以实现平滑过渡(这部分代码可以认为是一次性的)
2.对于新用户，额外的兼容代码就是冗余的
所以我依然希望把他当成一个BUG去处理，不对现有的做过多的修改

**Comment by lloydzhou** [comment]
我想，这里是不是应该改成合理的方式，再针对旧数据做一下兼容？
而不是，在不合理的方案上不停的打补丁？

**Comment by lloydzhou** [comment]
@DDDDD12138 

或者使用另一个API去处理这个事情，而不是依赖字符串比较或者手工去添加一堆兼容的map

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/minimize
https://caniuse.com/?search=intl.locale （浏览器兼容性也挺好的）

可能是一个比较好的兼容处理的方案：
1. 使用`const locale = Intl.Locale(navigator.language).maximize()`
2. 判断`locale.region.toLowerCase()`在支持语言列表里面就使用region
3. 如果不在，就判断`locale.language`是否在支持语言里面。
4. 如果都不在，就使用默认语言


以下部分展示了不同格式的language使用`Intl.Locale.minimize`处理之后的格式
```
new Intl.Locale('zh').maximize()
-->  Intl.Locale { baseName: "zh-Hans-CN", numeric: false, language: "zh", script: "Hans", region: "CN" }

new Intl.Locale('zh-CN').maximize()
--> Intl.Locale { baseName: "zh-Hans-CN", numeric: false, language: "zh", script: "Hans", region: "CN" }

new Intl.Locale('zh-TW').maximize()
--> Intl.Locale { baseName: "zh-Hant-TW", numeric: false, language: "zh", script: "Hant", region: "TW" }

// https://answers.microsoft.com/zh-hans/microsoftedge/forum/all/edgeie%E7%AD%89%E6%B5%8F%E8%A7%88%E5%99%A8/52d04efc-6283-4d1c-a3d4-73984f8b485b
// 部分浏览器返回的格式是这样的
new Intl.Locale('zh-Hant-TW').maximize()
--> Intl.Locale { baseName: "zh-Hant-TW", numeric: false, language: "zh", script: "Hant", region: "TW" }

new Intl.Locale('zh-Hant').maximize()
--> Intl.Locale { baseName: "zh-Hant-TW", numeric: false, language: "zh", script: "Hant", region: "TW" }
```

**Comment by DDDDD12138** [comment]
> 1. Intl.Locale

受教了，我已经把之前提的关闭了

**Comment by DDDDD12138** [comment]
> @DDDDD12138
> 
> 或者使用另一个API去处理这个事情，而不是依赖字符串比较或者手工去添加一堆兼容的map
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/minimize https://caniuse.com/?search=intl.locale （浏览器兼容性也挺好的）
> 
> 可能是一个比较好的兼容处理的方案：
> 
> 1. 使用`const locale = Intl.Locale(navigator.language).maximize()`
> 2. 判断`locale.region.toLowerCase()`在支持语言列表里面就使用region
> 3. 如果不在，就判断`locale.language`是否在支持语言里面。
> 4. 如果都不在，就使用默认语言
> 
> 以下部分展示了不同格式的language使用`Intl.Locale.minimize`处理之后的格式
> 
> ```
> new Intl.Locale('zh').maximize()
> -->  Intl.Locale { baseName: "zh-Hans-CN", numeric: false, language: "zh", script: "Hans", region: "CN" }
> 
> new Intl.Locale('zh-CN').maximize()
> --> Intl.Locale { baseName: "zh-Hans-CN", numeric: false, language: "zh", script: "Hans", region: "CN" }
> 
> new Intl.Locale('zh-TW').maximize()
> --> Intl.Locale { baseName: "zh-Hant-TW", numeric: false, language: "zh", script: "Hant", region: "TW" }
> 
> // https://answers.microsoft.com/zh-hans/microsoftedge/forum/all/edgeie%E7%AD%89%E6%B5%8F%E8%A7%88%E5%99%A8/52d04efc-6283-4d1c-a3d4-73984f8b485b
> // 部分浏览器返回的格式是这样的
> new Intl.Locale('zh-Hant-TW').maximize()
> --> Intl.Locale { baseName: "zh-Hant-TW", numeric: false, language: "zh", script: "Hant", region: "TW" }
> 
> new Intl.Locale('zh-Hant').maximize()
> --> Intl.Locale { baseName: "zh-Hant-TW", numeric: false, language: "zh", script: "Hant", region: "TW" }
> ```

受教了，我已经把之前提的关闭了
