### ISSUE TITLE
gpt登录页面输入邮箱后本应该进入输入密码页面，但页面一直显示重置密码（应该是输入密码），输入密码后继续点击也没任何反应[Bug] 

### ISSUE THREAD

**Issue by Joe0033** [ChatGPTNextWeb/ChatGPT-Next-Web#4857]
### Bug Description

gpt登录页面输入邮箱后本应该进入输入密码页面，但页面一直显示重置密码（应该是输入密码），输入密码后继续点击也没任何反应[Bug]
gpt login page After entering the mailbox should enter the password page, but the page keeps showing reset password (should be input password), after entering the password and continue to click no response 
![4581718767292_ pic](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/173224976/c2a79936-9aae-416a-ac99-1834b53b8780)

### Steps to Reproduce

gpt登录页面输入邮箱后本应该进入输入密码页面，但页面一直显示重置密码（应该是输入密码），输入密码后继续点击也没任何反应[Bug]
gpt login page After entering the mailbox should enter the password page, but the page keeps showing reset password (should be input password), after entering the password and continue to click no response 

### Expected Behavior

gpt登录页面输入邮箱后本应该进入输入密码页面，但页面一直显示重置密码（应该是输入密码），输入密码后继续点击也没任何反应[Bug]
gpt login page After entering the mailbox should enter the password page, but the page keeps showing reset password (should be input password), after entering the password and continue to click no response 
![4581718767292_ pic](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/173224976/f3e9f425-b78a-4321-95ed-1fe6ebbeb31d)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by Joe0033** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> **Title:** After entering your email address on the gpt login page, you should enter the password input page, but the page keeps showing the reset password (should be the passwor input). After entering the password and continuing to click, nothing happens [Bug]

I hope so, but it's not. crying...

**Comment by QAbot-zh** [comment]
哭错地方了啊，官网问题跟这个项目有啥关系

**Comment by wuyuan5896** [comment]
我也是

**Comment by MarKoRen** [comment]
Have you solved this problem? I also encountered a similar problem.

**Comment by essenlee88** [comment]
刚解决了这个问题，我的方法：

**Comment by hxstrongest** [comment]
我重新配置了vpn的rul链接，就可以登陆ChatGPT了。

**Comment by zsui2354** [comment]
> 刚解决了这个问题，我的方法：浏览器语言改成英文，去掉自动翻译，直到进入登录chatgpt页面没有自动翻译成其他语言。输入用户名点击，可以看到continue后，页面上方的标题从重置密码变成了登录账号。然后可以正常登录

你的方法很有用

**Comment by zzxvnet** [comment]
> vpn的rul链接，就可

what rules

**Comment by aoao12321** [comment]
> 刚解决了这个问题，我的方法：浏览器语言改成英文，去掉自动翻译，直到进入登录chatgpt页面没有自动翻译成其他语言。输入用户名点击，可以看到continue后，页面上方的标题从重置密码变成了登录账号。然后可以正常登录

您的方法对我很有用。
