### ISSUE TITLE
[功能请求]：增加同个模型的不同api切换功能

### ISSUE THREAD

**Issue by crcdlixx** [ChatGPTNextWeb/ChatGPT-Next-Web#4860]
### Problem Description

有时候部分中转api会有各种报错 切换另一个api很麻烦（指需要把接口地址和Api Key都写一遍）

### Solution Description

用户可以填写一段预设 在输入栏上方加一个按钮来切换预设

**Comment by lloydzhou** [comment]
#4930 从结构上支持一个模型多个api（gpt的模型可以同时切换azure和openai）
