### ISSUE TITLE
[Feature Request]: 手机版长按聊天记录空白处会将文本复制黏贴到输入框占满屏幕

### ISSUE THREAD

**Issue by skhyk** [ChatGPTNextWeb/ChatGPT-Next-Web#4861]
### Problem Description

当gpt回复的文字足够长时，我需要拖拽屏幕上去看，经常会无意识稍微长按一个位置，输入框就出现了回答的文本，占满了整个屏幕。我再想看聊天记录就得把文本手动删除才能看到。

### Solution Description

能否增加一个设置，长按回答空白处时选择是否自动复制黏贴回答到输入框，或者长按仅复制，或者长按弹出一排选项再选择如何操作呢？

**Comment by lloydzhou** [comment]
已经修复
