### ISSUE TITLE
Please add support to: claude-3-5-sonnet-20240620

### ISSUE THREAD

**Issue by dantengdanteng** [ChatGPTNextWeb/ChatGPT-Next-Web#4866]
### Problem Description

Custom setting up this new model is not working! 

### Solution Description

Please support the latest **claude-3-5-sonnet-20240620** model
It came out just a short while ago.
Tried a bit, beats all..

**Comment by dantengdanteng** [comment]
> Please follow the [issue template](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) to update title and description of your issue.

issue template -> 404 - page not found

**Comment by hengstchon** [comment]
Already opened a pull request [#4869], wait for merging.
