### ISSUE TITLE
[Feature Request]: 怎么删除默认的几十条prompt? #4581

### ISSUE THREAD

**Issue by chengfengfengwang** [ChatGPTNextWeb/ChatGPT-Next-Web#4879]
### Problem Description

自带的prompt基本用不到，太复杂了...目前的删除只看到了针对自己新增的。
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/23279667/93bd8d18-90e6-4774-ae02-fd094ae8c84b)

### Solution Description

提供禁用自带prompt或者删除的功能

**Comment by QAbot-zh** [comment]
可以勾选隐藏内置面具：

![Clip_2024-06-24_14-01-11](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/d1466627-cb63-4699-aff3-ee2de90779a7)
