### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by aofly** [ChatGPTNextWeb/ChatGPT-Next-Web#4880]
### Bug Description

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/129035806/85677664-d0b1-4291-9766-22f205c9d5fc)
一直提示这个，不知道是什么原因

### Steps to Reproduce

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/129035806/ffd2a4b3-e435-440f-9c09-45146011d27f)

### Expected Behavior

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/129035806/d8ff3fa6-d52b-468e-b85f-51b8718dcd30)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

**Comment by QAbot-zh** [comment]
首先检查你的api是否是可以正常的，包括网络问题；
其次F12，打开网络请求，查看更具体的报错信息
