### ISSUE TITLE
[Bug] 一直在一个页面不动，等一会儿就显示bug

### ISSUE THREAD

**Issue by Mingdr** [ChatGPTNextWeb/ChatGPT-Next-Web#4881]
### Bug Description

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/16832088/76a1a09e-b4ba-4afe-ab5c-84c03d19bce6)

### Steps to Reproduce

直接进入主页，其他的都点击不了

### Expected Behavior

按理说应该正常进入对话，但是显示好像是个js错误

### Deployment Method

- [ ] Docker
- [x] Vercel
- [ ] Server

**Comment by SchraderZhang** [comment]
+1 我也遇到了同样的问题

**Comment by fred-bf** [comment]
please try reset you CDN/proxy service cache

**Comment by fred-bf** [comment]
duplicated, will be tracked in https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4882

**Comment by Mingdr** [comment]
> @Mingdr please try reset you CDN/proxy service cache

OK，it work
