### ISSUE TITLE
[Bug] v2.12.14版本添加代理后无法访问

### ISSUE THREAD

**Issue by Icestab** [ChatGPTNextWeb/ChatGPT-Next-Web#4887]
### Bug Description

同样的配置在2.12.2中使用PROXY_URL是可以正常使用的，更新2.12.3后就无法访问页面，2.12.4仍然存在这个问题

### Steps to Reproduce

我查看的2.12.4提到了修复这个问题，但是我下载代码后docker build仍然不行，一但加入PROXY_URL就无法访问页面，我查看了2.12.2-2.12.4的dockerfile中的不同 尝试使用 proxychains -f $conf node server.js; build，不知道为什么还是不行，这个dockerfile build 2.12.2版本是可是正常使用的。

### Expected Behavior

2.12.4可以使用PROXY_URL运行

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by hugoyue** [comment]
#4771 这个问题一直没有真正解决，请参考[Docker镜像无法使用PROXY_URL字段的解决办法](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4747#issuecomment-2129103228)

**Comment by Icestab** [comment]
> #4771 这个问题一直没有真正解决，请参考[Docker镜像无法使用PROXY_URL字段的解决办法](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4747#issuecomment-2129103228)

但是在之前版本都是可以正常使用的，这是我疑惑的地方，最近两个版本才不行了，我已经试过这个去掉引号，有引号，去掉0.0.0.0，三个版本的dockerfile来build最新版都不行

**Comment by hugoyue** [comment]
> 我已经试过这个去掉引号，有引号

参考这个 https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4747#issuecomment-2129103228 重新构建镜像

**Comment by hugoyue** [comment]
> > #4771 这个问题一直没有真正解决，请参考[Docker镜像无法使用PROXY_URL字段的解决办法](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4747#issuecomment-2129103228)
> 
> 但是在之前版本都是可以正常使用的，这是我疑惑的地方，最近两个版本才不行了，我已经试过这个去掉引号，有引号，去掉0.0.0.0，三个版本的dockerfile来build最新版都不行

对不起我看错了，你应该参考这个[解决方案](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4795#issuecomment-2141328050)，重新构建镜像

**Comment by hugoyue** [comment]
> > #4771 这个问题一直没有真正解决，请参考[Docker镜像无法使用PROXY_URL字段的解决办法](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4747#issuecomment-2129103228)
> 
> 但是在之前版本都是可以正常使用的，这是我疑惑的地方，最近两个版本才不行了，我已经试过这个去掉引号，有引号，去掉0.0.0.0，三个版本的dockerfile来build最新版都不行

Dockerfile 最后一部分替换成

```
CMD if [ -n "$PROXY_URL" ]; then \
   export HOSTNAME="0.0.0.0"; \
   protocol=$(echo $PROXY_URL | cut -d: -f1); \
   host=$(echo $PROXY_URL | cut -d/ -f3 | cut -d: -f1); \
   port=$(echo $PROXY_URL | cut -d: -f3); \
   conf=/etc/proxychains.conf; \
   echo "strict_chain" > $conf; \
   echo "proxy_dns" >> $conf; \
   echo "remote_dns_subnet 224" >> $conf; \
   echo "tcp_read_time_out 15000" >> $conf; \
   echo "tcp_connect_time_out 8000" >> $conf; \
   echo "localnet 127.0.0.0/255.0.0.0" >> $conf; \
   echo "localnet ::1/128" >> $conf; \
   echo "[ProxyList]" >> $conf; \
   echo "$protocol $host $port" >> $conf; \
   cat /etc/proxychains.conf; \
   proxychains -f $conf node server.js; \
   else \
   node server.js; \
   fi
```

**Comment by Icestab** [comment]
> > > #4771 这个问题一直没有真正解决，请参考[Docker镜像无法使用PROXY_URL字段的解决办法](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4747#issuecomment-2129103228)
> > 
> > 
> > 但是在之前版本都是可以正常使用的，这是我疑惑的地方，最近两个版本才不行了，我已经试过这个去掉引号，有引号，去掉0.0.0.0，三个版本的dockerfile来build最新版都不行
> 
> Dockerfile 最后一部分替换成
> 
> ```
> CMD if [ -n "$PROXY_URL" ]; then \
>    export HOSTNAME="0.0.0.0"; \
>    protocol=$(echo $PROXY_URL | cut -d: -f1); \
>    host=$(echo $PROXY_URL | cut -d/ -f3 | cut -d: -f1); \
>    port=$(echo $PROXY_URL | cut -d: -f3); \
>    conf=/etc/proxychains.conf; \
>    echo "strict_chain" > $conf; \
>    echo "proxy_dns" >> $conf; \
>    echo "remote_dns_subnet 224" >> $conf; \
>    echo "tcp_read_time_out 15000" >> $conf; \
>    echo "tcp_connect_time_out 8000" >> $conf; \
>    echo "localnet 127.0.0.0/255.0.0.0" >> $conf; \
>    echo "localnet ::1/128" >> $conf; \
>    echo "[ProxyList]" >> $conf; \
>    echo "$protocol $host $port" >> $conf; \
>    cat /etc/proxychains.conf; \
>    proxychains -f $conf node server.js; \
>    else \
>    node server.js; \
>    fi
> ```

你是对的，使用你提供的dockerfile成功编译了可以使用代理的镜像，我编译的amd64和arm64两个版本，有需要的可以拉取[docker pull icestab/chatgpt-next-web:v2.12.4]

**Comment by 757957414** [comment]
看到问题关闭我以为已经修复了，但试了一下发现并没有

**Comment by Icestab** [comment]
> 看到问题关闭我以为已经修复了，但试了一下发现并没有

我本地代理已经可以正常使用了，不知道你为什么不行，你是自己自己编译的吗，可以试下我编译的镜像，我这边已经用了好几天了

**Comment by 757957414** [comment]
> > 看到问题关闭我以为已经修复了，但试了一下发现并没有
> 
> 我本地代理已经可以正常使用了，不知道你为什么不行，你是自己自己编译的吗，可以试下我编译的镜像，我这边已经用了好几天了

我是从docker hub中拉取的镜像，程序能正常启动，遇到也是配置了代理之后就无法访问页面的情况。同时尝试在网页中配置网页代理也无效所以只能退回2.12.12版本

**Comment by Icestab** [comment]
> > > 看到问题关闭我以为已经修复了，但试了一下发现并没有
> > 
> > 
> > 我本地代理已经可以正常使用了，不知道你为什么不行，你是自己自己编译的吗，可以试下我编译的镜像，我这边已经用了好几天了
> 
> 我是从docker hub中拉取的镜像，程序能正常启动，遇到也是配置了代理之后就无法访问页面的情况。同时尝试在网页中配置网页代理也无效所以只能退回2.12.12版本

官方镜像并没有重新打包，我修复后重新打包上传了，你可以试试[docker pull icestab/chatgpt-next-web:v2.12.4]

**Comment by daychou** [comment]
Why this question has not been repaired. After adding the Proxy_url parameter, there is a problem with the monitoring 3000 in the official mirror. Although it is open source and free, I hope the official will repair the Docker mirror as soon as possible
