### ISSUE TITLE
[Feature Request]: Open API 07.09 断供会影响使用吗

### ISSUE THREAD

**Issue by wxywj1005** [ChatGPTNextWeb/ChatGPT-Next-Web#4890]
### Problem Description

Open API 07.09 断供会影响使用吗

### Solution Description

Open API 07.09 断供会影响使用吗

**Comment by amwihgu** [comment]
同好奇
same question here

**Comment by JerryXu09** [comment]
我觉得压根不会，OpenAI API本身就没有向中国开放过。这个项目是通过你的服务器请求OpenAI API的。只要你的服务器不在国内，或者用vercel什么的部署，都不会有问题。只是OpenAI最近风控有点严，国内媒体趁机炒作罢了。

**Comment by lloydzhou** [comment]
可能相关的issue 
#4998 #4993

**Comment by app-arianamini** [comment]
Why have all those bug tickets been closed with this feature request, even though the issue still exists?

**Comment by app-arianamini** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5004#issuecomment-2252183332
