### ISSUE TITLE
在mac图标风格统一的问题[Bug] 

### ISSUE THREAD

**Issue by MaoSuYu** [ChatGPTNextWeb/ChatGPT-Next-Web#4897]
### Bug Description

Mac下载dmg安装后是圆形图标，与macOS其他程序风格差异很大，但是我看到在public目录下的macos.png存在着圆角矩形的图标，请问能否修复这个问题？谢谢

### Steps to Reproduce

1.安装为Mac提供的dmg文件。
2.安装完成查看桌面会看到圆形图标。

### Expected Behavior

希望将圆形图标替换为public目录下的macos.png图标

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

macOS

**Comment by lloydzhou** [comment]
#4946
