### ISSUE TITLE
请问本地部署以后怎么才能外网访问呢？

### ISSUE THREAD

**Issue by 1825679767** [ChatGPTNextWeb/ChatGPT-Next-Web#4905]
搭建完成后使用“yarn start”启动，本地http://localhost:3000能正常使用，但是根据提示使用“node .next/standalone/server.js”命令打开想要换成外网访问，就报错了WHITE_WEBDEV_ENDPOINTS参数也是填写的0.0.0.0

**Comment by 1825679767** [comment]
▲ Next.js 14.1.1
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Ready in 56ms
fatal: not a git repository (or any of the parent directories): .git
[Build Config] No git or not from git repo.
 ⚠ Unsupported metadata viewport is configured in metadata export in /serviceWorkerRegister.js. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata themeColor is configured in metadata export in /serviceWorkerRegister.js. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
fatal: not a git repository (or any of the parent directories): .git
[Build Config] No git or not from git repo.
 ⚠ Unsupported metadata viewport is configured in metadata export in /prompts.json. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata themeColor is configured in metadata export in /prompts.json. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
fatal: not a git repository (or any of the parent directories): .git
[Build Config] No git or not from git repo.
 ⚠ Unsupported metadata viewport is configured in metadata export in /favicon.ico. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata themeColor is configured in metadata export in /favicon.ico. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
fatal: not a git repository (or any of the parent directories): .git
[Build Config] No git or not from git repo.
 ⚠ Unsupported metadata viewport is configured in metadata export in /site.webmanifest. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata themeColor is configured in metadata export in /site.webmanifest. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
[OpenAI Route] params  { path: [ 'v1', 'chat', 'completions' ] }
[Auth] allowed hashed codes:  []
[Auth] got access code:
[Auth] hashed access code: d41d8cd98f00b204e9800998ecf8427e
[User IP]  127.0.0.1
[Time]  2024/7/1 19:59:28
[Auth] admin did not provide an api key
[Proxy]  v1/chat/completions?path=v1&path=chat&path=completions
[Base Url] https://api.openai.com
fatal: not a git repository (or any of the parent directories): .git
[Build Config] No git or not from git repo.
 ⚠ Unsupported metadata viewport is configured in metadata export in /serviceWorker.js. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
 ⚠ Unsupported metadata themeColor is configured in metadata export in /serviceWorker.js. Please move it to viewport export instead.
Read more: https://nextjs.org/docs/app/api-reference/functions/generate-viewport
[OpenAI]   [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}
}
[OpenAI Route] params  { path: [ 'v1', 'chat', 'completions' ] }
[Auth] allowed hashed codes:  []
[Auth] got access code:
[Auth] hashed access code: d41d8cd98f00b204e9800998ecf8427e
[User IP]  127.0.0.1
[Time]  2024/7/1 19:59:38
[Auth] admin did not provide an api key
[Proxy]  v1/chat/completions?path=v1&path=chat&path=completions
[Base Url] https://api.openai.com
[OpenAI]   [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}
}

**Comment by lloydzhou** [comment]
可以搜索（或者询问AI）一些内网穿透相关技术

这些东西与本项目无关，先关闭issue
