### ISSUE TITLE
[Bug] docker 镜像更新到latest还是提示v2.12.3，网页端还是提示升级。

### ISSUE THREAD

**Issue by lukemin** [ChatGPTNextWeb/ChatGPT-Next-Web#4909]
### Bug Description

[Bug] docker 镜像更新到latest还是提示v2.12.3，网页端还是提示升级。

### Steps to Reproduce

[Bug] docker 镜像更新到latest还是提示v2.12.3，网页端还是提示升级。

### Expected Behavior

希望能版本号统一一下。

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/12003375/4a2a403a-7e00-4c93-864b-85e1bf01e406)

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by Why-SVIP** [comment]
哥 解决了吗 我差点把12.3删了 安装.4

**Comment by lukemin** [comment]
solved
