### ISSUE TITLE
[Feature Request]: V2.12.4 之后使用claude 3.5 模型会强制走claude API，是否可以兼容Open API，可以使用中转平台的key呢。

### ISSUE THREAD

**Issue by alanblogooo** [ChatGPTNextWeb/ChatGPT-Next-Web#4912]
### Problem Description

 V2.12.4 之后使用claude 3.5 模型会强制走claude API，是否可以兼容Open API，可以使用中转平台的key呢。

### Solution Description

 V2.12.4 之后使用claude 3.5 模型会强制走claude API，是否可以兼容Open API，可以使用中转平台的key呢。

**Comment by czh020110** [comment]
我也觉得，中转只能用openai的模型了

**Comment by Silentely** [comment]
临时办法 claude重定向 增加模型就可以中转

**Comment by czh020110** [comment]
或者部署到vercel上的时候把模型都去了，全部自定义模型

**Comment by lloydzhou** [comment]
能列一下哪些中转平台吗？
或许可以做一个计划，对这些中转平台做一些兼容

**Comment by czh020110** [comment]
> 能列一下哪些中转平台吗？ 或许可以做一个计划，对这些中转平台做一些兼容

中转平台太多了，大多数是由one-api开源项目做的中转平台，但不管什么模型都走的是OpenAI服务商，用的格式都是OpenAI_key和Base_url

**Comment by ssssssshi** [comment]
> 能列一下哪些中转平台吗？
> 
> 或许可以做一个计划，对这些中转平台做一些兼容

one-api

**Comment by darwintree** [comment]
> 能列一下哪些中转平台吗？ 或许可以做一个计划，对这些中转平台做一些兼容

aihubmix

**Comment by alanblogooo** [comment]
我找到可以让其他模型走openai接口的方法了，就是自定义模型，比如自定义：claude-3-5-sonnet-20240620@OpenAI  ,那么这个模型就会走OpenAI的代理地址接口，其他模型参考这个设置就可以了。

**Comment by chnqwe4880** [comment]
> 我找到可以让其他模型走openai接口的方法了，就是自定义模型，比如自定义：claude-3-5-sonnet-20240620@OpenAI ,那么这个模型就会走OpenAI的代理地址接口，其他模型参考这个设置就可以了。

通过你的方式，我自己的中转服务也能成功使用了
