### ISSUE TITLE
[Feature Request]: 能不能加一个”继续生成“的选项。接着前一条没有输出完整的对话继续生成。

### ISSUE THREAD

**Issue by bestZwei** [ChatGPTNextWeb/ChatGPT-Next-Web#4914]
### Problem Description

能不能加一个”继续生成“的选项。接着前一条没有输出完整的对话继续生成。

### Solution Description

能不能加一个”继续生成“的选项。接着前一条没有输出完整的对话继续生成。

**Comment by lloydzhou** [comment]
可以试试，直接通过对话的形式让大模型继续生成
