### ISSUE TITLE
我怎么设置他成为一个子目录呢？nginx

### ISSUE THREAD

**Issue by bbhxwl** [ChatGPTNextWeb/ChatGPT-Next-Web#4928]
我想访问我主站 的/gpt 路径，代理这个地址。
测试了下404，资料加载不了。
location /gpt {
       proxy_pass http://127.0.0.1:6003/;
       proxy_buffering off;
       proxy_read_timeout 100s;
    }

**Comment by Interfish** [comment]
Same quesiton here

**Comment by lloydzhou** [comment]
@bbhxwl @Interfish 
try this:

```
server {
    listen       80;
    server_name _;
    location ~ /(_next|config|google-fonts|serviceWorkerRegister) {
        proxy_pass http://nextchat:3000;
    }
    location /chat {
        rewrite /chat/(.*) /$1 break;
        proxy_pass http://nextchat:3000;
        proxy_buffering off;
        proxy_read_timeout 100s;
    }
}
```

**Comment by lloydzhou** [comment]
another version:
```
server {
    listen       80;
    server_name _;
    location / {
        # can serve other site files, and try "@chat" at last
        try_files $uri $uri/ @chat;
    }
    location @chat {
        rewrite /chat/(.*) /$1 break;
        proxy_pass http://nextchat:3000;
        proxy_buffering off;
        proxy_read_timeout 100s;
    }
}

```

**Comment by bbhxwl** [comment]
> another version:
> 
> ```
> server {
>     listen       80;
>     server_name _;
>     location / {
>         # can serve other site files, and try "@chat" at last
>         try_files $uri $uri/ @chat;
>     }
>     location @chat {
>         rewrite /chat/(.*) /$1 break;
>         proxy_pass http://nextchat:3000;
>         proxy_buffering off;
>         proxy_read_timeout 100s;
>     }
> }
> ```

This definitely won't work because my main path has other websites and I just want them to be a part of my website

**Comment by bbhxwl** [comment]
> @bbhxwl @Interfish try this:
> 
> ```
> server {
>     listen       80;
>     server_name _;
>     location ~ /(_next|config|google-fonts|serviceWorkerRegister) {
>         proxy_pass http://nextchat:3000;
>     }
>     location /chat {
>         rewrite /chat/(.*) /$1 break;
>         proxy_pass http://nextchat:3000;
>         proxy_buffering off;
>         proxy_read_timeout 100s;
>     }
> }
> ```

[emerg] 2408809#2408809: "proxy_pass" cannot have URI part in location given by regular expression, or inside named location, or inside "if" statement, or inside "limit_except" block in

**Comment by bbhxwl** [comment]
> https://gist.github.com/lloydzhou/1bd2f63a85e5a622716d001a3a9c5a8d
> 
> the 2 version, work fine
> 
> ![image](https://private-user-images.githubusercontent.com/1826685/347278495-f7644296-704c-45d0-b758-738d153b6de1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1OTQ0NTcsIm5iZiI6MTcyMDU5NDE1NywicGF0aCI6Ii8xODI2Njg1LzM0NzI3ODQ5NS1mNzY0NDI5Ni03MDRjLTQ1ZDAtYjc1OC03MzhkMTUzYjZkZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMDY0OTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYxZmQ4ZDRkMDU1OTY0M2ZhZTAwMjc0MmZhNzg0ZTI4MDczZTVlMjAwNjg1NmIwZDNhMjgzNmQ0ZTEyNDEwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zh7RmIcXzWJ9SMniSxYIFjrdO0u0iaz6NKqt3_TztW0)

What I mean is that your root directory cannot be used for reverse proxy of other websites, right?

**Comment by kilgrims** [comment]
Have you solved it already?

**Comment by P2K0** [comment]
> https://gist.github.com/lloydzhou/1bd2f63a85e5a622716d001a3a9c5a8d
> 
> 2. 版本，运行良好
> 
> ![图像](https://private-user-images.githubusercontent.com/1826685/347278495-f7644296-704c-45d0-b758-738d153b6de1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDk5MzYsIm5iZiI6MTcyNjcwOTYzNiwicGF0aCI6Ii8xODI2Njg1LzM0NzI3ODQ5NS1mNzY0NDI5Ni03MDRjLTQ1ZDAtYjc1OC03MzhkMTUzYjZkZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMDEzMzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGY3NmJhNDRlZWI0NDE3ODFlMzU2MWQ5NjZiMWIwNmI4N2E2NzEwZDk3NWJlNWYxYTdiOGE4NDYyNWNhNWFkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yGc2BIBlkKgmebApwUKhMHqYAO4Nt5-3WKv_dDz3VC4)

没有用 其他资源跟路径跳转任然 404 
这种做法 如果当前站点有其他子站的话 会占用路径
也许需要 next中配置 basePath  assetPrefix
