### ISSUE TITLE
[Bug] 通过设置密码访问配置的环境变量方式的所有azure配置全部失效, 截止commit 70907ea还是正常的

### ISSUE THREAD

**Issue by lpdswing** [ChatGPTNextWeb/ChatGPT-Next-Web#4945]
### Bug Description

通过设置密码访问配置的环境变量方式的所有azure配置全部失效, 截止commit 70907ea还是正常的

### Steps to Reproduce

在设置中配置azure的相关参数,接口是可以正常请求的
<img width="1053" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/20874036/5d07efe9-4217-436d-8643-f897e9e21560">
这是我的配置, 之前一起正常, 版本更新到2.12.4后出现404
<img width="896" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/20874036/7ac3fdcf-f827-428c-8f29-ddf049ab57b6">
如果在设置中指定azure是正常的
<img width="1098" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/20874036/4f06d3e7-4d7c-4457-9f2b-1e6a3b00bbfb">

### Expected Behavior

希望输入密码可以正常加载环境变量的配置

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop OS

macos 14.5

### Desktop Browser

edge

**Comment by itcodes** [comment]
跟我遇到的一样。。感觉是这条 pr 的影响。然后 readme 还没更新。

**Comment by ice-lemon** [comment]
相同问题，如何解决？

**Comment by ice-lemon** [comment]
自己fork的暂时回滚到一周前的版本吧

**Comment by itcodes** [comment]
> 自己fork的暂时回滚到一周前的版本吧

你回滚后解决了吗

**Comment by ice-lemon** [comment]
> > 自己fork的暂时回滚到一周前的版本吧
> 
> 你回滚后解决了吗

用一周前的提交创建了个新分支，重新部署一下就好了

**Comment by lloydzhou** [comment]
@lpdswing 
关于你提到的配置失效，我尝试找了一下可能的原因，你可以帮忙看看是不是这样：
1. 按之前的配置模式`https://{azure-resource-url}/openai/deployments/{deploy-name}`
> 这个旧的配置实际上有问题：就是不管切换什么模型，只要走`azure`都只能发到这一个`deploy-name`对应的模型（也就是说在之前的版本在`azure`模式下切换模型是没有任何作用的）
2. pr (#4930) 实际上是解决了这个无法切换的问题。但是这里需要配合`CUSTOM_MODELS`借用`model_name=display_name`的格式来处理`azure`控制台`model_name`和`deployment_name`的对应关系（参考https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4930#issuecomment-2213521448）
> 例如：部署了gpt-3.5-turbo的模型，deployment_name为gpt3.5，那么在CUSTOM_MODELS里面加上`+gpt-3.5-turbo=gpt-3.5`应该就能解决你遇到的 deployment not found的问题



另外：
1. 前面这个pr合并的时候，对文档没有做及时更新（这里接下来会处理）
2. 这个pr针对一些旧的配置，没有做好向前兼容，这里需要想一下看看怎么处理会更好

**Comment by lloydzhou** [comment]
针对旧配置的向前兼容逻辑：

可以考虑判断一下`CUSTOM_MODELS`如果没有拿到`deployment_name`，并且`AZURE_URL`配置中包含`deploy-name`的时候，还是使用`AZURE_URL`中的`deploy-name`（而不是使用url中传递过来的`deployment_name`，这样应该就能避免旧配置导致的deployment not found的错误）

**Comment by itcodes** [comment]
> @lpdswing 关于你提到的配置失效，我尝试找了一下可能的原因，你可以帮忙看看是不是这样：
> 
> 1. 按之前的配置模式`https://{azure-resource-url}/openai/deployments/{deploy-name}`
> 
> > 这个旧的配置实际上有问题：就是不管切换什么模型，只要走`azure`都只能发到这一个`deploy-name`对应的模型（也就是说在之前的版本在`azure`模式下切换模型是没有任何作用的）
> 
> 2. pr ([support azure deployment name #4930](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4930)) 实际上是解决了这个无法切换的问题。但是这里需要配合`CUSTOM_MODELS`借用`model_name=display_name`的格式来处理`azure`控制台`model_name`和`deployment_name`的对应关系（参考[https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4930#issuecomment-2213521448）](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4930#issuecomment-2213521448%EF%BC%89)
> 
> > 例如：部署了gpt-3.5-turbo的模型，deployment_name为gpt3.5，那么在CUSTOM_MODELS里面加上`+gpt-3.5-turbo=gpt-3.5`应该就能解决你遇到的 deployment not found的问题
> 
> 另外：
> 
> 1. 前面这个pr合并的时候，对文档没有做及时更新（这里接下来会处理）
> 2. 这个pr针对一些旧的配置，没有做好向前兼容，这里需要想一下看看怎么处理会更好

@lloydzhou 你好，我的 model name 是 gpt-4o，我deployment_name也是gpt-4o，同时我用了CUSTOM_MODELS来限制`-all,+gpt-4o`，AZURE_URL是https://xxx.openai.azure.com/部署后，会出现 2 个版本的 gpt-4o，分别是 gpt4o(openai),gpt
4o(azure)，并且默认版本是gpt4o(openai)，如下图所示：
![CleanShot 2024-07-08 at 18 26 59@2x](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/8282645/3296a4e3-c290-4057-ac90-2658dc6f0561)

**Comment by Sha1rholder** [comment]
Same problem. Please update the document of the project. Thanks!

我遇到了一样的问题，请作者更新一下README来解释如何修改azure url，非常感谢！

**Comment by lloydzhou** [comment]
预计这个pr今天可会合并https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4953/files#diff-e6db595f1598cdd1968f25675bddebde43afe7e5a39e0aade96034d51c072ee7R161

**Comment by itcodes** [comment]
> 预计这个pr今天可会合并https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/4953/files#diff-e6db595f1598cdd1968f25675bddebde43afe7e5a39e0aade96034d51c072ee7R161

@lloydzhou 这个也解决了出现 2 个模型的困惑吗？比如 gpt4(openai)和 gpt4(azure)

**Comment by lloydzhou** [comment]
@itcodes 
1. 由于旧版对azure的处理本质上是对openai的覆盖，这个逻辑并不符合我们希望多个不同的ServiceProvider并存的情况。
2. 这里不能做到完全的无感知的升级。
3. 所以，你遇到的这个问题，在这个pr合并之后，只能通过更改`custom_models=+gpt-4o@azure={deploy-id}`的方式解决。

**Comment by itcodes** [comment]
> @itcodes
> 
> 1. 由于旧版对azure的处理本质上是对openai的覆盖，这个逻辑并不符合我们希望多个不同的ServiceProvider并存的情况。
> 2. 这里不能做到完全的无感知的升级。
> 3. 所以，你遇到的这个问题，在这个pr合并之后，只能通过更改`custom_models=+gpt-4o@azure={deploy-id}`的方式解决。
@lloydzhou 感谢解答
custom_models=-all+gpt-4o 这个不行了是吗？比如我部署名跟模型名都是 gpt-4o，如果按照新的，custom_models=+gpt-4o@azure=gpt-4o 这样吗？

**Comment by Sha1rholder** [comment]
非常支持这个更新，原本azure openai url要设置deploy name就很不合理吗，更新后可以使用多个azure部署的服务了。更新后希望能记得把文档同步更新好

**Comment by lpdswing** [comment]
> +gpt-3.5-turbo=gpt-3.5

我试了一下这样可以的
<img width="601" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/20874036/f12bfa38-cb55-4056-942c-729f22c921a0">
<img width="615" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/20874036/9db7ff4e-9c56-49e6-a579-f80ca5e14f92">
<img width="489" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/20874036/8f75d925-b8a0-4602-874a-c0b78f959daf">

**Comment by yexia553** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> > +gpt-3.5-turbo=gpt-3.5
> 
> I tried it and it worked <img alt="image" width="601" src="https://private-user-images.githubusercontent.com/20874036/346846119-f12bfa38-cb55-4056-942c-729f22c921a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjkyNjksIm5iZiI6MTcyMDc2ODk2OSwicGF0aCI6Ii8yMDg3NDAzNi8zNDY4NDYxMTktZjEyYmZhMzgtY2I1NS00MDU2LTk0MmMtNzI5ZjIyYzkyMWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA3MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOTA0YjJlNmE4Zjc5MjlhNzJjM2M3MGQ0ODNlYTYyZjc4NDA0MTNjYzgwYWJlMWM0NDlhYjFjYmYzMGFiYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zUfA88-S2iZa5HUpeO4LNMwgQnA8zjuuOPm-lEf9Ivk"> <img alt="image" width="615" src="https://private-user-images.githubusercontent.com/20874036/346846359-9db7ff4e-9c56-49e6-a579-f80ca5e14f92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjkyNjksIm5iZiI6MTcyMDc2ODk2OSwicGF0aCI6Ii8yMDg3NDAzNi8zNDY4NDYzNTktOWRiN2ZmNGUtOWM1Ni00OWU2LWE1NzktZjgwY2E1ZTE0ZjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA3MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmODA1MTExMDYwNzM5OGJmNzMwYTMwN2Q5YjlhOTRiNWU5ZTUwZGMwMGY5MDY2MTQ4NGZhNDc5NzgxMjQyZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cwor8-5BP8dvPXXgwTKNkyWyRrBwN3yCPbO_vJ_40vk"> <img alt="image" width="489" src="https://private-user-images.githubusercontent.com/20874036/346846625-8f75d925-b8a0-4602-874a-c0b78f959daf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjkyNjksIm5iZiI6MTcyMDc2ODk2OSwicGF0aCI6Ii8yMDg3NDAzNi8zNDY4NDY2MjUtOGY3NWQ5MjUtYjhhMC00NjAyLTg3NGEtYzBiNzhmOTU5ZGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA3MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMDg1OTAxMGRmMzYwMjAzMGYyY2FmZGYwMjhlN2M3MzIwMTJiMjMyMWRhNjRjZDJkOTljZTU5MGQwZjg0NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-5Bym6xD6INrHahLta20sFh9r2WEv8bNQSyuqAjuznA">

请问你是哪个commit这样配置可以使用？我enable了自动更新，使用你的配置不行，readme里面的配置也不行

**Comment by ice-lemon** [comment]
> > > Bot detected the issue body's language is not English, translate it automatically.
> > 
> > 
> > > +gpt-3.5-turbo=gpt-3.5
> > 
> > 
> > I tried it and it worked <img alt="image" width="601" src="https://private-user-images.githubusercontent.com/20874036/346846119-f12bfa38-cb55-4056-942c-729f22c921a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjkyNjksIm5iZiI6MTcyMDc2ODk2OSwicGF0aCI6Ii8yMDg3NDAzNi8zNDY4NDYxMTktZjEyYmZhMzgtY2I1NS00MDU2LTk0MmMtNzI5ZjIyYzkyMWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA3MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOTA0YjJlNmE4Zjc5MjlhNzJjM2M3MGQ0ODNlYTYyZjc4NDA0MTNjYzgwYWJlMWM0NDlhYjFjYmYzMGFiYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zUfA88-S2iZa5HUpeO4LNMwgQnA8zjuuOPm-lEf9Ivk"> <img alt="image" width="615" src="https://private-user-images.githubusercontent.com/20874036/346846359-9db7ff4e-9c56-49e6-a579-f80ca5e14f92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjkyNjksIm5iZiI6MTcyMDc2ODk2OSwicGF0aCI6Ii8yMDg3NDAzNi8zNDY4NDYzNTktOWRiN2ZmNGUtOWM1Ni00OWU2LWE1NzktZjgwY2E1ZTE0ZjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA3MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmODA1MTExMDYwNzM5OGJmNzMwYTMwN2Q5YjlhOTRiNWU5ZTUwZGMwMGY5MDY2MTQ4NGZhNDc5NzgxMjQyZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cwor8-5BP8dvPXXgwTKNkyWyRrBwN3yCPbO_vJ_40vk"> <img alt="image" width="489" src="https://private-user-images.githubusercontent.com/20874036/346846625-8f75d925-b8a0-4602-874a-c0b78f959daf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjkyNjksIm5iZiI6MTcyMDc2ODk2OSwicGF0aCI6Ii8yMDg3NDAzNi8zNDY4NDY2MjUtOGY3NWQ5MjUtYjhhMC00NjAyLTg3NGEtYzBiNzhmOTU5ZGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA3MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMDg1OTAxMGRmMzYwMjAzMGYyY2FmZGYwMjhlN2M3MzIwMTJiMjMyMWRhNjRjZDJkOTljZTU5MGQwZjg0NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-5Bym6xD6INrHahLta20sFh9r2WEv8bNQSyuqAjuznA">
> 
> 请问你是哪个commit这样配置可以使用？我enable了自动更新，使用你的配置不行，readme里面的配置也不行

+{displayname}@azure={deployname} 这样可以了的
