### ISSUE TITLE
[Bug] Repeat answers from Gemini

### ISSUE THREAD

**Issue by Graysonzhan** [ChatGPTNextWeb/ChatGPT-Next-Web#4955]
### Bug Description

When asking Google Gemini a question, it provides an answer that is repetitive, and reuses the same phrases and sentences within its response.

### Steps to Reproduce

Any question asked to Google Gemini will trigger this issue.

### Expected Behavior

Google Gemini stops sending repetitive responses.

### Screenshots

![screenshot](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/130341571/537a5118-983d-4bc4-a6f1-80903dd0bdcf)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop Browser

Chrome

### Desktop Browser Version

Latest

**Comment by lloydzhou** [comment]
@Graysonzhan fixed

**Comment by Graysonzhan** [comment]
> @Graysonzhan fixed

Thanks a lot!
