### ISSUE TITLE
自定义接口无法正常使用AWS的Claude模型

### ISSUE THREAD

**Issue by Aprilpl** [ChatGPTNextWeb/ChatGPT-Next-Web#4957]
### Bug Description

作者你好，这是一个非常棒的项目，但我在使用过程中遇到一个问题：自定义接口接入自己部署的litellm，OpenAI模型正常，但自定义的AWS的Claude模型异常，报错信息：
```
{
  "error": {
    "message": "BedrockException - BedrockException - bedrock does not support parameters: {'presence_penalty': 0, 'frequency_penalty': 0}, for model=anthropic.claude-3-5-sonnet-20240620-v1:0. To drop these, set `litellm.drop_params=True` or for proxy:\n\n`litellm_settings:\n drop_params: true`\n",
    "type": null,
    "param": null,
    "code": 500
  }
}
```
请问有什么好的解决方法吗？

### Steps to Reproduce

- 异常：anthropic.claude-3-5-sonnet-20240620-v1:0
<img width="634" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/67181825/9bbcf241-2f69-4887-8b82-52f6e13645ab">

PS: 通过代码方式使用anthropic.claude-3-5-sonnet-20240620-v1:0是可用的。

### Expected Behavior

通过自定义接口，我能够在web上正常使用AWS的Claude服务。

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

fadsfads

### Desktop Browser

fadsfads

**Comment by lloydzhou** [comment]
https://litellm.vercel.app/docs/completion/drop_params

> set `litellm.drop_params=True` or 
> or for proxy:
```
- litellm_params:
    drop_params: true # 👈 KEY CHANGE
```
