### ISSUE TITLE
[Bug] Type error: 'serverConfig.azureUrl' is possibly 'undefined'.

### ISSUE THREAD

**Issue by buoooou** [ChatGPTNextWeb/ChatGPT-Next-Web#4959]
### Bug Description

vercel和cloudflare无修改代码情况下，根据readme部署都报错
Type error: 'serverConfig.azureUrl' is possibly 'undefined'.
 81 |           const [_, providerName] = fullName.split("@");
  82 |           if (providerName === "azure" && !displayName) {
> 83 |             const [_, deployId] = serverConfig.azureUrl.split("deployments/");
     |                                   ^
  84 |             if (deployId) {
  85 |               realDeployName = deployId;
  86 |             }

### Steps to Reproduce

按照readme中cloudflare和vercel部署教程操作，直接报错异常，感觉是编译异常

### Expected Behavior

按照readme中cloudflare和vercel部署教程操作，直接报错异常，感觉是编译异常

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

**Comment by lloydzhou** [comment]
fixed: 147fc9a35a39187babb2b5aae156d47949547423
