### ISSUE TITLE
[Bug] masks.json文件找不到

### ISSUE THREAD

**Issue by gongjing2012** [ChatGPTNextWeb/ChatGPT-Next-Web#4961]
### Bug Description

masks.json文件找不到，本地报错

### Steps to Reproduce

masks.json文件找不到，本地报错

### Expected Behavior

masks.json文件找不到，本地报错

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

window11

### Desktop Browser

Chrome

### Additional Logs

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/34706161/74c155c1-1b75-4f10-8d7b-48642efed34d)

**Comment by lloydzhou** [comment]
请问是使用什么命令本地启动的项目？

不管是yarn dev还是yarn run build都会生成masks.json
> 这个文件其实是之前版本中内置的/app/masks/ 中定义的mask编译之后的文件

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/1826685/3de4736d-b7b7-49ce-8d06-d3fa3133f434)

**Comment by gongjing2012** [comment]
好的，谢谢回复。用的npm

**Comment by gongjing2012** [comment]
明白了，谢谢，我使用npm  run build就有了。
