### ISSUE TITLE
[Bug] 面具（以文搜图，小红书写手等）返回消息体中图片错误

### ISSUE THREAD

**Issue by oicoderr** [ChatGPTNextWeb/ChatGPT-Next-Web#4962]
### Bug Description

面具（以图搜文，小红书等）返回消息体中图片错误，无法展示，观察 image URL 有误

### Steps to Reproduce

1. 选择面具
2. 小红书写手/以文搜图
3. 图片错误并无法展示

### Expected Behavior

正确显示

### Screenshots

小红书写作：
<img width="715" alt="企业微信截图_b2165a47-89cb-49ab-89ae-4e897f4f15d6" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/25761931/cb82860c-c2f9-4518-b23c-281c0acd8d12">
图片真实链接（https://example.com/lavenderfields.jpg）

以文搜图：
<img width="737" alt="企业微信截图_0c78defc-275e-4e3b-af39-f29284e69c28" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/25761931/fffb568a-95af-45e4-ae61-5a80d4a6d01e">
图片真实链接（https://image.pollinations.ai/prompt/sunrise%20over%20a%20serene%20landscape,%20with%20soft%20pastel%20colors%20in%20the%20sky,%20gentle%20sunlight%20reflecting%20off%20a%20tranquil%20lake,%20and%20a%20silhouette%20of%20mountains%20in%20the%20background）

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

mapro 14.4.1

### Desktop Browser

chrome

### Desktop Browser Version

126.0.6478.62

### Smartphone Device

iphone13

### Smartphone OS

16.3

### Smartphone Browser

chrome

### Smartphone Browser Version

126

**Comment by QAbot-zh** [comment]
链接是对的，只是解析错了，把右括号也放进链接里去了：

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/40236765/2b20f738-2f02-4492-9746-a3d701a90e00)
