### ISSUE TITLE
main主分支拉下的代码，使用gemini模型响应的Content-Type: text/event-stream，界面上消息是重复的[Bug] 

### ISSUE THREAD

**Issue by gongjing2012** [ChatGPTNextWeb/ChatGPT-Next-Web#4966]
### Bug Description

1、main主分支拉下的代码，使用gemini模型响应的Content-Type: text/event-stream，界面上消息是重复的。
2、发现 onFinish(message) {
            debugger
            botMessage.streaming = false;
            if (message) {
              botMessage.content = message;
              get().onNewMessage(botMessage);
            }
            ChatControllerPool.remove(session.id, botMessage.id);
          },执行多次，消息就重复累加了，请帮忙看看前端哪需要修改？postman请求自己封装的接口是正常的。

### Steps to Reproduce

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/34706161/306d4afc-2dc2-43a4-92c4-604c62312a96)

### Expected Behavior

应该就是一条消息，而不是重复的消息。

### Screenshots

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/34706161/55d8ab65-d975-47e7-861d-705f8d138f1a)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/34706161/3b7ea886-a6dd-405b-8a77-3189fbbaf487)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/34706161/323ba50d-e792-4f05-aa32-605b9c0527c6)
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/34706161/8d8c310c-8111-42d3-aa9c-41c192aca1ad)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

window11

### Desktop Browser

Chrome

**Comment by lloydzhou** [comment]
#4955

**Comment by lloydzhou** [comment]
已修复
