### ISSUE TITLE
[Bug] 使用cloudflare ai-gateway Azure OpenAI 时报错"Resource not found"

### ISSUE THREAD

**Issue by ice-lemon** [ChatGPTNextWeb/ChatGPT-Next-Web#4976]
### Bug Description

根据 https://developers.cloudflare.com/ai-gateway/providers/azureopenai/
配置环境变量AZURE_URL 
https://gateway.ai.cloudflare.com/v1/{account_id}/{gateway_id}/azure-openai/{resource_name}/{deployment_name}
会报404"Resource not found"
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/13352244/2069bbd9-4b2e-4912-8d14-3b913297481f)

### Steps to Reproduce

Bug Description

### Expected Behavior

正常使用，适配Azure更新前可用  #4930
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/13352244/bac81db4-4887-4a24-9de1-639887873208)

### Deployment Method

- [ ] Docker
- [X] Vercel
- [ ] Server

### Desktop Browser

Chrome

### Desktop Browser Version

lasted

**Comment by vivaqq** [comment]
same issue after updated

**Comment by zoomhgtk** [comment]
same issue here.

**Comment by lloydzhou** [comment]
@ice-lemon please check on new version.

**Comment by ice-lemon** [comment]
#4979  更新后可以正常使用
