### ISSUE TITLE
[Feature Request]: Proxy API Functionality for Accessing GPT Official API / 代理API功能用于访问GPT官方API

### ISSUE THREAD

**Issue by CitrusFlavored** [ChatGPTNextWeb/ChatGPT-Next-Web#4977]
### Problem Description

Is there a new feature to add an official proxy API, or has it already been implemented and I just can't find it? 
请问有没有新增代理官方API的功能?或者已经实现我没找到?

### Solution Description

Due to well-known reasons, some regions may not be able to access the GPT official API directly. When deploying this project, it is common to address this issue. If a proxy address can be provided, other applications can use this project's proxy API for using and configuring the API interface without having to separately consider proxy issues.
因为众所周知的原因,某些地区可能无法正常使用GPT官方的API接口地址,部署本项目一般都会解决此问题,如果能提供一个代理的地址,那么其它应用在使用和配置API接口时可以使用本项目代理的API,而不需要在另外考虑代理的事情.

**Comment by lloydzhou** [comment]
https://developers.cloudflare.com/ai-gateway/providers/openai/

或许可以考虑 cloudflare 的产品
