### ISSUE TITLE
[Bug]  配置阿里的通义千问报错，显示 cors限制

### ISSUE THREAD

**Issue by kulame** [ChatGPTNextWeb/ChatGPT-Next-Web#4980]
### Bug Description

Access to fetch at 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

应该如何处理？

### Steps to Reproduce

1 配置ALIBABA_API_KEY和ALIBABA_URL

### Expected Behavior

配置通义千问的api结果报错，提示cors错误。

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

**Comment by RubuJam** [comment]
通义千问目前不支持跨域请求，当下只有修改源代码中的地址才行

Tongyi Qianwen does not currently support cross-domain requests. Currently, the only way to do this is to modify the address in the source code.

**Comment by lloydzhou** [comment]
直接填写官方的地址，在浏览器发请求会触发跨域错误。
可以使用 `/api/alibaba` 这个内置的地址走next server做转发，或者使用自己部署的转发地址。
但是还是建议通过`ALIBABA_API_KEY`以及`ALIBABA_URL`自己部署服务使用，以保护自己的key不外泄。
