### ISSUE TITLE
这个重复的问题好像没有解决，vercel部署拉取的最新代码，-all,+gpt-3.5-turbo,+gpt-4,+gpt-4o，没有关于azure的环境变量，这样配置还是显示了azure的选项

### ISSUE THREAD

**Issue by MadisonWirtanen** [ChatGPTNextWeb/ChatGPT-Next-Web#4981]
这个重复的问题好像没有解决，vercel部署拉取的最新代码，-all,+gpt-3.5-turbo,+gpt-4,+gpt-4o，没有关于azure的环境变量，这样配置还是显示了azure的选项

_Originally posted by @manjieqi in https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4940#issuecomment-2222490830_

同样情况

**Comment by lloydzhou** [comment]
see here: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4940#issuecomment-2225415015
