### ISSUE TITLE
[Feature Request]: 对第三方反代优化

### ISSUE THREAD

**Issue by bian-wz** [ChatGPTNextWeb/ChatGPT-Next-Web#4985]
### Problem Description

新版支持阿里通义千问的请求后，模型请求会用通义的格式，但我的通义模型是通过oneapi进行使用的，而oneapi统一采用openai的格式。

### Solution Description

加入一个新的变量用来判断是使用通义官方的格式，还是OpenAI的格式
或者根据是否填入通义模型的key来判断

### Alternatives Considered

使用旧版本

**Comment by lloydzhou** [comment]
如果想要使用通义千问  提供的openai兼容api

1. 使用通义千问的变量配置BASE_URL + OPENAI_API_KEY
2. 配置`CUSTOM_MODELS=-all,+qwen-turbo@OpenAI`   会展示`qwen-turbo(OpenAI)`的模型菜单，表示模型名称是`qwen-turbo`，但是走`OpenAI`的模式
