### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LiuElric** [ChatGPTNextWeb/ChatGPT-Next-Web#4987]
### Bug Description

<img width="721" alt="截屏2024-07-12 19 49 45" src="https://github.com/user-attachments/assets/617f906c-068c-4f42-a9d1-01ba262b7399">
文案错误，出现了两个接口密钥

### Steps to Reproduce

查看百度的配置即可

### Expected Behavior

API key & Secret Key

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by lloydzhou** [comment]
已修复
