### ISSUE TITLE
[Bug] GPT4-o输出的是一个网页代码，不管什么问题都是

### ISSUE THREAD

**Issue by legendxcheng** [ChatGPTNextWeb/ChatGPT-Next-Web#4993]
### Bug Description

<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body #challenge-error-text{background-

完全没法阅读

### Steps to Reproduce

直接问问题就会这样。昨天开始出现。
![image](https://github.com/user-attachments/assets/ac58d5f1-79e6-4938-ae35-09e7e313c0e7)

### Expected Behavior

应该要正常回答问题才对

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by LinYunerr** [comment]
我遇到了相同的问题，在mac和win上均出现

**Comment by fuchen2000** [comment]
@legendxcheng 哥们，解决了吗？

**Comment by QAbot-zh** [comment]
just a moment ? 这不显然是 cf 盾吗，怕不是逆向的 gpt4o 吧，联系 api 的中转商问问

**Comment by LinYunerr** [comment]
> just a moment ? 这不显然是 cf 盾吗，怕不是逆向的 gpt4o 吧，联系 api 的中转商问问

我的网络环境没产生任何变化，可能是VPN问题？我是用的官网api

**Comment by LinLL** [comment]
The default nextchat api is down

**Comment by QAbot-zh** [comment]
> > just a moment ? 这不显然是 cf 盾吗，怕不是逆向的 gpt4o 吧，联系 api 的中转商问问
> 
> 我的网络环境没产生任何变化，可能是VPN问题？我是用的官网api

最近OpenAI不是对api使用地区审查变严了吗，看看直接 curl 调用是不是也有类似问题

**Comment by LinYunerr** [comment]
> > > just a moment ? 这不显然是 cf 盾吗，怕不是逆向的 gpt4o 吧，联系 api 的中转商问问
> > 
> > 
> > 我的网络环境没产生任何变化，可能是VPN问题？我是用的官网api
> 
> 最近OpenAI不是对api使用地区审查变严了吗，看看直接 curl 调用是不是也有类似问题

具体技术我不太清楚，但我不改变VPN环境下，可以直接进api后台，也可以在后台用api回答问题

**Comment by nanshenwei** [comment]
遇到同样的问题，设置里的接口地址换成https://api.openai.com/解决。估计是默认的代理地址出现了问题。btw，2.13.0的releases没有mac的dmg打包

**Comment by yaway** [comment]
> 遇到同样的问题，设置里的接口地址换成 https://api.openai.com/ 解决。估计是默认的代理地址出现了问题。btw，2.13.0的releases没有mac的dmg打包

+1

**Comment by malagebidi** [comment]
windows客户端复现，网页端没问题。

**Comment by app-arianamini** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5004#issuecomment-2252183332
