### ISSUE TITLE
[Feature Request]: 关于模型名称展示的困惑

### ISSUE THREAD

**Issue by manjieqi** [ChatGPTNextWeb/ChatGPT-Next-Web#4997]
### Problem Description

![image](https://github.com/user-attachments/assets/9758cf3e-85aa-4252-9cde-11b86a487117)

CUSTOM_MODELS=-all,+gpt-3.5-turbo,+gpt-4,+gpt-4o,+gemini-1.5-pro,+claude-3-5-sonnet-20240620=claude-3.5-sonnet,+llama3-70b-8192=llama3-70b,+glm-4,+qwen-long,+deepseek-chat

一种厂商的API对应着它的模型名称，它的请求方式有些是被ChatGPT-Next-Web原生支持的，但是这里又没有显示对应的厂商，比如gemini-1.5-pro，qwen-long，另外还有没有被支持的厂商的模型。

由于不是所有模型名称都被ChatGPT-Next-Web预置，或者预置的模型不被中转厂商支持，就有必要填写CUSTOM_MODELS，readme里面使用@可以指定厂商，但这里并没有说清楚，这里指定是作为展示，还是使用对应的请求方式，并且目前只有两个模式？

### Solution Description

提供一个支持列表，包括支持哪些厂商的请求方式，所支持厂商的模型名称，以及它门在环境变量中的编码

最好是CUSTOM_MODELS变量中@就是指定用哪个厂商的请求方式

不然感觉就是黑箱操作，模型名称展示让人很困惑

比如gemini-1.5-pro@google，和gemini-1.5-pro@openai就是分别以google和opneai的请求格式发送请求，这样也便于接入例如oneapi的中转，因为总是有很多厂商ChatGPT-Next-Web是没有适配的

现在可能看代码才能理清整个逻辑

**Comment by lloydzhou** [comment]
确实，这一次对模型这里结构做了一些改进：
1. 一方面是为了解决之前Azure和OpenAI的逻辑不清晰的地方。
2. 另一方面，就是此次改动可以方便接入一些中转api，或者支持厂商发布新模型但是nextchat未更新的时候，能让用户第一时间通过CUSTOM_MODELS用上新模型的能力


最后：也是预留了以后可以通过CUSTOM_PROVIDERS自定义服务商，达到“某个模型以OpenAI的模式发消息，但是可以走一个新的路由/api/{provider_alias}，这样可以支持同时存在多个中转供应商”

**Comment by lloydzhou** [comment]
#5001
