### ISSUE TITLE
新发布的 ChatGPT-Next-Web  2.13 的 multi models，具体怎么使用呢？

### ISSUE THREAD

**Issue by 80imike** [ChatGPTNextWeb/ChatGPT-Next-Web#4999]
### Bug Description

新发布的 ChatGPT-Next-Web  2.13 的 multi models，具体怎么使用呢？

文档中没有任何使用说明，大佬们指导下吧

### Steps to Reproduce

新发布的 ChatGPT-Next-Web  2.13 的 multi models，具体怎么使用呢？

文档中没有任何使用说明，大佬们指导下吧

### Expected Behavior

新发布的 ChatGPT-Next-Web  2.13 的 multi models，具体怎么使用呢？

文档中没有任何使用说明，大佬们指导下吧

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by lloydzhou** [comment]
#5001
