### ISSUE TITLE
[Bug] Failed to execute 'setItem' on 'Storage': Setting the value of 'chat-next-web-store' exceeded the quota

### ISSUE THREAD

**Issue by mxdlzg** [ChatGPTNextWeb/ChatGPT-Next-Web#5002]
### Bug Description

There are more and more multi-modal model applications. The input pictures will occupy a lot of local storage space. If there are more than 50 dialogues, similar errors will occur, seriously affecting the use (or basically unusable).

![image](https://github.com/user-attachments/assets/7619d361-11d4-4a72-9c3f-9b7388f8a989)

### Steps to Reproduce

New conversation.

Ask llm with image everytime.

### Expected Behavior

Do not exceed quota, or use server-side storage.

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by lloydzhou** [comment]
[v2.13.1](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.13.1) 版本支持图片使用cache storage存储到本地缓存（这个存储体积与磁盘大小相关），localStorage中只保留图片链接。
应该可以解决使用多模态模型存储限制的问题。

**Comment by 17794** [comment]
v2.14.2 has the same question in windows exe version when use dalle-3 multi times

**Comment by lloydzhou** [comment]
经测试，app版本，无法注册serviceWorker成功，导致无法使用CacheStorage。
所以，后面会尝试先使用indexeddb缓解localStorage的问题。
再尝试在App端升级tauri插件，争取能让serviceWorker正常工作
