### ISSUE TITLE
仍然关于Gemini有疑问

### ISSUE THREAD

**Issue by alltobebetter** [ChatGPTNextWeb/ChatGPT-Next-Web#5003]
### Bug Description

我的vercel环境变量：
![image](https://github.com/user-attachments/assets/abc494b4-c08c-4d80-8342-68ee4011d605)
我的网站：
chat.suaolin.one
响应：
![image](https://github.com/user-attachments/assets/7c966f3c-96f1-4a9b-bc6e-49058726d577)
![image](https://github.com/user-attachments/assets/b4749462-2e44-43ff-a5c8-6417650cd78e)
完全不响应

### Steps to Reproduce

如图所示

### Expected Behavior

恢复

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

**Comment by alltobebetter** [comment]
亲测当版本滚回到2.12.x就没有问题，所以为什么捏

**Comment by lloydzhou** [comment]
我这边会继续尝试复现问题

**Comment by lloydzhou** [comment]
在您部署的站点测试了一下，确实有问题。默认使用的google的api地址拼接不正确，后续会很快修复

![image](https://github.com/user-attachments/assets/04daed3d-4f70-46d2-97ae-492e7fce63f0)

**Comment by llccing** [comment]
> ### Bug Description
> 我的vercel环境变量： ![image](https://private-user-images.githubusercontent.com/108602313/348520367-abc494b4-c08c-4d80-8342-68ee4011d605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTY1NjcsIm5iZiI6MTcyMTExNjI2NywicGF0aCI6Ii8xMDg2MDIzMTMvMzQ4NTIwMzY3LWFiYzQ5NGI0LWMwOGMtNGQ4MC04MzQyLTY4ZWU0MDExZDYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNzUxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWFiZDYxOGU0YzE4YWNjZmUxMDU2NjY2Yjk2NzQ5NjBkYTA2MzlmYjYzZmEyYzRmMjNkZGE2Y2JlMDI0ZjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5BNpvsZspWtBF_Wgx3wCJEw7uEHgyW2WzfHHQkv8siY) 我的网站： chat.suaolin.one 响应： ![image](https://private-user-images.githubusercontent.com/108602313/348520411-7c966f3c-96f1-4a9b-bc6e-49058726d577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTY1NjcsIm5iZiI6MTcyMTExNjI2NywicGF0aCI6Ii8xMDg2MDIzMTMvMzQ4NTIwNDExLTdjOTY2ZjNjLTk2ZjEtNGE5Yi1iYzZlLTQ5MDU4NzI2ZDU3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNzUxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODE3NGVkOGRlODQ2NTk3Y2I4MTJhNjNmOGFiNjMxOTNjZmE2MjY2ZmRhNDQ2M2Q2NzgzMWU5ZDcwMjU3NzQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l6Yvi7Kumgk7lKVsNd9ESwG4_BAKGkCBmTWmIoO-1yQ) ![image](https://private-user-images.githubusercontent.com/108602313/348520432-b4749462-2e44-43ff-a5c8-6417650cd78e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTY1NjcsIm5iZiI6MTcyMTExNjI2NywicGF0aCI6Ii8xMDg2MDIzMTMvMzQ4NTIwNDMyLWI0NzQ5NDYyLTJlNDQtNDNmZi1hNWM4LTY0MTc2NTBjZDc4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNzUxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmVlYTNjMzAzMjZjOGNjNjU4MGYwMTM0YjNiMDU1ZDBkZTQ4OGU5NmM4MmNhZDFmZGJmNjI0OWY1MjQ5NTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xk9ttUI9uxZlTYWttLz4TNbuQDH1F5qJgKzF8lcWNfA) 完全不响应
> 

你好，你这个custom模型的备注非常清晰，非常棒，如果方便可以分享一下吗

**Comment by fengzai6** [comment]
加一

**Comment by llccing** [comment]
不知道你是直接用的 Google的 api_key 还是走的api代理商，如果是后者，可以参考这个 https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5023 ，这个解决了我的问题，也许对你也有帮助

**Comment by fengzai6** [comment]
> 不知道你是直接用的 Google的 api_key 还是走的api代理商，如果是后者，可以参考这个 #5023 ，这个解决了我的问题，也许对你也有帮助

谷歌的，不知道为啥

**Comment by Dogtiti** [comment]
已修复~
