### ISSUE TITLE
[Feature Request]: 最新的2.13.0缺失macOS客户端

### ISSUE THREAD

**Issue by willzhqiang** [ChatGPTNextWeb/ChatGPT-Next-Web#5006]
### Problem Description

如题，看了release，找了一圈，没有发现dmg格式的安装包。

### Solution Description

编译打包macOS版本。

**Comment by m0rg5** [comment]
Ditto

**Comment by Mrxyx** [comment]
Ditto.

**Comment by Mrxyx** [comment]
[ Error failed to bundle project: failed to upload app to Apple's notarization servers.](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/actions/runs/9920340056/job/27407110030#step:8:842) The packaging failed. Can someone fix it？

**Comment by Feahter** [comment]
https://github.com/tauri-apps/tauri/issues/9400

**Comment by terryzwt** [comment]
+1

**Comment by lloydzhou** [comment]
success build app for macOS
![image](https://github.com/user-attachments/assets/1bdeca8f-3a85-417e-9792-9d23ed403640)
