### ISSUE TITLE
[Doc]文档似乎不是很清晰 

### ISSUE THREAD

**Issue by arloor** [ChatGPTNextWeb/ChatGPT-Next-Web#5007]
### Bug Description

试图使用docker（podman）部署nextchatweb来使用azure openai api。看文档没找到正确的路子，最后发现要这么配置环境变量：

```bash
podman run -d \
--pull=newer \
--name chatweb \
-p 127.0.0.1:3000:3000 \
--replace \
--rm \
-e AZURE_URL=https://xxxxxxx.openai.azure.com/openai \
-e AZURE_API_KEY=xxxxxxx \
-e AZURE_API_VERSION=2024-06-01 \
-e CUSTOM_MODELS=-all,+gpt-4o@azure=gpt-4o \
-e HIDE_USER_API_KEY=1 \
docker.io/yidadaa/chatgpt-next-web
```

有几个坑：
1. `AZURE_URL`不是 `https://{azure-resource-url}/openai/deployments/{deploy-name} `，而是 `https://{azure-resource-url}/openai `
2. 要设置 `CUSTOM_MODELS`，删除所有模型，仅手动增加azure的模型。否则页面会使用openai的模型而报错。关键在于我没有配置openai的相关东西，默认还走openai，应该默认走azure才合理。

另外我发现，总结对话的题目用的还是openai接口，我的日志里出现了访问openai超时的日志，并且无法生成对话标题。这应该也是默认行为不太合理的问题。

### Steps to Reproduce

以如下命令部署：

```bash
podman run -d \
--pull=newer \
--name chatweb \
-p 127.0.0.1:3000:3000 \
--replace \
--rm \
-e AZURE_URL=https://xxxxxxx.openai.azure.com/openai \
-e AZURE_API_KEY=xxxxxxx \
-e AZURE_API_VERSION=2024-06-01 \
-e CUSTOM_MODELS=-all,+gpt-4o@azure=gpt-4o \
-e HIDE_USER_API_KEY=1 \
docker.io/yidadaa/chatgpt-next-web
```

### Expected Behavior

期望修正文档，以及修改默认行为，避免使用未配置的openai接口

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server

**Comment by Dowanw0w** [comment]
I'm experiencing the same bug, if I use @azure to work with the model, I can't generate the title

**Comment by lloydzhou** [comment]
https://github.com/search?q=repo%3AChatGPTNextWeb%2FChatGPT-Next-Web+SUMMARIZE_MODEL&type=issues
![image](https://github.com/user-attachments/assets/9fad782d-cf93-45d6-83e1-21ae48042f22)

**Comment by Sha1rholder** [comment]
不是文档写不清晰的问题，是目前有azure openai有bug，现在应该在修代码而不是文档

**Comment by lloydzhou** [comment]
> 不是文档写不清晰的问题，是目前有azure openai有bug，现在应该在修代码而不是文档

按前面的命令启动docker没有发现azure的问题。
> 有一个请求发到/api/openai，这个是总结的请求。当前系统只支持gpt-3.5-turbo@openai以及gemini-pro@google，这属于另一个问题。

如果你这边有其他的问题。可以提供一下具体的配置以及报错信息，方便排查。

**Comment by arloor** [comment]
> @Sha1rholder
> 
> > 不是文档写不清晰的问题，是目前有azure openai有bug，现在应该在修代码而不是文档
> 
> 按前面的命令启动docker没有发现azure的问题。
> 
> > 有一个请求发到/api/openai，这个是总结的请求。当前系统只支持gpt-3.5-turbo@openai以及gemini-pro@google，这属于另一个问题。
> 
> 如果你这边有其他的问题。可以提供一下具体的配置以及报错信息，方便排查。

Can the summary request use azure openai in future versions?

**Comment by masyaf90** [comment]
“AZURE_URL不是 https://{azure-resource-url}/openai/deployments/{deploy-name} ，而是 https://{azure-resource-url}/openai ”

按这一条AZURE_URL里删除“deployments/{deploy-name}”终于成功了，
![image](https://github.com/user-attachments/assets/483333f2-5bc7-40ed-b1c0-1a7f7ef41a31)
AZURE_URL按文档填写https://{azure-resource-url}/openai/deployments/{deploy-name}或者https://{azure-resource-url}/openai/deployments/
都会出现404
![image](https://github.com/user-attachments/assets/64bc9a74-1e08-4e13-bd51-24046dbeb168)

请尽快修改文档

**Comment by arloor** [comment]
I can help to fix the document
