### ISSUE TITLE
[Bug] Gemini No Response

### ISSUE THREAD

**Issue by Graysonzhan** [ChatGPTNextWeb/ChatGPT-Next-Web#5014]
### 📦 Deployment Method

Vercel

### 📌 Version

V2.13

### 💻 Operating System

Windows

### 📌 System Version

Latest

### 🌐 Browser

Chrome

### 📌 Browser Version

Latest

### 🐛 Bug Description

No response from Gemini

**Comment by xunxuntj** [comment]
Vercel deployment, there's no response when selecting Gemini model

**Comment by cnhkbbs** [comment]
I also encountered this issue, Google seems to have banned API calls similar to those made by data center IPs🤔

**Comment by sunrisewestern** [comment]
> I also encountered this issue, Google seems to have banned API calls similar to those made by data center IPs🤔

Gemini pro 1.5 lastest works when roll back to 2.12.3 on vercel, so it's not a ip banned problem.

**Comment by yeung66** [comment]
it seems the hotfix https://github.com/sijinhui/ChatGPT-Next-Web/commit/c3eaa4762d10dbdb4b34262b6dadb709572c32aa#diff-0fd3ef592c8e209df48b628ffbeb8377cc264cacb5e25399722714aa5e8e09cb

**Comment by Dogtiti** [comment]
fixed~
