### ISSUE TITLE
[Bug] 2.13 报错 DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'chat-next-web-store' exceeded the quota

### ISSUE THREAD

**Issue by 80imike** [ChatGPTNextWeb/ChatGPT-Next-Web#5015]
### 📦 部署方式

Docker

### 📌 软件版本

2.13

### 💻 系统环境

Ubuntu

### 📌 系统版本

20.04

### 🌐 浏览器

Chrome

### 📌 浏览器版本

126.0.6478.127

### 🐛 问题描述

升级到 2.13 后，提问任何内容没有响应

<img width="1212" alt="image" src="https://github.com/user-attachments/assets/f5c65ac9-d1f0-4cb0-a64e-17c442f5106d">

控制台都报这个错

<img width="1128" alt="image" src="https://github.com/user-attachments/assets/0e6d200c-5761-4f0c-ac47-1f37398ef0b5">

**Comment by lloydzhou** [comment]
see #5013

**Comment by lloydzhou** [comment]
[v2.13.1](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.13.1) 版本支持图片使用cache storage存储到本地缓存（这个存储体积与磁盘大小相关），localStorage中只保留图片链接。
应该可以解决使用多模态模型存储限制的问题。
