### ISSUE TITLE
[Bug] docker compose 部署 DEFAULT_MODEL 参数无法生效

### ISSUE THREAD

**Issue by aiyurui** [ChatGPTNextWeb/ChatGPT-Next-Web#5017]
### 📦 Deployment Method

Docker

### 📌 Version

v2.13

### 💻 Operating System

Other Linux

### 📌 System Version

debian 11

### 🌐 Browser

Chrome

### 📌 Browser Version

126

### 🐛 Bug Description

最新版版本docker compose 部署
DEFAULT_MODEL参数没有过多介绍
但无论设置为gpt-3.5-turbo或者gpt-3.5-turbo@azure或者openai或者azure，都无法生效
或请教配置方法，谢谢

**Comment by SakuraCodes** [comment]
![image](https://github.com/user-attachments/assets/65bb250f-321f-470e-a75d-edbfa6a33b97)
同样情况

**Comment by crhope** [comment]
发现如果是chrome就会有问题，但是用firefox就一切正常了
