### ISSUE TITLE
[Feature Request] 能否添加对Deepbricks这家API供应商的API支持

### ISSUE THREAD

**Issue by CCMAYNOTXX** [ChatGPTNextWeb/ChatGPT-Next-Web#5023]
### 🥰 需求描述

如题，目前他家的API价格较低且支付便捷，请求作者增加支持

### 🧐 解决方案

如题

**Comment by llccing** [comment]
支持！

我用了另一个api供应商 - [gptnb](https://oneapi.gptnb.me/)，希望提供类似的通用的选项，针对这些供应商。

非常感谢！

**Comment by lloydzhou** [comment]
![image](https://github.com/user-attachments/assets/2616df0a-7b66-406a-b5a8-0019ba56ad65)

1. 看起来Deepbricks的API基本兼容OpenAI的格式
2. 可以把Deepbricks当作一个新的供应商使用即可，例如这里`CUSTOM_MODELS=-all,+claude-3.5-sonnet@OpenAI` 可以让这个claude3.5的模型以OpenAI的格式发送到Deepbricks的服务器。

![image](https://github.com/user-attachments/assets/d8ba732c-571d-4f31-a247-1b507b86e0a3)

![image](https://github.com/user-attachments/assets/00cd3414-7895-4253-8d4a-7fd5433523cb)

**Comment by CCMAYNOTXX** [comment]
感谢回答，按照你的方法去操作之后，确实可以正常访问了，该API下的其他模型也可以用此方法调用，谢谢你提供的帮助：）

**Comment by llccing** [comment]
> 支持！
> 
> 我用了另一个api供应商 - [gptnb](https://oneapi.gptnb.me/)，希望提供类似的通用的选项，针对这些供应商。
> 
> 非常感谢！

感谢回复，问题得到解决。

然后如果使用了 gptnb 的朋友可以按这个方式来配置，
![image](https://github.com/user-attachments/assets/40439d68-7dc4-4ad5-b834-f1baeec21023)
```
https://oneapi.gptnb.me


-all,+claude-3-5-sonnet-20240620@OpenAI=claude3.5 | Anthropic最新模型,+gemini-1.5-pro-latest@OpenAI=gemini-1.5-pro-latest | Google 最新模型,+gpt-4o=GPT-4o | OpenAI 最新模型

```

![image](https://github.com/user-attachments/assets/70b7ab0e-05f1-4950-9a33-6cd0370fff4a)
