### ISSUE TITLE
[Feature Request] mac inter V2.13.0 为啥没有安装包

### ISSUE THREAD

**Issue by DuXiao-Du** [ChatGPTNextWeb/ChatGPT-Next-Web#5024]
### 🥰 需求描述

mac inter V2.13.0 为啥没有更新包

### 🧐 解决方案

新增加 mac inter V2.13.0 安装新包

**Comment by JOKER-GU621** [comment]
please update package for mac inter V2.13.0

**Comment by lloydzhou** [comment]
已经修复 v2.13.0的包已经上传
