### ISSUE TITLE
[Feature Request] 支持多个 LLM 同时对话 Support multiple LLM simultaneous conversations

### ISSUE THREAD

**Issue by jiangying000** [ChatGPTNextWeb/ChatGPT-Next-Web#5027]
### 🥰 Feature Description

类似 https://app.chathub.gg/ （这个是闭源的，而且不支持设置api-key，不支持自定义prompt）
![image](https://github.com/user-attachments/assets/a6a3b6f6-5d1c-4d93-96f3-05780dc87921)

### 🧐 Proposed Solution

类似 https://app.chathub.gg/

**Comment by 80imike** [comment]
支持，这个可以有 open webui 也有这个功能

**Comment by lloydzhou** [comment]
这个需求应该偏离了本项目的方向。

不过你可以借助一些外部的软件之类的实现类似的效果，例如 adspower
https://www.adspower.com/news/synchronizer-control-multiple-accounts-at-once-in-adspower
![image](https://github.com/user-attachments/assets/608347de-fc5b-4968-a5c4-6c290cc0863d)

**Comment by Leizhenpeng** [comment]
Welcome PR, if there is a better design plan~

**Comment by kitaev-chen** [comment]
其实支持多个LLM的话，进一步支持多个LLM同时回复以及比较竞技，还是很自然且极具竞争力的。强烈建议支持！
推荐的工具有点高射炮打蚊子，不过也不错，谢谢！

> 这个需求应该偏离了本项目的方向。
> 
> 不过你可以借助一些外部的软件之类的实现类似的效果，例如 adspower

**Comment by kitaev-chen** [comment]
> 支持，这个可以有 open webui 也有这个功能

谢谢推荐，open webui 确实值得探索，我用用看看。
