### ISSUE TITLE
google gemini 用不了了[Bug] 

### ISSUE THREAD

**Issue by mokibox** [ChatGPTNextWeb/ChatGPT-Next-Web#5028]
### 📦 部署方式

Docker

### 📌 软件版本

2.13.0

### 💻 系统环境

Other Linux

### 📌 系统版本

docker

### 🌐 浏览器

Chrome

### 📌 浏览器版本

latest

### 🐛 问题描述

更新后，谷歌的gemini无法使用了，详情如图
![image](https://github.com/user-attachments/assets/4890459f-357c-4257-ad2d-ff91bf03500c)
![image](https://github.com/user-attachments/assets/4c1c4b43-0c08-4f62-a55f-3012f7e6774b)

### 📷 复现步骤

程序部署在k3s集群上面

### 🚦 期望结果

期望尽快修复

**Comment by aaro-n** [comment]
@mokibox 你的API暴露了。
确实google gemini现在用不了，现在使用 `gemini-1.0-pro`， `gemini-1.5-pro-latest`， `gemini-1.5-flash-latest`， `gemini-pro-vision`浏览器都会提示“405 Method Not Allowed”，因为我部署在vercel，使用google gemini时vercel日志不会显示访问记录，我挨个测试vercel 历史部署，最终找到`70907ea Merge pull request #4850 from ImBIOS/patch-2`这个部署可以正常使用google gemini
# 重点提示
`70907ea Merge pull request #4850 from ImBIOS/patch-2` 可以正常使用google gemini
`7218f13 Merge pull request #4934 from ConnectAI-E/feature/client-headers`就不可以使用google gemini，表现为“405 Method Not Allowed”
# vercel 部署历史
黑线框里的所有部署都不可以用google gemini
![部署日志](https://github.com/user-attachments/assets/7f85e74d-13b6-4a4f-a741-08b9ca7ab36d)

**Comment by Dogtiti** [comment]
@mokibox 帮你把api key的翻译机器人里的图片删掉了

**Comment by mokibox** [comment]
> @mokibox你的API暴露了。 确实google gemini现在用不了，现在使用，，，`gemini-1.0-pro`浏览器都会提示“405 Method Not Allowed”，因为部署在vercel，使用google gemini时vercel日志不会显示访问记录，我挨个测试vercel历史部署，最终找到这个部署可以正常使用google gemini`gemini-1.5-pro-latest``gemini-1.5-flash-latest``gemini-pro-vision``70907ea Merge pull request #4850 from ImBIOS/patch-2`
> 
> # 重点提示
> `70907ea Merge pull request #4850 from ImBIOS/patch-2`可以正常使用google gemini `7218f13 Merge pull request #4934 from ConnectAI-E/feature/client-headers`就无法使用google gemini，表现为“405 Method Not Allowed”
> 
> # vercel 部署历史
> 黑线框里的所有发布都不能用google gemini ![部署日志](https://private-user-images.githubusercontent.com/45537680/349090199-7f85e74d-13b6-4a4f-a741-08b9ca7ab36d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDA5ODgsIm5iZiI6MTcyMTE0MDY4OCwicGF0aCI6Ii80NTUzNzY4MC8zNDkwOTAxOTktN2Y4NWU3NGQtMTNiNi00YTRmLWE3NDEtMDhiOWNhN2FiMzZkLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0MzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZDk5OTY2ZDczOTRmNWY5ZDZiODUxMzMyMTUwZjc0ZmExYjkxNzIzMGU4NmI1NWI2MGQ0NjM2ODhjYjU5MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yFaS9mJBQ_j-56LQjjEGaYsb2gSjNEKLQqEviK3topU)

谢谢   目前退到2.12.4是可以正常使用gemini的  希望下个版本能恢复吧  gemini的图片识别挺好用的  给作者加鸡腿

**Comment by Graysonzhan** [comment]
vercel可以回滚到多天之前的部署吗？

**Comment by Dogtiti** [comment]
已修复~ 大家看看有没有问题

**Comment by tin22sh** [comment]
请教：怎样回退到以前版本？碰上同样问题嘞

**Comment by mokibox** [comment]
> 已修复~ 大家看看有没有问题

看到docker版本没有推送新镜像，是需要自己重新打下包吗？

**Comment by aaro-n** [comment]
google gemini API已经可以正常使用

**Comment by tin22sh** [comment]
谢谢！docker更新到最新版本 v2.13.1 问题解决
