### ISSUE TITLE
[Bug] [一些问题合集] 包括：[配置了代理的Gemini用不了、设定了默认模型后列表出现undefined等等]

### ISSUE THREAD

**Issue by charle00001** [ChatGPTNextWeb/ChatGPT-Next-Web#5030]
### 📦 部署方式

Cloudflare Pages & Vercel

### 📌 软件版本

v2.13.0, v2.12.4

### 💻 系统环境

Other Linux

### 📌 系统版本

Debian 12 （这个不重要吧？）

### 🌐 浏览器

Firefox

### 📌 浏览器版本

115.12.0 esr (64 位)

### 🐛 问题描述

部署方式：Cloudflare Pages & Vercel

**CF Pages的变量与 Vercel 的变量全程一致**

之前是用了 2.12.4 这个版本，配置了Gemini，配置了Gemini的代理（*代理接口 fakecat.vercel.app*），还配置了一些模型（glm4之类的，不过都不是官方接口，是一个公益接口，接口格式是OpenAI），描述一下两个版本问题：

### v2.12.4

**这个版本的问题是 Cloudflare Pages 独有的**
Gemini（配置了代理），使用 Gemini 的时候返回了代理接口的页面 HTML；而在 Vercel 上部署它就没问题（Gemini+代理），正常返回内容。我猜测这个问题是 Cloudflare Pages 没有去请求它的确切接口，而是直接请求了它的域名

### v2.13.0：

**这个版本的问题 Cloudflare Pages 和 Vercel 都有**
Gemini（配置了代理），使用 Gemini 的时候它去请求了那个公益接口！也就是说，它直接请求了base_url，没有请求google_url，离谱

另外，设置的默认模型之后，模型列表最上面有一个undifined，反正看着不舒服就对了（

图：

Vercel & CF Pages：

![图片](https://github.com/user-attachments/assets/2217dca5-7e1d-48cf-9023-d84709e19a39)

### 📷 复现步骤

在“问题描述”一栏已经写了

### 🚦 期望结果

总结：

希望修复（Cloudflare Pages）：

使用Gemini时请求base_url而不请求google_url的问题

使用Gemini时，直接返回代理接口的（index.html）的问题

接口选择列表，设置了默认模型后，最顶部出现“undefined”的问题

希望修复（Vercel）：

使用Gemini时请求base_url而不请求google_url的问题

接口选择列表，设置了默认模型后，最顶部出现“undefined”的问题

### 📝 补充信息

另：之前 Vercel 的版本因为未知原因没有升级成功，导致了我拿了 v2.12.4 版本的 Vercel 与 v2.13.0 版本的 CF Pages 比较，出现了一些误会（现在 Vercel 也有了一些问题，在“期望结果”一栏中。）

就这些问题，当然CF Pages的部署方式是测试阶段，所以后续有问题我会反馈，谢谢！（我感觉 v2.13.0 的更新很坏，更新了那个，影响了这个）

**Comment by charle00001** [comment]
另：我更改了第一条issue，但是翻译没更改，望周知

**Comment by i-square** [comment]
`v2.13.0` 今天刚升级

除了undefined问题，我还有个问题，没有配置 `AZURE_URL`，但是模型列表里会多出几个模型比如： `gpt-4(AZURE)`、`gpt-4o(AZURE)`

**Comment by lloydzhou** [comment]
@i-square 
> 我还有个问题，没有配置 AZURE_URL，但是模型列表里会多出几个模型比如： gpt-4(AZURE)、gpt-4o(AZURE)

这里之所以出现这个选项，原因在于：v2.13.0版本之后，`Azure`被提升到与`OpenAI`, `Google`等一个级别的供应商了，所以，这里逻辑上应该要展示。

**Comment by charle00001** [comment]
一会之前我更新到了v2.13.1，测试了一通，发现了之前的反馈还是不够详细，所以补充一下：

“为什么使用Gemini的时候它不请求google_url而是请求base_url？”

因为我设置了“DEFAULT_MODEL”。不知道为啥，将“DEFAULT_MODEL”设置为gemini-1.5-pro-latest之后，它就认为它是gemini-1.5-pro-latest@openai了，总之，设置了DEFAULT_MODEL变量之后，任何非openai接口格式的model都会被以为是openai接口格式。

但是，当你直接在模型选择里面选择gemini-1.5-pro-latest而不是undefined，它就正常了

另：这个版本还是有undefined，没修复

**Comment by i-square** [comment]
> @i-square
> 
> > 我还有个问题，没有配置 AZURE_URL，但是模型列表里会多出几个模型比如： gpt-4(AZURE)、gpt-4o(AZURE)
> 
> 这里之所以出现这个选项，原因在于：v2.13.0版本之后，`Azure`被提升到与`OpenAI`, `Google`等一个级别的供应商了，所以，这里逻辑上应该要展示。

@lloydzhou 但我并没有配置任何AZURE模型和AZURE地址，为什么会展示AZURE的东西？

**Comment by charle00001** [comment]
关了，大部分问题解决了
