### ISSUE TITLE
[Feature Request] 添加百度AI的免费模型ENIRE Speed和ENIRE Lite

### ISSUE THREAD

**Issue by aaro-n** [ChatGPTNextWeb/ChatGPT-Next-Web#5032]
### 🥰 需求描述

百度AI最近几个月宣布模型ENIRE Speed和ENIRE Lite可以免费使用，希望ChatGPT-Next-Web可以添加这两个模型。

### 🧐 解决方案

增加ENIRE Speed和ENIRE Lite模型

### 📝 补充信息

1. [千帆ModelBuilder 部分ERNIE系列模型免费开放公告](https://cloud.baidu.com/news/notice_c7a145b9-5c99-4870-939f-e09ba506aab3)
2. [平台预置服务调用](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/hlrk4akp7#1%E6%96%87%E5%BF%83%E5%A4%A7%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B)

**Comment by consistent-k** [comment]
@Dogtiti I have completed this issue. Please check my code. Thank you. https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/5040

**Comment by Dogtiti** [comment]
@consistent-k done~
