### ISSUE TITLE
[Bug] Default Model Set to 'gpt-3.5' but Option Displays ‘undefined’

### ISSUE THREAD

**Issue by DDDDD12138** [ChatGPTNextWeb/ChatGPT-Next-Web#5039]
### 📦 Deployment Method

Docker, Other

### 📌 Version

v2.13.0

### 💻 Operating System

Windows, Ubuntu

### 📌 System Version

Windows11, Ubuntu22

### 🌐 Browser

Edge

### 📌 Browser Version

126.0.2592.87

### Option Displays ‘undefined’
- When using the `DEFAULT_MODEL` environment variable to set the default model to `gpt-3.5`, the model option displays as `undefined`. Despite this, the functionality remains operational.

![option-undefined](https://github.com/user-attachments/assets/16797d8c-1b9e-429b-8804-cf98f87ec710)

#### Successful initial request：

![image](https://github.com/user-attachments/assets/9e0e02a0-454a-4144-a997-e41f25fb4e10)

#### Failed title request:

![image](https://github.com/user-attachments/assets/10a22a73-172f-439b-b909-38e2ae352dd9)

### 📷 Recurrence Steps

1. Set ENV
> ```env
> # Local Run
> # .env file
> DEFAULT_MODEL=gpt-3.5
> ```
> ```bash
> # Docker Example
> docker run -d -p 3000:3000 \
>   -e OPENAI_API_KEY=sk-xxxxx \
>   -e BASE_URL=https://xxxxxxxxx/ \
>   -e DEFAULT_MODEL=gpt-3.5 \
>   --name chatgpt-next-web \
>   chatgpt-next-web:v2.13.0
> ```
2. Run or deploy the application
3. Access the application. Open a new browser, or incognito mode (simulate a new user, to prevent cache effects)

[Open in StackBlitz](https://stackblitz.com/edit/github-gjrzrq?file=.env.development)

### 🚦 Expected Behavior

 The `DEFAULT_MODEL` environment variable should be correctly utilized

**Comment by Dogtiti** [comment]
have a try with `gpt-3.5@openai`

**Comment by DDDDD12138** [comment]
> have a try with `gpt-3.5@openai`

This looks no different.

![屏幕截图 2024-07-18 001332](https://github.com/user-attachments/assets/12cb048a-c582-4c3b-a85c-3e665f432330)

By the way, `gpt-3.5@openai` seems like a custom model. Are you referring to the `CUSTOM_MODELS` environment variable? 
Actually, `DEFAULT_MODEL` does not support this syntax.

**Comment by DDDDD12138** [comment]
@lloydzhou 

So, this update is just for compatibility, right? It no longer shows `undefined`, but now the default selection is `gpt-3.5-turbo`. I don’t have access to `gpt-3.5-turbo`, it’s become unusable for me.

![image](https://github.com/user-attachments/assets/764d5b93-7aa0-4196-8a01-91de02f35a5c)



As a result, I tried using `CUSTOM_MODELS`. It works, but by default, it shows that I haven’t selected any model.
```
CUSTOM_MODELS=+gpt-3.5@openai
```
![image](https://github.com/user-attachments/assets/56644e3f-bc80-41ec-9e3b-a1766d8fcd7e)
![image](https://github.com/user-attachments/assets/dd102459-c527-4b56-9b71-60d150285434)

**Comment by lloydzhou** [comment]
@DDDDD12138 
> So, this update is just for compatibility, right? It no longer shows undefined, but now the default selection is gpt-3.5-turbo. I don’t have access to gpt-3.5-turbo, it’s become unusable for me.

1. yes, fixed undefined bug.
2. if you config `defaultModel` not in model list, this config will be ignore.
3. why select `gpt-3.5-turbo`: the chat component will select model which defined in mask, if model not in available model list, just select the first one.

> As a result, I tried using CUSTOM_MODELS. It works, but by default, it shows that I haven’t selected any model.
1. gpt-3.5 is not a valid model name. so do not using this config. 
>  if you config `defaultModel` not in model list, this config will be ignore.
2. if you want to show custom model name, please see #5001 or [README.md](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web?tab=readme-ov-file#custom_models-optional).
