### ISSUE TITLE
不懂就问，什么时候才能修复Gemini剪切失败的问题[Bug] 

### ISSUE THREAD

**Issue by alltobebetter** [ChatGPTNextWeb/ChatGPT-Next-Web#5053]
### 📦 部署方式

Vercel

### 📌 软件版本

2.13.0

### 💻 系统环境

Other

### 📌 系统版本

vercel

### 🌐 浏览器

Chrome

### 📌 浏览器版本

所有版本都是这样

### 🐛 问题描述

老生常谈，我前面已经反馈过问题，相关人员也说几天内修复，看着这几天陆续有人也反馈这些问题，就是vercel部署的时候Gemini（Google官方）无法正常调用

**Comment by alltobebetter** [comment]
源issue在这里：https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5003

**Comment by Dogtiti** [comment]
已经修复了，帮忙测试看看呀，没问题的话告知我一下~

**Comment by alltobebetter** [comment]
谢谢呜呜呜修复好了

**Comment by alltobebetter** [comment]
thxxxxxxxxxxxxxx
