### ISSUE TITLE
[Bug] Alibaba's DashScope interface is not available

### ISSUE THREAD

**Issue by Sherlock290** [ChatGPTNextWeb/ChatGPT-Next-Web#5072]
### 📦 Deployment Method

Vercel

### 📌 Version

2.13.1

### 💻 Operating System

Windows

### 📌 System Version

win10 22h2

### 🌐 Browser

Edge

### 📌 Browser Version

126.0.2592.113 (正式版本) (64 位)

### 🐛 Bug Description

Alibaba's DashScope interface cannot be used, but it is normal for me to use the postman test interface. I think it should be a bug or other problem in the project.

![image](https://github.com/user-attachments/assets/58d3d972-822a-4438-ae69-9e199afd61f4)

### 📷 Recurrence Steps

1. Configure service provider parameters, select Alibaba, enter baseUrl, enter apiToken; select qwen-plus model
2. Open a new conversation, type "Hello", and send

### 🚦 Expected Behavior

Expect a reply: "Hello, if you have any questions or need help, please let me know. "
But the actual reply is as follows:

```json
{
  "error": true,
  "message": "Failed to fetch"
}
```

```json
{
  "error": true,
  "message": "empty response from server"
}
```

### 📝 Additional Information

![image](https://github.com/user-attachments/assets/b07c8aa0-da22-46ed-95d2-6d5b3a43430f)

![image](https://github.com/user-attachments/assets/381a0bbf-7fec-41d9-bb2c-8b68c863ab4b)

![Snipaste_2024-07-21_18-16-11](https://github.com/user-attachments/assets/eecbf69a-902d-4b27-99c9-1a0de131180e)

![image](https://github.com/user-attachments/assets/f2189d55-e079-4b96-928f-fa5ae1082aab)

**Comment by lloydzhou** [comment]
![image](https://github.com/user-attachments/assets/563ee2b2-518f-4539-a341-3d8bb562df69)

大多数大模型都不支持跨域。也就是说直接在浏览器往模型api发请求，基本都会失败。使用自定义接口的时候，可以只填写apikey，使用默认的接口地址（这个接口地址实际上是使用内置的next server在服务端发请求，这样就能避免出现跨域错误）
