### ISSUE TITLE
[Bug] 自定义模型建议可以根据厂家设置，而不是硬性绑定，现在使用的中转平台API都是用的OpenAI格式的，现在claude 3.5 直接绑定了，无法在openai代理的渠道下使用claude3.5的模型了

### ISSUE THREAD

**Issue by alanblogooo** [ChatGPTNextWeb/ChatGPT-Next-Web#5078]
### 📦 部署方式

官方安装包

### 📌 软件版本

2.13.1

### 💻 系统环境

Windows

### 📌 系统版本

win10

### 🌐 浏览器

Edge

### 📌 浏览器版本

最新的

### 🐛 问题描述

[Bug] 自定义模型建议可以根据厂家设置，而不是硬性绑定，现在使用的中转平台API都是用的OpenAI格式的，现在claude 3.5 直接绑定了，无法在openai代理的渠道下使用claude3.5的模型了

**Comment by lloydzhou** [comment]
#5001
