### ISSUE TITLE
[Bug] 建议修复ChatGPTNextWeb页面的无障碍问题

### ISSUE THREAD

**Issue by dpy013** [ChatGPTNextWeb/ChatGPT-Next-Web#5079]
### 📦 Deployment Method

Other

### 📌 Version

latest stable version

### 💻 Operating System

Windows

### 📌 System Version

windows10 latest stable version

### 🌐 Browser

Edge

### 📌 Browser Version

latest stable version

### 🐛 Bug Description

当前在使用chromium内核的浏览器访问部署的ChatGPTNextWeb页面的时候，出现了以下的无障碍问题：
名称和标签
当某个按钮没有无障碍名称时，屏幕阅读器会将它读为“按钮”，这会导致依赖屏幕阅读器的用户无法使用它。
链接缺少可识别的名称 
请确保链接文字（以及用作链接的图片替代文字）可识别、独一无二且可聚焦，这样做会提升屏幕阅读器用户的导航体验。
问题重现可以从[这里](https://www.nvaccess.org/download)下载屏幕阅读器进行重现
[dpyhome.cn-20240722T111443.json](https://github.com/user-attachments/files/16327423/dpyhome.cn-20240722T111443.json)
下面附上使用edge的开发工具的Lighthouse生成的检测报告：

### 📷 Recurrence Steps

首先从这里下载[屏幕阅读器](https://www.nvaccess.org/download)
然后运行他
接着打开部署的ChatGPTNextWeb，使用键盘浏览页面即可重现错误

**Comment by LiuElric** [comment]
你好，方便留个联系方式吗？想详细了解一下您是在如何使用的，我们来看一下怎么能更好的支持一下 @dpy013

**Comment by dpy013** [comment]
具体可以加我微信：
15051709597

**Comment by dpy013** [comment]
感谢@mayfwl 
@Dogtiti 
对此问题的修复。

**Comment by dpy013** [comment]
刚才进行了测试：
发现了有控件重复朗读的问题例如：
面具 面具 按钮
发现 发现 按钮
新的聊天 新的聊天 按钮
发送 发送 可编辑文本
其实只要读一次就可以了。
