### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kagoesy** [ChatGPTNextWeb/ChatGPT-Next-Web#5087]
### 📦 部署方式

Docker

### 📌 软件版本

2.13.1

### 💻 系统环境

Windows

### 📌 系统版本

all

### 🌐 浏览器

Chrome, Edge

### 📌 浏览器版本

unknown

### 🐛 问题描述

在最近的更新后，使用custom endpoint配置Azure OpenAI时，model会被自动填充成endpoint中deployments的名字且无法修改，但是在部署Azure OpenAI deployment时名字可以是多样的，导致当没有使用标准的model名字作为deployment名字时发送消息会一直报404:

### 📷 复现步骤

1. 部署deployment名字为gpt4oChris
![image](https://github.com/user-attachments/assets/a44c2d32-a3bf-47e5-883e-ecd73d5634ca)
2. 将endpoint及其他信息填入custom endpoint, 其中endpoint内容为“https://xxxxx.openai.azure.com/openai/deployments/gpt4oChris“  且model选为gpt-4o(Azure):
![image](https://github.com/user-attachments/assets/23c7fb1d-b97b-4fa2-8047-0acac259bbb7)
3. 发送消息得到404
![image](https://github.com/user-attachments/assets/230ed06a-7abb-49bd-aaeb-a68e71041c15)
4. 通过浏览器开发者模式可以看到请求发送的地址变成了"https://xxxxx.openai.azure.com/openai/deployments/gpt4oChris/deployments/gpt-4o"，多增加了有model自动写入的错误deployment名字
![image](https://github.com/user-attachments/assets/1b99e480-a8a8-48f2-9fdc-ca42d2797a3a)

### 🚦 期望结果

1. 如果按照提示的格式带有deployments id填写endpoint，则不应该在之后自动添加带有model名字的deployment id

或者

2. 如果不希望在endpoint时加入deployment id且要自动生成的话，可以使用custom model来填写deployment id，但是希望添加说明，以及根据测试，当前版本添加custom model时仍旧添加的是标准的模型名字为deployment id

**Comment by lloydzhou** [comment]
#5001

**Comment by kagoesy** [comment]
> #5001

懂了，原来是语法拓展了，那是不是endpoint的example提示可以修改一下以防产生歧义：
![image](https://github.com/user-attachments/assets/5ff3cba1-418d-401e-9bf6-6ddfbe182557)

**Comment by lloydzhou** [comment]
拓展语法的原因是为了使用Azure的时候，能使用多个不同的模型（之前的旧版，实际上只能使用单个版本，不管怎么切换其实都不起作用）

关于这里的example确实需要改

**Comment by ErYiii** [comment]
> > #5001
> 
> 懂了，原来是语法拓展了，那是不是endpoint的example提示可以修改一下以防产生歧义： ![image](https://private-user-images.githubusercontent.com/37411056/350970649-5ff3cba1-418d-401e-9bf6-6ddfbe182557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTM3OTYsIm5iZiI6MTcyMjMxMzQ5NiwicGF0aCI6Ii8zNzQxMTA1Ni8zNTA5NzA2NDktNWZmM2NiYTEtNDE4ZC00MDFlLTliZjYtNmRkZmJlMTgyNTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA0MjQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYTg4YzUwNTljNTQ3NGZiNzU4MTg1NjY4YzFmZmMxZTk4OTU4NTQ3Y2UyZGJhNGNkMTk5MDhjZjY5MThkZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jv_0vYDhHWEMIiHEDC_Vwc_nuMF2v27F1-woayaXuf0)

你好，请问新的API格式应该是怎样的呢，我也是用的AzureOpenAI，更新2.14后用不了了。。

**Comment by kagoesy** [comment]
> > > #5001
> > 
> > 
> > 懂了，原来是语法拓展了，那是不是endpoint的example提示可以修改一下以防产生歧义： ![image](https://private-user-images.githubusercontent.com/37411056/350970649-5ff3cba1-418d-401e-9bf6-6ddfbe182557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTM3OTYsIm5iZiI6MTcyMjMxMzQ5NiwicGF0aCI6Ii8zNzQxMTA1Ni8zNTA5NzA2NDktNWZmM2NiYTEtNDE4ZC00MDFlLTliZjYtNmRkZmJlMTgyNTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA0MjQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYTg4YzUwNTljNTQ3NGZiNzU4MTg1NjY4YzFmZmMxZTk4OTU4NTQ3Y2UyZGJhNGNkMTk5MDhjZjY5MThkZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jv_0vYDhHWEMIiHEDC_Vwc_nuMF2v27F1-woayaXuf0)
> 
> 你好，请问新的API格式应该是怎样的呢，我也是用的AzureOpenAI，更新2.14后用不了了。。

我理解的就是endpoint就只保留到openai就可以，不要加deployment ID，然后custom model要写成 model@azure=<deployment ID>的形式

**Comment by ErYiii** [comment]
> > > > #5001
> > > 
> > > 
> > > 懂了，原来是语法拓展了，那是不是endpoint的example提示可以修改一下以防产生歧义： ![image](https://private-user-images.githubusercontent.com/37411056/350970649-5ff3cba1-418d-401e-9bf6-6ddfbe182557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTM3OTYsIm5iZiI6MTcyMjMxMzQ5NiwicGF0aCI6Ii8zNzQxMTA1Ni8zNTA5NzA2NDktNWZmM2NiYTEtNDE4ZC00MDFlLTliZjYtNmRkZmJlMTgyNTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA0MjQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYTg4YzUwNTljNTQ3NGZiNzU4MTg1NjY4YzFmZmMxZTk4OTU4NTQ3Y2UyZGJhNGNkMTk5MDhjZjY5MThkZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jv_0vYDhHWEMIiHEDC_Vwc_nuMF2v27F1-woayaXuf0)
> > 
> > 
> > 你好，请问新的API格式应该是怎样的呢，我也是用的AzureOpenAI，更新2.14后用不了了。。
> 
> 我理解的就是endpoint就只保留到openai就可以，不要加deployment ID，然后custom model要写成 model@azure=deployment ID的形式

是的，中午琢磨半天，已经解决了。谢谢。
