### ISSUE TITLE
[Feature Request] 希望增加插件功能

### ISSUE THREAD

**Issue by ooeooo** [ChatGPTNextWeb/ChatGPT-Next-Web#5099]
## 目前NextWeb工作原理:

```
TextIn -> GPTServer -> TextOut

        ^            ^
        |            |
        |            |

可以在这两处添加插件处理逻辑, 插件的作用是对In和Out内容进行替换修改
```

## 插件的工作原理:

0. 插件有调用LLM的能力(开放接口)

1. 插件可以以js代码和HttpAPI在线服务的形式指定, 插件的输入是文本, 输出也是文本

2. 通过识别返回内容中是否包含指定文本(由用户通过正则表达式设定规则)来决定是否及如何运行插件

3. 插件可以由用户自定义启用, 并且放在面具的容器里, 在面具的配置中可以修改插件的配置(本文底部图片)

4. 通过改变插件位置可以指定插件工作流, 像https://www.langflow.org/

## 举例:

通过API插件在线搜索:
用户输入: 告诉我今天北京的天气状况
插件: 询问LLM返回搜索词(今天北京的天气), 使用API搜索(https://baidu.com/search?s=今天北京的天气)

通过JS插件进行计算:
用户输入: 三加6加九等于多少?
插件: 询问LLM返回格式化算式(3+6+9), 使用JS计算

![chrome_Cz5r5wUO96](https://github.com/user-attachments/assets/8a03638c-540d-465b-9833-d9d1b451551d)

🎉🎉

**Comment by ElricLiu** [comment]
it will be coming soon
