### ISSUE TITLE
[Bug] 更新到最新版本后google gemini API出现错误："Failed to fetch"

### ISSUE THREAD

**Issue by cmcccopy** [ChatGPTNextWeb/ChatGPT-Next-Web#5105]
### 📦 Deployment Method

Official installation package

### 📌 Version

2.13.1

### 💻 Operating System

Windows

### 📌 System Version

10

### 🌐 Browser

Chrome

### 📌 Browser Version

126.0.6478.185

### 🐛 Bug Description

从2.12.4版本更新到2.13.1版本后，Google Gemini API无法使用，出现"error": true,"message": "Failed to fetch"
![image](https://github.com/user-attachments/assets/2ad82dc3-fe4a-468a-b4be-af663e8358fa)
![image](https://github.com/user-attachments/assets/793010e9-625e-40e4-8bf3-3f34d26427d5)
请问是不是我设置出现了问题？非常感谢！

**Comment by lloydzhou** [comment]
使用的是browser，能截一下浏览器控制台的报错信息吗？

**Comment by cmcccopy** [comment]
> 使用浏览器，能停止一下浏览器控制台的报错信息吗？
抱歉可能我上面表述的有问题，我使用的不是浏览器，使用的是“NextChat_2.13.1_x64-setup.exe”，安装后填写API，发现Google Gemini 出现："error": true,"message": "Failed to fetch" 错误。windows版本：Windows 10 专业版 19044.1766
谢谢大佬。

**Comment by cmcccopy** [comment]
> @cmcccopy 下载最新的 2.14.0看看，这个应该修复了gemini的路径问题

依旧还是有这个问题，我的设置如图
![image](https://github.com/user-attachments/assets/f23dc48f-1e4d-4897-a4e3-7465b3503f78)
![image](https://github.com/user-attachments/assets/a273d16d-4868-415d-9f60-2375a552868c)


Gemini API也没有失效，代理也没有问题，可以打开Gemini的chat界面，如图
![image](https://github.com/user-attachments/assets/2af42f29-8cbb-4dfb-a7e2-edf989f262ef)


当我把版本回滚到2.12.3后，就可以正常访问了
![image](https://github.com/user-attachments/assets/3b74bf8b-d40f-42dc-80aa-208359bf3c3e)

感谢大佬！

**Comment by BrezeSea** [comment]
Nextchat version 2.14.0 still has the issue of Gemini being unusable. My settings are the same as yours, but using Nextchat version 2.13.0 works fine.
The error message from Nextchat is: "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API."

nextchat的2.14.0版本依旧存在gemini无法使用的问题，我的设置与你相同，使用2.13.0版本的nextchat则正常使用。
nextchat提示如下：“此方法不允许未注册的调用者（身份未经验证的调用者）访问。请使用 API 密钥或其他 API 消费者身份形式调用此 API。”

**Comment by longxingdeng** [comment]
我也是一样，请问这个问题解决了吗？

**Comment by Zeyun-Deng** [comment]
同样的问题。看来下次更新的时候得多注意一下了……

**Comment by lzl0167** [comment]
我的也是，
![image](https://github.com/user-attachments/assets/694a6f9c-43ac-4076-9743-7a611004b2b6)

**Comment by cmcccopy** [comment]
更新到2.14.1版本后bug已解决，感谢作者大佬。
