### ISSUE TITLE
[Bug]  https://api.nextchat.dev/api/proxy/openai dead?

### ISSUE THREAD

**Issue by f1h0** [ChatGPTNextWeb/ChatGPT-Next-Web#5106]
### 📦 Deployment Method

Other

### 📌 Version

no

### 💻 Operating System

Windows

### 📌 System Version

10

### 🌐 Browser

Chrome

### 📌 Browser Version

  Chrome  126.0.6478.182 

### 🐛 Bug Description

{
  "error": true,
  "message": "Failed to fetch"
}

{
  "error": true,
  "message": "empty response from server"
}

### 📷 Recurrence Steps

I want everything to work When you request and receive a correct response.

**Comment by lloydzhou** [comment]
will using [tauri http api](https://tauri.app/v1/api/js/http/) to solve CORS error in App

**Comment by f1h0** [comment]
> this server will down...

What does that mean, please explain. How will it affect the local application?

**Comment by lloydzhou** [comment]
@f1h0 
please see #5379, in local application, using rust http client, no "CORS" error
