### ISSUE TITLE
[Bug] 新版本的DEFAULT_MODEL怎么设置呢？

### ISSUE THREAD

**Issue by AndyLin2020** [ChatGPTNextWeb/ChatGPT-Next-Web#5115]
### 📦 部署方式

Docker

### 📌 软件版本

V2.14

### 💻 系统环境

Windows

### 📌 系统版本

Win 11

### 🌐 浏览器

Chrome

### 📌 浏览器版本

最新

### 🐛 问题描述

原来V2.12版本设置默认核心只需在Docker部署时加上：-e DEFAULT_MODEL=gemini-1.5-pro-latest，V2.13以后就不行了，另外设置以下格式也不行：-e DEFAULT_MODEL=gemini-1.5-pro-latest@Google ，默认核心一直是：gpt-3.5-turbo(OpenAi)

**Comment by Oatu4396** [comment]
新版本的./app/config/server.ts中有这样一段代码：
<img width="498" alt="image" src="https://github.com/user-attachments/assets/69837118-dbd5-48b9-8928-e08d4a72561e">
推测是这个导致的，但不知道作者加这段无视gpt-4的代码的意义

**Comment by DDDDD12138** [comment]
> 新版本的./app/config/server.ts中有这样一段代码： <img alt="image" width="498" src="https://private-user-images.githubusercontent.com/95117017/352887177-69837118-dbd5-48b9-8928-e08d4a72561e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMTk2NTcsIm5iZiI6MTcyMjIxOTM1NywicGF0aCI6Ii85NTExNzAxNy8zNTI4ODcxNzctNjk4MzcxMTgtZGJkNS00OGI5LTg5MjgtZTA4ZDRhNzI1NjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAyMTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMTc5YWUxYWQ2MmZkODFjOTMzYzIxZWIwYzdjNzczMzZmOWI0NjhjOTU4NjhjYWMzM2U2MmNhMDkxNjE3NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H9MBRzOVA244tSuLIGh5sXRZtEN0PoV1Mte7kr-SM_Y"> 推测是这个导致的，但不知道作者加这段无视gpt-4的代码的意义

只有添加了 `DISABLE_GPT4` 环境变量才会使用到这部分的逻辑，用来排除所有 `GPT4` 的模型，似乎和这个ISSUES没有关系
![image](https://github.com/user-attachments/assets/e5a5abba-9839-420d-b11d-e7643fcbfdac)

**Comment by MapleBay** [comment]
![image](https://github.com/user-attachments/assets/3f805823-2c82-419e-9c08-5bc60c635ecc)
我使用Vercel进行部署的也出现了这个问题，设置为4o-mini却始终没有生效，重新部署过多次也仍然无效

**Comment by AndyLin2020** [comment]
-e DEFAULT_MODEL=gemini-1.5-pro-latest@google
以上参数设置可以使用，不过设置中的默认模型还是gpt-3.5-turbo

**Comment by wang20150419** [comment]
最新版本，v2.14.2 一样，设置 DEFAULT_MODEL 无效。

**Comment by Tasselmi** [comment]
我的docker部署的也是一样的，设置 DEFAULT_MODEL 无效，还是显示的gpt-3.5，求修复

**Comment by whistle003** [comment]
这个确实是bug，我设置的DEFAULT_MODEL也无法生效

**Comment by Dogtiti** [comment]
fixed
