### ISSUE TITLE
什么时候能支持LLAMA大模型呢

### ISSUE THREAD

**Issue by JiangPee** [ChatGPTNextWeb/ChatGPT-Next-Web#5116]
### 🥰 需求描述

设置-自定义接口中增加META服务商，接口地址支持本地接口，模型下拉增加LLAMA3.0  LLAMA3.1

### 🧐 解决方案

像MaxKB一样可以自定义本地大模型 LLAMA3.1，输入接口地址与模型名称就可使用

**Comment by JiangPee** [comment]
![image](https://github.com/user-attachments/assets/1b7f2471-f898-40e4-bf71-f21eb3c3cca1)

**Comment by AndyX-Net** [comment]
建议加个中间件，整个人都会好起来的： https://github.com/songquanpeng/one-api
