### ISSUE TITLE
TypeError: Cannot read properties of undefined(reading 'inTable'）

### ISSUE THREAD

**Issue by NirvanaChan** [ChatGPTNextWeb/ChatGPT-Next-Web#5123]
### 📦 Deployment Method

Official installation package

### 📌 Version

网页直接使用

### 💻 Operating System

Windows

### 📌 System Version

Win10

### 🌐 Browser

Chrome

### 📌 Browser Version

116.0.5845.97

### 🐛 Bug Description

![屏幕截图 2024-07-29 113631](https://github.com/user-attachments/assets/b19258c9-0496-4d13-95d0-24f8e99bf6b9)

**Comment by killaragorn** [comment]
+1

**Comment by lloydzhou** [comment]
![image](https://github.com/user-attachments/assets/0edce0d8-ac36-484a-8588-197489a37ff6)

**Comment by lloydzhou** [comment]
```
{
    "version": "v2.12.3",
    "commitDate": "1721033307000",
    "commitHash": "02c878f1f25a4808b30eca06e4262495eb5be26c",
    "buildMode": "standalone",
    "isApp": false,
    "template": "{{input}}"
}
```

**Comment by lloydzhou** [comment]
不是很清楚现在的版本是否还有问题？
在线的app.nextchat.dev 应该是没有问题的
