### ISSUE TITLE
[Feature Request] 自定义模型展示列表

### ISSUE THREAD

**Issue by TyroneXie** [ChatGPTNextWeb/ChatGPT-Next-Web#5128]
### 🥰 需求描述

<img width="1033" alt="image" src="https://github.com/user-attachments/assets/975131ba-e0e1-4b21-858c-58ceca09f991">
这里展示的模型太多了，而且随着越来越多的大模型发布，这个列表还在不断扩展

### 🧐 解决方案

建议可以自定义展示在这里的模型列表，这样选择切换模型的时候也方便些。

**Comment by charle00001** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/README_CN.md#custom_models-%E5%8F%AF%E9%80%89

**Comment by Dogtiti** [comment]
same as #5050

**Comment by TyroneXie** [comment]
感谢，感谢，明白了
