### ISSUE TITLE
[Bug] AzureOpenAi not working in version 2.14

### ISSUE THREAD

**Issue by ErYiii** [ChatGPTNextWeb/ChatGPT-Next-Web#5142]
### 📦 Deployment Method

Official installation package

### 📌 Version

v2.14.0

### 💻 Operating System

macOS

### 📌 System Version

Sonoma

### 🌐 Browser

Other

### 📌 Browser Version

client

### 🐛 Bug Description

Cannot use AzureOpenAI after updating to version 2.14. API configuration has not changed.   return Resource not found

<img width="325" alt="image" src="https://github.com/user-attachments/assets/9b5e639f-d160-4b00-a825-1f31da38f8b9">

### 📝 Additional Information

Functions fine after rolling back to version 2.13

**Comment by ErYiii** [comment]
Resolved, the API sample was https://resourceurl}/openai/deployments/{deploy-id}, it needs to be adjusted to https://resourceurl}/openai.
Also need to change custom model name:[#5001 ](url)

**Comment by EdiWang** [comment]
My deployment works fine.

- `AZURE_URL: https://xxxxxx.openai.azure.com/openai/deployments/`
- `CUSTOM_MODELS: -all,+gpt-4o@azure=gpt-4o,+gpt-4o-mini@azure=gpt-4o-mini`
