### ISSUE TITLE
[Bug] can not select CUSTOM_MODELS in chat  

### ISSUE THREAD

**Issue by miracletiger** [ChatGPTNextWeb/ChatGPT-Next-Web#5144]
### 📦 Deployment Method

Docker

### 📌 Version

2.14.0

### 💻 Operating System

macOS

### 📌 System Version

13

### 🌐 Browser

Chrome, Edge

### 📌 Browser Version

 127.0.2651.74   (x86_64)

### 🐛 Bug Description

when I set CUSTOM_MODELS=-all,+gpt-4o@openai,+gpt-4-1106-preview@openai=gpt-4-turbo,+gpt-3.5-turbo@openai
then when I chat I can not select another model, and I find that  in the previous version like v2.13.1 t works .
![screenshot-20240730-154639](https://github.com/user-attachments/assets/74b68be8-15f1-456d-87f4-b29272470ac0)
![screenshot-20240730-154625](https://github.com/user-attachments/assets/0c9e5b05-009c-4c89-95ff-e232871013b8)

### 📷 Recurrence Steps

version: '3.8'
services:
  chatgpt-next-web:
    # profiles: [ "no-proxy" ]
    container_name: chatgpt-web
    image: chatgpt-next-web:latest
    build:
      context: ./
      dockerfile: DockerfileKylin 
    ports:
      - "3009:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY_NEXTCHAT}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CODE=${CODE}
      - BASE_URL=${BASE_URL}
      - OPENAI_ORG_ID=${OPENAI_ORG_ID}
      - HIDE_USER_API_KEY=${HIDE_USER_API_KEY}
      - DISABLE_GPT4=${DISABLE_GPT4}
      - ENABLE_BALANCE_QUERY=${ENABLE_BALANCE_QUERY}
      - DISABLE_FAST_LINK=${DISABLE_FAST_LINK}
      - OPENAI_SB=${OPENAI_SB}
      - TZ=Asia/Shanghai
      - CUSTOM_MODELS=-all,+gpt-4o@openai,+gpt-4-1106-preview@openai=gpt-4-turbo,+gpt-3.5-turbo@openai
      - DEFAULT_MODEL=gpt-4o
      docker-compose up 

### 🚦 Expected Behavior

no

### 📝 Additional Information

no

**Comment by Dogtiti** [comment]
![image](https://github.com/user-attachments/assets/0a718c98-5155-47ac-a605-6b015c0ba841)
try this

**Comment by miracletiger** [comment]
thanks, just find that the position of the model select button changed!
