### ISSUE TITLE
[Feature Request] DISABLE_GPT4 =1 时不要禁止 gpt-4o-mini 模型

### ISSUE THREAD

**Issue by sinfee** [ChatGPTNextWeb/ChatGPT-Next-Web#5145]
### 🥰 需求描述

gpt-4o-mini模型的推出目标是替代gpt-3.5，它的价格便宜，不应该和gpt-4划在一起，也就是说，如果禁用gpt-4的话，不应用禁用gpt-4o-mini

### 🧐 解决方案

DISABLE_GPT4 =1 时不要禁止 gpt-4o-mini 模型

**Comment by wang20150419** [comment]
如能提供这个功能，就太完美了。
上半年，开放给周边朋友用，有的不小心使用了 gpt-4，导致费用过多。

**Comment by interesmazing** [comment]
这个功能确实可以有。
添加DISABLE_GPT4的初衷就是怕误用导致费用过高，但现在4omini的费用比35还低，已经是日常主力模型了。
