### ISSUE TITLE
[Bug] cannot find correct deployment 

### ISSUE THREAD

**Issue by tfbubu111** [ChatGPTNextWeb/ChatGPT-Next-Web#5158]
### 📦 部署方式

Docker

### 📌 软件版本

2.14 

### 💻 系统环境

Windows

### 📌 系统版本

all

### 🌐 浏览器

Edge

### 📌 浏览器版本

unknown

### 🐛 问题描述

when connect azure openAI deployment, nextWeb connects to https://0530ai.openai.azure.com/openai/deployments/gpt-3.5-turbo, 
not my deployment which name is GPT-4. 

azure endpoint: https://0530ai.openai.azure.com/openai

chat will return error:
{
  "error": {
    "code": "DeploymentNotFound",
    "message": "The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."
  }
}

![image](https://github.com/user-attachments/assets/6fc73e53-7216-4438-9f6e-b8dee3c96c3b)
![image](https://github.com/user-attachments/assets/8e77a222-57c5-4a4d-8303-3844c280e533)

### 🚦 期望结果

please help understand if anything wrong in my settings 

### 📝 补充信息

also I tried to change the image version from 2.14 to 2.13.1, but still same issue

**Comment by johnsonperl** [comment]
我也遇到了这个问题

**Comment by lloydzhou** [comment]
这个issue #5001 以及readme中有说明，当使用azure的时候，deploy_name就等同于 display_name

**Comment by tfbubu111** [comment]
@lloydzhou 

用法这一块我这里设置的没问题：
customer models
gpt-4o@azure=GPT-4

然后我自己的deployment 名字是GPT-4
![image](https://github.com/user-attachments/assets/bda1c4f6-0e72-45de-a02b-eaccea3a2d73)

**Comment by tfbubu111** [comment]
问题在我又重新用docker镜像yidadaa/chatgpt-next-web部署以后消失了， tag默认latest。
