### ISSUE TITLE
一次提问调用两次API

### ISSUE THREAD

**Issue by Jaffoo** [ChatGPTNextWeb/ChatGPT-Next-Web#5164]
为什么有时候我提问一次会调用两次API呢，是不是因为我自定义的面具设置了预置对话呢？如果是的话为什么有时候是gpt-3.5-turbo-0125，有时候是正常的（gpt4o-mini）。我所有的面具都是用的gpt4o-mini，设置里默认也是gpt4o-mini，我不知道这是不是一个bug。

**Comment by Dogtiti** [comment]
提问之后会有一次总结会话的调用
