### ISSUE TITLE
[Bug] 使用azure的gpt-4o-mini，不会总结对话标题

### ISSUE THREAD

**Issue by 00010110** [ChatGPTNextWeb/ChatGPT-Next-Web#5165]
### 📦 部署方式

Docker

### 📌 软件版本

v-2.14

### 💻 系统环境

Ubuntu

### 📌 系统版本

18.04

### 🌐 浏览器

Chrome

### 📌 浏览器版本

Version 122.0.6261.94 (Official Build) (64-bit)

### 🐛 问题描述

使用azure的gpt-4o-mini，不会总结对话标题。这里应该有bug，没有匹配到gpt-4o-mini(Azure)
![image](https://github.com/user-attachments/assets/386d7728-ec8f-41f1-aac2-97f21094effa)
![image](https://github.com/user-attachments/assets/dc54ff53-6a40-4663-8ab4-4c6da9d4fd02)

**Comment by Lightmani** [comment]
I have the same issue

**Comment by Yirenxs** [comment]
I have the same issue

**Comment by sickles8888** [comment]
I have the same issue

**Comment by Dogtiti** [comment]
fixed
