### ISSUE TITLE
[Feature Request] 新增模型控制开关

### ISSUE THREAD

**Issue by wangweiX** [ChatGPTNextWeb/ChatGPT-Next-Web#5188]
### 🥰 需求描述

聊天框那里切换模型，下拉选择，一拉一长条，滚动找半天，其实有很多模型根本用不上，希望能在设置界面做个开关，让用户可以自己控制打开哪些模型。

### 🧐 解决方案

希望能在设置界面做个模型的控制开关，让用户可以自己控制打开哪些模型。

**Comment by lloydzhou** [comment]
可以尝试使用CUSTOM_MODELS配置，详情参考readme
另外，最近有issue提到一次性移除多个模型 #5050
