### ISSUE TITLE
[Bug] Docker部署出现-3001怎么解决

### ISSUE THREAD

**Issue by angler5930** [ChatGPTNextWeb/ChatGPT-Next-Web#5193]
### 📦 部署方式

Docker

### 📌 软件版本

v2.14

### 💻 系统环境

Windows

### 📌 系统版本

Windows 10

### 🌐 浏览器

Chrome

### 📌 浏览器版本

127.0.6533.89

### 🐛 问题描述

![q1](https://github.com/user-attachments/assets/a78dda76-e1c3-4a04-8134-347ea8ba28db)
用上面代码部署会出现-3001错误
![q2](https://github.com/user-attachments/assets/0dd8bf3e-9614-4023-91ba-6b54890ea8d4)
但是在设置里单独设置接口地址就没问题
![q3](https://github.com/user-attachments/assets/9d41b4a3-b621-4a19-9e80-015d7a3c1787)
![q4](https://github.com/user-attachments/assets/1a3cc26b-83be-4f86-9cfa-511b02e644db)
请问这个问题怎么解决呢？

**Comment by lloydzhou** [comment]
请自己检查配置的api地址是否正确，以及环境的网络情况。
这里getaddrinfo报错就是容器内路由不到这个地址。

**Comment by angler5930** [comment]
接口地址没问题，在设置里单独设置接口地址可以访问。单独设置太麻烦了

**Comment by lloydzhou** [comment]
但是，这个错误始终是一个底层的网络问题。应用的代码层面应该解决不了。

**Comment by angler5930** [comment]
此问题暂时已解决，把docker降级到26.0.0版本就可以了。这个版本没网络问题

**Comment by aoding94** [comment]
貌似是https未识别，我是写了两层https才可以的-e BASE_URL=https://https://gpt.datapipe.top/
