### ISSUE TITLE
[Bug] 2.14.0 版本自动生成标题功能失效

### ISSUE THREAD

**Issue by Ubivision** [ChatGPTNextWeb/ChatGPT-Next-Web#5210]
### 📦 部署方式

官方安装包

### 📌 软件版本

2.14.0

### 💻 系统环境

Windows, macOS

### 📌 系统版本

macOS14.5；win10 21H2

### 🌐 浏览器

Safari

### 📌 浏览器版本

Safari17.5

### 🐛 问题描述

无论是使用 macOS 的 universal 版本还是 win64 的 exe 安装版本，2.14.0 的**自动生成标题功能都失效了**。所有聊天标题都默认是“新的聊天”且不发生改变

**Comment by Dogtiti** [comment]
#5111 #5165
