### ISSUE TITLE
[Bug] mini模型名称有误

### ISSUE THREAD

**Issue by QAbot-zh** [ChatGPTNextWeb/ChatGPT-Next-Web#5221]
### 📦 部署方式

Vercel, Docker

### 📌 软件版本

v2.14.1

### 💻 系统环境

Other

### 📌 系统版本

web

### 🌐 浏览器

Chrome

### 📌 浏览器版本

0

### 🐛 问题描述

最近的pr更新中模型名称写错了

### 📝 补充信息

![image](https://github.com/user-attachments/assets/2252a41d-823a-48bf-8d88-557579d0f729)

**Comment by Dogtiti** [comment]
#5223
