### ISSUE TITLE
[Feature Request] 像GPTs那样，在一个普通对话 使用 @ 艾特多个GPTs在同一会话上下文中讨论

### ISSUE THREAD

**Issue by androidfans** [ChatGPTNextWeb/ChatGPT-Next-Web#5227]
### 🥰 需求描述

像GPTs那样，在一个普通对话 使用 @ 艾特多个GPTs在同一会话上下文中讨论

### 🧐 解决方案

像GPTs一样

### 📝 补充信息

![image](https://github.com/user-attachments/assets/6a15a7cb-8e66-46d2-bbaf-7c2a955d6db1)

**Comment by lloydzhou** [comment]
[v2.15.0](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.15.0) Support Plugin (GPTs like action based on function call)

you can using multi tools in one chat session.
