### ISSUE TITLE
[Bug] "The Quota has been exceeded" - Version 2.14.1 (20240806.144936) - Mac M1 

### ISSUE THREAD

**Issue by lupguo** [ChatGPTNextWeb/ChatGPT-Next-Web#5248]
### 📦 Deployment Method

Official installation package

### 📌 Version

Version 2.14.1 (20240806.144936)

### 💻 Operating System

macOS

### 📌 System Version

M1 Sonna 14.6(23G80)

### 🌐 Browser

Chrome

### 📌 Browser Version

Version 127.0.6533.100 (Official Build) (arm64)

#### 错误现象：打开App直接报错，错误内容无法Copy，直接截图呈现：

<img width="1477" alt="image" src="https://github.com/user-attachments/assets/3e74184c-3b95-4d19-b51d-ed93b33c923a">

#### 背景：

NextChat已用了1年多，累积了非常多数据，不清楚是否和数据量是否有关

检索关键字说是和容量相关：

> "The Quota has been exceeded"是在各种情境下常见的错误信息，特别是在计算机和在线服务中。它表示已达到或超过了预定的限制或配额，进一步的操作或请求在配额重置或增加之前无法处理。
> 

不清楚具体应该如何重置，下载了最新的`2.14.1`覆盖安装也不行！

**Comment by lupguo** [comment]
另外，如果对数据敏感的注意下，不要轻易点击“清除数据”；
App Crash后，我点击“清除数据”，NextChat会先提示你导出之前的Chat数据，不过我选择了目录后，没有按预期导出到指定目录

**Comment by Dogtiti** [comment]
应该是数据量太大了`localstorage`不够存了
目前一部分图片数据存储在`cache storage`,但是对话数据还是`localstorage`
下个版本会考虑加上`indexDB`存储对话数据

**Comment by lupguo** [comment]
> `localstorage`不够存储。

导出过程点击清理数据后，数据没有正常导出导致之前的一些prompt丢掉了，清理数据后新开的session app可以正常工作。
