### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CigarLu** [ChatGPTNextWeb/ChatGPT-Next-Web#5249]
### 📦 Deployment Method

Official installation package

### 📌 Version

latest

### 💻 Operating System

Other

### 📌 System Version

latest

### 🌐 Browser

Other

### 📌 Browser Version

latest

### 🐛 Bug Description

README_CN.md 中環境變數 DEFAULT_MODEL  應該是 DEFAULT_MODELS 

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/store/config.ts#L6

**Comment by QAbot-zh** [comment]
没错哦，是你理解错了

DEFAULT_MODELS 是保存了每个provider类型的默认模型列表，用来辅助模型排序的：
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/app/constant.ts#L348

作为环境变量的 DEFAULT_MODEL 是指定默认调用模型的：
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/cf1c8e8f2a12449a274fcfaad01223d85ad03005/app/config/server.ts#L118
