### ISSUE TITLE
[Bug] 更新到 2.14.1 之后 Gemini Free Tier 无法使用

### ISSUE THREAD

**Issue by Dakai** [ChatGPTNextWeb/ChatGPT-Next-Web#5255]
### 📦 部署方式

Vercel

### 📌 软件版本

2.14.1

### 💻 系统环境

Other Linux

### 📌 系统版本

Linux 6.10.3-1

### 🌐 浏览器

Other

### 📌 浏览器版本

Version 1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit)

### 🐛 问题描述

从 2.14.0 升级到 2.14.1 之后 Gemini-1.5-pro-latest 和 Gemini-1.5-flash-latest 这两个模型都无法使用，提示回复说：
```
{
  "error": {
    "code": 400,
    "message": "Gemini API free tier is not available in your country. Please enable billing on your project in Google AI Studio.",
    "status": "FAILED_PRECONDITION"
  }
}
```
Vercel 的 Function Region 地点都选择了北美地区。
Rollback 回 2.14.0 恢复正常

**Comment by mountainguan** [comment]
我也是，而且我自己加了一个worker代理地址，然后这个地址通过linux的curl调用非常正常，填进去配置里以后，就是间歇性抽风，也不是百分百不行，时不时可以，又时不时跟你一样的提示

**Comment by mountainguan** [comment]
上个图，圈住的两个请求，请求内容一致，一个一请求就400，另一个是正常200。这个异常时发生在请求应用路由阶段，后续的Fetch URL的逻辑也正常运行，但是400出来过后，就跟题主的内容一样，提示异常。这个应用时部署在vercel上的，gemini做了一个worker的简单代理，就是直接转发。在旧版本中，请求是直接发生在浏览器这边，没有出现过这种异常，现在请求需要从vercel这边对worker代理进行触发，就会间歇性抽风
![image](https://github.com/user-attachments/assets/338d28b6-1c11-444d-aa72-07635b325d79)
