### ISSUE TITLE
[Bug] 新版本检测错误

### ISSUE THREAD

**Issue by phpgao** [ChatGPTNextWeb/ChatGPT-Next-Web#5264]
### 📦 部署方式

官方安装包

### 📌 软件版本

2.14.1

### 💻 系统环境

macOS

### 📌 系统版本

14.6.1

### 🌐 浏览器

Chrome

### 📌 浏览器版本

127.0.6533.99

### 🐛 问题描述

新版本判断逻辑有问题
<img width="259" alt="企业微信截图_0c911ce8-6082-4367-a9be-e8e7df762a1a" src="https://github.com/user-attachments/assets/bef636d9-3cba-4eb1-8de1-caf9d5b1fba8">

### 📷 复现步骤

2.14.0 --> 2.14.1

**Comment by mayfwl** [comment]
> ### 📦 部署方式
> 官方安装包
> 
> ### 📌 软件版本
> 2.14.1
> 
> ### 💻 系统环境
> macOS操作系统
> 
> ### 📌 系统版本
> 14.6.1
> 
> ### 🌐 浏览器
> 铬
> 
> ### 📌 浏览器版本
> 127.0.6533.99
> 
> ### 🐛 问题描述
> 新版本判断逻辑有问题 <img alt="企业微信截图_0c911ce8-6082-4367-a9be-e8e7df762a1a" width="259" src="https://private-user-images.githubusercontent.com/8272879/357259347-bef636d9-3cba-4eb1-8de1-caf9d5b1fba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDI0ODgsIm5iZiI6MTcyMzcwMjE4OCwicGF0aCI6Ii84MjcyODc5LzM1NzI1OTM0Ny1iZWY2MzZkOS0zY2JhLTRlYjEtOGRlMS1jYWY5ZDViMWZiYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMDYwOTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE2ZjlkMmUyZGFlMzk2OGMzMmEyZjI4MmYzMjQyNDVjODFkMmRhYzVjM2E5OTU5NDUxZTc4MmYyNmM3MzZiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2TzxwFzmhx3l-F6fVMM9EZv6K5ZZ4sg6-WWBqqcSSAA">
> 
> ### 📷 复现步骤
> 2.14.0 --> 2.14.1
> 
> ### 🚦 期望结果
> _没有回应_
> 
> ### 📝 补充信息
> _没有回应_

怎么复现这个问题？

**Comment by mrifoxer** [comment]
缓存问题，清空浏览器缓存就行了
