### ISSUE TITLE
[Bug] 升級到 2.14.1 之後， google gemini 無法使用

### ISSUE THREAD

**Issue by changchichung** [ChatGPTNextWeb/ChatGPT-Next-Web#5267]
### 📦 Deployment Method

Official installation package

### 📌 Version

2.14.1

### 💻 Operating System

Windows

### 📌 System Version

win10 22H2

### 🌐 Browser

Firefox

### 📌 Browser Version

128.0.3（64 位元）

### 🐛 Bug Description

原本版本是 v2.12.4，檢查更新後發現有 2.14.1 ，下載安裝後，原本可以正常使用的google gemini 就無法使用了。

**Comment by lloydzhou** [comment]
现在应该没有这个问题了吧，最新的v2.15.5版本 gemini模型支持function call
