### ISSUE TITLE
[Bug] 讯飞星火无法对话

### ISSUE THREAD

**Issue by rjku6** [ChatGPTNextWeb/ChatGPT-Next-Web#5286]
### 📦 部署方式

Vercel

### 📌 软件版本

3.0

### 💻 系统环境

Windows

### 📌 系统版本

11

### 🌐 浏览器

Chrome

### 📌 浏览器版本

127.0.6533.120

### 🐛 问题描述

IFLYTEK_URL (可选)
讯飞星火Api Url.

IFLYTEK_API_KEY (可选)
讯飞星火Api Key.

IFLYTEK_API_SECRET (可选)
讯飞星火Api Secret.
对应的参数填写后对话显示
{
  "error": true,
  "message": "Failed to fetch"
}
星火官方：Spark_url = "wss://spark-api.xf-yun.com/v1.1/chat"
用Python调用是正常的
改为：Spark_url = "https://spark-api.xf-yun.com/v1.1/chat"
在nextweb上就无法对话了
模型版本是general

**Comment by QAbot-zh** [comment]
因为讯飞 wss 和 http 的接口网址不统一，你要填的话就填 https://spark-api-open.xf-yun.com

https://www.xfyun.cn/doc/spark/HTTP%E8%B0%83%E7%94%A8%E6%96%87%E6%A1%A3.html#_2-%E8%AF%B7%E6%B1%82%E5%9C%B0%E5%9D%80

**Comment by rjku6** [comment]
> 因为讯飞 wss 和 http 的接口网址不统一，可以不填保持默认，非要填的话就填 https://spark-api-open.xf-yun.com
> 
> https://www.xfyun.cn/doc/spark/HTTP%E8%B0%83%E7%94%A8%E6%96%87%E6%A1%A3.html#_2-%E8%AF%B7%E6%B1%82%E5%9C%B0%E5%9D%80

您好，保持默认的时候也是无法对话，输入您的链接对话响应的结果还是无法使用，您可以尝试一下看看

**Comment by QAbot-zh** [comment]
检查下你的网络环境？我这边几个基本模型都是可以正常对话的

![image](https://github.com/user-attachments/assets/06848de6-95d0-4595-a1aa-80e8e673a8f3)

![Clip_2024-08-17_20-02-02](https://github.com/user-attachments/assets/9d254256-6c08-432f-8e4f-09ccf773848b)

**Comment by rjku6** [comment]
> 检查下你的网络环境？我这边几个基本模型都是可以正常对话的
> 
> ![image](https://private-user-images.githubusercontent.com/40236765/358843983-06848de6-95d0-4595-a1aa-80e8e673a8f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTcxMDcsIm5iZiI6MTcyMzg5NjgwNywicGF0aCI6Ii80MDIzNjc2NS8zNTg4NDM5ODMtMDY4NDhkZTYtOTVkMC00NTk1LWExYWEtODBlOGU2NzNhOGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDEyMTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYjJhMDNiZTk2MGY0NjhlMGZlNzFlMDhiMzY5NjU5MWMxZDQ0MGFiMzcxN2QyZjBmMjNmYTIyODJmYjk4ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zw8e4C_djkM14SGkDUafuOCyQf65YWyqZ-_CtvKZeP8)
> 
> ![Clip_2024-08-17_20-02-02](https://private-user-images.githubusercontent.com/40236765/358843974-9d254256-6c08-432f-8e4f-09ccf773848b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTcxMDcsIm5iZiI6MTcyMzg5NjgwNywicGF0aCI6Ii80MDIzNjc2NS8zNTg4NDM5NzQtOWQyNTQyNTYtNmMwOC00MzJmLThlNGYtMDljY2Y3NzM4NDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDEyMTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNjI3YzgyYTYyMzA2NDhmYTVjZDYyMGM3YWY5NzQxOTMxNGIwMGUxNDZjNzJiNjNiYjU4YWJmOWY3NzVhNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kYB2BbJL_QkvuSKw54TV5uBn5Jeca569Q2MvYxJISJw)

您好，检查过了是代理IP的问题已经解决了感谢您的回答
