### ISSUE TITLE
[Bug] 每次对话都会重新请求生成一次标题

### ISSUE THREAD

**Issue by interesmazing** [ChatGPTNextWeb/ChatGPT-Next-Web#5307]
### 📦 Deployment Method

Vercel

### 📌 Version

2.14.2

### 💻 Operating System

Windows

### 📌 System Version

Windows10

### 🌐 Browser

Chrome

### 📌 Browser Version

127.0.6533.120

### 🐛 Bug Description

同一个回话页面下，除了第一次对话会生成标题，之后每次对话都会请求生成标题，大量消耗Prompt Token
![image](https://github.com/user-attachments/assets/30272386-799c-4a47-9504-896930e5bf4f)

**Comment by interesmazing** [comment]
同一个会话下，4o回答一次问题，4omini就会总结一次标题，但实际上标题并没有被更新。并且关闭“自动生成标题”之后，虽然前端不显示标题，但生成标题的请求一直都在。
![image](https://github.com/user-attachments/assets/343d70ff-64e8-47c8-aef3-837c2862762a)

**Comment by QAbot-zh** [comment]
不是标题生成，是对话总结（标题的补全都很小，很容易分辨），可以禁用它

![image](https://github.com/user-attachments/assets/ae58d8b8-20a8-4fbd-9cb6-787632f500da)

**Comment by interesmazing** [comment]
原来是这样 谢谢
