### ISSUE TITLE
[Feature Request] prompt chain

### ISSUE THREAD

**Issue by xiaoheimissu** [ChatGPTNextWeb/ChatGPT-Next-Web#5313]
### 🥰 需求描述

Is it possible to add a prompt chain in the mask feature? The specific requirement is that after the conversation initiated by the previous prompt ends, the next prompt in the mask is automatically entered and sent.

### 🧐 解决方案

Can add multiple prompts when adding a mask, instead of just adding a starting prompt. This allows for more automation when handling certain tasks. For instance, when translating, you can add translation prompt 1 and polishing prompt 2. After the translation is completed, prompt 2 can be automatically added to send the previous conversation for polishing.

**Comment by lloydzhou** [comment]
mask is not agent
