### ISSUE TITLE
[Feature Request] 输入框需要增加上传文档文件的地方

### ISSUE THREAD

**Issue by Alexbai10** [ChatGPTNextWeb/ChatGPT-Next-Web#5318]
### 🥰 需求描述

GPT4o支持上传文档文件解析，需要可以增加上传文档的入口

### 🧐 解决方案

在上传图片icon旁边增加一个文档icon即可

**Comment by QAbot-zh** [comment]
4o 也没支持呀
![image](https://github.com/user-attachments/assets/495a5870-8905-4b85-ab70-5a34f95efe03)

**Comment by Alexbai10** [comment]
![WechatIMG344](https://github.com/user-attachments/assets/86ea94ec-9f03-49a3-81e5-f2c3505144f6)
肯定是可以支持的，我才提需求的啊！

**Comment by QAbot-zh** [comment]
那是官网做了 RAG，api 又不支持
