### ISSUE TITLE
[Feature Request] Shortcuts for clear context

### ISSUE THREAD

**Issue by guluguru** [ChatGPTNextWeb/ChatGPT-Next-Web#5327]
### 🥰 Feature Description

Add shortcuts for clear current context, because I use that for over hundred times everyday.

### 🧐 Proposed Solution

I guess the description is clear and enough.

**Comment by QAbot-zh** [comment]
You can input quotation marks（`:`） to trigger the clearing context or to delete the current chat window.

![image](https://github.com/user-attachments/assets/e05e3f16-bbe5-4594-9946-28c0370d069a)

Or click this icon to clear context.
![image](https://github.com/user-attachments/assets/74bb6d57-5257-492a-9e76-5dfdfefc7eec)

**Comment by guluguru** [comment]
thank you, `:clear` meets my need
