### ISSUE TITLE
[Feature Request] github models过了，能不能用那里的token访问？

### ISSUE THREAD

**Issue by liuruidong4** [ChatGPTNextWeb/ChatGPT-Next-Web#5336]
### 🥰 Feature Description

不知道应该如何设置，根据github modles文档可以使用。

### 🧐 Proposed Solution

不知道应该如何设置，根据github modles文档可以使用。

**Comment by QAbot-zh** [comment]
自定义接口地址填：`https://models.inference.ai.azure.com/chat/completions?`
密钥填 github 生成的 token

**Comment by kiklata** [comment]
> 自定义接口地址填：`https://models.inference.ai.azure.com/chat/completions?` 密钥填 github 生成的 token

似乎没有成功，提示No authorization header found in request

**Comment by QAbot-zh** [comment]
> > 自定义接口地址填：`https://models.inference.ai.azure.com/chat/completions?` 密钥填 github 生成的 token
> 
> 似乎没有成功，提示No authorization header found in request

之前写错了，填这个：`https://models.inference.ai.azure.com/chat/completions#`，实测有效

**Comment by liuruidong4** [comment]
> > > 自定义接口地址填：`https://models.inference.ai.azure.com/chat/completions?` 密钥填 github 生成的 token
> > 
> > 
> > 似乎没有成功，提示No authorization header found in request
> 
> 之前写错了，填这个：`https://models.inference.ai.azure.com/chat/completions#`，实测有效

是的,可以了谢谢~

**Comment by ShiinaKin** [comment]
> > > 自定义接口地址填：`https://models.inference.ai.azure.com/chat/completions?` 密钥填 github 生成的 token
> > 
> > 
> > 似乎没有成功，提示No authorization header found in request
> 
> 之前写错了，填这个：`https://models.inference.ai.azure.com/chat/completions#`，实测有效

@QAbot-zh 很抱歉打扰你，但是想请问一下，是在设置的`自定义接口`下，自定义`Azure`的接口地址为`https://models.inference.ai.azure.com/chat/completions#`，接口密钥为GithubPAT，并自定义模型名为`Phi-3-medium-128k-instruct`之类的GitHub Models提供的模型吗

我这样设置后返回：
```json
{
  "error": {
    "message": "The model `Phi-3-medium-128k-instruct` does not exist or you do not have access to it.",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
  }
}
```

**Comment by QAbot-zh** [comment]
github Models 的模型都走 openai 格式，选择 openai 类型填就好了

![image](https://github.com/user-attachments/assets/bdb564fe-9dce-40c5-8739-652b1a5de227)

**Comment by ShiinaKin** [comment]
> github Models 的模型都走 openai 格式，选择 openai 类型填就好了
> 
> ![image](https://private-user-images.githubusercontent.com/40236765/363831708-bdb564fe-9dce-40c5-8739-652b1a5de227.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQ0ODgsIm5iZiI6MTcyNTMzNDE4OCwicGF0aCI6Ii80MDIzNjc2NS8zNjM4MzE3MDgtYmRiNTY0ZmUtOWRjZS00MGM1LTg3MzktNjUyYjFhNWRlMjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMjk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNDgxMWJmZjE3YzM0ODVlMDBjYTg0YzdjZDQyYWVlZjkwMTBmZjBmODMzOGM5YjUxODY2ZWIwODljNGEzZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T7_W3CNVqTIaMqjLPoyAaiQe5wf1mvJGhmzhCV1G5WE)

这样似乎会覆盖原有的openai设置，看来要等本项目加入对Github Model的支持了
