### ISSUE TITLE
[Bug] UI聊天历史消息发送问题

### ISSUE THREAD

**Issue by etjec4** [ChatGPTNextWeb/ChatGPT-Next-Web#5340]
### 📦 Deployment Method

Vercel

### 📌 Version

2.14.2

### 💻 Operating System

Windows

### 📌 System Version

11

### 🌐 Browser

Chrome

### 📌 Browser Version

new

### 🐛 Bug Description

![辰](https://github.com/user-attachments/assets/c4b69e3b-cccd-46c1-b5bb-451baabb289e)

Retry problem.

### 🚦 Expected Behavior

请修复UI聊天历史消息发送问题。

**Comment by Leizhenpeng** [comment]
太抽象,无法复现,,,,
