### ISSUE TITLE
[Feature Request] 腾讯混元怎么样自定义？

### ISSUE THREAD

**Issue by qidianlinjin1990** [ChatGPTNextWeb/ChatGPT-Next-Web#5343]
### 🥰 需求描述

腾讯混元只有appid，secretid和secretkey，而自定义需要api key，所以想知道api key的是怎么设置

### 🧐 解决方案

腾讯混元只有appid，secretid和secretkey，而自定义需要api key，所以想知道api key的是怎么设置

**Comment by lloydzhou** [comment]
![image](https://github.com/user-attachments/assets/76bab2cb-58b5-4ab5-90ca-c2f7b925fe56)
