### ISSUE TITLE
[Bug] webdav检查可用性通过，但是同步失败

### ISSUE THREAD

**Issue by influence312** [ChatGPTNextWeb/ChatGPT-Next-Web#5345]
### 📦 Deployment Method

Vercel

### 📌 Version

latest

### 💻 Operating System

Windows

### 📌 System Version

win11

### 🌐 Browser

Edge

### 📌 Browser Version

latest

### 🐛 Bug Description

使用的是坚果云的webdav，在vercel配置环境变量已经将地址添加进白名单，并且检查可用性通过，配置如图
<img width="828" alt="Snipaste_2024-08-31_19-44-47" src="https://github.com/user-attachments/assets/fb41a951-483f-477a-bfaf-b559a133bab1">
![image](https://github.com/user-attachments/assets/4ca4cae3-a1b6-453e-b1b2-0f021621e9da)
但是在同步时会显示同步失败，报错如图：
![image](https://github.com/user-attachments/assets/77f12898-fb15-4dca-b5ec-9785ba877be7)
![image](https://github.com/user-attachments/assets/0553869a-3ad1-48d3-8d42-6a39fb0b5cee)

**Comment by wsir88888** [comment]
请问跨越代理地址是什么啊，

**Comment by influence312** [comment]
> 请问跨越代理地址是什么啊，

是vercel给项目提供的域名，以app结尾那个

**Comment by influence312** [comment]
<img width="690" alt="Snipaste_2024-09-01_09-32-57" src="https://github.com/user-attachments/assets/d2d65f4f-a39e-4dc9-aa95-888d00344d20">
<img width="550" alt="Snipaste_2024-09-01_09-34-30" src="https://github.com/user-attachments/assets/7bcb14aa-5dbf-4746-bb9f-175b9ef607be">

我已经在坚果云建立了对应的文件夹和空的backup.json了
![image](https://github.com/user-attachments/assets/f5c65a12-4fc1-48d8-be9f-bf59564b2e11)

**Comment by influence312** [comment]
似乎是坚果云的问题，换成teracloud可以同步了

**Comment by wusongzhou** [comment]
> 似乎是坚果云的问题，换成teracloud可以同步了

老哥能分享下如何配置teracloud的，我尝试了两天各种webdav都不行。
