### ISSUE TITLE
[Bug] Updated to v2.14.2 but don't see Dall-E in list of models

### ISSUE THREAD

**Issue by mfarley281** [ChatGPTNextWeb/ChatGPT-Next-Web#5347]
### 📦 Deployment Method

Vercel

### 📌 Version

2.14.2

### 💻 Operating System

Ubuntu

### 📌 System Version

24.04

### 🌐 Browser

Chrome

### 📌 Browser Version

126

### 🐛 Bug Description

I updated to the latest version but do not see Dall-E in the list of models available. How can I use Dall-E?

### 📷 Recurrence Steps

Update to latest, go to settings, look at models available in the dropdown

### 🚦 Expected Behavior

Dall-E should be listed, it's not

**Comment by lloydzhou** [comment]
1. using `dall-e-3` model belong OpenAI, see https://app.nextchat.dev
![image](https://github.com/user-attachments/assets/c4452549-fc0f-42bb-96fd-0925d6ced6da)
2. after v2.15.0, can using `Dalle` as plugin. see: https://github.com/ChatGPTNextWeb/NextChat-Awesome-Plugins/tree/main/plugins/dalle
