### ISSUE TITLE
[Bug] 合并的indexedDB-storage这个代码，有严重bug，聊天对话页面刷新三次，聊天内容就没了，被重置了

### ISSUE THREAD

**Issue by laxfer** [ChatGPTNextWeb/ChatGPT-Next-Web#5354]
### 📦 Deployment Method

Official installation package

### 📌 Version

v2.14.2

### 💻 Operating System

Ubuntu

### 📌 System Version

24.04

### 🌐 Browser

Edge

### 📌 Browser Version

Microsoft Edge 版本 128.0.2739.54 (正式版本) (64 位)

### 🐛 Bug Description

合并了indexedDB-storage这个代码，有严重bug，聊天对话页面连着刷新2次以上，indexedDB库就被重置了，导致以前的对话记录丢失

### 📷 Recurrence Steps

合并了indexedDB-storage这个代码，有严重bug，聊天对话页面连着刷新2次以上，indexedDB库就被重置了，导致以前的对话记录丢失

### 🚦 Expected Behavior

希望能修复多次刷新页面，indexedDB库就被重置，对话内容丢失的BUG。

**Comment by Dogtiti** [comment]
Uploading 飞书20240903-164031.mp4…

**Comment by Dogtiti** [comment]
[飞书20240903-164031.zip](https://github.com/user-attachments/files/16845858/20240903-164031.zip)
我录了个屏 暂时没有复现 不排除是大数据量异步存储到indexeddb被刷新了，需要排查一下
如果着急可以回退版本 数据其实还是在localstorage里面
indexeddb 第一次会尝试从localstorage取数据 然后set到indexeddb 
后续indexeddb 里面有数据了就会直接从indexeddb 读取存储

**Comment by Dogtiti** [comment]
https://5356-vercelpreviewdeployment.pr.nextchat.dev/#/chat 
@laxfer 麻烦再这个地址帮忙测试一下呀 修复了一下

**Comment by laxfer** [comment]
@Dogtiti https://5356-vercelpreviewdeployment.pr.nextchat.dev/#/chat这个地址测试了，indexeddb里面一直是空的，根本没写入值

**Comment by laxfer** [comment]
我重新添加了你更新的代码到项目，这次的问题是数据并没写入indexeddb，经调试，indexeddb里面一直是空的。

**Comment by Dogtiti** [comment]
@laxfer 再试试 刚刚的是有点问题

**Comment by laxfer** [comment]
> @laxfer 再试试 刚刚的是有点问题

这次测试，多次刷新导致原来存的数据被重置的问题已经解决了，非常感谢

**Comment by laxfer** [comment]
> @laxfer 再试试 刚刚的是有点问题

这次测试，多次刷新导致原来存的数据被重置的问题已经解决了，非常感谢
