### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 2218675712** [ChatGPTNextWeb/ChatGPT-Next-Web#5359]
### 📦 Deployment Method

Vercel

### 📌 Version

使用官网域名https://app.nextchat.dev/，2.14.2

### 💻 Operating System

Windows

### 📌 System Version

11

### 🌐 Browser

Chrome

### 📌 Browser Version

128

### 🐛 Bug Description

使用自定义豆包模型，调用提示跨域错误，使用第三方接口工具可以正常调用
![image](https://github.com/user-attachments/assets/f11e2929-f1bb-4a99-9210-4d65dc84e9e7)
![image](https://github.com/user-attachments/assets/1822fbd7-da6c-4229-b35b-06c1bcb2e938)
![image](https://github.com/user-attachments/assets/9107f59a-5776-4a90-9c99-9d7a2faf4bc7)
使用三方工具
![image](https://github.com/user-attachments/assets/97a4c3fa-2220-4b5c-a980-8c28109bda92)

**Comment by lloydzhou** [comment]
网页版使用豆包模型的时候，自定义域名填写： `/api/bytedance` 而不是`https://ark.cn-beijing.volces.com`
