### ISSUE TITLE
[Feature Request] 能不能在设置里添加个模型列表

### ISSUE THREAD

**Issue by bo8888** [ChatGPTNextWeb/ChatGPT-Next-Web#5360]
### 🥰 需求描述

目前用 -e CUSTOM_MODELS=  不能用模糊匹配，而且很容易出错，可不可以在配置里加一个复选框的模型列表配置

### 🧐 解决方案

在配置里加一个复选框的模型列表配置

**Comment by Leizhenpeng** [comment]
related https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5361
