### ISSUE TITLE
[Bug] 代码显示区css的overflow-y错误设置为hidden

### ISSUE THREAD

**Issue by WJZ-P** [ChatGPTNextWeb/ChatGPT-Next-Web#5362]
### 📦 部署方式

Other

### 📌 软件版本

https://app.nextchat.dev/

### 💻 系统环境

Windows

### 📌 系统版本

win11

### 🌐 浏览器

Edge

### 📌 浏览器版本

版本 128.0.2739.63 (正式版本) (64 位)

### 🐛 问题描述

在gpt输出代码时，代码块的overflow-y为hidden，导致代码无法显示完全。
![image](https://github.com/user-attachments/assets/d3cfdad7-a634-4c74-86ac-b5a25d71711d)
![image](https://github.com/user-attachments/assets/bce3d240-68c0-4eb0-a478-ddeb5f788d23)

### 📷 复现步骤

让GPT输出长代码就行

### 🚦 期望结果

只需要把overflow-y设置成auto即可

### 📝 补充信息

无

**Comment by mayfwl** [comment]
主分支已修复，未发布新版本，预计今天发布
