### ISSUE TITLE
[Bug] 自定义 BASE_URL 无法使用自定义路径

### ISSUE THREAD

**Issue by ramondsq** [ChatGPTNextWeb/ChatGPT-Next-Web#5371]
### 📦 部署方式

Vercel

### 📌 软件版本

latest

### 💻 系统环境

Windows

### 📌 系统版本

win 11

### 🌐 浏览器

Chrome

### 📌 浏览器版本

128

### 🐛 问题描述

github models 的 endpoint 是 `https://models.inference.ai.azure.com/chat/completions`，但是无论`BASE_URL`设置为`https://models.inference.ai.azure.com`还是`https://models.inference.ai.azure.com/chat/completions`，请求都会被强制加上路径`v1/chat/completions`，导致无法使用。希望可以让用户自定义路径。

**Comment by QAbot-zh** [comment]
`https://models.inference.ai.azure.com/chat/completions#`

**Comment by ramondsq** [comment]
> `https://models.inference.ai.azure.com/chat/completions#`

setting `BASE_URL` as this could solve the problem
