### ISSUE TITLE
v2.15.0 ? v2.14.2 ?

### ISSUE THREAD

**Issue by TCOTC** [ChatGPTNextWeb/ChatGPT-Next-Web#5373]
### 🐛 问题描述

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.15.0 ：

v2.14.2 ?

![image](https://github.com/user-attachments/assets/00efed5d-8a0b-44c7-b6bd-ae0d25a62cc4)

**Comment by lloydzhou** [comment]
merge code and trigger Github action
