### ISSUE TITLE
[Bug] v2.15.0 "message": "Cannot read properties of undefined (reading 'map')"

### ISSUE THREAD

**Issue by xinmans** [ChatGPTNextWeb/ChatGPT-Next-Web#5378]
### 📦 部署方式

Docker

### 📌 软件版本

v2.15.0

### 💻 系统环境

Ubuntu

### 📌 系统版本

20.4

### 🌐 浏览器

Chrome

### 📌 浏览器版本

版本 127.0.6533.73（正式版本） （64 位）

### 🐛 问题描述

chatgpt3.5-turbo的接口，提交prompt后返回报错
"message": "Cannot read properties of undefined (reading 'map')"

### 📝 补充信息

回滚到上一个版本，正常。

**Comment by Dogtiti** [comment]
@xinmans 可以提供一些更详细的复现信息吗~

**Comment by SukkaW** [comment]
<img width="1334" alt="image" src="https://github.com/user-attachments/assets/658cf90e-03aa-432e-9154-c82a088d1687">
<img width="969" alt="image" src="https://github.com/user-attachments/assets/52b5f10d-06f8-4851-bc70-cdd2f6ff32cd">

**Comment by SukkaW** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/2ff292cbfa35de63d9382ac13effe15830893d20/app/client/platforms/openai.ts#L247

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blame/2ff292cbfa35de63d9382ac13effe15830893d20/app/client/platforms/openai.ts#L247

@lloydzhou Git blame shows that you introduce the bug. `useChatStore.getState().currentSession().mask?.plugin` can definitely be `undefined`, yet you deliberately ignore it using `as string[]`, causing the bug.
