### ISSUE TITLE
[Bug]  弹窗组件会先展示一个滚动条,然后又消失,样式和文案会在1s内抖动

### ISSUE THREAD

**Issue by Leizhenpeng** [ChatGPTNextWeb/ChatGPT-Next-Web#5398]
### 📦 Deployment Method

Vercel

### 📌 Version

*

### 💻 Operating System

macOS

### 📌 System Version

*

### 🌐 Browser

Chrome

### 📌 Browser Version

Newest version on Sep 08, 2024

### 🐛 Bug Description

https://github.com/user-attachments/assets/278444bf-06b8-4b78-9fdd-dff503d8adc8

**Comment by Dogtiti** [comment]
@DDMeaqua 去掉第一个disabled item 就行了
