### ISSUE TITLE
[Bug] 模型通过什么什么服务商来访问应该可以自定义，而不是固定

### ISSUE THREAD

**Issue by Ubivision** [ChatGPTNextWeb/ChatGPT-Next-Web#5407]
### 📦 部署方式

官方安装包

### 📌 软件版本

2.15.1

### 💻 系统环境

Windows, macOS

### 📌 系统版本

Sonama 14.5

### 🌐 浏览器

Chrome, Safari

### 📌 浏览器版本

safari17.5

### 🐛 问题描述

当自定义模型名称和已存在模型名称重复时，会强制使用模型列表中对应模型的 api 格式。比如我有自己的 oneapi 可以调用 cladue，但会被强制使用anthropic 的 api，导致 cladue 所有模型我都无法使用。

### 🚦 期望结果

模型可以自定义选择使用不同的模型服务商

**Comment by skymkmk** [comment]
请仔细阅读 #5001

**Comment by 3biubiu** [comment]
> 如果想要通过 OpenAI 兼容的api调用模型，自定义模型名称应该为 `<modelName>@OpenAI`，比如`claude-3-5-sonnet@OpenAI`，同理如果调用claude兼容的api接口，则使用 `<modelName>@Anthropic`。详情参考置顶issue #5001
> 
> 在使用对应的自定义模型前，需设置好相关的API_URL。

但是这样为什么会调用我配的 base url 而不是 ANTHROPIC_URL
