### ISSUE TITLE
[Feature Request] new OpenAI o1 model

### ISSUE THREAD

**Issue by chesha1** [ChatGPTNextWeb/ChatGPT-Next-Web#5409]
### 🥰 需求描述

OpenAI introduced [new o1 series model](https://openai.com/index/introducing-openai-o1-preview/) with SOTA performance.

And it can be used by API, I am wondering if ChatGPT-Next-Web can support new models.

### 🧐 解决方案

NOP

### 📝 补充信息

The o1 models are currently in beta with limited features. Access is limited to developers in [tier 5](https://platform.openai.com/docs/guides/rate-limits/usage-tiers?context=tier-five)

Tier 5 means user has paid over $1000 and it has been over 30 days since first successful payment

**Comment by echofly** [comment]
+1

**Comment by imaiya** [comment]
+1

**Comment by hikoxy** [comment]
+1

**Comment by wangbing35** [comment]
+1

**Comment by 1-bytes** [comment]
+1

**Comment by winlinvip** [comment]
Need some changes, o1-review does not support stream, no temperature, no max token.

**Comment by realzhukaihua** [comment]
how to use o1 model

**Comment by Dogtiti** [comment]
#5416
