### ISSUE TITLE
[Bug] vercel部署提示密码错误

### ISSUE THREAD

**Issue by Arthur409** [ChatGPTNextWeb/ChatGPT-Next-Web#5414]
### 📦 部署方式

Vercel

### 📌 软件版本

最近

### 💻 系统环境

Windows

### 📌 系统版本

Windows11

### 🌐 浏览器

Edge

### 📌 浏览器版本

最新

### 🐛 问题描述

用vercel部署，一直提示密码错误
<img width="898" alt="image" src="https://github.com/user-attachments/assets/6607b962-b7b9-47ea-b34c-affaa04aca6a">

### 🚦 期望结果

请解决这一问题

**Comment by Arthur409** [comment]
我确定密码是正确的，填写环境变量后也进行了重新部署

**Comment by 13517493830** [comment]
清除网页缓存
![image](https://github.com/user-attachments/assets/f8ccca48-c2f5-4449-af9d-b693cef16eb5)

**Comment by Arthur409** [comment]
没问题了，感谢感谢！
