### ISSUE TITLE
[Feature Request] 切换其它应用再次切换回来时，会自动滚动到底部，很不方便。

### ISSUE THREAD

**Issue by wcldyx** [ChatGPTNextWeb/ChatGPT-Next-Web#5420]
### 🥰 需求描述

切换其它应用再次切换回来时，会自动滚动到底部，每次都要手动滚动到原来的位置很不方便。

### 🧐 解决方案

保持滚动位置

![动画-1](https://github.com/user-attachments/assets/da81bbe3-24e6-48bd-b70c-452c9c9731f6)
![动画-2](https://github.com/user-attachments/assets/b8cef22c-22be-46c2-ba33-67138aca727a)

**Comment by lloydzhou** [comment]
这个需要大家讨论一下。其实在我看来，滚动到底部是方便的合理的

**Comment by lloydzhou** [comment]
抱歉，我理解错了，我以为是点击不同的会话自动切换到底部。

这里指的是，切换其他应用回来之后当前会话会自动滚动。这个交互确实不合理。

**Comment by skymkmk** [comment]
只有在输入框聚焦时才会滚动到最底部，我一直以为是开发者刻意设计的

**Comment by Leizhenpeng** [comment]
这个东西的根本原因是:

 A: 在切换应用的时候会默认激激活先切换应用的输入框 
 
 B: 而激活的输入框会自动滚动到页面底部 
 
  Ab这两个设计都是合理的 
  
  哈哈
  
参考: claud 以及 chatgpt的 网页版
