### ISSUE TITLE
[Bug] 插件按钮在切换模型后消失

### ISSUE THREAD

**Issue by zhoubinxin** [ChatGPTNextWeb/ChatGPT-Next-Web#5425]
### 📦 Deployment Method

Vercel

### 📌 Version

v2.15.2

### 💻 Operating System

Windows

### 📌 System Version

win11

### 🌐 Browser

Chrome

### 📌 Browser Version

128.0.6613.120

### 🐛 Bug Description

切换模型后插件按钮不可见

![recording](https://github.com/user-attachments/assets/a019e45e-5d2a-4e9b-af03-cb231f69d5c7)

环境变量设置了只设置了BASE_URL和CUSTOM_MODELS

**Comment by lloydzhou** [comment]
这边配置的`ServiceProvider`似乎不是内置的(`OpenAI`) 所以导致这里不展示插件按钮

**Comment by zhoubinxin** [comment]
明白了，感谢
