### ISSUE TITLE
[Bug] Anthropic authentication_error CORS

### ISSUE THREAD

**Issue by si1en7** [ChatGPTNextWeb/ChatGPT-Next-Web#5429]
### 📦 Deployment Method

Official installation package

### 📌 Version

2.15.2

### 💻 Operating System

Windows

### 📌 System Version

Windows 11

### 🌐 Browser

Other

### 📌 Browser Version

Desktop

### 🐛 Bug Description

Changes to Anthropic API now responds:
```
{
  "type": "error",
  "error": {
    "type": "authentication_error",
    "message": "CORS requests must set 'anthropic-dangerous-direct-browser-access' header"
  }
}
```
This was a recent change to the API and now prevents NextChat from communicating correctly.

### 📷 Recurrence Steps

Any interaction with any existing or new chat will cause this issue.

**Comment by Vaviera** [comment]
> ### 📦 Deployment Method
> Official installation package
> 
> ### 📌 Version
> 2.15.2
> 
> ### 💻 Operating System
> Windows
> 
> ### 📌 System Version
> Windows 11
> 
> ### 🌐 Browser
> Other
> 
> ### 📌 Browser Version
> Desktop
> 
> ### 🐛 Bug Description
> Changes to Anthropic API now responds:
> 
> ```
> {
>   "type": "error",
>   "error": {
>     "type": "authentication_error",
>     "message": "CORS requests must set 'anthropic-dangerous-direct-browser-access' header"
>   }
> }
> ```
> 
> This was a recent change to the API and now prevents NextChat from communicating correctly.
> 
> ### 📷 Recurrence Steps
> Any interaction with any existing or new chat will cause this issue.
> 
> ### 🚦 Expected Behavior
> _No response_
> 
> ### 📝 Additional Information
> _No response_

Abrí yoro

**Comment by sunilsoni** [comment]
My API is completely stopped working because of this error:



Invalid API Key, please check it in [Settings](/#/settings) page.

```json
{
  "type": "error",
  "error": {
    "type": "authentication_error",
    "message": "CORS requests must set 'anthropic-dangerous-direct-browser-access' header"
  }
}
```

**Comment by lloydzhou** [comment]
#5379

**Comment by lloydzhou** [comment]
You can now add the following HTTP request header to enable CORS support for the Anthropic API, which means you can make calls to Anthropic’s models directly from a browser:
```
anthropic-dangerous-direct-browser-access: true
```
https://simonwillison.net/2024/Aug/23/anthropic-dangerous-direct-browser-access/

**Comment by Sebastianxpp** [comment]
> You can now add the following HTTP request header to enable CORS support for the Anthropic API, which means you can make calls to Anthropic’s models directly from a browser:
> 
> ```
> anthropic-dangerous-direct-browser-access: true
> ```
> 
> https://simonwillison.net/2024/Aug/23/anthropic-dangerous-direct-browser-access/

But where to add it and how to make it work in this application :(

**Comment by andremacola** [comment]
Still not working
