### ISSUE TITLE
[Bug] 没有找到O1模型

### ISSUE THREAD

**Issue by Concertoss** [ChatGPTNextWeb/ChatGPT-Next-Web#5433]
### 📦 部署方式

Vercel

### 📌 软件版本

v2.15.2

### 💻 系统环境

macOS

### 📌 系统版本

12.2.1

### 🌐 浏览器

Chrome

### 📌 浏览器版本

128.0.6613.138

### 🐛 问题描述

在列表中并没有找到o1模型

**Comment by TinyQAQ** [comment]
I meet the same problem

**Comment by jh-Gong** [comment]
same

**Comment by DadddyWang** [comment]
same

**Comment by shihao1895** [comment]
same+1

**Comment by Dogtiti** [comment]
@skymkmk  可以帮忙看一看呀

**Comment by skymkmk** [comment]
> @skymkmk 可以帮忙看一看呀

只改了 constant 和 OpenAI 的 chat API，根本没动前端的代码，不应当有任何理由前端不显示的吧？

**Comment by skymkmk** [comment]
都确定没在环境变量中删除模型，比如 `-all` 之类的？

**Comment by JusenD** [comment]
设置 - 立即重置所有设置 可以解决

**Comment by Dogtiti** [comment]
> > @skymkmk 可以帮忙看一看呀
> 
> 只改了 constant 和 OpenAI 的 chat API，根本没动前端的代码，不应当有任何理由前端不显示的吧？

或许对于新增模型时的合并逻辑有点问题？

**Comment by skymkmk** [comment]
> 或许对于新增模型时的合并逻辑有点问题？

那这应该算历史遗留问题了，如果不在 env 指定自定义模型的话，按理来说每一次加模型都应该出现这个问题，我很好奇以前竟然没有人提过这个问题？

我找到问题在哪里了，今天太晚了，今早我提个 pr 吧

**Comment by DadddyWang** [comment]
> 设置 - 立即重置所有设置 可以解决
有效

**Comment by skymkmk** [comment]
#3924 与以前的 pr 相比改法没有任何区别。预计在水合阶段修复这个问题。

**Comment by Pear-sudo** [comment]
I have the same problem and I haven't set any environment variables.

**Comment by cnmozzie** [comment]
https://app.nextchat.dev/ 官方的示例网站显示版本是v2.15.2，照理来说已经加入了新模型，但是在列表中也没能找到

**Comment by mountainguan** [comment]
自定义模型可以使用

**Comment by Dogtiti** [comment]
#5444
