### ISSUE TITLE
[Feature Request] 建议优化对话时的时间显示

### ISSUE THREAD

**Issue by ThemanRonin** [ChatGPTNextWeb/ChatGPT-Next-Web#5436]
### 🥰 需求描述

![image](https://github.com/user-attachments/assets/95c70b89-62f4-4cda-82fc-1412aa5a7ec0)

如图所示
发出问题的时间和AI回答的时间是完全一致的,这样的话不利于直观的看到每轮对话的耗时。

我建议将AI的回答的时间改成 **"回复完成的时间"**

例如：

- 我在 2024-09-14 21:00:00 发送了一条消息
- AI在 2024-09-14 21:00:10 完成该轮对话
- 那么最后右下角的时间应该也是显示 2024-09-14 21:00:10
- 而不应该是和我一起发送的时间 2024-09-14 21:00:00

**这样的话也更直观看到AI的响应速度和时间**，因为本身聊天对话的逻辑就是，把全部内容都写完之后再发送才是发出的时间，而不是打出第一个字的时间

### 🧐 解决方案

建议将AI的回答的时间改成 **"回复完成的时间"**

**Comment by Leizhenpeng** [comment]
好主意哈哈哈
