### ISSUE TITLE
[Feature Request] 多回复尝试记录与回复续写

### ISSUE THREAD

**Issue by skymkmk** [ChatGPTNextWeb/ChatGPT-Next-Web#5439]
### 🥰 需求描述

在 ChatGPT 中，当用户点击重试时，会产生多个回答记录可供切换，而并非 ChatGPTNextWeb 中的覆盖原来的回答；同时，当 AI 因种种原因（上下文长度限制、补全 token 参数限制）未完全回复完成时，提供按钮用于继续回答而非以用户发送“继续”二字来继续补全。

### 🧐 解决方案

如果 owner 有意纳入此功能，我会提供 pr

### 📝 补充信息

对于 GPT 与 Claude，当发送的 message 最后角色为 assistant 时，模型会尝试继续回复。

另外补充，若有意纳入此 功能，我将只提供 GPT 的继续回答功能，因我没有 Claude API 用来测试结束原因

**Comment by Dogtiti** [comment]
为啥关闭了呀

**Comment by skymkmk** [comment]
> 为啥关闭了呀

因为翻了翻代码，耦合的比我想象中的还严重，等有时间了我再 pr 吧🤣
