### ISSUE TITLE
[Bug] 页面上未找到 o1 相关的模型

### ISSUE THREAD

**Issue by RandyInterfish** [ChatGPTNextWeb/ChatGPT-Next-Web#5465]
### 📦 Deployment Method

Docker

### 📌 Version

2.15.2

### 💻 Operating System

Ubuntu

### 📌 System Version

22.04

### 🌐 Browser

Edge

### 📌 Browser Version

128.0.2739.79

### 🐛 Bug Description

用docker 部署，`docker rmi` 了原来的 image，并 pull 了最新的 2.15.2。但是在web页面的模型选择中没有找到 o1-preview 之类的字样。
![image](https://github.com/user-attachments/assets/346f1103-6e27-4b08-8615-2aa2031f76df)
![image](https://github.com/user-attachments/assets/d4a3059e-d700-40bc-8bbd-23261ebac5fb)
![image](https://github.com/user-attachments/assets/6851fb3b-d165-4390-98ea-4d60278ae2e4)

**Comment by skymkmk** [comment]
#5444 @Dogtiti can close it

**Comment by skymkmk** [comment]
四种解决方案：

- 等待新发版 docker
- 自行编译最新 main 分支代码部署
- 点击设置中的重置设置按钮
- 在自定义模型（服务器环境变量或设置中）加上 o1 相关模型
