### ISSUE TITLE
[Bug] manjaro gnome +  fcitx5 + next-chat_2.15.2_amd64.AppImage, 在窗口内无法切换为中文输入法. 对比其他应用则无问题

### ISSUE THREAD

**Issue by today20210616** [ChatGPTNextWeb/ChatGPT-Next-Web#5481]
### 📦 部署方式

官方安装包

### 📌 软件版本

next-chat_2.15.2_amd64.AppImage

### 💻 系统环境

Other Linux

### 📌 系统版本

manjaro最新

### 🌐 浏览器

Chrome

### 📌 浏览器版本

Version 128.0.6613.119 (Official Build) Arch Linux (64-bit)

**Comment by lloydzhou** [comment]
i using nextchat@2.15.2 on archlinux arm, with fcitx@4.2.9.9 and  gnome-flashback@3.52.1 , it's ok.

**Comment by lloydzhou** [comment]
不过我是改了nextchat-bin 这个aur的配置文件，通过arm64.deb 的安装包安装的

**Comment by today20210616** [comment]
> 不过我是改了nextchat-bin 这个aur的配置文件，通过arm64.deb 的安装包安装的

Yes, it works. Thank you very much. You've been a great help
