### ISSUE TITLE
[Feature Request] web上新建的plugin,应该默认打开代理访问,

### ISSUE THREAD

**Issue by Leizhenpeng** [ChatGPTNextWeb/ChatGPT-Next-Web#5487]
### 🥰 Feature Description

UI 应该保证用户最小心智完成操作, 原理上网页插件不打开代理是访问不了资源的

### 🧐 Proposed Solution

默认代理为打开

**Comment by Leizhenpeng** [comment]
![CleanShot 2024-09-22 at 10 30 24@2x](https://github.com/user-attachments/assets/499c6599-2c0c-476e-8838-a774166a938e)

**Comment by lloydzhou** [comment]
考虑一个问题：
是不是不应该给这个选项？网页版本就直接走proxy，app环境就不走。
感觉给出了选项之后，反而带来不必要的复杂度...

**Comment by Leizhenpeng** [comment]
如果请求 chorm:// 或者 其他协议的的插件 ,本机的优势就来了

**Comment by lloydzhou** [comment]
#5508 
remove this config.

**Comment by kelvin8906** [comment]
> [#5508](https://github.com/ChatGPTNextWeb/NextChat/pull/5508) remove this config.

发现在NextChat AI的环境下的时候，这里没办法配置插件代理，官方转发也失效了，就导致插件无法使用了
