### ISSUE TITLE
[Bug] 当接口请求失败的时候, 不应该更新标题~

### ISSUE THREAD

**Issue by Leizhenpeng** [ChatGPTNextWeb/ChatGPT-Next-Web#5494]
### 📦 Deployment Method

Official installation package

### 📌 Version

*

### 💻 Operating System

Windows, Other

### 📌 System Version

*

### 🌐 Browser

Chrome

### 📌 Browser Version

*

### 🐛 Bug Description

![CleanShot 2024-09-23 at 10 07 44@2x](https://github.com/user-attachments/assets/7740a2cf-61ec-4499-8b65-c1a868625479)
再手动更新标题的时候, 当接口请求失败的时候, 不应该更新标题~

### 📷 Recurrence Steps

当接口请求失败的时候, 不应该更新标题~

**Comment by QAbot-zh** [comment]
+1

**Comment by Leizhenpeng** [comment]
![CleanShot 2024-09-23 at 11 09 16@2x](https://github.com/user-attachments/assets/909f7a7a-6e72-45e0-9579-f65bccbb3fbd)


正常对话失败,如何更新请求对话失败,也不应该跟新标题, 取个默认名字比较合理
