### ISSUE TITLE
[Feature Request] 添加类似公告的提示信息

### ISSUE THREAD

**Issue by MoonShadowIllusions** [ChatGPTNextWeb/ChatGPT-Next-Web#5496]
### 🥰 需求描述

可以使用markdown或html编写提示信息，做为对用户的提示。
举例：当有多个模型时，用户可以在docker或其他方式部署时设置提示信息，告诉用户不同模型的特点

### 🧐 解决方案

提供环境变量，指出公告对应的文件的路径，并在前端显示这个提示信息

**Comment by lloydzhou** [comment]
当前的开源版本，基本是个人部署自己使用，或者个人安装后自己使用，并不是一个类似SaaS的产品，所以，做这个不是很有必要。

如果需要使用在线SaaS版本可以看这里  https://nextchat.dev/chat
如果是团队使用，可以关注   https://enterprise.nextchat.dev/
