### ISSUE TITLE
[Bug] 请教下，VIA浏览器里面打开后，模型可选少了很多，只有GPT4和GPT3.5等十几个，4o等还有claud之类全没了

### ISSUE THREAD

**Issue by themis0009** [ChatGPTNextWeb/ChatGPT-Next-Web#5514]
### 📦 部署方式

Docker

### 📌 软件版本

2.15.2

### 💻 系统环境

Other Linux

### 📌 系统版本

24.22

### 🌐 浏览器

Other

### 📌 浏览器版本

5.8

### 🐛 问题描述

手机上使用VIA浏览器打开后，可用模型少了很多，只有GPT4和GPT3.5等十几个，4o等还有claud之类全没了。
电脑上打开或者用别的浏览器打开就正常。

**Comment by lloydzhou** [comment]
see this issue
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5465

**Comment by themis0009** [comment]
> see this issue #5465

感谢~重置后正常

**Comment by lloydzhou** [comment]
对应的pr已经合并到main分支，下一个版本会正式上线
