### ISSUE TITLE
[Feature Request] 预装插件提供删除功能

### ISSUE THREAD

**Issue by holzora** [ChatGPTNextWeb/ChatGPT-Next-Web#5524]
### 🥰 需求描述

public/plugins.json中预装的插件除非清除所有数据否则无法删除，希望添加删除功能

### 🧐 解决方案

同上

### 📝 补充信息

![Screenshot_2024-09-25-11-31-10-305_mark via](https://github.com/user-attachments/assets/86d4df7d-6d52-41e9-a99d-453c17201dd5)

**Comment by lloydzhou** [comment]
可以参考masks，提供不线上内置插件按钮
不提供删除按钮

否则不好判断是否已经安装上内置插件。

**Comment by holzora** [comment]
> 可以参考masks，提供不线上内置插件按钮 不提供删除按钮
> 
> 否则不好判断是否已经安装上内置插件。

但是给别人用的话，如果更改了预装插件，客户端不会有任何变化
