### ISSUE TITLE
[Bug] 发现了一个官方与非官方调用url的问题

### ISSUE THREAD

**Issue by alltobebetter** [ChatGPTNextWeb/ChatGPT-Next-Web#5533]
### 📦 部署方式

Vercel

### 📌 软件版本

2.15.3

### 💻 系统环境

Other Linux

### 📌 系统版本

vercel

### 🌐 浏览器

Chrome, Edge

### 📌 浏览器版本

all

### 🐛 问题描述

假设我们在vercel上部署，并且使用某些以openai的url格式的镜像（或者说是代理）站点来使用的话，claude-3-5-sonnet-20240620 是无法正常使用的，因为claude-3-5-sonnet-20240620使用的是anthropic的url来调用，纯小白，不知道怎么改调用的url
另外，用环境变量只改动claude的baseurl也没用，因为调用方式是openai

### 📷 复现步骤

部署环境变量的时候用非官方的站点。

### 🚦 期望结果

了解修改哪些文件可以修改调用url

**Comment by lloydzhou** [comment]
see #5001
