### ISSUE TITLE
[Feature Request] Run failed: Upstream Sync - main (f12bc06)

### ISSUE THREAD

**Issue by luluyayawawa123** [ChatGPTNextWeb/ChatGPT-Next-Web#5535]
### 🥰 Feature Description

fork的项目，在actions里，自动和手动同步更新失败

### 🧐 Proposed Solution

fork的项目，在actions里，自动和手动同步更新失败。手动更新依然失败。

**Comment by Dogtiti** [comment]
![image](https://github.com/user-attachments/assets/5f9cadbf-ca45-4569-8805-e4bde18c792c)
我这边昨天手动更新一次之后后面就正常sync，具体报错贴出来看看

**Comment by luluyayawawa123** [comment]
> ![image](https://private-user-images.githubusercontent.com/38354472/370978385-5f9cadbf-ca45-4569-8805-e4bde18c792c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDA5NjUsIm5iZiI6MTcyNzM0MDY2NSwicGF0aCI6Ii8zODM1NDQ3Mi8zNzA5NzgzODUtNWY5Y2FkYmYtY2E0NS00NTY5LTg4MDUtZTRiZGUxOGM3OTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA4NTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMDcyYjg4MDZkMWE4YTg5ZWM3YjNiZThiOTU3NjFkOWNiMDRmMzA0MzBhYzRkMTAzMjIyY2IzY2YxYmIyYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.opJeB-9od8U0qNCP8IleIUAxAOF1vUW5xfUvpyvrq4g) 我这边昨天手动更新一次之后后面就正常sync，具体报错贴出来看看

没错，我当然试过手动更新，就是Upstream Sync 页面里 手动点run workflow，一样的报错。 错误提示告诉我手动更新，不好用。
![QQ截图20240926165348](https://github.com/user-attachments/assets/77640ef6-4fc2-4533-bab1-fdde606dc4a9)
![QQ截图20240926165447](https://github.com/user-attachments/assets/5d327aeb-7532-4ef1-a69a-86df0992a487)

**Comment by lloydzhou** [comment]
@luluyayawawa123 手动更新是点这里，不是手动运行action

![image](https://github.com/user-attachments/assets/52c0b7c6-f505-4f50-875b-a45f291b676e)

**Comment by luluyayawawa123** [comment]
> @luluyayawawa123 手动更新是点这里，不是手动运行action
> 
> ![image](https://private-user-images.githubusercontent.com/1826685/371111017-52c0b7c6-f505-4f50-875b-a45f291b676e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczOTA1OTYsIm5iZiI6MTcyNzM5MDI5NiwicGF0aCI6Ii8xODI2Njg1LzM3MTExMTAxNy01MmMwYjdjNi1mNTA1LTRmNTAtODc1Yi1hNDVmMjkxYjY3NmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMjIzODE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWY3NTk4NjBjNjJjNDhlNTYwYjVlMjk0ODliNzJmNWMzYjUxNGJmYjYzMmEzMTJjYmFkNWZhY2VmZGI1N2NiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PKY3pO0ppLDg8J2-UkZbmTp39SR1MId24wmICsYz-cM)

感谢！ 原来如此，这样操作就好了嘿嘿！
