### ISSUE TITLE
[Bug] 通义千问调用地址不正确

### ISSUE THREAD

**Issue by MrArlong** [ChatGPTNextWeb/ChatGPT-Next-Web#5538]
### 📦 部署方式

Docker

### 📌 软件版本

2.15.3

### 💻 系统环境

macOS

### 📌 系统版本

13

### 🌐 浏览器

Chrome

### 📌 浏览器版本

129.0.6668.59（正式版本） (arm64)

### 🐛 问题描述

A域名是oneapi，B域名是ChatGPTNextWeb，使用其他大模型请求地址是正常的A域名，换成通义千问请求地址变成了B域名，导致请求报错，提示apikey不正确

以下图片为同一个聊天框切换模型
![image](https://github.com/user-attachments/assets/2c9136bf-1f25-4b08-aa2e-f7bbd3965e7a)
以下图片为正常请求地址
![image](https://github.com/user-attachments/assets/fbf6f2a7-5e76-4eb1-bef3-09d22838f856)
以下图片为请求通义千问请求地址
![image](https://github.com/user-attachments/assets/7fa7706d-fe32-492f-8584-8b9c9cc9174f)

### 📷 复现步骤

oneapi添加渠道，配置qwen-max，qwen-plus模型，使用这两个模型报apikey不正确

### 🚦 期望结果

能正常使用通义千问

**Comment by lloydzhou** [comment]
see #5001

**Comment by MrArlong** [comment]
> 参见#5001

感谢，直接把通义千问的三个模型后面加上openai就可以了
