### ISSUE TITLE
[Feature Request] OPENAI_API_KEY （必填项）这个配置有点不理解

### ISSUE THREAD

**Issue by pensacola1989** [ChatGPTNextWeb/ChatGPT-Next-Web#5539]
### 🥰 需求描述

OPENAI_API_KEY （必填项）
然后又看到了。custom_model，我现在的需求是，使用自己包装过的各种模型的代理

### 🧐 解决方案

能支持，自定义URL么？而不是某个模型的配置。。。

### 📝 补充信息

无

**Comment by QAbot-zh** [comment]
支持自定义 url 的，如果不配置 BASE_URL ，就默认请求 openai，如果配置了，就请求你指定的 url

**Comment by pensacola1989** [comment]
> 支持自定义 url 的，如果不配置 BASE_URL ，就默认请求 openai，如果配置了，就请求你指定的 url

我们包装了openapi等其他模型的接口一起的。。。不是个镜像代理，鉴权啥的都是自己的。。

**Comment by QAbot-zh** [comment]
> > 支持自定义 url 的，如果不配置 BASE_URL ，就默认请求 openai，如果配置了，就请求你指定的 url
> 
> 我们包装了openapi等其他模型的接口一起的。。。不是个镜像代理，鉴权啥的都是自己的。。

反正参数跟 openai 一致就行，不需要是官方 key
