### ISSUE TITLE
[Bug] gemini-1.5-pro-latest模型使用不了

### ISSUE THREAD

**Issue by xxbsxy** [ChatGPTNextWeb/ChatGPT-Next-Web#5540]
### 📦 部署方式

Docker

### 📌 软件版本

v2.15.3

### 💻 系统环境

Other Linux

### 📌 系统版本

Debian 12

### 🌐 浏览器

Chrome

### 📌 浏览器版本

129.0.6668.59

### 🐛 问题描述

[gemini-1.5-pro-latest调用不了 配置的是vercel的代理地址 但是使用LobeChat可以调用 看了控制台好像是key传递的方式不一样
![Snipaste_2024-09-26_15-59-04](https://github.com/user-attachments/assets/53c6e762-81b2-4050-9e33-d561dec6b5e7)
![Snipaste_2024-09-26_15-59-49](https://github.com/user-attachments/assets/e37cb407-34ff-4efc-b8f3-c75c8bfc1eb4)

**Comment by toniexly** [comment]
mistral的也调用不了，好象是因为不支持penalty参数。。

**Comment by mountainguan** [comment]
the same

**Comment by dupl** [comment]
> ### 📦 部署方式
> Docker
> 
> ### 📌 软件版本
> v2.15.3
> 
> ### 💻 系统环境
> Other Linux
> 
> ### 📌 系统版本
> Debian 12
> 
> ### 🌐 浏览器
> Chrome
> 
> ### 📌 浏览器版本
> 129.0.6668.59
> 
> ### 🐛 问题描述
> [gemini-1.5-pro-latest调用不了 配置的是vercel的代理地址 但是使用LobeChat可以调用 看了控制台好像是key传递的方式不一样 ![Snipaste_2024-09-26_15-59-04](https://private-user-images.githubusercontent.com/88436533/371041262-53c6e762-81b2-4050-9e33-d561dec6b5e7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODY5MDUsIm5iZiI6MTcyNzU4NjYwNSwicGF0aCI6Ii84ODQzNjUzMy8zNzEwNDEyNjItNTNjNmU3NjItODFiMi00MDUwLTllMzMtZDU2MWRlYzZiNWU3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA1MTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MjJkNmIxNTQ1ZjI3NjZiYjg4YWU0MTcxMWIyNDQyMDg1ZDllZjhkYmE4YmFjOTg0NGI5ZjMzNjcwMzZmNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SwiLeqoWr_D_0LksJb5OA8AaiH4iTo0v4abALw4Zqgk) ![Snipaste_2024-09-26_15-59-49](https://private-user-images.githubusercontent.com/88436533/371041272-e37cb407-34ff-4efc-b8f3-c75c8bfc1eb4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODY5MDUsIm5iZiI6MTcyNzU4NjYwNSwicGF0aCI6Ii84ODQzNjUzMy8zNzEwNDEyNzItZTM3Y2I0MDctMzRmZi00ZWZjLWI4ZjMtYzc1YzhiZmMxZWI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA1MTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OTBkYjc4OTkyMjEwZTA3M2M3ZTRmYTc1ODdhNWI3Y2JiNDdmNGM5NGYxZjZkOGNkMmY1MmZlMzMxZjE4ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Rwbo9XXjFJ9yY0es8JeAb2fGyBhiWjX_FZ5o_YnW99k)
> 
> ### 📷 复现步骤
> _No response_
> 
> ### 🚦 期望结果
> _No response_
> 
> ### 📝 补充信息
> _No response_

Gemini无法用的bug咋还不修复，急的我又部署了lobe🐱

**Comment by lloydzhou** [comment]
#5541 这个pr应该已经处理了google的api发送api key的方式。已经合并到main分支，只是没有发新版。
如果使用vercel部署，可以直接更新。
docker版本，需要等发新版的时候才会有新的docker镜像

**Comment by mountainguan** [comment]
> #5541 这个pr应该已经处理了google的api发送api key的方式。已经合并到main分支，只是没有发新版。 如果使用vercel部署，可以直接更新。 docker版本，需要等发新版的时候才会有新的docker镜像

目前测试并不行

**Comment by mountainguan** [comment]
> > ### 📦 部署方式
> > Docker
> > ### 📌 软件版本
> > v2.15.3
> > ### 💻 系统环境
> > Other Linux
> > ### 📌 系统版本
> > Debian 12
> > ### 🌐 浏览器
> > Chrome
> > ### 📌 浏览器版本
> > 129.0.6668.59
> > ### 🐛 问题描述
> > [gemini-1.5-pro-latest调用不了 配置的是vercel的代理地址 但是使用LobeChat可以调用 看了控制台好像是key传递的方式不一样 ![Snipaste_2024-09-26_15-59-04](https://private-user-images.githubusercontent.com/88436533/371041262-53c6e762-81b2-4050-9e33-d561dec6b5e7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODY5MDUsIm5iZiI6MTcyNzU4NjYwNSwicGF0aCI6Ii84ODQzNjUzMy8zNzEwNDEyNjItNTNjNmU3NjItODFiMi00MDUwLTllMzMtZDU2MWRlYzZiNWU3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA1MTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MjJkNmIxNTQ1ZjI3NjZiYjg4YWU0MTcxMWIyNDQyMDg1ZDllZjhkYmE4YmFjOTg0NGI5ZjMzNjcwMzZmNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SwiLeqoWr_D_0LksJb5OA8AaiH4iTo0v4abALw4Zqgk) ![Snipaste_2024-09-26_15-59-49](https://private-user-images.githubusercontent.com/88436533/371041272-e37cb407-34ff-4efc-b8f3-c75c8bfc1eb4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODY5MDUsIm5iZiI6MTcyNzU4NjYwNSwicGF0aCI6Ii84ODQzNjUzMy8zNzEwNDEyNzItZTM3Y2I0MDctMzRmZi00ZWZjLWI4ZjMtYzc1YzhiZmMxZWI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA1MTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OTBkYjc4OTkyMjEwZTA3M2M3ZTRmYTc1ODdhNWI3Y2JiNDdmNGM5NGYxZjZkOGNkMmY1MmZlMzMxZjE4ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Rwbo9XXjFJ9yY0es8JeAb2fGyBhiWjX_FZ5o_YnW99k)
> > ### 📷 复现步骤
> > _No response_
> > ### 🚦 期望结果
> > _No response_
> > ### 📝 补充信息
> > _No response_
> 
> Gemini无法用的bug咋还不修复�，急的我又部署了lobe🐱

我怀疑他们没有对gemini的api进行测试....出过几次异常主维护者都自己测不出来

**Comment by dupl** [comment]
> #5541 这个pr应该已经处理了google的api发送api key的方式。已经合并到main分支，只是没有发新版。
> 如果使用vercel部署，可以直接更新。
> docker版本，需要等发新版的时候才会有新的docker镜像

用的最新commit版，vercel部署，依然无法使用Gemini😭

**Comment by lloydzhou** [comment]
> 我怀疑他们没有对gemini的api进行测试....出过几次异常主维护者都自己测不出来

1. 刚刚在app.nextchat.dev这个线上环境测试了，`gemini-1.5-pro-latest`正常工作
2. 刚刚使用`yidadaa/chatgpt-next-web:v2.15.3`本地启动一个新的容器测试了，`gemini-1.5-pro-latest`正常工作

3. 刚才使用最新的main分支测试了一下，确实有问题，在#5562 进行修复：
   a. 修复传递头的名称 `x-google-api-key` --> `x-goog-api-key`
   b. 修复传递`alt=sse`参数导致可能出现404错误

**Comment by dupl** [comment]
喜大普奔，终于修复了🙂
