### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Aiden-Coding** [ChatGPTNextWeb/ChatGPT-Next-Web#5556]
### 📦 Deployment Method

Vercel

### 📌 Version

latest

### 💻 Operating System

Windows

### 📌 System Version

10

### 🌐 Browser

Edge

### 📌 Browser Version

latest

### 🐛 Bug Description

api/google/v1beta/models/gemini-1.5-flash-001:streamGenerateContent?alt=sse
请求方法:
POST
状态代码:
404 Not Found

**Comment by lloydzhou** [comment]
![image](https://github.com/user-attachments/assets/bcc31b80-debd-4f34-b78e-78806c2afe96)
我映像中没有这个模型吧

**Comment by mountainguan** [comment]
> ![image](https://private-user-images.githubusercontent.com/1826685/371817981-bcc31b80-debd-4f34-b78e-78806c2afe96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1Nzk2MTksIm5iZiI6MTcyNzU3OTMxOSwicGF0aCI6Ii8xODI2Njg1LzM3MTgxNzk4MS1iY2MzMWI4MC1kZWJkLTRmMzQtYjc4ZS03ODgwNmMyYWZlOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMDMwODM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzFiYjZiYWU0ZTk1YjY4NTMzZTIzOTE2ODRhYzcwNDZmMmM1ZGI1YjYxNzA5YjExYWFhMGZiY2FlMDFkMzMxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1SNQnDcNx6E14XQlaynwBzPxIFpbg1ose8QXLqvS7ME) 我映像中没有这个模型吧

出了个002的

**Comment by Aiden-Coding** [comment]
接口404![image](https://github.com/user-attachments/assets/8cda1422-346d-495d-b1f6-f714852b2fda)

**Comment by Aiden-Coding** [comment]
> ![image](https://github.com/user-attachments/assets/bcc31b80-debd-4f34-b78e-78806c2afe96)
> 
> 我映像中没有这个模型吧

不是模型的问题，是接口404

**Comment by lloydzhou** [comment]
google官方的接口，将模型名称放到了url里面，所以，接口404应该就代表没有这个模型？

**Comment by Aiden-Coding** [comment]
> google官方的接口，将模型名称放到了url里面，所以，接口404应该就代表没有这个模型？

gemini-1.5-flash-latest模型是有的，但是还是报了404，不知道是哪个大佬提交的代码导致的404

**Comment by lloydzhou** [comment]
刚刚在最新的v2.15.3的线上版本（https://app.nextchat.dev/#/chat）测试了，`gemini-1.5-flash-latest`的模型是正常的，所以，还是不清楚问题在哪里？

![image](https://github.com/user-attachments/assets/4a10ef86-87b4-469f-bc4e-c9a0a70b14fc)

**Comment by dupl** [comment]
> > google官方的接口，将模型名称放到了url里面，所以，接口404应该就代表没有这个模型？
> 
> gemini-1.5-flash-latest模型是有的，但是还是报了404，不知道是哪个大佬提交的代码导致的404

gemini-1.5-pro-latest也用不了，不知道哪位大佬搞的🥹

**Comment by mountainguan** [comment]
> 刚刚在最新的v2.15.3的线上版本（`https://app.nextchat.dev/#/chat`）测试了，`gemini-1.5-flash-latest`的模型是正常的，所以，还是不清楚问题在哪里？
> 
> ![image](https://private-user-images.githubusercontent.com/1826685/371827008-4a10ef86-87b4-469f-bc4e-c9a0a70b14fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1OTY3NjIsIm5iZiI6MTcyNzU5NjQ2MiwicGF0aCI6Ii8xODI2Njg1LzM3MTgyNzAwOC00YTEwZWY4Ni04N2I0LTQ2OWYtYmM0ZS1jOWEwYTcwYjE0ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMDc1NDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzkyN2Q2ZTA2ZjliMTMyYzljODdkZDhjZjBjZTBiNmMzZDUxNDM4OGI1MDQ1M2U0Y2IyNDg0NmY2MWYxOGJhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.m9rAMXj1H9aongTwNByvv9i9MCsXT8Z3DQ-UuXqn9QQ)

你是不是指定了版本来部署，我们是拉最新代码到vercel的，比2.15.3多了几天的代码，前天上班下午的时候还更新过，那时候都还行。今天回来上班就发现异常了

**Comment by Aiden-Coding** [comment]
> 刚刚在最新的v2.15.3的线上版本（`https://app.nextchat.dev/#/chat`）测试了，`gemini-1.5-flash-latest`的模型是正常的，所以，还是不清楚问题在哪里？
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/4a10ef86-87b4-469f-bc4e-c9a0a70b14fc)
> 
> 

我是用的是最新的代码，前几天还可以的，拉取最新代码就报404

**Comment by lloydzhou** [comment]
> > google官方的接口，将模型名称放到了url里面，所以，接口404应该就代表没有这个模型？
> 
> gemini-1.5-flash-latest模型是有的，但是还是报了404，不知道是哪个大佬提交的代码导致的404

#5541 这个pr确实引入了bug导致404错误。
> 之前调用google api的时候，将key放到url里面传递（google的接口一直是这么调用的）最近支持使用`x-goog-api-key`传递

#5562 这个pr修复了这个404的问题

这两个pr都是合并到main分支，并未发新版，所以线上的app.nextchat.dev，docker的包以及App端并不受影响。

**Comment by mountainguan** [comment]
> > > google官方的接口，将模型名称放到了url里面，所以，接口404应该就代表没有这个模型？
> > 
> > 
> > gemini-1.5-flash-latest模型是有的，但是还是报了404，不知道是哪个大佬提交的代码导致的404
> 
> #5541 这个pr确实引入了bug导致404错误。
> 
> > 之前调用google api的时候，将key放到url里面传递（google的接口一直是这么调用的）最近支持使用`x-goog-api-key`传递
> 
> #5562 这个pr修复了这个404的问题
> 
> 这两个pr都是合并到main分支，并未发新版，所以线上的app.nextchat.dev，docker的包以及App端并不受影响。

确实解决了，辛苦了，已经拉取最细弄的代码到vercel顺利运行了

**Comment by Aiden-Coding** [comment]
> > > google官方的接口，将模型名称放到了url里面，所以，接口404应该就代表没有这个模型？
> 
> > 
> 
> > gemini-1.5-flash-latest模型是有的，但是还是报了404，不知道是哪个大佬提交的代码导致的404
> 
> 
> 
> #5541 这个pr确实引入了bug导致404错误。
> 
> > 之前调用google api的时候，将key放到url里面传递（google的接口一直是这么调用的）最近支持使用`x-goog-api-key`传递
> 
> 
> 
> #5562 这个pr修复了这个404的问题
> 
> 
> 
> 这两个pr都是合并到main分支，并未发新版，所以线上的app.nextchat.dev，docker的包以及App端并不受影响。
> 
> 

幸苦了，感谢
