### ISSUE TITLE
[Bug] html 处理导致代码块切分异常

### ISSUE THREAD

**Issue by QAbot-zh** [ChatGPTNextWeb/ChatGPT-Next-Web#5557]
### 📦 部署方式

Vercel

### 📌 软件版本

v2.15.3

### 💻 系统环境

Windows

### 📌 系统版本

windows 10

### 🌐 浏览器

Chrome

### 📌 浏览器版本

127.0.6533.100

### 🐛 问题描述

当代码块为 html 的时候，会忽略结尾的 ``` 控制符，导致它被解析为下一个代码块进行渲染，和 artifacts 无关，关闭 artifacts 渲染也无法正确解析渲染：

![image](https://github.com/user-attachments/assets/8a087d0b-b954-483c-98a7-28b31f94611d)

![Clip_2024-09-27_23-10-15](https://github.com/user-attachments/assets/a23b4454-fd19-413d-a5df-4c4d713d4670)

非 html 代码块，正常渲染：

![image](https://github.com/user-attachments/assets/13d6c3be-ae83-4246-96b4-47d53910ea80)

![image](https://github.com/user-attachments/assets/094e0153-467b-4228-9971-5f9e79fd7c7a)

### 📷 复现步骤

使用 ``` 控制符生成 html 代码块

### 🚦 期望结果

正常渲染，不要把正文渲染成代码块，提升可读性

**Comment by chengxgm** [comment]
![image](https://github.com/user-attachments/assets/36a25ce6-5232-431c-b933-41184c7674a2)
设置界面不勾选此选项即可
