### ISSUE TITLE
[Bug] 使用4turbo进行图片识别时，会发生回答中断，100%复现率

### ISSUE THREAD

**Issue by gaojunyang666** [ChatGPTNextWeb/ChatGPT-Next-Web#5558]
### 📦 Deployment Method

Docker

### 📌 Version

v1.20.2

### 💻 Operating System

Windows

### 📌 System Version

11

### 🌐 Browser

Edge

### 📌 Browser Version

latest

### 🐛 Bug Description

[Bug] 使用4turbo进行图片识别时，会发生回答中断，100%复现率
![image](https://github.com/user-attachments/assets/43f166b8-0cc3-4891-9347-8e71045250ad)

### 📷 Recurrence Steps

使用lobe向4-turbo模型发送图片就可以复现

### 🚦 Expected Behavior

![image](https://github.com/user-attachments/assets/57d3e853-6e38-4a2c-a7c7-0d329423ed68)
正常应该回答不中断

### 📝 Additional Information

谢谢

**Comment by QAbot-zh** [comment]
你汇报错项目了，你应该去 lobe 提 issue，另外建议你可以修改一下 max_tokens 设置再试试
