### ISSUE TITLE
[Feature Request] 后续有出apk的计划吗

### ISSUE THREAD

**Issue by BuringFlames** [ChatGPTNextWeb/ChatGPT-Next-Web#5561]
### 🥰 需求描述

网页版的部署用起来不是很方便，想问下后续有没有包一个apk出来的计划

### 🧐 解决方案

apk应用，安装后，初始化配置即用

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
I put the necessary dlls in the archive

**Comment by Leizhenpeng** [comment]
mac 版本在 release 直接可以用 

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.15.3
