### ISSUE TITLE
[Bug] 使用 Azure 模型时应该是 @Azure 而文档中是 @azure

### ISSUE THREAD

**Issue by jia-niang** [ChatGPTNextWeb/ChatGPT-Next-Web#5574]
### 📦 部署方式

Docker

### 📌 软件版本

v2.15.3

### 💻 系统环境

Ubuntu

### 📌 系统版本

22.04.4 LTS

### 🌐 浏览器

Chrome

### 📌 浏览器版本

129.0.6668.71 (ARM)

### 🐛 问题描述

使用 Azure 模型时，在 `CUSTOM_MODELS` 中必须写成 `@Azure`，而文档中给出的是 `@azure` 大小写不对，按照文档的写配置不成功。

文档截图：
![image](https://github.com/user-attachments/assets/c19d384a-bef9-4965-a41b-68cf94119698)

**Comment by itcodes** [comment]
@jia-niang 感谢，30 天没升级，升级后果然出问题了。也就是说现在要这么设置吗？-all,+gpt-4o@Azure=gpt-4o,+gpt-4o-mini@Azure=gpt-4o-mini

**Comment by jia-niang** [comment]
> @jia-niang 感谢，30 天没升级，升级后果然出问题了。也就是说现在要这么设置吗？-all,+gpt-4o@Azure=gpt-4o,+gpt-4o-mini@Azure=gpt-4o-mini

对的，是这样。
也可以简化一点，写成：`-all,+gpt-4o@Azure,+gpt-4o-mini@Azure`。
版本先用 2.15.2，暂时别用 2.15.3，因为新版本对 Azure 用户而言 bug 很多
另外 `DEFAULT_MODEL` 要配置成 `gpt-4o(Azure)` 这种格式才行，别的都不行
