### ISSUE TITLE
[Bug] 返回的代码中，会在$前面强制加了一个\

### ISSUE THREAD

**Issue by deving-git** [ChatGPTNextWeb/ChatGPT-Next-Web#5583]
### 📦 Deployment Method

Vercel

### 📌 Version

v2.15.3

### 💻 Operating System

macOS

### 📌 System Version

15

### 🌐 Browser

Chrome

### 📌 Browser Version

na

### 🐛 Bug Description

比如
```
ACTION=\$1
VERSION=\$2
OUTPUT_FORMAT=\$3

print_message() {
    local status=\$1
    local pid=\$2
    local job_status=\$3
}
```

**Comment by lloydzhou** [comment]
#4393
