### ISSUE TITLE
[Bug] MacAPP设置自定义域名不生效

### ISSUE THREAD

**Issue by wangdawai** [ChatGPTNextWeb/ChatGPT-Next-Web#5596]
### 📦 Deployment Method

Official installation package

### 📌 Version

2.15.3

### 💻 Operating System

macOS

### 📌 System Version

15.0

### 🌐 Browser

Other

### 📌 Browser Version

None

### 🐛 Bug Description

使用Mac客户端，设置完自定义域名后，抓包发现没有把请求发送到自定义域名，依然发送到：api.nextchat.dev

**Comment by lloydzhou** [comment]
please test in v2.15.4
