### ISSUE TITLE
[Bug] 生成标题永远使用的model是gpt-4o-mini

### ISSUE THREAD

**Issue by rufeng-h** [ChatGPTNextWeb/ChatGPT-Next-Web#5603]
### 📦 部署方式

Docker

### 📌 软件版本

2.15.3

### 💻 系统环境

macOS

### 📌 系统版本

15.0

### 🌐 浏览器

Chrome

### 📌 浏览器版本

129.0.6668.60

### 🐛 问题描述

使用本地的ollama服务，CUSTOM_MODELS=-all,qwen2.5:7b-instruct,DEFAULT_MODEL=qwen2.5:7b-instruct，总结对话生成标题时model仍为gpt-4o-mini，生成的标题为后台错误提示json串。

### 📷 复现步骤

如上

### 🚦 期望结果

使用当前选择模型生成标题

### 📝 补充信息

无

**Comment by QAbot-zh** [comment]
改下这里的设置

![image](https://github.com/user-attachments/assets/e756726e-39bc-4f60-8a80-8bee879e97e0)
