### ISSUE TITLE
[Bug] Invalid type for 'messages[x].content

### ISSUE THREAD

**Issue by iswangyk** [ChatGPTNextWeb/ChatGPT-Next-Web#5614]
### 📦 Deployment Method

Docker

### 📌 Version

v2.15.4

### 💻 Operating System

Ubuntu

### 📌 System Version

18.04

### 🌐 Browser

Edge

### 📌 Browser Version

Version 129.0.2792.79 (Official build) (arm64)

### 🐛 Bug Description

<img width="869" alt="image" src="https://github.com/user-attachments/assets/7a8f4aa4-81be-4081-ad03-e5d3ca018dcb">

**Comment by lloydzhou** [comment]
复现了一下：
使用webPageReader读取网页的时候，返回的结构是一个json，导致openai的接口报错
![image](https://github.com/user-attachments/assets/fca651d7-49a2-41ab-b4f8-7fca4d58a352)
![image](https://github.com/user-attachments/assets/3b02dd19-1bb0-43e7-af41-ba5e1710c07e)

**Comment by lloydzhou** [comment]
现在在app.nextchat.dev修复了这个问题。docker镜像暂未修复，下一个版本会合并进去

**Comment by iswangyk** [comment]
请问docker合进去了吗 @lloydzhou

**Comment by lloydzhou** [comment]
docker的新版本已经发布，现在支持google gemini调用function call
