### ISSUE TITLE
[Bug] arxiv search@v1.0.0 无法使用

### ISSUE THREAD

**Issue by jhbgh** [ChatGPTNextWeb/ChatGPT-Next-Web#5619]
### 📦 部署方式

官方安装包

### 📌 软件版本

v2.15.4

### 💻 系统环境

Windows

### 📌 系统版本

Windows11

### 🌐 浏览器

Edge

### 📌 浏览器版本

129.0.2792.79

### 🐛 问题描述

升级到 v2.15.4 论文搜索插件 arxiv 无法使用

### 📷 复现步骤

![arxiv search error](https://github.com/user-attachments/assets/6ac13701-95e7-4205-a318-d528ff1c9cfb)

**Comment by lloydzhou** [comment]
1. 早上我自己使用新版的时候确实复现了问题，有问题的代码应该在
![image](https://github.com/user-attachments/assets/af19beef-ed99-417f-a97c-1f33a7667cb7)
2. 但是，中间去编辑了一下插件的schema内容，重新保存之后问题不再出现。所以，没找到确切的原因。

**Comment by jhbgh** [comment]
> 1. 早上我自己使用新版的时候确实复现了问题，有问题的代码应该在
>    ![image](https://private-user-images.githubusercontent.com/1826685/375205185-af19beef-ed99-417f-a97c-1f33a7667cb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzYwNTEsIm5iZiI6MTcyODUzNTc1MSwicGF0aCI6Ii8xODI2Njg1LzM3NTIwNTE4NS1hZjE5YmVlZi1lZDk5LTQxN2YtYTk3Yy0xZjMzYTc2NjdjYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMDQ0OTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE2Mzg2ZjhiM2M2NDMyMmNmYjEwZTUwYTZhZDdjMWUzNzhkM2Y1NzAwOTAzN2E2OTYyNTI5ZDk0NGM0ZDJkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7z5NCIlRm8twlOX6cuWY9gOn2afw9l_pZJSPe5JZUrQ)
> 2. 但是，中间去编辑了一下插件的schema内容，重新保存之后问题不再出现。所以，没找到确切的原因。

目前好像每次第一次查询会报错，然后再点刷新一下就能查询了，好神奇。

**Comment by jhbgh** [comment]
> ![image](https://private-user-images.githubusercontent.com/38354472/375314022-8c641da2-55df-4c8b-93e2-6c1ba19e82ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTM5MjgsIm5iZiI6MTcyODU1MzYyOCwicGF0aCI6Ii8zODM1NDQ3Mi8zNzUzMTQwMjItOGM2NDFkYTItNTVkZi00YzhiLTkzZTItNmMxYmExOWU4MmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA5NDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxN2RjMmQ3NWMxNGVhNmY3MDUxYjBkZmVmNjEzZWMwNmM2NDE4MDBhYjFjYTA4YjRjYmNiMDVkZTk3ZTEyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6KCypGtKRiOHfOuoDnGZ4RUcvB4u_TvDM-lr0CoBvuQ) 我尝试了一下没有复现，使用的是什么模型呢

Azure GPT4o和4o mini，但是现在好了，可能网络问题？
