### ISSUE TITLE
[Feature Request] 对话框上面的按钮功能, 能默认显示文字吗?

### ISSUE THREAD

**Issue by askgh** [ChatGPTNextWeb/ChatGPT-Next-Web#5623]
### 🥰 需求描述

![图片](https://github.com/user-attachments/assets/b1c49987-4aaa-4d00-bcba-8926cdbaddab)

把文字隐藏, 也不知道什么功能, 鼠标移过去, 还一晃一晃的, 难受

### 🧐 解决方案

默认显示文字, 带图标

**Comment by Dogtiti** [comment]
#5620
