### ISSUE TITLE
[Feature Request] 这个git repo 目录, 能支持本地部署吗

### ISSUE THREAD

**Issue by askgh** [ChatGPTNextWeb/ChatGPT-Next-Web#5624]
### 🥰 Feature Description

只看到一个dockerfile, 没看到怎么启动啊

### 🧐 Proposed Solution

本地启动方法是什么

**Comment by lloydzhou** [comment]
请仔细阅读README

**Comment by askgh** [comment]
> 请仔细阅读README

看到了, next 挺好
