### ISSUE TITLE
[Bug] docker部署提示[: line 0: syntax error: unexpected end of file (expecting "then")

### ISSUE THREAD

**Issue by SDCOM-0415** [ChatGPTNextWeb/ChatGPT-Next-Web#5641]
### 📦 部署方式

Docker

### 📌 软件版本

2024.10.11的docker latest版本

### 💻 系统环境

Other Linux

### 📌 系统版本

Debian12.6（fnOS 属于nas系统）

### 🌐 浏览器

Edge

### 📌 浏览器版本

129.0.2792.79

### 🐛 问题描述

docker部署后提示[: line 0: syntax error: unexpected end of file (expecting "then")
还没有运行起来就报错退出了
![image](https://github.com/user-attachments/assets/1f10715c-7f89-4002-842d-04593842f22c)
![image](https://github.com/user-attachments/assets/0eaa617a-6951-4299-af49-d618bfc7c9f7)
![image](https://github.com/user-attachments/assets/81386321-2cbf-4813-a746-a11bcc3d9d71)
运行方式参考https://bbs.naixi.net/thread-1174-1-1.html
![image](https://github.com/user-attachments/assets/ac66cabe-4bbf-47fc-b0ad-999c50a6fb37)
docker镜像为1p镜像

### 📷 复现步骤

直接运行

### 🚦 期望结果

能够成功运行

**Comment by luojiyin1987** [comment]
https://stackoverflow.com/questions/18155852/syntax-error-end-of-file-unexpected-expecting-then  
应该是  不同平台上换行符的问题。

**Comment by lloydzhou** [comment]
你可以覆盖一下 docker的cmd 启动，传自己平台支持的命令就好了  
![](https://gitmaya.com/api/667ce442a7fe4d0012d239e6/667ce4449d2ddb00149623e5/om_ab5cae97b9682c5cab7c33774a835c4d/image/img_v3_02fj_2833e150-6f50-4312-9864-8edcb21e43cg)

**Comment by SDCOM-0415** [comment]
> 你可以覆盖一下 docker的cmd 启动，传自己平台支持的命令就好了 ![](https://camo.githubusercontent.com/fb8c3f5caa53a19f5fe05f1bb1edd46dd598371266afa850937c370f413c59f0/68747470733a2f2f6769746d6179612e636f6d2f6170692f3636376365343432613766653464303031326432333965362f3636376365343434396432646462303031343936323365352f6f6d5f61623563616539376239363832633563616237633333373734613833356334642f696d6167652f696d675f76335f3032666a5f32383333653135302d366635302d343331322d393836342d386564636232316534336367)

不会修改啊，而且其他项目似乎运行正常

**Comment by SDCOM-0415** [comment]
> https://stackoverflow.com/questions/18155852/syntax-error-end-of-file-unexpected-expecting-then 应该是 不同平台上换行符的问题。
不太可能能吧，因为那是win配置文件到Linux吧

**Comment by luojiyin1987** [comment]
> > https://stackoverflow.com/questions/18155852/syntax-error-end-of-file-unexpected-expecting-then 应该是 不同平台上换行符的问题。
> 
> 不太可能吧，因为那是win配置文件到Linux吧

那你提供更多的信息。 你用的容器运行时， 对应的 docker compose 文件。  你可以尝试使用strace 进行动态跟踪。

**Comment by lloydzhou** [comment]
@SDCOM-0415 
我说的覆盖cmd指的是，通过控制启动docker的命令，覆盖内置的cmd

[Docker 文档](https://docs.docker.com/reference/cli/docker/container/run/)
![image](https://github.com/user-attachments/assets/0cc53bb1-5518-4144-b6f1-30e8ef94990a)
