### ISSUE TITLE
[Feature Request] Need an option to start client with NextChat AI

### ISSUE THREAD

**Issue by renkun-ken** [ChatGPTNextWeb/ChatGPT-Next-Web#5656]
### 🥰 Feature Description

I find NextChat AI great for users to try different models. It just works out of the box. But if a user only uses this mode (not using any self-maintained API providers and keys), it seems that every time the user starts the client, one has to go to settings and click the button to switch to NextChat AI mode.

<img width="1336" alt="image" src="https://github.com/user-attachments/assets/102d08eb-5a49-4e84-854b-0e8ad6b27fc0">

### 🧐 Proposed Solution

It would be nice if there is an option to make the client start with NextChat AI by default so that users won't have to click the button every time.

**Comment by Dogtiti** [comment]
you can just use https://nextchat.dev/chat

**Comment by lloydzhou** [comment]
这里应该是在app内部点击的时候，会从app内部直接打开SaaS版本。

这里需要调整一下：
要么，在App内部点击的时候，跳转SaaS网页版。
要么，这里点击走后面的SaaS版本的App下载？

**Comment by Dogtiti** [comment]
> 这里应该是在app内部点击的时候，会从app内部直接打开SaaS版本。
> 
> 这里需要调整一下： 要么，在App内部点击的时候，跳转SaaS网页版。 要么，这里点击走后面的SaaS版本的App下载？

可以

**Comment by renkun-ken** [comment]
> you can just use https://nextchat.dev/chat

Yes, that's what I'm using now. But I'd still prefer a local client though 😸

**Comment by lloydzhou** [comment]
预计本月内会发一个SaaS版的客户端

**Comment by renkun-ken** [comment]
Just notice <https://nextchat.dev/chat?utm_source=officesite#/download>.
