### ISSUE TITLE
[Feature Request] 更新docker

### ISSUE THREAD

**Issue by iswangyk** [ChatGPTNextWeb/ChatGPT-Next-Web#5669]
### 🥰 需求描述

docker版本似乎有一阵子没更新了，之前反馈的bug修复完了无法在体现在docker上

### 🧐 解决方案

希望定期更新docker

**Comment by lloydzhou** [comment]
new version `v2.15.5` published

**Comment by kitaev-chen** [comment]
> new version `v2.15.5` published

为什么我docker更新latest后，还是2.15.4?

**Comment by lloydzhou** [comment]
![image](https://github.com/user-attachments/assets/261d7fe5-d978-4f03-a62b-b2d7c4a3cc83)

2.15.5的tag，5天前就更新了，你检查一下本地的docker镜像

**Comment by kitaev-chen** [comment]
pull latest or 2.15.5 的镜像后，docker run 2.15.5 都显示为 2.15.4.
![image](https://github.com/user-attachments/assets/7b220c94-55e1-4a90-8291-5710a7c2af27)

**Comment by xiaonian233** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/1826685/378195651-261d7fe5-d978-4f03-a62b-b2d7c4a3cc83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTkxMjQsIm5iZiI6MTcyOTQ5ODgyNCwicGF0aCI6Ii8xODI2Njg1LzM3ODE5NTY1MS0yNjFkN2ZlNS1kOTc4LTRmMDMtYTYyYi1iMmQ3YzRhM2NjODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjFUMDgyMDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWVkMmNlYmIyY2M2YjA3YjBlMzcwOTkxMGUzY2UzNDljOGUxZTIxZWNiNDliODQ0MDJlZTg5M2UwM2ZjNDY2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5wMbVsITAzobS7zmDsSXfJ3fCTtfWqTKcV-fKYfbJOw)
> > 2.15.5的tag，5天前就更新了，你检查一下本地的docker镜像
> 
> 本地的docker和镜像全都清理干净了，重新拉取创建的容器，还是 2.15.4 版本啊...

我也一样，甚至换了台机子仍然是2.15.4

**Comment by lloydzhou** [comment]
看来我理解错了，我以为说的是docker的tag

实际上的问题是`yidadaa/chatgpt-next-web:2.15.5`的容器，运行之后设置页面显示的版本号还是旧的v2.15.4

**Comment by xiaonian233** [comment]
> 看来我理解错了，我以为说的是docker的tag
> 
> 实际上的问题是`yidadaa/chatgpt-next-web:2.15.5`的容器，运行之后设置页面显示的版本号还是旧的v2.15.4

对对，是这个意思
