### ISSUE TITLE
[Bug] the assets version of v2.15.5 are still v2.15.4

### ISSUE THREAD

**Issue by yuhui0531** [ChatGPTNextWeb/ChatGPT-Next-Web#5673]
### 📦 Deployment Method

Other

### 📌 Version

v2.15.5

### 💻 Operating System

macOS

### 📌 System Version

15.1 

### 🌐 Browser

Chrome

### 📌 Browser Version

版本 129.0.6668.100（正式版本） (arm64)

### 🐛 Bug Description

i have tried to download v2.15.5, but the assets are still v2.15.4
<img width="1003" alt="image" src="https://github.com/user-attachments/assets/88b2ab97-4615-4b78-8eac-a6fad562ed34">

**Comment by lloydzhou** [comment]
fixed.


thank you!
