### ISSUE TITLE
[Bug] o1-mini/o1-preview 返回 504

### ISSUE THREAD

**Issue by ihnfsax** [ChatGPTNextWeb/ChatGPT-Next-Web#5675]
### 📦 部署方式

Vercel

### 📌 软件版本

cda4494

### 💻 系统环境

Windows

### 📌 系统版本

10

### 🌐 浏览器

Edge

### 📌 浏览器版本

131.0.2875.0

### 🐛 问题描述

使用 Vercel 部署的服务，过去访问 o1-mini/o1-preview 没有问题。今天出现 504 错误，其他模型能够正常使用。
<img width="304" alt="2024-10-15_215735" src="https://github.com/user-attachments/assets/5bbc5d1d-fd50-4e7d-8cd6-1198e99edbcb">
我使用的是 OpenAI 中转服务，在中转服务上能看到接收到请求和 token 被消耗。
Vercel 日志：
<img width="320" alt="2024-10-15_220031" src="https://github.com/user-attachments/assets/1d8b2ade-454b-447d-8dfc-cca93e2fab42">
重新部署服务，以及调整 Function Max Duration 后重新部署都无法解决问题。

**Comment by ihnfsax** [comment]
也不是每一次请求中转服务都能记录到。记录到的从 vercel 发起请求，到中转服务收到模型输出，一般间隔 40~60s。但我把 Function Max Duration 设置为 60s 没有作用。

**Comment by wyuc** [comment]
hi，我也遇到这个问题了，咋解决的呀？

**Comment by lloydzhou** [comment]
o1模型尽量使用官方的接口。
客户端这边，o1和dalle默认的过期时间是 4 * REQUEST_TIMEOUT_MS也就是4分钟。
你的这个问题看起来是中转的服务器过期时间不够长，o1模型没有在过期时间之前返回结果

**Comment by lloydzhou** [comment]
可以看看这个issue https://github.com/vercel/vercel/discussions/4502

这里的错误可能不是中转服务报错，这个错误信息“An error occurred with you deployment” 可能是vercel给出来的报错。
