### ISSUE TITLE
[Bug]电脑版的配置阿里的通义千问，使用不成功

### ISSUE THREAD

**Issue by Keetop** [ChatGPTNextWeb/ChatGPT-Next-Web#5680]
### 📦 Deployment Method

Official installation package

### 📌 Version

v2.15.5

### 💻 Operating System

Windows

### 📌 System Version

window11

### 🌐 Browser

Chrome

### 📌 Browser Version

129.0.6668.101（正式版本）

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/8f763a6d-f00f-4f73-b806-9d6b160961aa)
我电脑版配置了阿里云的通义千问的key，然后接口地址写的是/api/alibaba。但是请求不成功，不知道哪里问题。但是同样的配置，我用docker在服务器上部署，配置同样的key和接口请求地址。是正常使用通义千问的，不知道为什么，电脑版的好几个版本了都这样，希望解决一下

**Comment by lloydzhou** [comment]
客户端接口地址不能写这个，客户端请参考提示直接写千问官方的api地址

**Comment by lloydzhou** [comment]
docker部署服务器的时候，填写/api/alibaba 实际上是走了一遍docker所在服务器的代理地址，客户端没有server，直接写官方的地址
