### ISSUE TITLE
[Bug] 永远failed to fetch。自己写的python客户端都是正常的。

### ISSUE THREAD

**Issue by Davidasx** [ChatGPTNextWeb/ChatGPT-Next-Web#5683]
### 📦 Deployment Method

Vercel

### 📌 Version

Latest

### 💻 Operating System

Other Linux

### 📌 System Version

Arch Linux Rolling（不重要）

### 🌐 Browser

Edge

### 📌 Browser Version

129

### 🐛 Bug Description

![截图 2024-10-18 00-41-42](https://github.com/user-attachments/assets/f3165d47-3a44-4afd-9d39-8db2d0e1f230)

从来没有成功过。写的程序代理转发API，本地和服务器都试过，都是这个错误。但是用我自己写的python客户端时都是好的。
请问时怎么回事？是我写的程序功能不全吗？那应该补充哪些功能什么的？

### 📷 Recurrence Steps

由于隐私原因，不提供

### 🚦 Expected Behavior

应该正常开始对话

**Comment by lloydzhou** [comment]
感觉bug没有描述清楚。
出于隐私，不需要提供详细的东西，但是至少给一些复现步骤之类的

**Comment by Davidasx** [comment]
I used codr from this repo ljnchn/cocopilot2gpt to create an API client. I t can run with my own python client, but it can't run with this web UI. The program has been ran both on a server and locally.

**Comment by Davidasx** [comment]
When I go back in noon I'll open source my python client and help you see the difference.

**Comment by QAbot-zh** [comment]
如果是自己开发的 api 转发，那要注意跨域问题，F12 打开看具体错误是什么，什么都不提供别人又没问题，只能理解为你没做好

**Comment by Davidasx** [comment]
是这样的，我的服务器不支持https，导致这样的错误。打算后端搞nginx反代成https试试。
![截图 2024-10-18 13-36-13](https://github.com/user-attachments/assets/bb9b75c9-0ba6-4e34-8ee0-91bc75504b4f)

**Comment by lloydzhou** [comment]
如果使用chrome访问网页，可以简单的加上启动参数`--allow-running-insecure-content`可以屏蔽这个报错

**Comment by Davidasx** [comment]
是的，但我还是最好搞一个ssl，安全而且省事。

**Comment by Davidasx** [comment]
各位开发者，非常抱歉，是我的问题。
我没有开启HTTPS，然后由于浏览器安全规则导致拒绝请求，不是你们的问题。
你们的工作做得非常好，应该感谢你们。
非常抱歉，打扰了。

**Comment by QiuZiXian** [comment]
> 如果使用chrome访问网页，可以简单的加上启动参数`--allow-running-insecure-content`可以屏蔽这个报错

请问一下，这个参数是加在哪里，docker启动报错
unknown flag: --allow-running-insecure-content
See 'docker run --help'.

**Comment by discarded-account-davidasx** [comment]
> > 如果使用chrome访问网页，可以简单的加上启动参数`--allow-running-insecure-content`可以屏蔽这个报错
> 
> 请问一下，这个参数是加在哪里，docker启动报错
> unknown flag: --allow-running-insecure-content
> See 'docker run --help'.

chromium浏览器。。
