### ISSUE TITLE
[Bug] 作为一个开源项目，强制加上Google的统计ID，还不给去掉，是什么意思呢？

### ISSUE THREAD

**Issue by deving-git** [ChatGPTNextWeb/ChatGPT-Next-Web#5684]
### 📦 部署方式

官方安装包

### 📌 软件版本

1

### 💻 系统环境

Windows

### 📌 系统版本

1

### 🌐 浏览器

Chrome

### 📌 浏览器版本

1

### 🐛 问题描述

export const DEFAULT_GA_ID = "G-89WN60ZK2E";
请问这是什么用意呢？

**Comment by lloydzhou** [comment]
1. 当前只是为了统计跳转SaaS版本的情况，并未收集其他用户信息（源码是开放的，你可以自己审查）
2. 这是开源项目，你在做二次开发或者部署的时候，可以移除（所以不存在强制的说法）。
