### ISSUE TITLE
[Feature Request] 实时语音api接口

### ISSUE THREAD

**Issue by QingMoer** [ChatGPTNextWeb/ChatGPT-Next-Web#5685]
### 🥰 需求描述

您好 关于gpt-4o-audio-preview这个模型 会在将来的版本有计划适配吗？

### 🧐 解决方案

能够使用浏览器进行实时语音对话（gpt-4o-audio-preview)

**Comment by QingMoer** [comment]
不好意思 搞错了 应该是这篇文章中的realtime
https://platform.openai.com/docs/api-reference/realtime

**Comment by Dogtiti** [comment]
正在实现中~

**Comment by QingMoer** [comment]
> 正在实现中~

好~麻烦啦
