### ISSUE TITLE
[Feature Request] 开发者大佬能不能新个功能

### ISSUE THREAD

**Issue by IsYang68** [ChatGPTNextWeb/ChatGPT-Next-Web#5686]
### 🥰 需求描述

通过谷歌账号登入接入自己的ChatGPT账号，无需API-KEY使用

### 🧐 解决方案

通过谷歌账号登入接入自己的ChatGPT账号，无需API-KEY使用

**Comment by QAbot-zh** [comment]
都是网页前端，那为什么不直接官网使用呢，nextchat 核心是面向 api 开发的，你说的很难做到，而且也不能避免代理问题
