### ISSUE TITLE
xAi support

### ISSUE THREAD

**Issue by iamysfy** [ChatGPTNextWeb/ChatGPT-Next-Web#5698]
xAi just dropped! and we need NextChat to support it.

https://accounts.x.ai/sign-in?redirect=cloud-console

**Comment by proxyxai** [comment]
https://chat.proxyxai.com

**Comment by lloydzhou** [comment]
# docs
https://docs.x.ai/docs/quickstart#making-your-first-request

# pricing
![image](https://github.com/user-attachments/assets/59245bfa-e5d5-4f66-b550-0f0dc338f4ca)

**Comment by lloydzhou** [comment]
can using openai sdk
![image](https://github.com/user-attachments/assets/46a9b893-9b6a-45b5-a831-2ffceb340eb1)
