### ISSUE TITLE
[Bug] 二次开发页面卡顿，然后页面崩溃了，显示out of memory

### ISSUE THREAD

**Issue by qhw233** [ChatGPTNextWeb/ChatGPT-Next-Web#5703]
### 📦 部署方式

Other

### 📌 软件版本

2.15.0

### 💻 系统环境

Windows

### 📌 系统版本

win11 23H2

### 🌐 浏览器

Chrome

### 📌 浏览器版本

105.0.5195.102

### 🐛 问题描述

![C525EE99-1681-4c6c-9006-6EAC8330ABB7](https://github.com/user-attachments/assets/e17cbc5f-42d4-44ab-9749-0dab164e2494)
[我自己二次开发了一下，一个窗口中存在两个对话，但是在进行一段时间的对话之后，页面会出现卡顿，打字机的效果也变得不流畅，然后页面旧崩溃了。在浏览器的开发者模式下，看到react-dom的js文件，提示“在潜在的问题出现暂停”，断点
![屏幕截图 2024-10-22 102200](https://github.com/user-attachments/assets/7825539e-86ed-4194-b6ad-99fb8c5faeaa)
在了一个usestate的函数上。

**Comment by qhw233** [comment]
版本是2.14.2

**Comment by Dogtiti** [comment]
二次开发的问题没法解决哈
如果是本身项目问题 请提供复现路径
