### ISSUE TITLE
[Feature Request] app不支持GLM4吗？

### ISSUE THREAD

**Issue by shengshimeiyan** [ChatGPTNextWeb/ChatGPT-Next-Web#5714]
### 🥰 需求描述

建议app支持GLM4。目前配置好以后请求url不对
![屏幕截图 2024-10-25 103810](https://github.com/user-attachments/assets/d10c2c5e-16d4-461c-af8c-0e482e96b494)

### 🧐 解决方案

给一个修改请求path的选项

**Comment by lloydzhou** [comment]
可以最近加上glm的模型

**Comment by shengshimeiyan** [comment]
现在的调用path有问题，调用不到，看我上面的图

**Comment by DDMeaqua** [comment]
@shengshimeiyan 看看你的设置？下面是我刚调用的图

![image](https://github.com/user-attachments/assets/aea411be-e4d6-4da4-aa6e-5d6b3d623ac4)

![image](https://github.com/user-attachments/assets/9e7db4bf-8935-42a4-9cf7-05a86bde8a9b)

**Comment by shengshimeiyan** [comment]
为什么我的模型服务商里没有ChatGLM？
![image](https://github.com/user-attachments/assets/8c8d9290-5222-4f45-97a2-2badd52b20e3)
我的接口地址是：https://open.bigmodel.cn/api/paas/v4/chat/completions

**Comment by DDMeaqua** [comment]
@shengshimeiyan 可以用最新的main分支里的代码，app.nextchat.dev 里可能还没更新

**Comment by lloydzhou** [comment]
app.nextchat.dev 需要在发新版本的时候更新
