### ISSUE TITLE
[Bug] update error what to do

### ISSUE THREAD

**Issue by rdbox** [ChatGPTNextWeb/ChatGPT-Next-Web#5716]
### 📦 Deployment Method

Other

### 📌 Version

2.15

### 💻 Operating System

Windows

### 📌 System Version

win10

### 🌐 Browser

Chrome

### 📌 Browser Version

130.0.6723.69 

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/b02c3c34-1f9c-43b9-9ecb-572536c71adc)
I don't understand what happened.
![image](https://github.com/user-attachments/assets/b8f54ee7-473b-42e8-8002-3ada5f464d1c)

**Comment by lloydzhou** [comment]
1. Update Failed，没有复现
2. statusText error, 与 #5717  重复（已经在 #5719 修复）
