### ISSUE TITLE
[Bug] Failed to construct 'Response': Failed to read the 'statusText' property from 

### ISSUE THREAD

**Issue by f1h0** [ChatGPTNextWeb/ChatGPT-Next-Web#5717]
### 📦 Deployment Method

Other

### 📌 Version

2.15.6

### 💻 Operating System

Windows

### 📌 System Version

win 10

### 🌐 Browser

Chrome

### 📌 Browser Version

130.0.6723.69 

### 🐛 Bug Description

None of the versions works and gives an error it never happened.
```
{
  "error": true,
  "message": "Failed to construct 'Response': Failed to read the 'statusText' property from 'ResponseInit': String contains non ISO-8859-1 code point."
}
```

![image](https://github.com/user-attachments/assets/f58e6236-83b2-444e-b4a0-41d243cb9592)

**Comment by mayfwl** [comment]
怎么复现这个问题

**Comment by f1h0** [comment]
I opened the ChatGPTNextWeb application and just started typing my question I press Enter and get this error I rolled back a few versions ago everything works correctly apparently something needs to be fixed something is broken somewhere

**Comment by lloydzhou** [comment]
`err.source().expect("REASON").to_string()` may by non `ISO-8859-1` code


![img_v3_02g0_c15dcdb5-79ee-48e4-aaba-c87871e2555g](https://github.com/user-attachments/assets/442860ec-94df-4fb8-a287-41820ef8ce98)

**Comment by f1h0** [comment]
> `err.source().expect("REASON").to_string()` may by non `ISO-8859-1` code
> 
> ![img_v3_02g0_c15dcdb5-79ee-48e4-aaba-c87871e2555g](https://private-user-images.githubusercontent.com/1826685/380049870-442860ec-94df-4fb8-a287-41820ef8ce98.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDA5NjUsIm5iZiI6MTcyOTg0MDY2NSwicGF0aCI6Ii8xODI2Njg1LzM4MDA0OTg3MC00NDI4NjBlYy05NGRmLTRmYjgtYTI4Ny00MTgyMGVmOGNlOTguanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjVUMDcxNzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2IxYzI4NDQ3ZmZlNzAxOWM2YmFlY2Q5ZTlmZDdmNWE2OWRjN2JiM2RkM2Y2ZWRjNzIzMDE1ZTJmZDk4YzI0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ILFKoVsvYqCscNz2kn1p1vmqSqHsn25SqIGZYemWfLE)

Tell me as a user who uses not develops software What I need to do I just download the application and use it as a user I do not develop it?

**Comment by lloydzhou** [comment]
应该是非英语用户（Windows操作系统语言非英语）api请求报错的时候，会出现这个错误。

如果API配置正确，应该不会触发这个报错。

**Comment by f1h0** [comment]
@lloydzhou 
That's right, I use non-English words in my native language, which is different from English.

**Comment by f1h0** [comment]
![image](https://github.com/user-attachments/assets/650fb533-cb2c-4b34-8a16-700f8c23f8a3)
no verification works what to do urgently? how to use I have a lot of work to do

**Comment by lloydzhou** [comment]
bug已经在主分支修复，只是未发布新版本，预计本周发布v2.15.7会包含这个修复
