### ISSUE TITLE
[Feature Request] 增加自定义多模态大模型上传图片按钮

### ISSUE THREAD

**Issue by Martinfeng** [ChatGPTNextWeb/ChatGPT-Next-Web#5724]
### 🥰 需求描述

本地部署qwen2-vl模型，无法识别为图片对话模型，没有上传图片的按钮，只能把模型命名为gpt-4o-mini等才会出现上传图片按钮。

### 🧐 解决方案

自定义多模态大模型列表，能够出现上传图片按钮

**Comment by lloydzhou** [comment]
#5815 已经处理
