### ISSUE TITLE
[Bug] 搭配newapi oneapi聊天主题报错异常，如何解决

### ISSUE THREAD

**Issue by comba-cat** [ChatGPTNextWeb/ChatGPT-Next-Web#5725]
### 📦 Deployment Method

Docker

### 📌 Version

v2.15.6

### 💻 Operating System

Other Linux

### 📌 System Version

9.4

### 🌐 Browser

Chrome

### 📌 Browser Version

chrome 122

### 🐛 Bug Description

搭配one-api主题报错

![image](https://github.com/user-attachments/assets/1339ecfa-7f76-40de-9a7b-866b9e2e7a6e)

### 📷 Recurrence Steps

![image](https://github.com/user-attachments/assets/db4f2ed3-ce7d-4b52-b11a-629f465fca90)

**Comment by q3cc** [comment]
刷新标题试下

**Comment by JIeJaitt** [comment]
同样的问题，现在nextchat不能自定义模型了吗？

**Comment by QAbot-zh** [comment]
> 同样的问题，现在nextchat不能自定义模型了吗？

可以啊，你点开F12 看下调用的模型是什么，以及报错是什么

**Comment by JIeJaitt** [comment]
@QAbot-zh hi~大佬。我在自定义模型里面定义-all,+claude-3-5-sonnet-20240620@OpenAI,+claude-3-haiku-20240307@OpenAI
然后我在对话框里面去选择模型的时候并没有看到我的模型，我的版本是2.15.5。

**Comment by QAbot-zh** [comment]
> -all,+claude-3-5-sonnet-20240620@OpenAI,+claude-3-haiku-20240307@OpenAI

刚试了下官方部署网站： https://app.nextchat.dev ，修改是即时生效的，版本是 2.15.6，你是自己部署的嘛，有设置环境变量 CUSTOM_MODELS 吗，那个有时候会和前端设置冲突

![image](https://github.com/user-attachments/assets/69997c9e-9aca-4600-b8ae-b364f0e525c1)

**Comment by phengite** [comment]
你 F12 查看请求，如果是预置的模型似乎都是调用 gpt-4o-mini 来生成标题，你接口没这模型就会这样。one api 里建个同名模型就行至于实际转向哪个模型无所谓。预置里完全没有的自定义模型就是用自身再请求一次生成标题。

**Comment by JIeJaitt** [comment]
@QAbot-zh 谢谢大佬帮助，我升级版本之后问题已经解决。
@phengite 谢谢大佬，我实际上用的是New API，不过这个项目是基于One api开发的，我不知道有没有自定义某个模型的名字指向另外一个模型的功能，晚点探索一下
