### ISSUE TITLE
[Bug] Inconsistent credits displayed on website and client

### ISSUE THREAD

**Issue by renkun-ken** [ChatGPTNextWeb/ChatGPT-Next-Web#5727]
### 📦 部署方式

官方安装包

### 📌 软件版本

v2.15.6

### 💻 系统环境

macOS

### 📌 系统版本

macOS 15.0.1

### 🌐 浏览器

Firefox

### 📌 浏览器版本

131.0.3

### 🐛 问题描述

After I switched my plan from monthly Basic to annual Pro, the plan I subscribe displayed on website and client are consistent but the credits look different.

<img width="578" alt="image" src="https://github.com/user-attachments/assets/0a1641dc-c39a-4cf1-a6d8-395c05b018ee">

Website:

<img width="533" alt="image" src="https://github.com/user-attachments/assets/c5910209-d4a1-49e2-bcf0-51fab735334d">

Client (the credits do not seem to be updated with the new plan):

<img width="544" alt="image" src="https://github.com/user-attachments/assets/4c4a8c8e-9f26-4c1d-9f43-c66bace544fc">

I tried log-out and log-in on client-side but made no difference.

### 🚦 期望结果

The credits should be consistent across website and all clients.

**Comment by Dogtiti** [comment]
下个版本会修复，不影响使用
