### ISSUE TITLE
[Feature Request] 本地的native版本能否打开类似于web段的console/调试窗口 ？我希望能看各类参数和日志

### ISSUE THREAD

**Issue by jiangying000** [ChatGPTNextWeb/ChatGPT-Next-Web#5728]
### 🥰 需求描述

我希望能看各类参数和日志，本地的native版本能否打开类似于web段的console/调试窗口

### 🧐 解决方案

是否有快捷键之类的

**Comment by jiangying000** [comment]
一个是按下F12瞬间就弹出来了啥信息都有，一个还得专门监听之类的

**Comment by lloydzhou** [comment]
因为releases上面发布的并不是调试版本，而是给C端用户使用的正式版本，所以不建议在native版本直接打开dev console

如果需要调试信息：
1. 可以直接使用网页版
2. 可以clone本项目，并在本地使用`yarn app:dev`运行可以进入调试模式，打开dev console
