### ISSUE TITLE
[Bug] docker 环境变量HIDE_USER_API_KEY值无效

### ISSUE THREAD

**Issue by IMStepFather** [ChatGPTNextWeb/ChatGPT-Next-Web#5745]
### 📦 Deployment Method

Docker

### 📌 Version

2.15.6

### 💻 Operating System

Ubuntu

### 📌 System Version

24.1

### 🌐 Browser

Firefox

### 📌 Browser Version

132.0

### 🐛 Bug Description

docker compose 部署后环境变量
HIDE_USER_API_KEY=0，也会关闭自定义接口（API key）功能。注释掉该行后才正常。
DEFAULT_MODEL=gpt-4o-mini 参数不生效

**Comment by QAbot-zh** [comment]
是文档说明和代码没有统一好，代码是这么写的：
```
hideUserApiKey: !!process.env.HIDE_USER_API_KEY
```
只有【不设置该环境变量】或者【该环境变量为空字符串】时，它才【不关闭自定义 api】，剩下设置成任意字符串（包括0，false）都会使其生效

**Comment by IMStepFather** [comment]
good
