### ISSUE TITLE
[Bug] built-in plugin dalle3 error

### ISSUE THREAD

**Issue by JingSyue** [ChatGPTNextWeb/ChatGPT-Next-Web#5787]
### 📦 Deployment Method

Vercel

### 📌 Version

1

### 💻 Operating System

Windows

### 📌 System Version

1

### 🌐 Browser

Chrome

### 📌 Browser Version

1

### 🐛 Bug Description

無法調用內置的dalle3插件

### 📷 Recurrence Steps

openai api key可以對話的情況下

model: gpt-4o-mini
複製貼上官方的plugin template可以調用dalle3插件
![image](https://github.com/user-attachments/assets/3c6ab572-a40c-4805-9aa0-814723e10d6f)

model: gpt-4o-mini
無法調用內置的dalle3插件(已配置open api key)
![image](https://github.com/user-attachments/assets/1f06e580-e8f9-4c7f-9bbd-eaecde1edd6a)

### 📝 Additional Information

錯誤訊息
![image](https://github.com/user-attachments/assets/f820c659-774a-454a-9407-391085d6b326)

**Comment by lloydzhou** [comment]
![image](https://github.com/user-attachments/assets/a475486d-73c0-4a88-9307-20e0777d2231)
可能是这里的问题？
