### ISSUE TITLE
[Bug] o1-preview Doesn't detect system prompts.

### ISSUE THREAD

**Issue by jmartinezb3** [ChatGPTNextWeb/ChatGPT-Next-Web#5796]
### 📦 Deployment Method

Official installation package

### 📌 Version

2.15.7

### 💻 Operating System

Windows

### 📌 System Version

Win 10

### 🌐 Browser

Other

### 📌 Browser Version

WebView-Dektop version.

### 🐛 Bug Description

When using a system prompt with o1-preview, it seems it doesn't detect the instructions provided through this mechanism, which doesn't happen with GPT-4o. I suspect it's an error in how the client handles the system prompt.

GPT-4o output:

![Windows 10 python dev](https://github.com/user-attachments/assets/63ad5df3-a5ea-4b9b-b566-eebe100cc2c7)

o1-preview Output:

![Windows 10 python dev o1-preview](https://github.com/user-attachments/assets/bccc0925-4ede-4a2e-935a-514950746964)

### 🚦 Expected Behavior

o1-preview should be aware of the system prompt instructions and respond accordingly, just like GPT-4o does.

**Comment by QAbot-zh** [comment]
The o1 model does not support system messages, so the system message has been removed.

https://platform.openai.com/docs/guides/reasoning

![image](https://github.com/user-attachments/assets/bce6e79b-57f4-408f-a852-3a9df94c34a9)

**Comment by jmartinezb3** [comment]
> The o1 model does not support system messages, so the system message has been removed.
> 
> https://platform.openai.com/docs/guides/reasoning
> 
> ![image](https://private-user-images.githubusercontent.com/40236765/384686097-bce6e79b-57f4-408f-a852-3a9df94c34a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNjI2NzcsIm5iZiI6MTczMTI2MjM3NywicGF0aCI6Ii80MDIzNjc2NS8zODQ2ODYwOTctYmNlNmU3OWItNTdmNC00MDhmLWE4NTItM2E5ZGY5NGMzNGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE4MTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YjFiNTBiNjA2ZDllMDU1ODQ1NzZlOGMyNjY2MGM4ZjAyNGZmMjhkNWNlY2Q3NGU2YjQ2ZTk0MGI0YzlkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3sa0M9TBcgKQTOt-uiCRrKrGajuUTSiq4jpv3aKtpTo)

Oh. I see, well, thanks :)
