### ISSUE TITLE
[Bug] 代码渲染错误

### ISSUE THREAD

**Issue by SuiYunsy** [ChatGPTNextWeb/ChatGPT-Next-Web#5797]
### 📦 Deployment Method

Vercel

### 📌 Version

v2.15.7

### 💻 Operating System

Windows

### 📌 System Version

Win10

### 🌐 Browser

Edge

### 📌 Browser Version

130

### 🐛 Bug Description

错误情况：
![image](https://github.com/user-attachments/assets/6d34c585-58b1-4736-984c-d1429ffa3b15)

正确情况：
![image](https://github.com/user-attachments/assets/58d719fe-e697-46f7-9b83-4222cbd61111)

---

渲染有问题的回答内容，供测试：

[code.txt](https://github.com/user-attachments/files/17690578/code.txt)

**Comment by OPChips** [comment]
@SuiYunsy 这两个图中的代码内容不一致
图一的 res.end( 中多了一个 ```html，而图二没有，导致渲染失败
让AI原样输出 code.txt 的内容渲染没有问题

**Comment by SuiYunsy** [comment]
> @SuiYunsy 这两个图中的代码内容不一致 图一的 res.end( 中多了一个 ```html，而图二没有，导致渲染失败 让AI原样输出 code.txt 的内容渲染没有问题

我明白，这正是nextchat渲染导致的：

![image](https://github.com/user-attachments/assets/309b3dd8-05ac-4c0a-bf25-d137ecafd5d8)

![image](https://github.com/user-attachments/assets/64539a29-da72-4be5-9d70-690437120fc1)

我猜想问题出在这个函数：

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/819d249a099ba84017afc5b5c20ae8309889b060/app/components/markdown.tsx#L245-L260

第251行：

https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/819d249a099ba84017afc5b5c20ae8309889b060/app/components/markdown.tsx#L251

**Comment by SuiYunsy** [comment]
问题已解决，非常感谢！
