### ISSUE TITLE
[Feature Request] 更加人性化的自动滚动

### ISSUE THREAD

**Issue by SuiYunsy** [ChatGPTNextWeb/ChatGPT-Next-Web#5798]
### 🥰 Feature Description

改进自动滚动行为：当生成的消息填满屏幕时，自动滚动将停止，以提高可读性。

### 🧐 Proposed Solution

现在模型输出速度越来越快、内容越来越多，生成内容时会不断向下滚动消息👀

希望当生成内容的第一行已经紧贴标题栏下方时，就停止自动滚动，这样可以不需要读者手动操作、向上滚动来打断自动滚动，读者可以不被影响地继续阅读生成的内容😀

**Comment by lloydzhou** [comment]
这个和速度有关系，同时也和长度有关系

**Comment by SuiYunsy** [comment]
https://github.com/user-attachments/assets/6afc8d7d-09b1-4fbe-ad0d-32b156596ac8

是在chatbox上体验到这个feat，觉得很人性化，所以才提了这个请求😀

![image](https://github.com/user-attachments/assets/28ee65b3-f29e-420c-b187-032694f48305)
