### ISSUE TITLE
[Bug] TTS报错

### ISSUE THREAD

**Issue by SuiYunsy** [ChatGPTNextWeb/ChatGPT-Next-Web#5801]
### 📦 Deployment Method

Vercel

### 📌 Version

v2.15.7

### 💻 Operating System

Windows

### 📌 System Version

Win10

### 🌐 Browser

Edge

### 📌 Browser Version

130

### 🐛 Bug Description

某些情况下，一些文本会导致TTS朗读失败，具体信息为：

ConsoleMsg:
`[OpenAI Speech] DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data`

PopTips:
![image](https://github.com/user-attachments/assets/cbd86024-5283-429c-aaca-e6697df5f7a1)

**例1：**

![image](https://github.com/user-attachments/assets/1284af38-4d1e-4700-9ad4-e794fdfc3c18)

**例2：**

```text
容斥原理（Inclusion-Exclusion Principle）是组合数学中的一个重要工具，用于计算多个集合的并集的大小。它的基本思想是通过逐步添加和减去各个集合的大小来避免重复计算。

假设有 \( n \) 个集合 \( A_1, A_2, \ldots, A_n \)，容斥原理可以用以下公式表示：

\[
|A_1 \cup A_2 \cup \ldots \cup A_n| = \sum_{i=1}^{n} |A_i| - \sum_{1 \leq i < j \leq n} |A_i \cap A_j| + \sum_{1 \leq i < j < k \leq n} |A_i \cap A_j \cap A_k| - \ldots + (-1)^{n+1} |A_1 \cap A_2 \cap \ldots \cap A_n|
\]
```

**反例（此例能够正常朗读）：**

```text
我们可以使用容斥原理来解决这个问题。设：

- \( |A| \) 为参加游泳的人数，\( |A| = 17 \)
- \( |B| \) 为参加跑步的人数，\( |B| = 20 \)
- \( |C| \) 为参加跳绳的人数，\( |C| = 22 \)
- \( |A \cap B| + |A \cap C| + |B \cap C| = 24 \)（同时参加两个项目的人数）

我们需要找出同时参加三个项目的人数，设为 \( x \)（即 \( |A \cap B \cap C| = x \)）。

根据容斥原理，我们可以写出以下公式：

\[
|A \cup B \cup C| = |A| + |B| + |C| - (|A \cap B| + |A \cap C| + |B \cap C|) + |A \cap B \cap C|
\]
```

**Comment by DDMeaqua** [comment]
可以过几天再试试，目前bing那边有问题
![image](https://github.com/user-attachments/assets/fda17a11-0bad-48a2-8fb2-e554401c4eb9)

**Comment by SuiYunsy** [comment]
> 可以过几天再试试，目前bing那边有问题

感觉不是bing的问题，而是特殊字符的问题😂
参考文档：https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-synthesis-markup-structure#special-characters

**Comment by SuiYunsy** [comment]
让AI改了一下，目前是可以播放了，没管啥健壮性可维护性，后续遇到问题再看看🥳
![image](https://github.com/user-attachments/assets/c5b86402-64b6-43fb-9447-1eb3de81c543)
