### ISSUE TITLE
自定义模型无法使用[Bug] 

### ISSUE THREAD

**Issue by SunshineWood** [ChatGPTNextWeb/ChatGPT-Next-Web#5802]
### 📦 部署方式

Other

### 📌 软件版本

最新

### 💻 系统环境

Windows

### 📌 系统版本

22631.4391

### 🌐 浏览器

Edge

### 📌 浏览器版本

版本 125.0.2535.85 (正式版本) (64 位)

### 🐛 问题描述

在使用自定义模型的时候，我的代理通过openai的接口，转发了所有的模型，比如包括claude在内模型；实际上我需要用openai的接口去访问自定义接口claude-3-5-sonnet-20240620的时候，这个自定义模型不会出现在列表，应该是由于和默认的模型名字一样，导致使用起来有些问题。

### 🚦 期望结果

自定义模型的名字不应该受其他的标准模型名称影响。

**Comment by QAbot-zh** [comment]
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5001

**Comment by SunshineWood** [comment]
> #5001
谢谢，我测试了一下，没有问题。

**Comment by SunshineWood** [comment]
#5001 中已经有解决方案， 问题关闭！
