### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by thefreeman007** [ChatGPTNextWeb/ChatGPT-Next-Web#5824]
### 📦 Deployment Method

Docker

### 📌 Version

最新new

### 💻 Operating System

Ubuntu

### 📌 System Version

18.04

### 🌐 Browser

Chrome

### 📌 Browser Version

130.0.6723.117

### 🐛 Bug Description

{
  "error": {
    "message": "The model `gpt-4o` does not exist or you do not have access to it.",
    "type": "invalid_request_error",
    "param": null,
    "code": "model_not_found"
  }
}
所有模型都显示模型不存在 不知道是为什么…………

**Comment by QAbot-zh** [comment]
上游检查过了吗，有没有可能是你的api确实不支持呢？

**Comment by thefreeman007** [comment]
> > Bot 检测到 issue body 的语言不是英文，自动翻译。
> 
> 上游检查了吗？您的 API 是否可能不支持它？

3.5也有同样的情况，我记得3.5好像是免费的，而且新号有18美元的初始金额吧？  照理说应该是可以的

**Comment by QAbot-zh** [comment]
版本落后了哥，18 美元 api 已经是上上上个政策了，现在新号早就不送额度了，而且 api 对所有模型都收费

**Comment by thefreeman007** [comment]
> 版本落后了哥，18 美元 api 已经是上上上个政策了，现在新号早就不送额度了，而且 api 对所有模型都收费

好吧 渣英文误解了…………不过我是老号  很早注册的  刚出来那段时间注册的。只是一直没用过  我再看看有没有充值途径吧

**Comment by QAbot-zh** [comment]
可以试试马斯克家的 grok 模型，至少比 3.5 强

**Comment by thefreeman007** [comment]
> 可以试试马斯克家的 grok 模型，至少比 3.5 强

谢谢 兄弟
