### ISSUE TITLE
[Feature Request] support  grok-beta API

### ISSUE THREAD

**Issue by arboreal78** [ChatGPTNextWeb/ChatGPT-Next-Web#5831]
### 🥰 需求描述

I have seen grok-beta exist on the model list.  However, I can't find any document to demo how to configure it. Could you confirm whether we already support it or not. If yes, how can I configure to use grok-beta API.  any example?

### 🧐 解决方案

Give a clear instruction how to configure  to support grok-beta

**Comment by SHIJS1999** [comment]
https://github.com/search?q=repo%3AChatGPTNextWeb/ChatGPT-Next-Web%20XAI_API_KEY&type=code

**Comment by arboreal78** [comment]
Thanks a lot. it works when I configure it like -e XAI_API_KEY=xai-xxxx
