### ISSUE TITLE
[Bug] 无法使用豆包模型

### ISSUE THREAD

**Issue by LiMinghan1220** [ChatGPTNextWeb/ChatGPT-Next-Web#5832]
### 📦 部署方式

官方安装包

### 📌 软件版本

v2.15.8

### 💻 系统环境

Windows

### 📌 系统版本

版本	Windows 11 专业版 版本号	23H2 安装日期	‎2024/‎5/‎17 操作系统版本	22631.4460 体验	Windows Feature Experience Pack 1000.22700.1047.0

### 🌐 浏览器

Edge

### 📌 浏览器版本

版本 132.0.2953.0 (正式版本) canary (64 位)

### 🐛 问题描述

![image](https://github.com/user-attachments/assets/3fd91705-4f23-408d-a795-7907abf03708)
使用https://ark.cn-beijing.volces.com/api/v3
model=ep-20241116115401-*****
在OpenAI模式下正确配置可使用，相同的配置换到新出的ByteDance却报错。

### 📷 复现步骤

![image](https://github.com/user-attachments/assets/e11b25cd-df66-4269-9269-07abb012c62a)
正确填写，其他不变

### 🚦 期望结果

火山引擎本身兼容OpenAISDK，可否直接使用OpenAISDK或fix bug？

**Comment by 954708775** [comment]
这个目前是说可以解决了
Completed means now it has been solved?

**Comment by ench2** [comment]
> 这个目前是说可以解决了 Completed means now it has been solved?

怎么解决的
