### ISSUE TITLE
error trying to connect: operation timed out

### ISSUE THREAD

**Issue by make-liuchenjun** [ChatGPTNextWeb/ChatGPT-Next-Web#5834]
### 📦 部署方式

官方安装包

### 📌 软件版本

v2.15.8

### 💻 系统环境

Windows

### 📌 系统版本

win11 23H2 22631.4460

### 🌐 浏览器

Edge

### 📌 浏览器版本

没用浏览器，是客户端

### 🐛 问题描述

![{0840E2D0-2465-4D49-833F-AC54A1C7FCE9}](https://github.com/user-attachments/assets/af848c41-d5d5-421f-8eca-ae8c0e3e6856)

### 📷 复现步骤

发送一个消息就提示error trying to connect: operation timed out

**Comment by Mrszcup** [comment]
me too。macos    
error trying to connect: operation timed out

**Comment by BenjaminPiette** [comment]
worked for me perfectly with 2.15.3, just upgraded to 2.15.8 and getting this error. I'm over a sock proxy. macos.

**Comment by bert82503** [comment]
MacBook Pro，use Version 2.15.8 (20241125.085340), I also encountered this issue.

![Image](https://github.com/user-attachments/assets/7fc5da57-aa76-4fd8-857c-c98db0d05b96)

**Comment by shmilee** [comment]
同遇到此错误。和我的网络环境有关，不换网换个api地址，或者不换api地址切换网络，都可以解决。

**Comment by lupguo** [comment]
这个问题仍然存在(>2.15.3)，切换到2.15.3 后一切正常
