### ISSUE TITLE
[Feature Request]自定义的模型名称太长，导致在模型选择中不显示

### ISSUE THREAD

**Issue by jackwwy** [ChatGPTNextWeb/ChatGPT-Next-Web#5859]
### 🥰 需求描述

我在设置中自定义了一个模型claude-3-5-sonnet-20241022，但是在模型选择中找不到这个模型。应该是因为名字太长导致不显示

### 🧐 解决方案

让名字长的模型也可以选择

**Comment by QAbot-zh** [comment]
我这么长都没问题，不显示是不是因为你没有往下划啊，模型多你就先 -all 再加上你要用的模型

![image](https://github.com/user-attachments/assets/ec91faee-f3c7-47c4-be00-8bd43d307a0d)

**Comment by QAbot-zh** [comment]
那你就这么写：claude-3-5-sonnet-20241022@OpenAI

**Comment by jackwwy** [comment]
好的，谢谢你！！！
