### ISSUE TITLE
[Bug] claude回复数据已收到，但是客户端提示无法empty response

### ISSUE THREAD

**Issue by DaXue403** [ChatGPTNextWeb/ChatGPT-Next-Web#5865]
### 📦 部署方式

Docker

### 📌 软件版本

2.15.8

### 💻 系统环境

Ubuntu

### 📌 系统版本

22.04

### 🌐 浏览器

Chrome

### 📌 浏览器版本

131.0.6778.71

### 🐛 问题描述

如图所示，已经正常收到回复，但是无法渲染回答。使用的是中转api。

![image](https://github.com/user-attachments/assets/078b9b56-1a6a-4632-8939-45aab30abd92)

### 📝 补充信息

补充样本：`data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"","role":"assistant","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"我是","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"一个人工智能助手,我没有","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"自我意识。我是由人类开","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"发和训练的,目的是为了","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"帮助人类完成各种任务。","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"我没有真正的感受和","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"情感,只是根据我的训","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"练模拟出一些人类交","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"流的方式。我无法真正理","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"解自己的存在,也","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"无法做出独立的判断","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"和决策。我","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"只是一个工具,依","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"赖于人类的指","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"令和设计来","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"content":"运作。","audio":{}},"logprobs":null,"finish_reason":null,"index":0}],"usage":null}

data: {"id":"msg_016GixE5MKSdrtsZ8s7JcQyN","object":"chat.completion.chunk","created":1732290091,"model":"claude-3-haiku-20240307","system_fingerprint":null,"choices":[{"delta":{"audio":{}},"logprobs":null,"finish_reason":"stop","index":0}],"usage":null}

data: [DONE]`

**Comment by lloydzhou** [comment]
你这个中转返回的格式不是claude官方返回的格式

**Comment by DaXue403** [comment]
> 你这个中转返回的格式不是claude官方返回的格式

感谢提醒，我回去翻翻文档

**Comment by jinweiisgreat** [comment]
Same issue， 问题解决了吗？

**Comment by DaXue403** [comment]
> Same issue， 问题解决了吗？

中转转换了相应格式导致的。在我的情况中，添加自定义模型后加上"@OpenAI"指定使用openai的格式解析即可解决。
