### ISSUE TITLE
实时语音无法使用

### ISSUE THREAD

**Issue by Concertoss** [ChatGPTNextWeb/ChatGPT-Next-Web#5876]
### 📦 部署方式

Vercel

### 📌 软件版本

v2.15.8

### 💻 系统环境

iOS

### 📌 系统版本

all

### 🌐 浏览器

Chrome

### 📌 浏览器版本

new

### 🐛 问题描述

无法启动realtime 麦克风一直为禁用状态，也无法启用
<img width="325" alt="image" src="https://github.com/user-attachments/assets/0f4bc159-9247-44ba-a71f-b6e6a8aed9e8">

**Comment by dustookk** [comment]
一样的情况， 请作者看一下是什么原因导致的

**Comment by bywangxp** [comment]
求解决
