### ISSUE TITLE
[Bug] Google's Gemini-1.5-flash latest cannot be used.

### ISSUE THREAD

**Issue by Rocky-Jinxing** [ChatGPTNextWeb/ChatGPT-Next-Web#5910]
### 📦 Deployment Method

Docker

### 📌 Version

v2.15.8

### 💻 Operating System

Windows

### 📌 System Version

Windows11,23h2

### 🌐 Browser

Chrome

### 📌 Browser Version

131.0.6778.109

### 🐛 Bug Description

[Bug] Google's Gemini-1.5-flash latest cannot be used.
![image](https://github.com/user-attachments/assets/37d0b5dc-5497-4dae-a752-c2f1839feaf5)

### 📷 Recurrence Steps

My OpenAI is normal.

**Comment by QAbot-zh** [comment]
翻译一下 message
