### ISSUE TITLE
[Feature Request] 打开 https://app.nextchat.dev/ 官方网址, 填入 url/key, 无脑使用就行吧?

### ISSUE THREAD

**Issue by LeoLeeTech** [ChatGPTNextWeb/ChatGPT-Next-Web#5917]
### 🥰 需求描述

打开 https://app.nextchat.dev/ 官方网址, 填入 url/key使用就行吧?

我记得以前看过 url/key只存储在浏览器端, 不需要考虑密码之类的

我是客户端的老用户, 这次准备给别人推荐一下, 想让对方直接访问/体验

### 🧐 解决方案

麻烦了

**Comment by Dogtiti** [comment]
不推荐这样，有泄露key的风险
推荐自己部署然后开启访问码即可

**Comment by LeoLeeTech** [comment]
> 不推荐这样，有泄露key的风险 推荐自己部署然后开启访问码即可

感谢
不过我想问一下, 目前知道的会怎么泄露呢? 

1. 钓鱼网站, 读取本地的 session/key
2. 网络抓包
