### ISSUE TITLE
[Feature Request] 请求添加智谱AI的免费模型：图像识别模型glm-4v-flash、文生图模型cogview-3-flash、文生视频模型cogvideox-flash

### ISSUE THREAD

**Issue by dupl** [ChatGPTNextWeb/ChatGPT-Next-Web#5921]
### 🥰 需求描述

请求添加智谱AI的免费模型：图像识别模型glm-4v-flash、文生图模型cogview-3-flash、文生视频模型cogvideox-flash

### 🧐 解决方案

请求添加智谱AI的免费模型：图像识别模型glm-4v-flash、文生图模型cogview-3-flash、文生视频模型cogvideox-flash

### 📝 补充信息

请求添加智谱AI的免费模型：图像识别模型glm-4v-flash、文生图模型cogview-3-flash、文生视频模型cogvideox-flash

**Comment by ruixing1001** [comment]
手动可以添加，加一个glm-4v-flash@chatglm就行，但是还不能识图。

**Comment by dupl** [comment]
请求添加智谱AI的免费模型：图像识别模型glm-4v-flashx、文生图模型cogview-3-flash、文生视频模型cogvideox-flash

**Comment by dupl** [comment]
> 手动可以添加，加一个glm-4v-flash@chatglm就行，但是还不能识图。

又有新的免费模型了：文生图模型cogview-3-flash、文生视频模型cogvideox-flash

**Comment by Dogtiti** [comment]
#5996
