### ISSUE TITLE
官网写的GPT-4.5不符合事实

### ISSUE THREAD

**Issue by gy-0** [ChatGPTNextWeb/ChatGPT-Next-Web#5957]
### 📦 部署方式

官方安装包

### 📌 软件版本

1

### 💻 系统环境

macOS

### 📌 系统版本

1

### 🌐 浏览器

Chrome

### 📌 浏览器版本

1

### 🐛 问题描述

没有gpt-4.5

**Comment by QAbot-zh** [comment]
哪个官网写了 4.5
